### ISSUE TITLE
unkown identifier with replace tactic

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#1013]
I get the error `unknown identifier 'n'` with the following code:

``` lean
-- either library
open nat
example : Π(n : ℕ), n + 0 = n :=
begin 
  intro n, replace (n+0) with n,
end
```

**Comment by robertylewis** [comment]
Hmm. This seems to only happen when the intro is done in tactic mode:

``` lean
open nat

example : Π(n : ℕ), n + 0 = n := λ n,
begin
  replace (n+0) with n, -- works
end

example (n : ℕ) : n + 0 = n :=
begin
  replace (n+0) with n, -- works
end

example : Π(n : ℕ), n + 0 = n :=
begin
  intro n, replace (n+0) with n, -- doesn't work
end
```

I'll try to figure it out on Wednesday, if Leo doesn't see the mistake before.

**Comment by robertylewis** [comment]
The following works as well:

``` lean
example : Π(n : ℕ), n + 0 = n :=
begin
  intros, change n = n,
end
```

I think the issue might be at the parsing stage -- @leodemoura , does that make sense? The `replace_tactic` code is never reached in the bad examples.

**Comment by robertylewis** [comment]
Yes, it's a parsing issue. When the parser reaches `n`, it doesn't find it in the environment (https://github.com/leanprover/lean/blob/master/src/frontends/lean/parser.cpp#L1509). Using the `change` tactic, it's assumes `n` is local (https://github.com/leanprover/lean/blob/master/src/frontends/lean/parser.cpp#L1526), but using `replace` it assumes neither local nor global and so it fails. I don't know where/when these get set, and I'm over my head in the parser code -- hopefully this makes it easy for @leodemoura to find the issue?

**Comment by leodemoura** [comment]
I am closing this issue, `replace` tactic is not needed in `lean3`.
