### ISSUE TITLE
Check project-type

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#1017]
@avigad reported:

> I tried then entering "lean" or ".lean" or just return, and in each case I get 
> 
>  Symbol's function definition is void: nil
> 
> The messages buffer says this:
> 
>  replace-regexp-in-string: Symbol's function definition is void: nil

This happens because it's expected to take either `standard` or `hott` (the choices are given btw).

I'll make a change so that it will also accept `lean`, `hlean` and throw an error if it gets an unlisted argument from a user.

**Comment by avigad** [comment]
@soonhokong When I did this, I did not see any choices. Was I supposed to? My prompt is this:

  Project type::

Now I see that if I press the up/down arrows, I get the "standard" / "hott" options, but that was not clear to me at the time.

Are the choices supposed to be given in the prompt? One solution would be to make the prompt

  Project type (standard or hott): 

It would also be nice if just hitting return would give standard as the default. (I have not pulled your changes yet.)

**Comment by avigad** [comment]
P.S. I see that you have added an error message so the user can try again.

**Comment by soonhokong** [comment]
![screen shot 2016-03-04 at 2 52 21 pm](https://cloud.githubusercontent.com/assets/403281/13538470/b7009cc4-e218-11e5-8f9b-f87b92a9c47c.png)

@avigad, this is what I have in my emacs. It must be because of some extra packages that I'm using on my instance.

**Comment by soonhokong** [comment]
> It would also be nice if just hitting return would give standard as the default.

I'll do this.

> One solution would be to make the prompt
> 
> Project type (standard or hott):

I'll do this as well.

**Comment by avigad** [comment]
Thanks!
