### ISSUE TITLE
false typecheck ok

### ISSUE THREAD

**Issue by zraffer** [leanprover/lean3#1024]
https://gist.github.com/zraffer/291a6ea0841ed1955e5a

the above code typechecks, but must not: in `a (P a) t f` should be two arguments of `P a` type, whereas there are two of types `P tt` and `P ff`.

```
namespace foo

    definition bool := ∀ a : Prop, a → a → a
    definition tt : bool := λ (a : Prop) (c d : a), c
    definition ff : bool := λ (a : Prop) (c d : a), d

    definition ind_on_T := ∀ P : bool → Prop, ∀ a : bool, P tt → P ff → P a
    definition ind_on : ind_on_T := λ (P : bool → Prop) (a : bool) (t : P tt) (f : P ff), a (P a) t f
    check ind_on

end foo
```

**Comment by robertylewis** [comment]
In your example, `bool` has type `Prop`. `Prop` is proof irrelevant: that is, for any `t1` and `t2` of type `bool`, `t1` and `t2` will be definitionally equal. (Morally, this is saying that all proofs of a proposition are the "same".) `a`, `tt`, and `ff` are all proofs of `bool`, and so are all definitionally equal, and therefore `P a`, `P tt`, and `P ff` are definitionally equal as well.

**Comment by zraffer** [comment]
Thank you.
