### ISSUE TITLE
Error in auto-theorem generation for mutual inductive types

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1027]
I attempted the following inductive definition:

```
inductive ex :=
| intro : ex2 → ex
with ex2 :=
| intro : (ℕ → ex) → ex2
```

There is an error in one of the auto-theorems (not sure which) generated by this:

```
type mismatch at application
  ex2.rec (λ (n : ex), poly_unit) C_2 (λ (a : ex2) (v_0 : C_2 a), poly_unit.star)
    (λ (a : ℕ → ex) (v_0 : poly_unit), e_2 a)
term
  λ (a : ℕ → ex) (v_0 : poly_unit),
    e_2 a
has type
  Π (a : ℕ → ex),
    poly_unit → C_2 (ex2.intro a)
but is expected to have type
  Π (a : ℕ → ex),
    (ℕ → poly_unit) → C_2 (ex2.intro a)
```

**Comment by leodemoura** [comment]
Dear Mario,

Thanks for reporting the problem.
I'm currently working on the branch `lean3` (next version). I will fix this problem there.
It will take a few months to see the fix in the `master` branch.

Best,
Leo

**Comment by leodemoura** [comment]
We are removing mutually inductive datatypes from the kernel.
We will encode them using indexed families: https://github.com/leanprover/lean/wiki/Inductive-datatypes
@dselsam is implementing this encoding and the support for nested datatypes.
