### ISSUE TITLE
Inaccessible variables in context of placeholders

### ISSUE THREAD

**Issue by spl** [leanprover/lean3#1029]
Given:

``` lean
definition f {A B : Type} (x : A) : B → A := λ x, _
```

Lean shows:

``` lean
don't know how to synthesize placeholder
 A : Type,
 B : Type,
 x : A,
 x : B
 ⊢ A
```

The `x : A` is not accessible at the placeholder, so it probably shouldn't be shown.

Also related, given:

``` lean
definition f {A : Type} (x : A) : A → A := λ x, _
```

Lean shows:

``` lean
don't know how to synthesize placeholder
 A : Type,
 x x : A
 ⊢ A
```

The duplicate `x`s are confusing. Only one `x` should probably be shown.

See also [this discussion](https://groups.google.com/d/msg/lean-user/-Da6fPijAjY/ZK9JHUfyKAAJ).

**Comment by leodemoura** [comment]
Remark: we have a `rename` tactic, and it is useful to handle situations like the one above.
The tactic `rename x y` will rename the "most recent" `x` to `y`. 
In the example above, it would change the goal to:

```
 A : Type,
 B : Type,
 x : A,
 y : B
 ⊢ A
```

here is a full example:

``` lean
constant g {A B : Type} : A → B → A

definition f {A B : Type} (x : A) : B → A := λ x, 
begin
  rename x y,
  exact g x y
end
```

**Comment by spl** [comment]
@leodemoura Interesting! Thanks!

One thing to add: As I've noticed and Mario Carneiro pointed out in the mailing list discussion, the more recent `x` appears renamed (e.g. to `x_1`) in displayed implicit values and error messages. This adds a bit to the confusion.

Nevertheless, I guess having the `rename` tactic is reason enough to leave everything as it is. Feel free to close this issue if you want.

**Comment by leodemoura** [comment]
I am closing the issue. The `x_1` name problem has been fixed in `lean3`.
