### ISSUE TITLE
Warning for variable shadowing

### ISSUE THREAD

**Issue by spl** [leanprover/lean3#1030]
Consider this (trivial) definition:

``` lean
definition f {A : Type} (x : A) : A → A := λ x, x
```

I should not have named the binding after the `λ` as `x` because it made the top `x : A` binding inaccessible.

I would like to have a warning that would tell me if I'm shadowing a variable in scope. This would help me avoid problems when writing proofs. It's especially important when you consider that you can set `variables` well ahead of `definition`s:

``` lean
variable (x : A)
-- ...
definition f {A : Type} : A → A := λ x, x
```

I imagine something like this:

``` lean
-- No warning here.
set_option warn_var_shadowing true
-- The warning only occurs after the above line.
```

By default the option `warn_var_shadowing` would be `false` to avoid creating warnings for existing code.

I don't have any opinion on what the warning text should be, but it should probably include the locations of both the shadowed and the shadower variables.

See also [this discussion](https://groups.google.com/d/msg/lean-user/-Da6fPijAjY/ZK9JHUfyKAAJ).

**Comment by leodemoura** [comment]
Dear Sean,

Thanks for your suggestion.
I understand your point, but this is very low priority.
I'm the only one working on the actual implementation, and I'm totally overwhelmed.
I usually ask for volunteers and help, but this is not a good time for external contributions to the `master` branch, because I'm working on the new branch `lean3` which is very different from `master`. 

Best,
Leo

**Comment by spl** [comment]
@leodemoura Thanks for the explanation. No worries. This is a rather minor issue after all. Consider it far-distant future work, if you will.

**Comment by leodemoura** [comment]
I will tag this issue as `wontimplement` and close it. I will not do it, and nobody volunteered to do it in more than 6 months.

**Comment by spl** [comment]
@leodemoura You said at https://github.com/leanprover/lean/issues/1030#issuecomment-201371636 that it was “not a good time for external contributions” which would generally discourage people from volunteering. So it's no real surprise nobody, including me, volunteered.

I would suggest something that I've seen in other projects: a “help needed” label. You can use it to indicate that you don't currently plan on implementing something but would welcome contributions for. This differs from a “won't implement” label, which can be (mis-)interpreted to mean that it is not desired.

If you are now open to contributions, I may look into it, given time.
