### ISSUE TITLE
error in generating dependency files

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#1035]
@EgbertRijke gets errors after updating Lean to the newest version and building from source. Last week it worked fine, but now he gets errors in the dependency files, but only for the standard library, not for the HoTT library. For example the contents of `binary.d` is

```
/home/egbert/Documents/Lean/library/algebra/binary.olean: \
 /home/egbert/Documents/Lean/library/error:\ file\ 'binary'\ not\ found\ in\ the\ LEAN_PATH
```

The `LEAN_PATH` seems to point to the right thing and the file `binary` does exists.

```
> echo $LEAN_PATH
/home/egbert/Documents/Lean: 
```

This is done on Ubuntu, after cleaning the whole `Lean` folder using `git clean -Xf`.

**Comment by soonhokong** [comment]
I just tried on my Ubuntu box, but I couldn't reproduce the problem. @fpvandoorn, could you reproduce it on your machine?

**Comment by fpvandoorn** [comment]
No, for me it works fine...

**Comment by soonhokong** [comment]
@EgbertRijke, could you do the following and let us know if it works?

``` bash
cd /home/egbert/Documents/Lean/library
git clean -fxd
../bin/linja
```

**Comment by EgbertRijke** [comment]
My apologies for having been unresponsive...

I have just run these commands: and the first error message that I get is:

[6/190] "/home/egbert/Documents/Lean/b...Lean/library/data/finset/equiv.ilean" 
FAILED: "/home/egbert/Documents/Lean/bin/lean"  /home/egbert/Documents/Lean/library/data/finset/equiv.lean -o "/home/egbert/Documents/Lean/library/data/finset/equiv.olean" -c "/home/egbert/Documents/Lean/library/data/finset/equiv.clean" -i "/home/egbert/Documents/Lean/library/data/finset/equiv.ilean" 
/home/egbert/Documents/Lean/library/data/finset/equiv.lean:6:0: error: invalid import, unknown module 'init'

**Comment by leodemoura** [comment]
We don't use linja anymore on the latest version.
