### ISSUE TITLE
Fun_infos on too many arguments

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1041]
The following precondition is not actually asserted in the code:

https://github.com/leanprover/lean/blob/master/src/library/fun_info_manager.h#L91-L93

It happens to be asserted after the fact here:

https://github.com/leanprover/lean/blob/master/src/library/blast/blast.cpp#L980-981

This assertion is being triggered in cases when the `fun_info_manager` returns fewer `param_info`s than the `nargs` argument that it is passed. This will currently happen for functions with "weird" types, such as `bool.no_confusion`. 

How should this situation be handled in general? The simplest approach would be to simply remove the assertion in `blast.cpp`, and accept that we will not be able to normalize instances inside some strange (and I presume extremely rare) constructions such as:

``` Lean
import algebra.group
constants (A : Type.{1}) (s : group A) (x y : A)
definition myType (A : Type) (b : bool) : Type :=
  match b with
   | bool.tt := Π [s : group A], A
   | bool.ff := A
  end
constant myFun (A : Type) (b : bool) : myType A b
check @myFun A bool.tt s
```

Note however that this same issue appears in other places as well, and ignoring the extra arguments might not always be a viable option.

A more principled approach might be to change the `fun_info_manager` API so that it that takes an application and returns the prefix expression, a buffer of the remaining arguments, and the `param-info`s for the remaining arguments. Under this design, the `fun_info_manager` could automatically specialize (and reduce) to accommodate the actual arguments that have been passed.

Note that the following bloated pattern appears in a few different places in the code:

https://github.com/leanprover/lean/blob/master/src/library/blast/blast.cpp#L973-L980

and it might be nice to encapsulate it all in the `fun_info_manager` anyway.

**Comment by leodemoura** [comment]
I'm closing this issue since blast has been removed from Lean3.
