### ISSUE TITLE
Memory corruption with tcmalloc 2.5

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1044]
Well, this is a fun one:

```
$ bin/lean library/standard.lean 
LEAN ASSERTION VIOLATION
File: src/util/name.cpp
Line: 128
g_anonymous->is_anonymous()
```

The cause is a memory corruption in `lean::initialize_name`. I was able to ultimately trace this to an object being created by Lean's `operator new` but being destroyed by tcmalloc's new [C++14 sized `operator delete`](https://github.com/gperftools/gperftools/commit/782165fa7f2c49d6a67c2415626a1f215cc21ac2). Note that this can only happen for allocations in tcmalloc itself.

I'm not sure how to fix this. Conditionally implement the functions and hope libtcmalloc was built under the same conditions?

**Comment by leodemoura** [comment]
@kha I can't reproduce the problem right now. I'm traveling and my notebook is using a different tcmalloc. I think a possible fix is to define the new `sized operator delete` in the following file:
https://github.com/leanprover/lean/blob/master/src/util/memory.cpp#L190-L195

**Comment by Kha** [comment]
@leodemoura That should fix it, but we should still guard against older compilers, shouldn't we? I'm not experienced enough with cmake to know how to best implement this.

**Comment by soonhokong** [comment]
> I'm not experienced enough with cmake to know how to best implement this.

@Kha, could you check my [master branch](https://github.com/soonhokong/lean/commits/master)? I've added two commits to check whether a compiler has sized-deallocation feature and to use this check result to include the new definitions of sized-deallocation functions. When you confirm that it's OK, please make a PR and let's ask @leodemoura to review them.

FYI, it uses https://github.com/foonathan/compatibility.

**Comment by Kha** [comment]
@soonhokong Works, very nice!

```
-- Checking flags for C++11
-- Checking flags for C++11 - Found: -std=c++11
-- Checking flags for C++14
-- Checking flags for C++14 - Found: -std=c++14
-- Checking flags for C++17
-- Checking flags for C++17 - Found: -std=c++17
-- Checking for feature sized_deallocation
-- Checking for feature sized_deallocation - Success
```
