### ISSUE TITLE
Documentation for Emacs lean-mode

### ISSUE THREAD

**Issue by corwin-of-amber** [leanprover/lean3#1046]
There is some information in `src/emacs/README.md` and some in section 5.4 of the tutorial (which is a little bit hard to find when you need some reference, esp. since the online version of the tutorial does not have a table of contents). Could be nice to have a conclusive list of all Emacs commands and key bindings somewhere, with descriptions of what they do.

**Comment by avigad** [comment]
This is a good point. There is also a list in the appendix to the tutorial, but we'll check for completeness, and then put a copy in the README file. Thanks for the suggestion.

**Comment by avigad** [comment]
The pull request provides a more detailed list of Emacs mode commends here:

  https://github.com/leanprover/lean/blob/master/src/emacs/README.md

I also added a link from the main Github page. The list in the tutorial is not quite as good, but it is reasonable. Eventually we will do a major overhaul of the tutorial and improve that too.
