### ISSUE TITLE
rewrite ↑... at {n}

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1057]
I'm trying to unfold a specific occurence of a definition, which fails because the parameters differ from the definition matched first. [Example](https://github.com/Kha/rustabelle/blob/master/thys/core/pre.lean#L225-L226)

This is similar to #686, but because I have an unfold step, I can't specify a pattern. While I can work around it by unfolding the definition multiple times as in the example, I'd like to avoid that since the definition is quite big in my current case.

I have not looked at the code yet, but is there a fundamental reason or limitation for matching the definition including bound arguments? Alternatively, could we allow specifying patterns for unfold steps? I would _hope_ that this is mostly a parsing problem.

**Comment by leodemoura** [comment]
The latest version uses a completely new tactic framework.
