### ISSUE TITLE
"have" blocking class inference

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#1061]
The first of these works, but the second one (with a nonsense "have" in between) gives a "don't know how to synthesize ..." error.

``` lean
open classical

noncomputable definition foo : decidable (∃ x : Prop, x = x) :=
_

noncomputable definition foo' : decidable (∃ x : Prop, x = x) :=
have H : ∀ x : Prop, x = x, from λ x, rfl,
_
```

**Comment by leodemoura** [comment]
I'm closing this issue, it has been fixed in the `lean3` branch
