### ISSUE TITLE
Infering parent classes in class definition

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1066]
It seems parent structures do not participate in class inference inside a definition:

``` lean
structure A [class] := (n : ℕ)

definition f [A] := A.n

structure B [class] extends A :=
(Hf : f = 0) -- failed to synthesize placeholder
```

There is the workaround of explicitly declaring the parent, but it becomes a bit verbose with multiple parent structures.

``` lean
structure B' [class] :=
(to_A : A)
(Hf : f = 0)

attribute B'.to_A [trans_instance]
```

**Comment by robertylewis** [comment]
Another workaround is the following:

``` lean
structure B [class] extends A :=
(Hf : @A.n (A.mk n) = 0)
```

It will also be fairly verbose, but lets you avoid declaring the trans_instances by hand.

**Comment by Kha** [comment]
Ah, that's also a possibility. Unfortunately, in my case, the parent class is `order_pair`, so that would be a long invocation of `mk`.

**Comment by robertylewis** [comment]
I vaguely remember there being a way to introduce local notation in structure definitions. (e.g. to be able to use the `+` symbol in the following:

``` lean
structure foo' (T : Type) extends has_add T :=
(Hf : ∀ t1 t2 : T, (t1 + t2 = t1))
```

.) I can't find documentation of this, but if it exists, it could simplify my suggestion:

``` lean
structure B [class] extends A :=
(local notation An := @A.n (A.mk n))
(Hf : An = 0)
```

But maybe I just dreamed that this feature exists.

**Comment by robertylewis** [comment]
I'm pretty sure this problem might have come up before, because it's also the reason you can't normally write 

``` lean
structure foo' (T : Type) extends has_add T :=
(Hf : ∀ t1 t2 : T, (t1 + t2 = t1))
```

(`+` becomes `@has_add.add [has_add T], and the resolution fails.)

If you're only using the axioms/constants of an order_pair, you can do it without notation, but I suspect that's not the case for you. I'm not sure of a better workaround (or if it's fixable), but I'd guess @leodemoura has thought about this before.

**Comment by Kha** [comment]
The syntax should be like this, but `n` doesn't seem to be visible inside the notation:

``` lean
structure B'' [class] extends A := mk ::
  local notation `An` := @A.n (A.mk n)
(Hf : An = 0)
```

**Comment by robertylewis** [comment]
Hmm. That's not quite right, since this fails too (in a different place):

``` lean
structure B'' [class] extends A := mk ::
  local notation `An` := @A.n (A.mk 0)
 (Hf : An = 0)
```

**Comment by Kha** [comment]
Ah, it probably only works in `inductive` then.

**Comment by Kha** [comment]
@leodemoura If this is just a matter of constructing Pi types in the right order for elaboration and the final type, I can give it a try some time. I took a short look at `structure_cmd`, but it was a bit too short for that complexity.

**Comment by fpvandoorn** [comment]
Here is another, slightly easier workaround. But class inference for parent structures would be useful, it has come up already a couple times in the HoTT library.

``` lean
structure B [class] extends parent : A :=
(Hf : @f parent = 0)
```

**Comment by Kha** [comment]
Huh, I did not know you could declare a binding in `extends`. Nice!

**Comment by robertylewis** [comment]
Oh, cool! I had tried that, but only with parentheses around `(parent : A)`. Good to know how that works.

**Comment by leodemoura** [comment]
@Kha,

> @leodemoura If this is just a matter of constructing Pi types in the right order for elaboration and the final type, I can give it a try some time. I took a short look at structure_cmd, but it was a bit too short for that complexity.

I think we would need to create and register a local instance.
It would be great if you could give a shot.

**Comment by leodemoura** [comment]
@fpvandoorn,

> But class inference for parent structures would be useful, it has come up already a couple times in the HoTT library.

Yes, it would be very useful. It would also enable us to use notation such as `*` when axiomatizing algebraic structures (e.g., `group`).
