### ISSUE TITLE
Idea: Introduce "variables" (like as in imperative programming languages)

### ISSUE THREAD

**Issue by vporton** [leanprover/lean3#1070]
Today I've got the following idea. Not sure if the idea is good and should be implemented, but I present it for your consideration.

[Earlier I suggested that we should have hint databases.](https://github.com/leanprover/lean/issues/1018)

What is a hint database? It is a variable (in imperative programming sense) which holds either an array or a set (not sure which of these two) of some formulas.

Now I propose to support variables containing all kinds of objects (not only arrays or sets).

The variables could be updated by assignments (we don't turn it into a full featured imperative programing language, because we have no cycles and a variable thus cannot be changed inside a cycle).

The most often update is to update it by a function like `x := f(x)`. For this we may introduce a special syntax like: `update x by f`.

Now let us try to invent situations where my idea may be useful. The first thing which comes to my mind is a variable containing some kind of graph containing information of what we know for some topic.

**Comment by vporton** [comment]
Probably we should allow using of variables only in proofs and tactics, because if we have a variable in a theorem conditions the meaning of the theorem changes if we move it, that is bad.

**Comment by vporton** [comment]
Rough idea: It looks reasonable for me to (re)implement proof state as a variable.

It seems for me, that this way we could easily write tactics, which could modify the proof state in arbitrary way.

However, right now I lack understanding about how here imperative and functional programming (especially cycles and/or recursion) can be combined to implement manipulation of the proof state variable. Should a variable be local for a functional programming statement?

**Comment by vporton** [comment]
Further thought (quite not sure whether right or wrong):

To manipulate variables in any way we want, we can make tactic language fully imperative (so that we would be able even to assign variables in cycles). As far as I understand now, it is already imperative in the sense that it manipulates proof state even in cycles. We can extend it for all variables.

**Comment by vporton** [comment]
It seems for me that the best way to modify variables is: 1. make tactics into an imperative language; 2. allow to call tactics as top-level statements.

Also: It seems reasonable to disallow tactics in proofs to modify global variables. Please discuss.

**Comment by vporton** [comment]
Quite probably my idea to introduce variables of arbitrary types (not only arrays or sets of hint) may be useless.

Till now, I have invented only one example what it can be instead of a set of hints: We can keep track of the biggest known prime number.

However on [my question](http://math.stackexchange.com/q/1824145/4876) on usefulness of largest known prime, I have been basically answered that they are no useful.

However I call you to brainstorm further ideas about types of variables which may be useful.

**Comment by vporton** [comment]
Another idea is to store into a variable the values of first N (say 10 is the last we know) of some hard-to-calculate sequence.

This would be an example of variable type which is not a set but another data type.

Is it useful? Can we proceed with just N theorems `theorem f i = ...`?

**Comment by leodemoura** [comment]
This can be simulated using a new feature implemented by @Kha (user-declared attributes).
Here is an example:
https://github.com/leanprover/lean/blob/lean3/tests/lean/user_attribute.lean
