### ISSUE TITLE
Cannot compile `lean3` branch (dependencies issue with lean files in library)

### ISSUE THREAD

**Issue by danielhenrymantilla** [leanprover/lean3#1078]
There seems to be a problem with the dependecies in the `lean3` branch:

When running ([Cmake + Ninja](https://github.com/leanprover/lean/blob/master/doc/make/cmake_ninja.md))

```
git clone git@github.com:leanprover/lean.git -b lean3 lean3/
cd lean3
mkdir -p build/release
cd build/release
cmake -DCMAKE_BUILD_TYPE=RELEASE -G Ninja ../../src
ninja
```

I get a failure when it tries to compile the `.lean` files in `library`:
`FAILED: cd /Users/daniel.henrymantilla/git/lean3/library && /usr/bin/python /Users/daniel.henrymantilla/git/lean3/src/../bin/linja all tags`,

more precisely regarding a dependency in `init/meta/options.lean`: `init/meta/name.*lean` seems to be amiss.

```
FAILED: "/Users/daniel.henrymantilla/git/lean3/bin/lean"  /Users/daniel.henrymantilla/git/lean3/library/init/meta/options.lean -o "/Users/daniel.henrymantilla/git/lean3/library/init/meta/options.olean" -c "/Users/daniel.henrymantilla/git/lean3/library/init/meta/options.clean" -i "/Users/daniel.henrymantilla/git/lean3/library/init/meta/options.ilean" 
/Users/daniel.henrymantilla/git/lean3/library/init/meta/options.lean:7:7: error: invalid import, unknown module 'init.meta.name'
```

and then of course the errors carry on.

(It also happens with [Cmake + Make](https://github.com/leanprover/lean/blob/master/doc/make/cmake_make.md))

(Compilation works with `origin/master` branch)

**Comment by leodemoura** [comment]
@danielhenrymantilla `lean3` branch is working in progress.
It contains what will be Lean's next version. @dselsam and I are currently working on this branch and submitting tons of commits. This branch is not going to be stable in the near future. 
It will eventually become the master branch (hopefully in the end of the year).

**Comment by leodemoura** [comment]
I am closing this issue since lean3 is a "work in progress" branch
