### ISSUE TITLE
Emacs gets stuck in infinite loop when using Tab autocompletion

### ISSUE THREAD

**Issue by tomsib2001** [leanprover/lean3#1079]
Hi,
I don't know how to properly report this bug but sometimes when I try to use autocomplete with tab in emacs, I lose access to my emacs session and I have to restart emacs. Is this a known bug? Is there some log file I should upload? I'm on Ubuntu 14.04, using the ppa.

**Comment by robertylewis** [comment]
I've also experienced this on occasion, but I've never been able to reproduce it. You haven't noticed anything that triggers this, have you?

**Comment by tomsib2001** [comment]
My assumption is that it happens when the autocomplete is likely to yield a huge amount of answers, for example after typing one letter or accidentally hitting space before hitting tab. One other (possibly unrelated) thing that happens is that after a while in a Lean session, tab stops working and I have to restart.

**Comment by soonhokong** [comment]
This is a known problem which I was not able to fix completely. It'd be great if you can provide a way to reproduce the problem.

**Comment by robertylewis** [comment]
> One other (possibly unrelated) thing that happens is that after a while in a Lean session, tab stops working and I have to restart.

This one can be quickly fixed by restarting the Lean server process. `M-x lean-server-restart-process` (or there's a shortcut that I don't remember off the top of my head, `C-c C-r` maybe?).

**Comment by tomsib2001** [comment]
Unfortunately I have little experience in how to reproduce bugs, but I will try.

**Comment by soonhokong** [comment]
> This one can be quickly fixed by restarting the Lean server process.

This is a relatively simple workaround but not a real fix..

**Comment by soonhokong** [comment]
> Unfortunately I have little experience in how to reproduce bugs, but I will try.

Thanks!

**Comment by tomsib2001** [comment]
When I do the restart lean process command I see a message "menu-bar Lean Restart lean process" in the minibuffer but it does not seem like anything is actually happening, how could I check that?

**Comment by soonhokong** [comment]
> When I do the restart lean process command I see a message "menu-bar Lean Restart lean process" in the minibuffer but it does not seem like anything is actually happening, how could I check that?

That should be it. But in the background, you have a fresh Lean server process running.

**Comment by fpvandoorn** [comment]
Yes, I also experience this quite often. It usually happens to me after a while of work (and usually after a while of work it happens), but I haven't found something specific which triggers it. `M-x lean-server-restart-process` does fix it (but maybe you have to make 1 change in the file so that the current file is recompiled again).

**Comment by spl** [comment]
Also run into this using Aquamacs on Mac OS X.

**Comment by Kha** [comment]
When autocompletion freezes for me, I can usually abort it via C-g (I
think?). It even completes on the second try most times.

**Comment by tomsib2001** [comment]
Yes I just noticed that actually.

**Comment by leodemoura** [comment]
`--server` option has been deleted from the `lean3` branch. All `lean-server-*` emacs commands were also deleted. Autocompletion will be eventually reimplemented in the `lean3` branch using a much simpler architecture suggested by Clément Pit.
