### ISSUE TITLE
safe apply (useful for writing automation in Lean)

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#1120]
For the tableau reasoners, it would be useful to have a tactic command `is_defeq e1 e2` which determines whether e1 and e2 can be unified without instantiating any metavariables.

It also would be helpful to have `apply_safe e`, which applies `e` to the goal without instantiating any metavariables in the goal (and fails if that is not possible). It is o.k. if `apply_safe` creates new metavariables. It might also be helpful to have the same for `fapply`.

I don't care much about the name, only the functionality.

**Comment by leodemoura** [comment]
`is_def_eq` has already been added.

**Comment by avigad** [comment]
Oh! Thanks!
