### ISSUE TITLE
Segfault from new elaborator

### ISSUE THREAD

**Issue by jroesch** [leanprover/lean3#1130]
Just wanted to document this failure, this instance declaration crashes in the latest revision of my branch on top of Lean3. 

https://github.com/jroesch/lean/commit/1d060f648cdaf3a007c573ac7e4a64a2c3c6384d#diff-565f8b5221f1e31379d2d5f9755e3f7dR35

**Comment by jroesch** [comment]
The stack trace is huge, so I'm not going to post it, but it fails when touching the ref count of a cell.

**Comment by leodemoura** [comment]
fixed in the `lean3` branch
