### ISSUE TITLE
Infinite recursion in normalization

### ISSUE THREAD

**Issue by gebner** [leanprover/lean3#1134]
The following code results in an infinite recursion between `normalize` and `normalize_app`:

``` lean
eval expr.alpha_eqv (expr.mk_var 0) (expr.mk_var 0)
```

**Comment by leodemoura** [comment]
The `expr.alpha_eqv` is a meta definition and its is treated by the kernel as an axiom.
So, the kernel normalizer tries to normalize `expr.mk_var 0` which expands into `expr.var (unsigned.of_nat 0)`.
Here is the problem, the definition of  `unsigned.of_nat` is

```
definition of_nat (n : nat) : unsigned :=
if H : n < unsigned_sz then fin.mk n H else fin.mk 0 zero_lt_unsigned_sz
```

Where `unsigned_sz` is `2^32`. The kernel takes forever trying to normalize `2^32` as  `succ (succ ... zero))`

**Comment by leodemoura** [comment]
Note that `vm_eval` is very efficient because it uses the builtin implementation for `expr.alpha_eqv`, and `nat` are implemented using big numbers in the lean VM.
