### ISSUE TITLE
master broken: LEAN ASSERTION VIOLATION in tc_multigraph.cpp

### ISSUE THREAD

**Issue by catalin-hritcu** [leanprover/lean3#1138]
Hello there. I have tried building the Lean `master` branch for the first time using the instructions here:
https://github.com/leanprover/lean/blob/master/doc/make/ubuntu-12.04-detailed.md#build-lean-in-debug-mode
Things failed at some point and I'm not sure how to proceed now:

```
[9/104] "/home/hritcu/Research/others/lean/bin/lean"  /home/hritcu/Rese...i "/home/hritcu/Research/others/lean/hott/algebra/ordered_field.ilean" 
FAILED: "/home/hritcu/Research/others/lean/bin/lean"  /home/hritcu/Research/others/lean/hott/algebra/ordered_field.hlean -o "/home/hritcu/Research/others/lean/hott/algebra/ordered_field.olean" -c "/home/hritcu/Research/others/lean/hott/algebra/ordered_field.clean" -i "/home/hritcu/Research/others/lean/hott/algebra/ordered_field.ilean" 
LEAN ASSERTION VIOLATION
File: /home/hritcu/Research/others/lean/src/library/tc_multigraph.cpp
Line: 124
tgt.is_anonymous()
(C)ontinue, (A)bort, (S)top, Invoke (G)DB
INVALID COMMAND
```

Is Lean `master` the right thing to try? If so how can I make this work?

**Comment by jroesch** [comment]
@catalin-hritcu I'm not sure about the current state of master, Leo will have to clarify. The bleeding edge branch we are working from is the `lean3` branch if you are interested (note: many features aren't complete yet).

**Comment by leodemoura** [comment]
@catalin-hritcu I fixed the issue in the `master` branch. As @jroesch said, we are working on the `lean3` branch. The meta-programming features I presented on Tuesday are only available on the `lean3` branch.  Some features are still working in progress, and we still have to port the standard library to `lean3`. I'm looking forward to see you again in Redmond next week.

**Comment by leodemoura** [comment]
2014b86cf7234f24
