### ISSUE TITLE
Reserving notations for use within inductive types

### ISSUE THREAD

**Issue by brendanzab** [leanprover/lean3#1149]
In Coq it seems like you can reserve notation before defining inductive types. Eg, in [Software Foundations](https://www.cis.upenn.edu/~bcpierce/sf/current/Imp.html#lab312):

``` coq
Reserved Notation "e '⇓' n" (at level 50, left associativity).

Inductive aevalR : aexp → nat → Prop :=
  | E_ANum : ∀(n:nat),
      (ANum n) ⇓ n
  | E_APlus : ∀(e1 e2: aexp) (n1 n2 : nat),
      (e1 ⇓ n1) → (e2 ⇓ n2) → (APlus e1 e2) ⇓ (n1 + n2)
  | E_AMinus : ∀(e1 e2: aexp) (n1 n2 : nat),
      (e1 ⇓ n1) → (e2 ⇓ n2) → (AMinus e1 e2) ⇓ (n1 - n2)
  | E_AMult : ∀(e1 e2: aexp) (n1 n2 : nat),
      (e1 ⇓ n1) → (e2 ⇓ n2) → (AMult e1 e2) ⇓ (n1 * n2)

  where "e '⇓' n" := (aevalR e n) : type_scope.
```

Is there a way to do this in Lean?

Here are my types:

``` lean
open nat

inductive aexp : Type :=
| num : ℕ → aexp
| add : aexp → aexp → aexp
| sub : aexp → aexp → aexp
| mul : aexp → aexp → aexp

reserve infixl ` ⇓ `:50

inductive aeval : aexp → ℕ → Prop :=
| num : ∀ (n : ℕ),
        aeval (aexp.num n) n

| add : ∀ (a₁ a₂ : aexp) (n₁ n₂ : ℕ),
        aeval a₁ n₁ →
        aeval a₂ n₂ →
        aeval (aexp.add a₁ a₂) (n₁ + n₂)

| sub : ∀ (a₁ a₂ : aexp) (n₁ n₂ : ℕ),
        aeval a₁ n₁ →
        aeval a₂ n₂ →
        aeval (aexp.sub a₁ a₂) (n₁ - n₂)

| mul : ∀ (a₁ a₂ : aexp) (n₁ n₂ : ℕ),
        aeval a₁ n₁ →
        aeval a₂ n₂ →
        aeval (aexp.mul a₁ a₂) (n₁ * n₂)

infixl ` ⇓ ` := aeval

check aexp.num 1 ⇓ 1
```

I'm not sure how to apply my operator previous inductive type though. I'd like to be able to do something like:

``` lean
reserve infixl ` ⇓ `:50

inductive aeval : aexp → ℕ → Prop :=
| num : ∀ (n : ℕ),
        aexp.num n ⇓ n

| add : ∀ (a₁ a₂ : aexp) (n₁ n₂ : ℕ),
        a₁ ⇓ n₁ →
        a₂ ⇓ n₂ →
        aexp.add a₁ a₂ ⇓ n₁ + n₂

| sub : ∀ (a₁ a₂ : aexp) (n₁ n₂ : ℕ),
        a₁ ⇓ n₁ →
        a₂ ⇓ n₂ →
        aexp.sub a₁ a₂ ⇓ n₁ - n₂

| mul : ∀ (a₁ a₂ : aexp) (n₁ n₂ : ℕ),
        a₁ ⇓ n₁ →
        a₂ ⇓ n₂ →
        aexp.mul a₁ a₂ ⇓ n₁ * n₂

and infixl ` ⇓ ` := aeval
```

I tried searching the repo, but couldn't really find any similar examples. Is this possible, or is it just not implemented yet, or have you made an explicit decision not to allow this?

**Comment by jroesch** [comment]
I'm not aware of us supporting this style of notation definition (yet). Its possible a clean solution could fall out from the planned parser extensions, or maybe just allowing lazy name resolution in notations.

**Comment by brendanzab** [comment]
Yeah, I have a feeling that you are pretty concerned with having a fast parser without backtracking, which is why I thought it might be an explicit choice. But if it might be a possibility, then that would be great! I know things like the typing relation can get pretty unwieldy without some shorthand :(

**Comment by fpvandoorn** [comment]
Actually, it is possible, but I think it is not documented. The syntax is 

``` lean
reserve infixl ` ⇓ `:50

inductive aeval : aexp → ℕ → Prop :=
infixl ` ⇓ ` := aeval
| num : ∀ (n : ℕ),
        aexp.num n ⇓ n

| add : ∀ (a₁ a₂ : aexp) (n₁ n₂ : ℕ),
        a₁ ⇓ n₁ →
        a₂ ⇓ n₂ →
        aexp.add a₁ a₂ ⇓ n₁ + n₂

| sub : ∀ (a₁ a₂ : aexp) (n₁ n₂ : ℕ),
        a₁ ⇓ n₁ →
        a₂ ⇓ n₂ →
        aexp.sub a₁ a₂ ⇓ n₁ - n₂

| mul : ∀ (a₁ a₂ : aexp) (n₁ n₂ : ℕ),
        a₁ ⇓ n₁ →
        a₂ ⇓ n₂ →
        aexp.mul a₁ a₂ ⇓ n₁ * n₂

infixl ` ⇓ ` := aeval
check aexp.num 1 ⇓ 1
```

Some remarks:
- You have to declare the notation again after defining the inductive type (it is somewhere on Leo's long to do list to fix this, but probably near the bottom)
- Something similar which doesn't work yet is define notation inside a structure definition for one of the projections. That is, something like this is not yet possible

``` lean
structure semigroup [class] (A : Type) :=
(mul : A → A → A)
(infixr * := mul)
(mul_assoc : ∀a b c, (a * b) * c = a * (b * c))
```
- [here](https://github.com/leanprover/lean/blob/7e9f574ef36324af9d12b61687312596c7919a9f/tests/lean/run/soundness.lean#L63-L76) is another example to see it in use, and [here](https://github.com/leanprover/lean/issues/500#issuecomment-98059166) are some comments about the feature.
- @avigad: is it on the to do list for the next version of the tutorial to mention this feature?

**Comment by avigad** [comment]
I didn't know about this feature...

> @avigad: is it on the to do list for the next version of the tutorial to mention this feature?

It is now! Thanks.

**Comment by leodemoura** [comment]
BTW, @Kha recently implemented a relevant feature that allows us to write

```
structure semigroup [class] (A : Type) extends has_mul A :=
(mul_assoc : ∀a b c, (a * b) * c = a * (b * c))
```

**Comment by brendanzab** [comment]
Thanks for the great answer @fpvandoorn! Should we close this, and make a new issue regarding adding it to the documentation?

**Comment by avigad** [comment]
It is still on my to-do list, and also to document the means for referring to parent structures in a structure definition. I won't forget.
