### ISSUE TITLE
Warning when match case is just a variable.

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean3#1162]
I think Lean should issue a warning when the first case in a match expression is a variable.  Otherwise, a simple typo makes it very easy to make a case accidentally match every pattern.

I've included some code below illustrating the problem; the definition of `ppday` is wrong here, but this seemed like a very easy mistake to make.

```
inductive weekday : Type :=
| sunday : weekday
| monday : weekday
| tuesday : weekday
| wednesday : weekday

definition ppday (d : weekday) : nat :=
match d with
| sunday    := 0
| monday    := 1
| tuesday   := 2
| wednesday := 3
end

eval ppday weekday.tuesday
0
```

Another alternative would be to issue a warning if cases can be statically determined to be never used as in the code below.

**Comment by leodemoura** [comment]
This issue has been addressed in the `lean3` branch (see commit above). The definition `ppday` produces the following error message now:

```
1162.lean:10:12: error: equation compiler error, equation #2 has not been used in the compilation, note that the left-hand-side of equation #1 is a variable
```
