### ISSUE TITLE
RFC: Parameters/apply handler on user attributes

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1167]
(template shamelessly borrowed from http://github.com/rust-lang/rfcs)
# Summary

Provide user-declared attributes with a way to
- accept arguments of arbitrary types using the same interface as tactics in `begin end` blocks (`@[unfold 1 2 3]`, `@[intro]`, `@[intro 42]`)
- install a callback called on attribute application that receives these arguments and can do both sanity checks and modify the environment
# Motivation

Both features have immediate applications for automation attributes. @avigad mentioned the use case of an `@[auto.intro]` attribute that (optionally) takes a priority and installs an `@[auto.intro_rule]` definition on use. He further pointed out that in this case the attribute manager doesn't even need to persist the attribute argument since it's already persisted in the generated `intro_rule` definition. In general, we can leave persisting arguments to the application callback for now, so it makes sense to implement both features at the same time.
# Detailed design

A new (C++) attribute `user_attribute.on_apply` can be applied to definitions that take a name plus optionally parameters from `tactic.interactive.types` and produce `command`, which will be applied to the global environment:

``` lean
meta def opt_qexpr : Type := option qexpr -- doesn't exist yet
meta def generate_intro_rule : name → option expr → command := ...

@[user_attribute.on_apply auto.intro]
meta def intro_rule.on_apply (dest : name) (prio : opt_qexpr) : command :=
do
  prio ← match prio : opt_qexpr → tactic (option expr) with
  | none := return none
  | some q := (do
      e ← to_expr q,
      eval_expr ℕ e,
      return $ some e)
    <|> fail "expected non-negative constant as priority argument"
  end,
  generate_intro_rule dest prio
```

The single argument to `user_attribute.on_apply` must be a registered `user_attribute`. Only the callback registered last will be called.
# Drawbacks

Even if we do persist the arguments in C++, we would have to generate separate accessors per `user_attribute` because they wouldn't share a common function signature like below.
# Alternatives

Implement a strongly typed API that accepts exactly one parameter:

``` lean
meta class user_attribute.parameterized (attr : user_attribute) :=
(Param : Type)

meta constant user_attribute.get_param (attr : user_attribute) [user_attribute.parameterized attr]
  : name → tactic (user_attribute.parameterized.Param attr)

meta class user_attribute.on_apply_callback (attr : user_attribute) :=
(on_apply : name → command) -- would presumably be executed in an env where `get_param` works
```

While the API might be nicer, there would be some immediate drawbacks: less flexibility, C++ is responsible for persisting, `user_attribute.parameterized` would live in `Type.{2}`.
# Unresolved questions

**Comment by avigad** [comment]
Here is a very general question: do we want to have a general mechanism for turning off or disabling attributes that have previously been assigned? It seems dangerous to forcibly remove an object from the environment, but we can store booleans somewhere in the environment that indicate whether something is active.

In that case, do we need an attribute-disable handler that does whatever special-purpose bookkeeping might be relevant?

And -- uh oh! -- what gets stored in the olean file? If file A assigns an attribute, files B and C delete it in parallel, file D imports B and turns it on, and file E imports D and C, what is the ultimate state? Oy!

Isabelle's attributes (like simp and auto rules) can be enabled and disabled, but it seems like a messy process.

So maybe attributes should never be unassigned?

**Comment by gebner** [comment]
> And -- uh oh! -- what gets stored in the olean file? If file A assigns an attribute, files B and C delete it in parallel, file D imports B and turns it on, and file E imports D and C, what is the ultimate state? Oy!

Clearly the attribute is turned off after this sequence of events. :smile:

As far as I understand the current lean module system, we can consider a module to be the list of the modifications it performs to the environment--an environment transaction log, if you will.  We write precisely this list of modifications to the olean file.  Now deleting and adding attributes are modifications, so they should be included in this list.  When importing[0], we do a post-order traversal on the dependency DAG[1], at each point replaying the modifications made by that (transitively) imported module.

So in the example, we would import the dependent modules in the following order:
1. A: attribute is set
2. B: attribute is unset
3. D: attribute is set
4. C: attribute is unset

[0] With the current multi-threaded import some of these operations can occur in a different order if e.g. they modify an rb_map, but there is special-case support for the operations which need to be performed in a specific order.
[1] This is a DAG where the outgoing edges of each node are ordered (by the order they are listed in the import statement of each module).

**Comment by Kha** [comment]
@avigad we already have attribute removal, but it's deliberately restricted to local scopes: https://github.com/leanprover/lean/blob/lean3/tests/lean/caching_user_attribute.lean#L21

The current implementation allows attribute removal only for attributes that have registered either both `after_set` and `before_unset` C++ callbacks, or none of them. So using `user_attribute.on_apply` will automatically make your attribute non-removable. I didn't think of exposing the second callback to Lean (I forgot all about it), but it wouldn't be much work.

**Comment by Kha** [comment]
> restricted to local scopes

(so just what you'd need for Isabelle's `simp del: foo`)

**Comment by avigad** [comment]
Thanks for this information. I can see advantages and disadvantages to both approaches. If a certain simp rule is causing problems for some project, it would be nice to turn it off at a single entry point for the project and leave it off, rather than have to turn it off in every single file. But it would be confusing to have settings change with every import, and even if there is an internal protocol, it will often feel nondeterministic as to which imports take precedence. For example, suppose the user writes "import foo bar", but the second import is unnecessary, because it is including in the import chain for foo. Do we import bar again just to make sure that its settings take precedence? What about bar's hereditrary imports? At least the current approach is simple and reliable. I don't have a strong opinion about this.

By the way, the same issues hold for parameters. Suppose I assign an [intro] attribute with a certain priority, i.e. [intro 50]. Can I later reassign the attribute with a different priority, e.g. [intro 25]? Attributes are starting to feel like options, so maybe attributes and options should be handled in the same way.

As far as the intro / intro_rule example, I can think of at least two ways to handle the state change:
- When an [intro] rule is disabled, a handler can decide to disable the corresponding [intro_rule].
- Each intro rule can store its parent (if there is one), and the "get cache" function for intro rules can filter the ones whose parents are unset.
  Both seem o.k. to me.

**Comment by Kha** [comment]
> If a certain simp rule is causing problems for some project, it would be nice to turn it off at a single entry point for the project and leave it off, rather than have to turn it off in every single file.

Yes, I've definitely done that a few times in Isabelle. We can always go back and allow deletion globally.

> By the way, the same issues hold for parameters.

You're right, and I'm not sure how to handle that for user attributes. Remove and re-add the attribute (which would implicitly fail for attributes that only have an `on_apply` handler)?

> When an [intro] rule is disabled, a handler can decide to disable the corresponding [intro_rule].

This option sounds nicer to me, but I'm not sure how we would implement it. If we derive the intro_rule definition name purely from the intro def name, we'd get a conflict if we import two theories that independently tag the same def with `[intro]`. If we instead generate a fresh name, I don't see how we can get it back in the removal callback.

I'm starting to wonder about a more basic question: Now that Leo has added support for user attribute cache handlers that can depend on other attributes, does it actually make sense to derive intro_rule defs eagerly from intro defs?

**Comment by leodemoura** [comment]
> While the API might be nicer, there would be some immediate drawbacks: less flexibility, C++ is responsible for persisting, user_attribute.parameterized would live in Type.{2}.

This is another example where having "output" type class parameters would be perfect.

``` lean
meta class user_attribute.parameterized (attr : user_attribute) (Param : Type) 

meta constant user_attribute.get_param {Param : Type} (attr : user_attribute) [user_attribute.parameterized attr Param]
                                       : name → tactic Param
```

Here `Param : Type` would be tagged as output.

**Comment by leodemoura** [comment]
> While the API might be nicer, there would be some immediate drawbacks: less flexibility, C++ is responsible for persisting, user_attribute.parameterized would live in Type.{2}.

Independently of whether we support type class output parameters or not, we should allow users to write`tactic A` even when `A` is not in universe `1`. This is a minor change at `tactic.lean`, and would address similar problems in the future.

**Comment by leodemoura** [comment]
@kha I'm using the attribute manager for many tactics. Even the ones implemented in C++.
The main advantage is that we get all the cache management for free. 
I'm using the following idiom:
1- Define a new data structure (e.g., `hinst_lemmas`)
2- Define an attribute generator in Lean (e.g., https://github.com/leanprover/lean/blob/master/library/init/meta/smt/ematch.lean#L116). The idea is to have `mk_*` function for creating attributes that give me back the data structure defined in the previous step.
3- Create a default attributes for our new tactic (e.g., https://github.com/leanprover/lean/blob/master/library/init/meta/smt/smt_tactic.lean#L13-L14).
4- Have a configuration option for changing which attribute is used (e.g., https://github.com/leanprover/lean/blob/master/library/init/meta/smt/smt_tactic.lean#L42).

Everything is working great. The only missing thing is validation. For example, not every lemma is a valid `hinst_lemma`. However, right now, we only get the error when we try to retrieve the attribute data (https://github.com/leanprover/lean/blob/master/src/library/tactic/smt/smt_state.cpp#L407).

**Comment by Kha** [comment]
Since we now have output parameters, should we go with
```lean
meta class user_attribute.parameterized (attr : user_attribute) (α : out_param Type) [has_quote α] :=
(parser : lean.parser α)

meta constant user_attribute.get_param {α : Type} (attr : user_attribute) [user_attribute.parameterized attr α]
                                       : name → tactic α
```
?

Having just a single parameter is not a real restriction using custom parsers that can encode data in tuples.

**Comment by Kha** [comment]
@leodemoura For validation, I think we should just expose the C++ API in `user_attribute`:
```lean
(after_set    : _root_.name → bool → nat → command := λ d global prio, tactic.skip)
(before_unset : _root_.name → bool → command := λ d global, tactic.skip)
```
We can analyze instances to be registered as to whether they override these fields, so that attributes that define just `after_set` are not removable just like in C++.

**Comment by leodemoura** [comment]
@Kha Can we close this issue?

**Comment by Kha** [comment]
@leodemoura The parameters part is still missing

**Comment by Kha** [comment]
> The parameters part is still missing

Not any more! (#1809)
