### ISSUE TITLE
lean-server: usability of "show goal"

### ISSUE THREAD

**Issue by gebner** [leanprover/lean3#1169]
Consider the following incomplete proof:

``` lean
lemma add_comm' (n m : nat) : n + m = m + n :=
begin induction n end
```

With the current `show-goal-at-pos`, you can only see the tactic state before the induction tactic.  There seems no to be no point where we show the (failed) tactic state after the induction tactic.

In addition, we should probably clear the `*lean-info*` buffer if we cannot find a tactic state at a given point.

**Comment by leodemoura** [comment]
> In addition, we should probably clear the _lean-info_ buffer if we cannot find a tactic state at a given point.

The commit above doesn't address this one.
Any suggestions?
Should we have another exception (e.g., `show_goal_no_found_exception`)?

**Comment by gebner** [comment]
Ah, that's something purely on the emacs side.  We do get the information that there is no goal at that point, but tight now we just show an error message at the bottom of the screen.  However the last tactic state still remains visible in the `*lean-info*` buffer.
