### ISSUE TITLE
Lean evaluator performance degredation

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean3#1195]
The Lean eval command seems to get progressively slower on computations with more bindings on the bitvec library.

This is was tested with a release build of the lean3 branch at commit 31e159b80c8ad70dfc6a6a3f530fb1c3311b5473.

The code below does a shift-left operation using repeated adds (it's intentionally not optimized).

```
def bv_my_shl {n} (x : bitvec n) : ℕ → bitvec n
| 0 := x
| (nat.succ m) :=
  let y := bv_my_shl m
   in y + y
```

When running the `eval` command on an expression of the form `bv_my_shl (7 : bitvec 8) n` the performance seems to get quadratically slower with respect to the size of `n`:
  
```
-- 0.24s
--eval bv_my_shl (7 : bitvec 8) 10
-- 0.24s
-- eval bv_my_shl (7 : bitvec 8) 11
-- 0.73s
--eval bv_my_shl (7 : bitvec 8) 20
-- 0.88s
--eval bv_my_shl (7 : bitvec 8) 21
-- 4.28s
--eval bv_my_shl (7 : bitvec 8) 31
-- 4.90s
-- eval bv_my_shl (7 : bitvec 8) 32
-- 5.50s
--eval bv_my_shl (7 : bitvec 8) 33
-- 6.16 seconds
eval bv_my_shl (7 : bitvec 8) 34
```

I initially suspected this could be loss of sharing, but further testing with use of a doubling function  with no repeated variables suggested that's not the cause, or at least not the only cause.  It doesn't seem like this problem is specific to the bitvec library as one would expect the performance of `bv_my_shl` should be linear with respect to the shift amount.

The performance problem also manifests itself when defining larger bitvector literals `eval (0x40000 : bitvec 32)`.

**Comment by leodemoura** [comment]
Joe, `eval` is a symbolic evaluator based on the `whnf` procedure (weak-head-normal-form).
For example, it processes `let`-expressions `let x := v in t` by replacing `v` in `t`.
This is why you are getting exponential behavior in this example.

For ground terms, we can use `vm_eval`. It compiles the expression into bytecode and execute it using an efficient interpreter. Perhaps, in the future, we should rename these commands (e.g., `eval` to `reduce` and `vm_eval` to `eval`). 

BTW, to execute these examples efficiently, you need the latest version. Today, I fixed a problem in the code generator. It was eagerly expanding let-expressions (see: https://github.com/leanprover/lean/commit/62d6b885709828f56fd86c66d85ce1cb4ce6d870).

**Comment by joehendrix** [comment]
Ah, In some other code, I had replaced the call to add with a linear doubling procedure, and had the same behavior, but I now see that still had repeated variables inside some of the low level functions.

I think renaming the functions would help clarify things, or a symbolic evaluator that did call-by-need (assuming that is feasible), but I'll close this.
