### ISSUE TITLE
New lean server protocol

### ISSUE THREAD

**Issue by gebner** [leanprover/lean3#1197]
With #1178 on its way, it becomes necessary to think about a revision of the server protocol.  The main big limitation with the current protocol is that it only handles a single file per server process.  Since adding support for multiple files is a significant change, it might make sense to roll up some other changes as well.

 * Support for multiple files.  The protocol somewhat supports this already, the immediate stumbling block is that the complete and info commands do not specify the filename.
   * It would be nice to have the list of currently visible files and maybe even line number ranges as well, in order to prioritize the visible stuff.
   * Unloading files?
 * Push messages.  Right now the only way to incrementally get error messages is by polling; we try and see which messages are already available, and if there are not complete yet, we try again 500ms later.  It would be nice if we could get those messages earlier.
   * At the moment, the server cannot send unsolicited messages; every response necessarily corresponds to a request.  One way to fix this is to introduce sequence numbers for every request: the server then includes this number in the corresponding response and the client can the figure out which response corresponds to which request (or was unsolicited).
 * What should the `LEAN_PATH` be?  With the one-server-per-file approach we do the following: we look for the closest parent directory that has a `.project` file and start the server there.
 * How do we want to implement the debugger interface?  Should we do it via the server interface?  (We do not have to do this right now.  I just want to make sure that we can easily integrate debugging later on.)

@Kha @jroesch Ideas, comments, wishes?

There was a bit of talk on slack about the [LSP](https://github.com/Microsoft/language-server-protocol), which is used by VS Code and the new Rust IDE support.  Does anybody have an opinion on whether/how we should adopt/copy it?
Personally I don't think it would buy us much to implement it directly.  Pretty much the only editor that supports it at the moment is VS Code, and we would still need to develop syntax highlighting and an input method to get VS Code support.  On the other hand, the LSP is focused pretty narrowly on syntax checking, and probably won't ever support debugging. For a potential VS Code plugin, I'd rather do a proxy that translates between lean and LSP, and also implements the VS-Code-specific debug protocol.

**Comment by Kha** [comment]
> At the moment, the server cannot send unsolicited messages

That's mostly a restriction of tq.el, no? As long as the server makes sure never to send out outdated responses, I would assume that with something like `process-filter` the client could just handle and display that information, without actually relating it to a prior request.

> What should the LEAN_PATH be? With the one-server-per-file approach we do the following: we look for the closest parent directory that has a .project file and start the server there.

All I can think of right now is taking the union of all projects roots. Somewhat related to multiple points, we may want to make sure jumping into the standard library doesn't kick off too much work. Ideally, we shouldn't do anything when entering a file with an up-to-date olean file, but then we can't even do another go-to definition. We would have to cache the info_manager on disk for that.

> There was a bit of talk on slack about the LSP, which is used by VS Code and the new Rust IDE support. Does anybody have an opinion on whether/how we should adopt/copy it?

As you said, there's not much benefit to supporting LSP right now.

**Comment by gebner** [comment]
> That's mostly a restriction of tq.el, no? As long as the server makes sure never to send out outdated responses, I would assume that with something like process-filter the client could just handle and display that information, without actually relating it to a prior request.

Yes, that is a restriction of tq.el and we just need to roll our version with `process-filter` as you said.

>> What should the LEAN_PATH be?
>
> All I can think of right now is taking the union of all projects roots. 

This is one possiblity.  We start a single server per emacs, and add an extra command to the server that allows changing the LEAN_PATH.  As long as nobody tries to have their own version of `data/nat/basic.lean` this would probably work fine.

Another possibility is to start one server per project.  This would require a bit more infrastructure in emacs as we would need to keep track of a map of project roots to server processes, but would not require fiddling with the LEAN_PATH.

> Somewhat related to multiple points, we may want to make sure jumping into the standard library doesn't kick off too much work. Ideally, we shouldn't do anything when entering a file with an up-to-date olean file, [...]

I think it's reasonable to parse the file and elaborate all the proofs again.  Then we would have all the info-manager support.  We should just make sure that this doesn't cause the whole standard library to be recompiled.
What if the user accidentally changes a file in the standard library?
