### ISSUE TITLE
Non-refl lemmas for structural recursion

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1198]
```Lean
constant F : ℕ → Type

inductive Foo : ℕ → Type
| H : Π (n : ℕ), F n → Foo n
| k : F 0 → Foo 0

noncomputable def foo : Π {n : ℕ}, Foo n → Prop
| n (Foo.H .n xs) := true
| 0 (Foo.k xs)    := false
```
`foo._main` does `nat.cases_on` and so the first equation does not hold definitionally. All four lemmas generated for `foo` are refl lemmas, and in particular no lemma is generated for the first user-provided equation. One can prove it easily though:
```Lean
lemma foo.equations.non_refl_1 : ∀ {n : ℕ} {xs : F n}, foo (Foo.H n xs) = true :=
begin intros n xs, cases n with n, reflexivity, reflexivity end
```
Have you considered auto-generating such lemmas?

**Comment by leodemoura** [comment]
Quick answer:
```
constant F : ℕ → Type

inductive Foo : ℕ → Type
| H : Π (n : ℕ), F n → Foo n
| k : F 0 → Foo 0

noncomputable def foo : Π {n : ℕ}, Foo n → Prop
| .n (Foo.H n xs) := true
| .0 (Foo.k xs)    := false

print foo.equations.eqn_1
print foo.equations.eqn_2
```

**Comment by leodemoura** [comment]
> foo._main does nat.cases_on twice and so the first equation does not hold definitionally. 

It does `nat.cases_on` only once. The second (nested) `cases_on` is on `Foo`.
This is the expected behavior since you have used explicit patterns in the first argument.
You can avoid that by making the first argument as an inaccessible pattern (see example in the comment above)

> Have you considered auto-generating such lemmas?

Yes, and I decided not to do it. At least, not in the near future. There are much more important features in the TODO list.

**Comment by dselsam** [comment]
Thanks very much, this solves the problem I had that this example is derived from. I had a few pathological cases a while back for which I could not make the first `nat` inaccessible, and I got into the bad habit of not even considering marking it inaccessible.

> It does nat.cases_on only once.

Yes, my original example used `1` instead of `0` and so it was twice, and I forgot to change the prose.
