### ISSUE TITLE
RFC: Projects and dependencies

### ISSUE THREAD

**Issue by gebner** [leanprover/lean3#1200]
Most modern programming languages have designated build tools that allow the easy inclusion of third-party code. (I'm thinking of haskell/cabal, rust/cargo, js/npm, coq/opam, ...)
Lean doesn't (to the best of my knowledge), and this significantly limits its extensibility (e.g. you cannot use the resolution prover from the `library_dev` repo anywhere else..).

Practically speaking, we only have two usable ways to reuse code right now: 1) put it into the standard library, or 2) copy&paste it into the same directory.  (This is because we set the LEAN_PATH to the current directory plus the standard library.)

I think we should have an easy and standard way to include external dependencies.  Has anyone worked on this?  I kind of expect this question to come up at POPL as well, so it would be good to have at least a rough plan on what we want to do.

**Comment by Kha** [comment]
Quick remark: You _can_ add dependency roots via the LEAN_PATH environment variable, there's just absolutely no tooling around it right now. I would argue this information could go into the `.project` file.

**Comment by leodemoura** [comment]
@jroesch has been prototyping a package management system: https://github.com/jroesch/mu

**Comment by leodemoura** [comment]
BTW, @jroesch said he eventually wants to write the package manager in Lean. I think it would be a good motivation for extending the IO monad.

**Comment by gebner** [comment]
I think in the long run having the build tool written in lean is cool, and definitely a much smaller dependency than rust. This seems to be the repo for the package manager in lean: https://github.com/jroesch/muri
(To be honest, I like the `mu` name much better, and it also fits well with the lean theme.  No build system should be called `muri`, IMHO.)

AFAICT, neither has any actual build or dependency resolution functionality at the moment.  @jroesch Do you already have concrete plans?

**Comment by jroesch** [comment]
@gebner lost track of this issue on vacation, mu was attempt #2, they were just repository names instead of something lame like `lbuild`. I've been focusing on improving the native compiler the past week. Currently I don't think we have design consensus for a standard library. Especially one that allows us to implement a build tool quickly, and be a useful standard library for doing verification + programming.

I would rather implement it in a more mature language so we can do parsing, invoking git, and so on, figure out the design and eventually port. I am open to using Haskell or Rust to do so, but would rather not try and implement a tool in C++, it adds unnecessary pain for no real reason.

**Comment by gebner** [comment]
> Currently I don't think we have design consensus for a standard library. Especially one that allows us to implement a build tool quickly, and be a useful standard library for doing verification + programming.
> I would rather implement it in a more mature language so we can do parsing, invoking git, and so on, figure out the design and eventually port.

I agree, and this sounds like a good plan.

However I'm not sure how I feel about requiring Haskell or Rust.  As much as I like either language, they are huge dependencies.  It will probably take a while until we can do the build tool in lean, and during that time people will want/need to use the prototype.  From a strategic point of view, I'd rather choose a more lightweight dependency such as python for the prototype.

**Comment by leodemoura** [comment]
@gebner Should we close this one?

**Comment by gebner** [comment]
@leodemoura This issue is still wide open.  But it's mainly here to gather discussion, not to report a bug.

**Comment by leodemoura** [comment]
> @leodemoura This issue is still wide open. But it's mainly here to gather discussion, not to report a bug.

You are right, I just reread the thread.

**Comment by alashworth** [comment]
Just chiming in here that I have used Conda to package a mixed Python and C++ app and it works very well. It is language agnostic and I believe it might be worth investigating. Certainly I think getting started with it would be much less work than developing a package manager from scratch.

[Conda](https://github.com/conda/conda)

**Comment by gebner** [comment]
As promised, to get the discussion rolling, let me present a more-or-less concrete proposal for a package manager for Lean.  This is really just a first draft, please feel free to demand major changes and complete rewrites!

The directory layout of a package (as checked into git) would look as follows:
```
myproject
├── leanpkg.toml
├── myfile.lean
├──  ...
```

After installing the dependencies it would look this:
```
myproject
├── leanpkg.toml
├── myfile.lean
├──  ...
├── leanpkg.path
└── _target
    └── deps
        ├── library
        │   └──  ...
        ├── measure_theory
        │   └──  ...
        └── topology
            └──  ...
```

The package metadata is stored in the `leanpkg.toml` file using the well-hyped TOML format.
```toml
[package]
name = "myproject"
version = "0.1"

[dependencies]
library = { git = "https://github.com/leanprover/library", rev = "3.2.0" }
measure_theory = { git = "https://github.com/leanprover/measure_theory", rev = "master" }
```
The syntax is deliberately close to cargo, in order to appeal to a large number of lean developers.  (N.B.: I've never used cargo.)  Another possible dependency type would be `{ path = "/home/leo/projects/tmp/" }` for local dependencies.

Running `leanpkg build` produces a `leanpkg.path` file that contains the search path:
```
_target/deps/library
_target/deps/topology
_target/deps/measure_theory
```

Dependencies are resolved (that is, package sources are assigned to package names) via a pre-order traversal of the package dependency graph.  We only allow one source for each package name (e.g. "topology").  Conflicts are resolved by taking the first package source that we encounter.  Since we resolve a package's dependencies section first, before proceeding to the dependencies, the top-level package can "override" any packages.

For tooling, we provide a `leanpkg` command line tool that supports the "usual" commands:
```
leanpkg new
leanpkg build
leanpkg upgrade
leanpkg require https://github.com/leanprover/analysis
leanpkg install https://github.com/leanprover/library
  # user-local installation for use in non-package files
```

Policy changes:
 * We change how the `lean` executable, as well as emacs, determine the search path: if the LEAN_PATH environment variable is set, we use its value.  Otherwise we look in all ancestor directories for a `leanpkg.path` file.  If we cannot find such a file, we try `~/.lean/leanpkg.path` (on unix) for the user-local installation.  The search path contains by default only the bundled library (which continues to be resolved according to the current heuristics).  If a `leanpkg.path` file has been found, its content is added to the search path.
 * In emacs, if we there is no `leanpkg.path` file but there is a `leanpkg.toml` file, we prompt the user to run `leanpkg build`.
 * In vscode, the Lean extension is activated if and only if there exists a `leanpkg.toml` file in the root directory of the current workspace.
 * Relative imports outside of the current package, absolute imports that are not included in the package's dependencies, any imports in non-package files, are all unspecified.

We can implement the `leanpkg` tool in Lean itself.  The only missing piece would be a TOML parser.  Spawning external processes (git) is already possible.  In the long term, the `leanpkg` tool might include more features, and have dependencies of its own--bootstrapping might become an issue then.

The tool itself would not need to do much.  For example, `leanpkg build` would only need to do:
 1. `git clone` for all the git dependencies
 2. read their `leanpkg.toml` files, and maybe go back to 1.
 3. write the `leanpkg.path` file
 3. run `lean --make`

**Comment by gebner** [comment]
So, I made an early prototype of the `leanpkg` tool.  [See here.](https://github.com/leanprover/lean/compare/master...gebner:leanpkg)

 * I reused @avigad's parser code from library_dev.  Unfortunately it seems to be difficult to implement good parser combinators in a total programming language.  For example, `many` is defined as "at most a thousand times".  The (tiny subset of) TOML parser has a similar restriction on nested tables (a maximum recursion depth).  Does anybody have ideas, or know good parser libaries for Coq/Agda/Idris/etc. that we could imitate?
 * The string horror is making me crazy.  The default string type definitionally reduces to another type that has the opposite append operation.  The IO library wants a different string type (char buffers), but there are no conversions from the default string type.  I have been randomly adding and removing `.reverse` until things work.  IMHO we should just make `char_buffer` the default string.  See also #1175.
 * There is no reasonable way to pass command-line arguments to programs implemented in Lean at the moment.  See also #1289.
 * The process library is a bit bare-bones at the moment.  Concretely, I want to 1) start a process with a different working directory (this is easy, just add a `working_directory` field to the process structure), and 2) wait for a process to finish and get its exit value (not so obvious, add a process_handle type, or maybe make process.child abstract?)
 * I need to add some utility functions for file paths.  resolve a relative path against a given path, check whether a directory exists, etc.
 * The hash_map data structure works nicely, but we should probably add a `[has_hash α]` type-class, and provide default hash functions for all data types.
 * It might be nice to extend the `leanpkg.path` file so that we can not only set the LEAN_PATH, but also options.

In any case, it works well enough that it follows transitive dependencies and manages to clone the library_dev repo.  As next steps I'm looking at running `main` functions #1289, and making lean actually use the generated `leanpkg.path` files.

**Comment by leodemoura** [comment]
> IMHO we should just make char_buffer the default string. See also #1175.

@gebner I'm happy with this change, but there is one potential issue.
The efficient `char_buffer` implementation is only available in the VM.
In the kernel, they are just structures with nested closures. I'm not sure how bad the performance is in this case. This may become an issue if one day we want to define a strongly typed `printf` function.
```lean
printf (s : string) : decode_type s
```
Example: `printf "value: %d, %d"` has type `nat -> nat -> io unit`.
In this case, `decode_type s` has to be reduced in the kernel.
It would be nice to try experiments like this one before making the change, and avoid surprises in the future. What do you think?

**Comment by leodemoura** [comment]
> Unfortunately it seems to be difficult to implement good parser combinators in a total programming language. For example, many is defined as "at most a thousand times". 

@gebner This problem is hard to address now. For example, one of the solutions we discussed on slack ("abstract fuel") would require well founded recursion support in the equation compiler.

**Comment by leodemoura** [comment]
> There is no reasonable way to pass command-line arguments to programs implemented in Lean at the moment. See also #1289.

@gebner I'm happy with the following suggestion you made at #1289 

> Another option would be cmdline_args : io (list string) and exit' : nat -> io α. Exit would just return an error value.

**Comment by leodemoura** [comment]
> The process library is a bit bare-bones at the moment. Concretely, I want to 1) start a process with a different working directory (this is easy, just add a working_directory field to the process structure), and 2) wait for a process to finish and get its exit value (not so obvious, add a process_handle type, or maybe make process.child abstract?)

It would be great to have these extensions. I think we should postpone the `process_handle` part.
We should wait until we have a nice story for encoding potentially non-terminating functions in Lean.
In the meantime, we can survive by just having a primitive that waits the process to finish and returns the exit code, and the content of the stdout and stderr.

**update** @gebner 

@jroesch and I were discussing this issue this morning, and we added the following primitive to `io.interface`.
https://github.com/leanprover/lean/blob/6c68aeee011b367d5b94a9b3202b24c7259075d4/library/system/io.lean#L38
So, we can use it to write potentially non-terminating functions in `io`.
For example, we used it to define `read_file` in Lean.
https://github.com/leanprover/lean/blob/6c68aeee011b367d5b94a9b3202b24c7259075d4/library/system/io.lean#L134-L141

So, I think the suggestion "add a process_handle type, or maybe make process.child abstract?" is the way to go.

**Comment by jroesch** [comment]
Re: parsing I think its pretty tricky, most people end up building things that compile to state machines. There is some work on doing verified parsing in a couple domains, they do verified parsing/decoding of x86-64 using parsing with derivatives here (http://www.cse.psu.edu/~gxt29/paper/rocksalt.pdf), http://gallium.inria.fr/blog/verifying-a-parser-for-a-c-compiler/. @wilcoxjay has been looking into this a lot lately, not sure if he has any new insights to share.

**Comment by gebner** [comment]
> In the kernel, they are just structures with nested closures. I'm not sure how bad the performance is in this case. [..] It would be nice to try experiments like this one before making the change, and avoid surprises in the future. What do you think?

I think the performance will depend on two things:
 1. How we encode string literals.
 2. What operations we expect on them.

I have no idea about 1. -- nested `nat.cases_on`?  For 2. I think that buffers will see more random access compared to lists.

With that in mind, the only relevant benchmark that I can think of is to benchmark the kernel whnf of `buffer.read' "foobarbaz" 6`.  I'm not sure what to make of the results however.  Comparing the results to lists is probably misleading as well, since we don't want to use random access on lists.

> @gebner This problem is hard to address now. For example, one of the solutions we discussed on slack ("abstract fuel") would require well founded recursion support in the equation compiler.

I think one practical option is to have `many p` fail if `p` consumes zero input.  If we use char buffers for strings, the length is easily available, and we can then define `many` using structural recursion.  Using the same trick, we can also define a fixpoint combinator, where `fix F` fails if `F` immediately calls itself.

**Comment by leodemoura** [comment]
> I think the performance will depend on two things:

@gebner I think the main questions is: do we want to compute with strings in the kernel or not?
I tried some experiments, and even with `list char` the behavior is quite messy. 
The problem is that `char` is a subtype of `nat`. So, in the kernel, a char literal is a pair `(nat, proof)`, and `nat` is encoded in unary. Decoding a string such as `"val: %d, %d"` is quite expensive. 
```lean
def decode_char : char → Type
| #"d" := nat
| #"s" := string
| _    := unit

def decode_aux : string → Type → Type
| []                  r := r
| [c]                 r := r
| (c₁ :: c₂ :: rest)  r :=
  if c₂ = #"%" then decode_aux rest (decode_char c₁ → r)
  else decode_aux (c₂ :: rest) r

def format_string_type (s : string) : Type :=
decode_aux s string

constant format_string (s : string) : format_string_type s

#check format_string "val: %d, %s" (10:nat) 
``` 
With buffers, it is even more expensive because we have proofs when reading the string, and we have the closures. We would have code such as:
```lean
def decode_aux : ∀ (i : nat) (b : buffer char), i < b.size → Type
| 0 b h :=
  let c := b.read ⟨0, h⟩ in decode_char c → string
| (i + 1) b h :=
  let c := b.read ⟨i+1, h⟩ in decode_char c → decode_aux i b (array.lt_aux_1 h)
```
I think the easy answer to the question above is: no, we will not compute with strings in the kernel. So, let's switch to `buffer char`. BTW, if someone wants to compute with strings in the kernel, then they can define their own alternative `string` type which is better for kernel computations.

**Comment by leodemoura** [comment]
> I think one practical option is to have many p fail if p consumes zero input. If we use char buffers for strings, the length is easily available, and we can then define many using structural recursion. Using the same trick, we can also define a fixpoint combinator, where fix F fails if F immediately calls itself.

@gebner I'm happy this option.

**Comment by Kha** [comment]
> I think the easy answer to the question above is: no, we will not compute with strings in the kernel.

For `printf` and even more complex applications, we could also implement a macro system that allows them to use the full power of the VM and the meta level.

```lean
@[macro]
meta def printf (fmt : parse string_literal) : tactic expr := ...

#check printf! "%d: %s" -- [printf macro]: nat -> string -> string
```

edit: That's probably just a special version of custom notation parsers.

**Comment by leodemoura** [comment]
> For printf and even more complex applications, we could also implement a macro system that allows them to use the full power of the VM and the meta level.

@Kha This is a cool feature.

**Comment by gebner** [comment]
Writing parser combinators is fun.  I now have a [nice library](https://gist.github.com/gebner/b4c12bf19dfc96abead83c5864c4ef44) for parser combinators on char_buffers in pure Lean, with a general repetition operator, fixed points, and error reporting:
```
version = xyz "0.1" 
          ^

expected: { | false | true | "
```

**Comment by gebner** [comment]
Status update: parsing, fetching dependencies (including transitive ones and diamonds), and collecting the components for the LEAN_PATH works pretty reliably now.  Command-line arguments work as well.

To do:
 * Support absolute paths in for `path` dependencies.  (Requires function to resolve relative paths.)
 * Read `leanpkg.path` in the lean executable.
 * Modify editor interfaces to support `leanpkg.toml`.
 * User-local packages (that get used for files which are not part of projects).

**Comment by gebner** [comment]
I think we can close this now that leanpkg has been merged.
