### ISSUE TITLE
apply tactic annoying without approximation in unification

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1208]
```Lean
lemma foo {α : Type*} {f : α → α} (a : α) : f a = f a := rfl
example {X : Type} (h : X → X) (x₀ : X) : h x₀ = h x₀ := by apply (foo x₀)
/-
error: invalid apply tactic, failed to unify
  h x₀ = h x₀
with
 ?m_1 x₀ = ?m_1 x₀
-/
```
Fails here:
https://github.com/leanprover/lean/blob/lean3/src/library/type_context.cpp#L1559-L1560

**Comment by dselsam** [comment]
Similar issue with `rewrite`:
```Lean
lemma ss_fns {α : Type} [subsingleton α] {f : α → α} (x : α) : f x = x := sorry
example {α : Type} [subsingleton α] (f : α → α) (x : α) : f x = x := by rw (ss_fns x)
/-
error: rewrite tactic failed, did not find instance of the pattern in the target expression
  ?m_1 x
state:
α : Type,
_inst_1 : subsingleton α,
f : α → α,
x : α
⊢ f x = x
-/
```
Note: although these may seem like weird examples. I have been running into this issue repeatedly in a larger project where the implicit arguments are too large to provide manually.

**Comment by dselsam** [comment]
A general theme is that I seem to very often want simple first order unification. It is always off-putting when something that looks like it could syntactically unify fails to do so.

**Comment by leodemoura** [comment]
BTW, the rewrite example does not work even after we use the commit above.
Reason: the rewrite tactic is based on keyed matching, and the key in the example is a meta-variable.
