### ISSUE TITLE
performance problems inside is_def_eq with macros

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1218]
The following code runs for a very long time on my machine:
```Lean
example : "hello" = "goodbye" := by reflexivity
```
This is a stupid thing to do, but this issue can be triggered in more subtle ways such as in the `try reflexivity` call in `rewrite`. 

The `type_context` currently unfolds all macros during `is_def_eq`:
https://github.com/leanprover/lean/blob/master/src/library/type_context.cpp#L572

I think this will be a recurring issue -- `is_def_eq` between macros of the same type. We may consider extending the macro API to have an `lbool quick_is_def_eq(expr const & e)` and giving it a chance in `type_context::quick_is_def_eq` before ever calling `whnf_core`, which is where the macros get expanded.  

Note that this still will not solve the problem on its own, because `type_context::is_def_eq_lazy_delta` does not give `type_context::quick_is_def_eq` a shot between unfolding and calling `whnf_core`, so the following example would cause the first macro to be unfolded: 
```Lean
example : id "hello" = "goodbye" := by reflexivity
```
Ignoring performance in common cases, it seems ideal to always try `type_context::quick_is_def_eq` between changing a term (e.g. unfolding) and calling `whnf_core`.

**Comment by leodemoura** [comment]
The new offset constraints (issue #1226) also solve this performance problem.
