### ISSUE TITLE
cases tactic with user provided names

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1222]
The cases tactic introduces new things that need to be introduced and then erases them at the end, and currently the names the user provides do not end up corresponding to the names of the resulting hypotheses.

Here is an example:
```Lean
inductive vec (α : Type*) : ℕ → Type*
| nil {} : vec 0
| cons   : α → Π {n : nat}, vec n → vec (nat.succ n)

namespace vec
def head {α : Type} : Π {n : ℕ}, vec α (nat.succ n) → α
| n (cons x xs) := x
end vec

constant P : ℕ → Prop

example (x : vec ℕ 1) : P (vec.head x) :=
begin
cases x with x vnil,
trace_state
end
```
yields
```Lean
x : ℕ,
a : vec ℕ 0
⊢ P (vec.head (vec.cons x a))
```
I think it would be more intuitive if the resulting state were:
```Lean
x : ℕ,
vnil : vec ℕ 0
⊢ P (vec.head (vec.cons x vnil))
```
This way, the user doesn't need to think about how many things need to be generalized behind the scenes inside the `cases` tactic in order to name their hypotheses. If you agree, then you can assign this to me.

**Comment by leodemoura** [comment]
`cons` has 3 "fields". One of them is implicit. Here is the revised example.
```
example (x : vec ℕ 1) : P (vec.head x) :=
begin
cases x with x n vnil,
trace_state
end
```
In your example, `vnil` was used to name the implicit `n`.

**Comment by dselsam** [comment]
I realize that. My concern is that it is awkward for the user to need to think about how many things get generalized behind the scenes, and to need to leave the right number of dummy names for them. Since these implicit variables will not end up in the resulting state, the user doesn't care what they are called.

**Comment by leodemoura** [comment]
> I realize that. My concern is that it is awkward for the user to need to think about how many things get generalized behind the scenes, and to need to leave the right number of dummy names for them. Since these implicit variables will not end up in the resulting state, the user doesn't care what they are called.

He doesn't need to think at all. The number of names is equal to the number of constructor fields. Note that the number of names has nothing to do with what gets generalized behind the scenes.
On the other hand, in the approach you are suggesting, the user has to think about which constructor fields are fixed by type inference and skip them. 

In the following example:
```
example (n : nat) (x : vec ℕ (succ n)) : P (vec.head x) :=
begin
cases x with x m vnil,
trace_state
end
```
we get the state
```
x m : ℕ,
vnil : vec ℕ m   
⊢ P (vec.head (vec.cons x vnil))
```

**Comment by dselsam** [comment]
> I realize that.

Whoops, I thought I knew what you meant but missed an important point. You are completely right, sorry about that.
