### ISSUE TITLE
Tutorial missing description of 'import'

### ISSUE THREAD

**Issue by duganc** [leanprover/lean3#1228]
I have been working through the (pdf version) of the Tutorial, which is been very helpful, but I've been unable to import my own modules and the tutorial does not seem to contain an adequate description of how to do that.  For example, the following questions don't seem to be answered:

- Where does the module have to reside to be found by the import statement, "import [my_module]?"  
- Is it possible to provide a filepath to a module in an import statement?
- It appears that the module name is the filename without the ".lean" extension.  Is that right?

Apologies if I'm missing something or if this does not warrant a formal issue, and thanks for any help you can provide.

**Comment by avigad** [comment]
@duganc The next two paragraphs are from Section 5.5 of the tutorial. Do they answer your questions? We are currently working on a new version of the tutorial, and maybe we should change the name of the section to something like "Projects and Imports" to make the information easier to find. I believe you can also change the default search path by setting the `LEAN_PATH` environment variable.

At this point, it will be helpful to convey more information about the inner workings of Lean. A .lean file (or .hlean file, if you are working on homotopy type theory) consists of instructions that tell Lean how to construct formal terms in dependent type theory. "Processing" this file is a matter of filling in missing or implicit information, constructing the relevant terms, and sending them to the type checker to confirm that they are well-formed and have the specified types. This is analogous to the compilation process for a programming language: the .lean or .hlean file contains the source code that is then compiled down to machine representations of the desired formal objects. Lean stores the output of the compilation process in files with the extension ".olean", for "object Lean".

It is these files that are loaded by the import command. When Lean processes an import command, it looks for the relevant .olean files in standard places. By default, the search path consists of the root of the standard library (or the hott library, if the file is a .hlean file) and the current directory. You can specify subdirectories using periods in the module name: for example, import foo.bar.baz looks for the file "foo/bar/baz.olean" relative to any of the locations listed in the search path. A leading period, as in import .foo.bar, indicates that the .olean file in question is specified relative to the current directory. Two leading periods, as in import ..foo.bar, indicates that the address is relative to the parent directory, and so on.

**Comment by duganc** [comment]
@avigad Thanks, this does answer my question.  My PDF client wasn't letting me cntl-F the file, so I missed this section.  

I think your suggestion of changing the section name would be good.  

One other note (and let me know if I should open a separate issue for it): in my haste to create the .olean file, I typed the command "lean -o foo.lean" rather than "lean -o foo.olean foo.lean" which overwrote my "foo.lean" file.  I had a backup, so it wasn't a big deal, but I would suggest configuring the command to require both filenames or warn the user that a file is about to be overwritten.

**Comment by avigad** [comment]
Ah, good point. In the new version of Lean, the syntax has changed. "lean foo.lean" just checks the file, whereas "lean --make foo.lean" build foo.olean as well.

**Comment by duganc** [comment]
Great.  Thanks!
