### ISSUE TITLE
RFC: do-syntax support "monad".bind without ret

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean3#1235]
In desugaring do syntax, my understanding is that bind is essential, but ret is not.  I'd like to propose introducing a subclass of monad that just contains bind without ret.

The use case for this was implementing a lean version of the Get monad in Haskell’s binary package.  In particular, it would be useful to impose a restriction type level to statically identify instance of the Get monad that consume at least one byte.  This would allow combinators to, for example, apply the monad until the input bytes are empty and return either the resulting list or an error.

If lean provided "do" syntax over a datatype that just had bind, then one could define a Get instance which only statically enforced the requirement that all Get values read at least one byte.

This might be alternatively be handled via a more general mechanism for encoding path properties, such as a dependent bind, but that seemed significantly more complex.

**Comment by leodemoura** [comment]
Should we call it `pre_monad`?

**Comment by joehendrix** [comment]
`pre_monad` would work for me.
