### ISSUE TITLE
error: file 'data/nat' not found in the LEAN_PATH & segfault

### ISSUE THREAD

**Issue by Hodapp87** [leanprover/lean3#1262]
I followed [CMake & Make](https://github.com/leanprover/lean/blob/master/doc/make/cmake_make.md) build instructions verbatim for latest master on two different systems (one Arch, one Debian), followed by `make install`. I am trying to run just the second example in the [Short tutorial](https://github.com/leanprover/lean/blob/master/doc/lean/tutorial.org), that is, I've put the following into `test.lean`:

```lean
import data.nat
open nat
-- defines the double function
definition double (x : nat) := x + x
```

and then tried to run with `lean test.lean`. This simply gives me:

```
/home/hodapp/source/lean/test.lean:1:0: error: file 'data/nat' not found in the LEAN_PATH
Segmentation fault
```

Setting `LEAN_PATH` to `/usr/local/lib/lean/library` (what is it even supposed to be?) doesn't change anything. Running `leanemacs` and merely putting an `import` produces a similar error both in the editor and if I attempt to compile.

**Comment by Kha** [comment]
The short tutorial has not been updated in quite a while, we should probably remove it for now (at least from the root readme). Please see the longer [Theorem Proving in Lean](https://leanprover.github.io/theorem_proving_in_lean/index.html) instead, which should be up-to-date with the `master` branch.

**Comment by leodemoura** [comment]
> The short tutorial has not been updated in quite a while, we should probably remove it for now (at least from the root readme).

@kha I agree.
