### ISSUE TITLE
kabstraction in approximate unification

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1268]
I have hit the following issue many times now in different contexts.

```Lean
constants (f : ℕ → ℕ) (E : (ℕ → ℕ) → ℕ)
          (H : ∀ (g : ℕ → ℕ), E (λ x, g (f x)) = 0)

example (g h : ℕ → ℕ) : E (λ x, h (g (f x))) = 0 := by simp [H]
```
yields the following trace
```Lean
[type_context.is_def_eq_detail] [1]: E (λ (x : ℕ), h (g (f x))) =?= E (λ (x : ℕ), ?x_0 (f x))
[type_context.is_def_eq_detail] process_assignment ?x_0 (f x) := h (g (f x))
[type_context.is_def_eq_detail] [2]: f x =?= g (f x)
[type_context.is_def_eq_detail] [3]: f =?= g
[type_context.is_def_eq_detail] on failure: f =?= g
[type_context.is_def_eq_detail] on failure: f x =?= g (f x)
[type_context.is_def_eq_detail] on failure: E (λ (x : ℕ), h (g (f x))) =?= E (λ (x : ℕ), ?x_0 (f x))
[type_context.is_def_eq] E (λ (x : ℕ), h (g (f x))) =?= E (λ (x : ℕ), ?x_0 (f x)) ... failed  (approximate mode)
0. [debug.simplify.try_rewrite] fail to unify 'H':
------------------------------------------------
E (λ (x : ℕ), h (g (f x)))
=?=
E (λ (x : ℕ), ?x_0 (f x))
------------------------------------------------
```
This is as expected according to A5: https://github.com/leanprover/lean/blob/master/src/library/type_context.cpp#L1536-L1539

However, what I want in this situation is to kabstract all occurrences of `f x`, to yield the following assignment:
```Lean
?x_0 := (λ (fx : ℕ), h (g fx))
```
Even if we do not add any features to the type-context, it would be good to have a canonical solution to this problem.

A few possibilities:

1. Try this in `approximate` mode when FO fails.
2. Add a new `kapproximate` flag.
3. Have an annotation that tells the type-context explicitly to use this approach, e.g.
```Lean
(H : ∀ (g : ℕ → ℕ), E (λ x, (:kapprox g) (f x)) = 0)
```
4. Expose `kabstract` and probably many other things in Lean, so that users can write special converters for each lemma that requires this kind of unification.

Any thoughts? There may also be satisfactory workarounds that I have overlooked. At first glance I like the precision of (3), but I haven't thought through all the details yet.

**Comment by leodemoura** [comment]
> I have hit the following issue many times now in different contexts.

This is yet another gadget for the unifier/matcher. The example you have described is very abstract. 
Could you elaborate it?
Did you try to workaround it? 
Do you think this will happen in other application domains?

Have you tried hacks such as folding function composition?
```lean
constants (f : ℕ → ℕ) (E : (ℕ → ℕ) → ℕ)
          (H : ∀ (g : ℕ → ℕ), E (g ∘ f) = 0)

local attribute [semireducible] function.comp

@[simp] lemma fold_comp {α β δ : Type} (g : β → δ) (f : α → β) : (λ x, g (f x)) = g ∘ f :=
rfl

@[simp] lemma comp_id {α β : Type} (f : α → β) : f ∘ (λ x, x) = f :=
rfl

@[simp] lemma comp_assoc {α β δ γ : Type} (h : γ → δ) (g : β → γ) (f : α → β) : h ∘ (g ∘ f) = (h ∘ g) ∘ f :=
rfl

example (g h : ℕ → ℕ) : E (λ x, h (g (f x))) = 0 :=
begin
  simp [H]
end
```

**Comment by dselsam** [comment]
I apologize for not posting a follow-up. Your approach is clever, I had not thought of that. I spoke to Jeremy about this issue though, and we have a different workaround (actually, a more elegant solution) for the specific case I was stuck on when I posted. Jeremy has yet to hit an issue like this at all, and we agreed it was not worth adding another gadget to the unifier unless more annoyances accumulated in other application domains. I am happy to close this issue for now if you agree.

**Comment by leodemoura** [comment]
No problem. We can reopen if we find it again.
