### ISSUE TITLE
Add a way to control which optimizations are applied

### ISSUE THREAD

**Issue by jroesch** [leanprover/lean3#1273]
Obviously in the general case we want as many optimizations as possible to apply, but it would be nice to able to turn off the optional ones. 

For example when trying to understand code generator bugs it becomes hard to write reproducible test cases in the face of constant evaluation. Earlier tonight I was debugging an issue with projections and when trying to print literal tuples the problematic code would just get computed away before code generation.

**Comment by leodemoura** [comment]
Which ones do you want to disable?

**Comment by jroesch** [comment]
I think this was actually just projections being normalized, and not really a big issue once I debugged the error in the compiler. I am not sure if we should revisit this later, or just ignore it. I definitely plan to expose controls to the native only optimizations.

**Comment by leodemoura** [comment]
I'm closing this issue. We can add new options for any optimization we may want to disable.
