### ISSUE TITLE
app_builder_exception

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1279]
The following snippet produces an `app_builder_exception` message. I'm not sure what that means, but it seems unlikely to be the desired behaviour.

    structure Category : Type.{2} :=
      (Obj : Type)
      (Hom : Obj → Obj → Type)  
      (compose : Π ⦃A B C : Obj⦄, Hom A B → Hom B C → Hom A C)
    
    open Category
    
    set_option trace.app_builder true 
    
    structure Functor (source target : Category) : Type :=
      (onObjects     : Obj source → Obj target)
      (onMorphisms   : Π ⦃A B : Obj source⦄, Hom source A B → Hom target (onObjects A) (onObjects B))
      (functoriality : Π ⦃A B C : Obj source⦄ (f : Hom source A B) (g : Hom source B C),
                        onMorphisms (compose source g f) = compose target (onMorphisms g) (onMorphisms f))

(The `set_option` has no effect: I added it because the error messages suggests doing so.)

**Comment by kim-em** [comment]
(While we're at it, if anyone want to explain to me what I should be doing instead of writing `Type.{2}` in the above --- perhaps using type variables?? --- I'd love to know.)

**Comment by johoelzl** [comment]
@semorrison: you can use type universe variables, e.g.

```lean
structure {u v} Category : Type ((max u v) + 1) :=
  (Obj : Type u)
  (Hom : Obj → Obj → Type (max u v))
  (compose : Π ⦃A B C : Obj⦄, Hom A B → Hom B C → Hom A C)
```

Here `u` and `v` are type universe variables. I only now the encoding using `max` and `+ 1` to tell Lean that `Category` is one level above the types of `Obj` and `Hom`. In the example I used two variables to allow that `Hom` is in a bigger type universe.

There was a short discussion on the `lean-user` mailing list: https://groups.google.com/forum/#!topic/lean-user/TDCcc6fPIPY

**Comment by kim-em** [comment]
Thanks, @johoelzl.

I now realise that I may have made a mistake raising this as an issue, rather than asking on the mailing list first. With the `set_option` command, the following extra message appears (sometimes?):

    10:1: [app_builder] failed to create an 'monad'-application,
        failed to solve unification constraint for #1 argument
        (Type ? → Type ? =?= Obj source → Type (max u v))

I'm unsure if this is all my fault or Lean's fault!
