### ISSUE TITLE
Add an easy way to run a program with the VM from the CLI

### ISSUE THREAD

**Issue by jroesch** [leanprover/lean3#1289]
It would be nice to have `--run` or something similar that looks for a known symbol (e.g `main`) and tries to `vm_eval` it. We could add a configuration flag and share this symbol for both the `--run` command and `--compile`.

**Comment by leodemoura** [comment]
@jroesch Could you elaborate this one? This feature doesn't look very useful.
What is the difference between having a file with `vm_eval t` and another one containing `def main := t`, and using `--run` to execute `main`?

I think this feature would only be useful if `main` could take an extra argument: `args : list string`.
Then, the meaning would be: any argument after `--run` is an argument to `main` and not lean itself.

**Comment by dselsam** [comment]
I didn't notice this issue until just now, but I independently thought this would be nice feature (even without the `args` string). Two reasons:
1. When I run Lean programs, I need to manually change my .lean file every time I switch from using the VM to the compiler and back. 
2. For long computations that I don't want emacs to run, I need to enter `vm_eval t` while outside of `lean-mode` just to prevent it from computing. 

Ideally there is a way to "interpret" the same file that would be compiled, without it actually executing the code when run normally.

**Comment by leodemoura** [comment]
@dselsam Both reasons are not very convincing. Suppose your file is named `foo.lean`, you can add your long computations in another file: `test_foo.lean`. Then, you work on `foo.lean`, and use `test_foo.lean` outside of `lean-mode` to test it and run the long computations. `test_foo.lean` contains an `import foo` and all `vm_eval` commands.

**Comment by leodemoura** [comment]
@dselsam We can also add a primitive `meta constant in_server_mode : bool`. This primitive is `tt` when running lean using Emacs or VS Code, and `ff` in batch mode. 
I think this primitive may be useful in different scenarios. Example: we can implement `ide_admit tac`. When editing the file inside an editor, it will skip `tac` and just use `admit`. In batch mode, it just executes `tac`. 
Another example: you would be able to add `vm_eval when (not in_server_node) t` which executes `t` only if we are in batch mode.

**Comment by Kha** [comment]
As a simple and more general alternative to `--run`, we can also allow `-` to signify reading a theory file from stdin. The only downside is that you may need an explicit import in it.

**Comment by jroesch** [comment]
Sorry been busy and ignoring Github notifications. 

My motivation for this mode is to avoid polluting my file with temporary commands when there is a clear main function which I would like to run often. This is especially important because I want to add a function like `env.get_args` to retrieve arguments passed on the command line. It would be ideal for this to function identically for interpretive mode and compiled mode, especially given interpretative mode is quicker for testing.

For example I would like to be able to implement a `coqdoc` equivalent directly in Lean, where the set of arguments are the files to be compiled. It would be very nice to do:
`lean leandoc.lean --run "file1.lean file2.lean"` 

Re: @dselsam point's, regardless of "usefulness" I believe this is a big user experience win.
I agree it is possible to do what Daniel wants by setting up your files in the manner you described, but theorem provers often have non-standard ways of doing things, that programmers find bizarre. I personally want to avoid many of the annoying design decisions used by other systems.

I have talked with a few functional programmers about Coq and Lean, and top-level commands alone are strange to them. It is even worse if we tell them they need to create two files, and annotate a top-level command to simply run a program in interpretive mode, and compiled mode.

I feel it is much better to draw inspiration from programming languages like Python, Ruby, Scala, etc, where invoking the tool with a file will do the right thing.

**Comment by gebner** [comment]
> I think this feature would only be useful if main could take an extra argument: `args : list string`.

This would be awesome.

So I guess we'd have a lean file `main.lean`:
```lean
import system.io
variable [io.interface]

def main (args : list string) : io unit := -- or tactic unit
io.put_str_ln $ "Hello, " ++ args.head ++ "!"
```

And we can then call it using `--run`:
```
$ lean --run main.lean world
Hello, world!
```

**Comment by Kha** [comment]
Alternatively (the Rust way), a `meta constant cmdline_args : list string`.

**Comment by gebner** [comment]
Another option would be `cmdline_args : io (list string)` and `exit' : nat -> io α`.  Exit would just return an error value.

**Comment by jroesch** [comment]
@gebner I think we should just add `exit`, I added an implementation last week to the old axiomatized `io` framework, but I think it got lost during porting. I also think we should add `--run` and an `environment` module, Haskell's and Rust's are good examples[1] [2].

- [1] https://hackage.haskell.org/package/base-4.9.1.0/docs/System-Environment.html
- [2] https://doc.rust-lang.org/std/env/index.html

**Comment by gebner** [comment]
We now have a `--run` switch.
