### ISSUE TITLE
Flycheck error reporting can prioritize warnings over errors

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#1294]
A very minor issue, but I just noticed it trying out an example from the mailing list. In the following example:
```lean
structure S :=
  (α : Type)
  (β : unit)

structure T (c : S)

structure U (c: S) (A : c^.α)

definition V (c : S) : S := -- line 9
{
  α := T c,
  β := by sorry
}

definition W { c : S } ( F : T c ) := U (V c) F -- line 15
```
Lean reports an error at 9:0 (`definition`) and a warning at 9:11 (`V`). It marks the whole line with an orange ? instead of a red !. I didn't notice at first that this declaration was causing an error.

There's also a warning at 15:11 (`W`) and an error at 15:38 (`U`), and this line gets marked correctly as an error.

**Comment by avigad** [comment]
The error message is also confusing: it is "code generation failed, VM does not have code for 'sorry'". It refers not to the definition of V, but the fact that "sorry" is being used as a tactic. It would be clearer if they error message was labelled at "by" rather than at "definition".

**Comment by leodemoura** [comment]
I had a similar problem. In the following example, there is an error at the `close` tactic, but I get its type instead of the error message when hover over `close`.
```lean
example (a : nat) : a = 1 → nat.succ 0 = a :=
begin [smt]
  close
end
```

**Comment by Kha** [comment]
I'll take a look.

**Comment by leodemoura** [comment]
BTW, to reproduce the problem above, we need to first type `M-x <something>`, then press `Ctrl-x o`, then hover over `close`. It seems the issue only happens if the mini-buffer contains something.

**Comment by Kha** [comment]
I'm assuming that the original issue is a flycheck bug. I can open an issue
in their repo.
The location of the VM error message should be fixed by
https://github.com/leanprover/lean/pull/1298/commits/99316e7f6a4a0b52c403b069d50d8e0bcb6cc116
.
Leo, I wasn't able to reproduce your issue, but it does sound like a bad
flycheck/eldoc interaction.

**Comment by leodemoura** [comment]
@kha thanks!
I agree the remaining problems seem to be in flycheck. 
Let's close this issue.
