### ISSUE TITLE
Non-intuitive behavior in the interactive tactic mode

### ISSUE THREAD

**Issue by ilyasergey** [leanprover/lean3#1313]
Assume I'm proving the following statement in a tactic mode (using Lean mode for Emacs):

```
example (p q : Prop) (a : p) (b : q) : p ∧ q ∧ p :=
begin
<C>
end
```

where `<C>` is current the position of the pointer.

I expect the goal to be shown upon pressing `C-c C-g`, but nothing happens, except for the mini-buffer showing _No goal found at point_. 

I would expect the functionality similar to Coq's `C-c C-enter` that would show a goal corresponding to the current pointer position and a part of the processed proof.

Related to that,  assume now I progressed in the proof, so it looks as follows:

```
example (p q : Prop) (a : p) (b : q) : p ∧ q ∧ p :=
begin
apply and.intro,<C>
end
```

Again, I'm unable to display the changed goal context with the "Show goal" keystroke. For this I need to put the pointer to the next line (with `end`) before invoking it. Furthermore, in the following case:

```
example (p q : Prop) (a : p) (b : q) : p ∧ q ∧ p :=
begin
apply and.intro,
<C>

end
```

it still isn't possible to show the goals -- for this I need navigate with the pointer further to the `end` keyword.

I would be desirable to have an interactive proof mode with a logic similar to Coq, so it would be possible to show the goals basing on the proof script processed up to the current pointer position.

At the moment, this mode can be _partially_ emulated via `Lean-Next-Error` (`Ctrl-C-N`) mode, but this mode doesn't allow selecting text in the buffer. Yet, in this case, it's impossible to see _intermediate_ goals in, e.g., the following case:

```
example (p q : Prop) (a : p) (b : q) : p ∧ q ∧ p :=
begin
apply and.intro,
<C>
{exact a},
end
```

**Comment by robertylewis** [comment]
I agree that the current behavior is unintuitive. Actually, I can't tell exactly what logic it's following.

Roughly, I'd expect that with the cursor anywhere in a tactic proof, Ctrl-C Ctrl-G would print the tactic state at the most recent completed tactic (that is, at the last comma, `begin`, or `{` that occurs before the cursor).

**Comment by leodemoura** [comment]
@kha, AFAICT, your commit #1319 solved this issue. Should we close it?

**Comment by Kha** [comment]
I think it's not quite right yet - a comma before a `{}` block will show
the state inside the block. I will need to change the elaborator to record
more tactic states to fix that.

**Comment by leodemoura** [comment]
I'm closing this issue since all problems described above have been fixed.
