### ISSUE TITLE
Evaluating/checking/etc without changing the caret position

### ISSUE THREAD

**Issue by ilyasergey** [leanprover/lean3#1314]
Assume we have the following script in Emacs Lean mode:

```
check 42<C>
```

where <C> is the position of the caret in the editor. It would be nice to see the result in the minibuffer without changing the caret position (e.g., via a dedicated keybinding).

Currently, it's possible to reach this effect with a flyspeck error mode on, but this mode disables other editing features (e.g., selection).

**Comment by leodemoura** [comment]
@kha Any ideas on how to address this issue? Does it make sense to use the same trick you have used for the show goal?

**Comment by Kha** [comment]
I do believe that the Next Error display is the best solution here (even if its name suggests otherwise :) ). @ilyasergey Could you check whether the new implementation still interferes with editing features, and if so open a separate issue for that?

**Comment by ilyasergey** [comment]
@Kha It does interfere, indeed. I will create a separate issue.

**Comment by Kha** [comment]
I think we can close this issue, Next Error display should be exactly the right tool for this.

**Comment by leodemoura** [comment]
> I think we can close this issue, Next Error display should be exactly the right tool for this.
Done :)
