### ISSUE TITLE
Error message for duplicate pattern matching definition

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#1322]
(This is very low priority.)

```lean
def foo : ℕ → ℕ
| 0 := 0
| n := n

def foo : ℕ → ℕ
| 0 := 0
| n := n
```
Lean complains that the environment already has an object named `foo._main`. That's true, but it's more relevant to the user that the environment already has an object named `foo`.

**Comment by leodemoura** [comment]
I'm closing this issue because I think the current behavior is acceptable.
