### ISSUE TITLE
Equation compiler failure

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#1334]
```lean
inductive nlist
| atom : nlist
| mk : list nlist → nlist

open nlist list

meta def fn : nlist → nlist
| (mk l) := mk [] 
| _ := atom
```
The equation compiler fails on `fn`, but I'm not sure how to interpret its output. It also fails with a generic pattern `e` in place of the placeholder in the last line, but succeeds if you replace the placeholder with `atom`.

**Comment by jroesch** [comment]
This is a known limitation, the pattern match compiler currently can not compile wildcard patterns for nested inductive types.

If you do:

```lean
meta def fn : nlist → nlist
| (mk l) := mk [] 
| atom := atom
```

It should work, we hope to fix this soon, my understanding is the nested compiler needs to be extended.

**Comment by leodemoura** [comment]
@jroesch Do you have "energy" to work with me on this issue next week? We are currently missing a lot of features for nested inductive datatypes. Example: the compiler generates very naive code for them (the problem we have discussed in Paris). The goal would be: finish support for well-founded recursion (needed when using nested inductives); "complete" transition for nested (this issue); avoid coercions from/to auxiliary datatypes produced by the inductive compiler when generating code; cleanup inductive compiler code.
