### ISSUE TITLE
LEAN_PATH doesn't seem to work on windows

### ISSUE THREAD

**Issue by Pyriphlegethon** [leanprover/lean3#1339]
I just installed lean, set the `LEAN_PATH` environment variable to the `library` directory but lean fails with the error `file 'init' not found in the LEAN_PATH`.

**Comment by leodemoura** [comment]
Here is an example on Windows. The lean library located at `C:\Users\leonardo\projects\lean\library`, and the binary is at `C:\Users\leonardo\projects\test`.  
```
C:\Users\leonardo\projects\test>dir
 Volume in drive C is OSDisk
 Volume Serial Number is A693-D902

 Directory of C:\Users\leonardo\projects\test

01/26/2017  12:19 PM    <DIR>          .
01/26/2017  12:19 PM    <DIR>          ..
01/26/2017  12:19 PM        10,230,177 lean.exe
01/26/2017  12:19 PM                15 tst.lean
               5 File(s)     10,230,573 bytes
               4 Dir(s)  537,108,856,832 bytes free

C:\Users\leonardo\projects\test>.\lean.exe

C:\Users\leonardo\projects\test>.\lean.exe tst.lean
C:\Users\leonardo\projects\test\tst.lean:1:0: error: file 'init' not found in the LEAN_PATH
C:\Users\leonardo\projects\test\tst.lean:1:0: error: invalid import: init could not resolve import: init
hello

C:\Users\leonardo\projects\test>SET LEAN_PATH=C:\Users\leonardo\projects\lean\library

C:\Users\leonardo\projects\test>.\lean.exe tst.lean
hello
```

Which command are you using to set the `LEAN_PATH`?

**Comment by Pyriphlegethon** [comment]
Interesting. LEAN_PATH doesn't seem to work when I'm on the C: drive while lean is installed on the D: drive.

**Comment by Kha** [comment]
@leodemoura I assume this is because of having both `;` and `:` as path sep on Windows? I.e., `LEAN_PATH=C:\Users\leonardo\projects\lean\library` is really two paths: `C` and `\Users\leonardo\projects\lean\library`.

**Comment by leodemoura** [comment]
@kha It might be. Thanks. I will check it tomorrow. BTW, I thought we handled the `;` vs `:` on Windows. I will double check it too.

**Comment by leodemoura** [comment]
@kha You right, it is breaking `C:\Users\leonardo\projects\lean\library` into `C` and `\Users\leonardo\projects\lean\library
