### ISSUE TITLE
RFC: revising the decision of identifying Type 0 and Prop

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1341]
In the current implementation, `Type 0` is `Prop`. This is useful because it allows us to write universe polymorphic definitions that work on data and proofs. Example: given `p : Prop`, `@id p` is a proof for `p -> p`

However, this decision forces us to use the `max 1 u` when declaring universe polymorphic inductive datatypes. Example, given `A : Type u` and `B : Type v`, we have `prod A B : Type (max 1 u v)` and `option A : Type (max 1 u)`. We use the `max 1 ...` to make sure the inductive datatype is never a proposition, and consequently the recursor can eliminate into arbitrary `Type u`. 
This decision is explained at: https://groups.google.com/forum/#!topic/lean-user/0b0ncyv8thM

An alternative design is to stop identifying `Type 0` with `Prop`. This decision would prevent us from declaring universe polymorphic definitions that work for `Type` and `Prop`, but we would not need to use the `max 1 ...` trick for declaring inductive datatypes. For example, we would have to define the identity function for data (i.e., `Type u`) and for propositions.
```
def {u} id {α : Type u} : α → α :=
λ a, a

lemma p_imp_p {p : Prop} : p → p :=
λ h, h
```

I'm not sure how often we write universe polymorphic definitions that are simultaneously useful for data and propositions. For sure, avoiding the `max 1 ...` trick will simplify universe constraints we need to solve, and counter intuitive behavior like the one in the lean-user thread above.

**Comment by avigad** [comment]
I just came across exactly this problem when writing a monadic parser (see #1340). Initially, I designed the parser monad so that return values could be in a type in any universe, but it was a pain in the neck, and I had to add ugly annotations to make it work.

I don't think it would cause any serious damage to separate `Type` and `Prop`, and a clean separation is probably healthy. But wouldn't it be a lot of work to make this change?

**Comment by leodemoura** [comment]
> But wouldn't it be a lot of work to make this change?

I don't think so. However, I'm not sure how often we use universe polymorphic definitions in proofs. Anyway, it should not be hard to patch the standard library.
 
BTW, the reference type checker would have to be patched too.

**Comment by robertylewis** [comment]
There are pedagogical/psychological/moral reasons for avoiding many of these polymorphic definitions. I would generally avoid using `id` on `Prop` because it "isn't" the identity function, it's a proof that every proposition implies itself, and should be named accordingly.

I have used `list Prop` before, and it would be a pain to create and maintain a parallel list library for prop. It's not really essential where I've used it, but there could be other situations where it's harder to work around.

**Comment by leodemoura** [comment]
@rlewis1988 We would still be able to use `list Prop`. We would not be able to write `list (a = b)`, which doesn't make a lot of sense since all proofs for `a = b` are definitionally equal.

**Comment by leodemoura** [comment]
BTW, I'm currently making some experiments. There are some good and bad news.
Good news: we don't need the universe level operator `imax` anymore. 
Bad news: we need two recursors for inductive datatypes that can eliminate into `Type`: one that eliminates into `Prop` and another one that eliminates into `Type u`. Right now, we have a single one that eliminates into `Type u`, and consequently in `Prop` since `Prop` is `Type 0` (in the current implementation).

**Comment by leodemoura** [comment]
BTW, I'm trying the following design.

1- `Prop` is not identified with `Type 0`, that is the set of universe levels is `{prop, 0, 1, 2, ...}`
2- A universe polymorphic parameter `u` ranges over `{0, 1, 2, ...}`. So, `Type u` is never `Prop`.
3- The universe `prop` cannot be the argument of the universe operators: `succ` and `max`.
4- We need two recursors for inductive datatypes that eliminate into `Type`. For example, for `nat`, we would have
```lean
list.rec.{u v} : Π {T : Type u} {C : list T → Type v}, C list.nil → (Π (h : T) (t : list T), C t → C (h :: t)) → Π (n : list T), C n

list.ind.{u} : Π {T : Type u} {C : list T → Prop}, C list.nil → (Π (h : T) (t : list T), C t → C (h :: t)) → Π (n : list T), C n
```
Some inductive predicates have only the second kind (e.g., `or` and `exists`).    
   
Item 4 is the one that requires many modifications in the code base.

**Comment by robertylewis** [comment]
> @rlewis1988 We would still be able to use list Prop. We would not be able to write list (a = b), which doesn't make a lot of sense since all proofs for a = b are definitionally equal.

Oh, right, of course. That makes me much less concerned.

> Bad news: we need two recursors for inductive datatypes that can eliminate into Type: one that eliminates into Prop and another one that eliminates into Type u. 

I can see this would be annoying to implement and could lead to some confusion. However, it would also enforce the pedagogical/psychological/moral distinction between `rec` and `ind`!

**Comment by fpvandoorn** [comment]
Here is an option which doesn't change the universe levels, but which does solve the confusion from the email:
Make `Type u` notation for what is now `Type (u+1)`, and add some other notation (e.g. `Type* u`) for what is now `Type u`. That way the universes are indeed 
`Prop` (`=Type* 0`)
`Type 0` (`= Type* 1`)
`Type 1` (`= Type* 2`)
...
but if recursors use `Type* u` they can eliminate to both `Prop` and `Type u`.

Option 2: If it's confusing that `Type u` is different than `Type* u`, another option might be to make `Type* u` behave as above, make `Type 0` ill-typed and `Type u` means that `u` is a universe level at least 1. In this case we have
`Prop` (`=Type* 0`)
`Type 1` (`= Type* 1`)
`Type 2` (`= Type* 2`)

Although I also see Rob's point that it might be pedagogically better to distinguish `Prop` and type universes completely.

**Comment by leodemoura** [comment]
@fpvandoorn Option 1 is very attractive since we would only need to change the parser. 
Some concerns:
1- Users would be surprised when they find out that `Type u` is really `Type* u+1`. 
2- Do we keep the illusion when pretty printing terms? That is, `Type* u+1` is displayed as `Type u`.
  Note that `Type ?u` will now be displayed as `Type* ?u`.
3- It is not clear to me how much more complicated the universe level constraints would be.

Option 2 addresses the first two concerns. I will try to experiment with it.

**Comment by leodemoura** [comment]
Small update: it is not viable to completely separate `Prop` and `Type`. For example, we would need two equalities: one for `Type u`, and another for proofs. We do use equality between proofs in many places.

I think @fpvandoorn's approach is the only viable one.

**Comment by joehendrix** [comment]
As a sporadic user, I really like @fpvandoorn's approach.  In addition to the operations mentioned, I also use ite and dite for both proofs and values.  Although there is some pedagogical simplicity to the simplicity when first learning dependent types, it also increases the number of symbols one has to (re)learn.

**Comment by leodemoura** [comment]
I made a few experiments. In the commit above `Type u` is the old `Type (u+1)`.
I used `PType u` (short for `Prop_or_Type`) instead of `Type* u` because we already use `Type*` as notation for `Type _`.

In the commit above, we can compile the standard library, but we still have > 70 broken tests.
I'm using Floris' option 1. 

```
(Type u)  is the old (Type (u+1))
(PType u) is the old (Type u)
Type*     is the old (Type (_+1))
PType*    is the old Type*
Prop      is PType 0
Type      is PType 1
Type 0    is PType 1
Type 1    is PType 2
```

I had to use `PType` in many different places. Examples: to define `eq`, `ite`, `dite`.
I also needed two versions of `prod` and `sum`. One with `Type` and another with `PType`. The `Type` version is for users, but some of the internal constructions require the `PType` version. Otherwise, we would have to do it 4 times (Type and Type; Type and Prop; Prop and Type; Prop and Prop).

The code base broke in many places because the signatures changed. For example, `0 : nat` is now `@zero.{0} nat nat.has_zero` instead of `@zero.{1} nat nat.has_zero`.

I fixed most of the problems, but we still have a bug in the inductive compiler. AFAICT, the bug was there before this commit, but it was not being exposed by the test suite.

I think most uses of `PType` will be in the `init` folder. 
I have observed many clear improvements.
Examples:
```lean
before: def option_t (m : Type (max 1 u) → Type v) [monad m] (α : Type u) : Type v :=
after:  def option_t (m : Type u → Type v) [monad m] (α : Type u) : Type v :=

before: meta constant {u} task : Type u → Type (max u 1)
after:  meta constant {u} task : Type u → Type u

before: @[reducible] meta def vm (α : Type) : Type := option_t.{1 1} vm_core α
after:  @[reducible] meta def vm (α : Type) : Type := option_t vm_core α

 instance pred2subtype {A : Type u} : has_coe_to_sort (A → Prop) :=
before: ⟨Type (max 1 u), (λ p : A → Prop, subtype p)⟩
after:  ⟨Type u, (λ p : A → Prop, subtype p)⟩
```

**Comment by leodemoura** [comment]
Please take a look in the commit above, and send feedback.

BTW, here is another example that improved
```lean
before: Functor.{u_1 u_2 u_3 u_4} : Category.{u_1 u_2} → Category.{u_3 u_4} → Type (max 1 (imax u_1 u_1 u_2 u_4) (imax u_1 u_3))

after:  Functor.{u_1 u_2 u_3 u_4} : Category.{u_1 u_2} → Category.{u_3 u_4} → Type (max u_1 u_3 u_2 u_4)
```

**Comment by gebner** [comment]
I like the change as it introduces a more sensible default behavior for universe polymorphic definition.  In the common case you don't need to write any level operators or worry about Prop anymore, just type `Type u`, `Type v`, etc. and everything will work most of the time.

I don't like the `sum`/`psum` distinction so much.  The current definition subsumes both variants.  The problem from the mailing list is already solved by the `Type u := PType (u+1)` change.

Re: pretty-printing.  I think printing `PType (u+1)` as `Type u` is fine.

I hate to be the guy who brings naming convention into the discussion, but could we use this opportunity to unify the nomenclature between Lean/C++?  Right now we use `sort` in C++ and `Type` in Lean.  My proposal would be to just rename `PType` to `Sort`, that is:
 * In the Lean syntax we have: `Prop` is `Sort 0`, and `Type u` is `Sort (u+1)`
 * In C++ and for meta programming: ``sort (level.param `u)`` means `Sort u`

**Comment by kim-em** [comment]
I certainly like that last improvement in the signature of `Functor`!

I didn't see above much discussion of @fpvandoorn's [option #2](https://github.com/leanprover/lean/issues/1341#issuecomment-275884892). I fear that having `(Type u = PType u+1)` will be very confusing, and it would be good to not risk all these off-by-one errors

**Comment by leodemoura** [comment]
@gebner 

> I don't like the sum/psum distinction so much. The current definition subsumes both variants. The problem from the mailing list is already solved by the Type u := PType (u+1) change.

We need the `psum` and `pprod` for the inductive and equation compilers. They create auxiliary definitions using them, and their arguments may be propositions.

> My proposal would be to just rename PType to Sort, that is:

This is good.

**Comment by leodemoura** [comment]
@semorrison 

> I didn't see above much discussion of @fpvandoorn's option #2. I fear that having (Type u = PType u+1) will be very confusing, and it would be good to not risk all these off-by-one errors

AFAICT, option 2 only works for explicit universes (0, 1, 2, ...). 
I don't see how to define a universe polymorphic definition (e.g., `Functor`) where the parameters `u_1` ... `u_4` can only be instantiated with values > 0. We would have to change the kernel and make sure it tracks these constraints. Option 1 didn't require any kernel modification.

**Comment by gebner** [comment]
> We need the psum and pprod for the inductive and equation compilers. They create auxiliary definitions using them, and their arguments may be propositions.

I understand that.  But we could keep the current definition:
```lean
inductive sum (α : Sort u) (β : Sort v) : Sort (max 1 u v)
```

For me it's important that it's easy and painless to create your own universe polymorphic definitions, and the change to `Type` already achieves that.  I don't think having more general types in the standard library is a problem, I could only see it being a problem with universe level inference.

**Comment by leodemoura** [comment]
> In the Lean syntax we have: Prop is Sort 0, and Type u is Sort (u+1)

BTW, I think this is also a nice way to explain it in the documentation.

**Comment by gebner** [comment]
> AFAICT, option 2 only works for explicit universes (0, 1, 2, ...).

Could we do `Type u := Sort (max 1 u)`?

**Comment by leodemoura** [comment]
> Could we do Type u := Sort (max 1 u)?

In principle, we can. 
We only need to try and test how complicated the universe constraints  will be.
BTW, `Type 0` and `Type 1` would be both `Sort 1`.

**Comment by leodemoura** [comment]
@gebner 

Using option 1, `Semigroup` and `Category` would have type
```lean
Semigroup.{u} : Sort (u+2)
Category.{u v} : Sort (max (u+2) (v+2))
```
which are pretty printed in the commit above as
```lean
Semigroup.{u} : Type (u+1)
Category.{u v} : Type (max (u+1) (v+1))
```
I think this is nice.

Using option 2, we get
```lean
Semigroup.{u} : Sort (max 2 (u+1))
Category.{u v} : Sort (max 2 (u+1) (v+1))
```
They could be pretty printed as:
```lean
Semigroup.{u} : Type (max 2 (u+1))
Category.{u v} : Type (max 2 (u+1) (v+1))
```
since `max 1 (max 2 (u+1)) = (max 2 (u+1))`, but the `max` would stay there. We need the `2` for the case `u` is `0`.

**Comment by leodemoura** [comment]
> I don't think having more general types in the standard library is a problem, I could only see it being a problem with universe level inference.

Yes, the universe level inference was the motivation for having `prod` and `sum` with `Sort (u+1)` parameters. We can experiment with keeping them in `Sort u` and see if run into trouble or not.
It might work, as soon as, the user starts using `Type u` (i.e., `Sort (u+1)`), all these `max 1 ...` will vanish from constraints.

**Comment by fpvandoorn** [comment]
> I don't like the `sum`/`psum` distinction so much.

I think it's fine to have two versions. The question is what version is more useful for users. I think it's the one which is only defined for `Sort (_+1)`, because we will also define all other type constructors only for non-`Prop` universes. And then we need a second version for the automatically generated definitions. There is also a `poly_unit` inductive type (which is just `unit` in universe `u`) which is used in automatically generated definitions, but never(?) used by any user.

> In the Lean syntax we have: Prop is Sort 0, and Type u is Sort (u+1)

I also like this.

**Comment by avigad** [comment]
Using the current Lean terminology, yesterday I had the problem that if I defined `foo {α : Type (max 1 u)} (x : α} := ...` and applied it to an argument of type `nat`, which is `Type 1`, then `u` could not be inferred. I had to give it explicitly by writing `foo.{1}`.

This speaks in favor of defining `Type u := Sort (u + 1)` rather than `Type u := Sort (max 1 u)`. I don't think this is too confusing. There is a simple story: we have `Prop` and we have `Type 0`, `Type 1`, `Type 2`. When we want to be polymorphic over both, we enumerate them like this:
```
Prop, Type 0, Type 1, ...
```
with `Sort 0 := Prop`. I expect that users can get used to that, and that it will not cause problems in day-to-day use.

**Comment by leodemoura** [comment]
> Using the current Lean terminology, yesterday I had the problem that if I defined foo {α : Type (max 1 u)} (x : α} := ... and applied it to an argument of type nat, which is Type 1, then u could not be inferred. I had to give it explicitly by writing foo.{1}.

This is a great example for showing why option 2 is problematic. 
We don't want to perform any case analysis when solving universe constraints.
This example generates the universe constraint `max 1 ?u =?= 1`. 
This constraint has two solutions `?u := 0` or `?u := 1`.

**Comment by leodemoura** [comment]
The branch `new_Type_u` is working and all tests are passing. https://github.com/leanprover/lean/commits/new_Type_u
It uses option 1 and `Sort`.

**Comment by robertylewis** [comment]
This looks really nice, and sounds easy enough to get used to!

**Comment by leodemoura** [comment]
I will merge the branch `new_Type_u` with `master`. We can make any necessary adjustments there.

**Comment by leodemoura** [comment]
Merged. I'm closing this issue.

**Comment by robertylewis** [comment]
Awesome.

This change is probably worth announcing on the mailing list, if/when you're ready to generate discussion. Without an official announcement, I'm sure there will be questions soon enough.

**Comment by leodemoura** [comment]
We will announce when we make the next release.
We now have infrastructure for automating the release process.
The idea is to make sure all documentation is in sync with every release.
Moreover, we should tell external users to download lean from the following places: 
http://leanprover.github.io/download/
https://github.com/leanprover/lean/releases/latest
