### ISSUE TITLE
Lean emacs not working

### ISSUE THREAD

**Issue by daly** [leanprover/lean3#1344]
From: Tim Daly <daly@axiom-developer.org>:

Emacs lean-mode key definitions don't seem to work
https://leanprover.github.io/presentations/20150123_lean-mode/lean-mode.pdf

Emacs recognizes that the file is lean-mode.
M-x lean-server-restart-process [No match]

Ubuntu Xenial, emacs 24.5.1

git pull origin master

per instructions this was added to .emacs:

				; for Lean
;; You need to modify the following two lines:
(setq lean-rootdir "~/lean")
(setq lean-emacs-path "~/lean/src/emacs")

(setq lean-mode-required-packages '(company dash dash-functional f
                               flycheck let-alist s seq))

(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)
(let ((need-to-refresh t))
  (dolist (p lean-mode-required-packages)
    (when (not (package-installed-p p))
      (when need-to-refresh
        (package-refresh-contents)
        (setq need-to-refresh nil))
      (package-install p))))

(setq load-path (cons lean-emacs-path load-path))

(require 'lean-mode)

**Comment by avigad** [comment]
Tim, that presentation is old; the current documentation is on the Download and Documentation pages of http://leanprover.github.io/documentation/.

@leodemoura Should we remove this presentation from the presentations page?

**Comment by leodemoura** [comment]
> @leodemoura Should we remove this presentation from the presentations page?

Yes :)

**Comment by daly** [comment]
Fixed. Thanks.
