### ISSUE TITLE
Library does not build in trust level zero

### ISSUE THREAD

**Issue by gebner** [leanprover/lean3#1347]
One of the problems is this declaration:
```lean
structure cc_config :=
(ignore_instances : bool               := tt)
(ac               : bool               := tt)
(ho_fns           : option (list name) := none)
(em               : bool               := tt)
```
The kernel type-checker complains about the `annotation` macro (that's because of the default values, right?):
```
/home/gebner/lean/library/init/meta/smt/congruence_closure.lean:11:42: error:
declaration contains macro with trust-level higher than the one allowed
(possible solution: unfold macro, or increase trust-level)
```

Related question: I guess we should test that the library builds in trust level zero.  It's probably too long for a unit test, maybe we should do a separate travis configuration?

**Comment by leodemoura** [comment]
> Related question: I guess we should test that the library builds in trust level zero. It's probably too long for a unit test, maybe we should do a separate travis configuration?

I agree. A separate travis configuration is the way to go.
