### ISSUE TITLE
segfault in library_dev repo

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#1363]
I don't expect the library_dev repo to compile right now, but `data/list/comb.lean` is causing a segfault in `mem_product` (https://github.com/leanprover/library_dev/blob/master/data/list/comb.lean#L497 ).

Making the type arguments to product explicit `@product α β l₁ l₂` in the statement of the theorem fixes the problem.

**Comment by robertylewis** [comment]
Note: this seems to be unrelated to `comb.lean` being broken in other places. I fixed it and its dependency `list/basic.lean` to compile up to the declaration of `mem_product`, and still get the segfault without the explicit types.

**Comment by gebner** [comment]
This seems to be a fallout from the error-recovery changes in the elaborator, if I switch off error-recovery, then the segfault is gone.  The segfault happens during type class synthesis inside `type_context::is_def_eq` when called with the following two terms (the first one is the inferred instance).
```
?M.22.13712 l₁ l₂
list.has_mem.{uu} α
```
However `l₁` and `l₂` are not in the local context at that time.

**Comment by leodemoura** [comment]
@gebner I'm experiencing a different problem. Lean is looping when I try 
```
lean -j 0 comb.lean
```
The loop is here:
https://github.com/leanprover/lean/blob/master/src/util/utf8.cpp#L63

The issue is that the input string is not valid utf8. 
Force `sz = 1` when the character is not valid utf8 produces an assertion violation later.

**Comment by gebner** [comment]
@leodemoura `lean -j0 data/list/comb.lean` also segfaults for me.

**Comment by leodemoura** [comment]
> @leodemoura lean -j0 comb.lean also segfaults for me.

Did you erase the old .olean files?

**Comment by gebner** [comment]
Yes, everything is completely fresh.

**Comment by gebner** [comment]
BTW, the segfault happens for me at this line: https://github.com/leanprover/lean/blob/96ccb148b14e16872aca8ed2b97bb48783548be4/src/library/type_context.cpp#L486

**Comment by leodemoura** [comment]
@gebner I managed to reproduce the problem.
I will modify the `type_context`, and make sure it accepts invalid local contexts.

**Comment by leodemoura** [comment]
There are other problems :(

**Comment by gebner** [comment]
@leodemoura What problem did you find?

**Comment by leodemoura** [comment]
Assertion violations. I'm investigating them.
