### ISSUE TITLE
nat.sub and norm_num 

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean3#1365]
It appears that tactic.norm_num replaces subtraction with add and a negation.  This reduces its utility with Nat instances as they have subtraction, but no meaningful negation (along with no has_neg/add_comm_group instances).  

Could norm_num be modified to support sub directly without the need for negation?

Here's a simple example:

```
meta def norm_num_eq : tactic unit := do
  (lhs_e, bound_e) ← tactic.target >>= match_expr "eq" expr.is_eq,
  (diff_norm, lhs_eq) ← tactic.norm_num lhs_e,
  return ()

lemma test_norm_num_sub : (4 - 1 : ℕ) = 3 := by norm_num
```

**Comment by leodemoura** [comment]
> Could norm_num be modified to support sub directly without the need for negation?

Yes, we will add it.
