### ISSUE TITLE
Config problem in Lean online 

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover/lean3#1366]
When I do nothing more than "check nat" in https://leanprover.github.io/theorem_proving_in_lean/, I get the following errors reported:

1:0:error: invalid import: init
'unreachable' code was reached
1:0:error: file '/library/init/wf.lean' not found in the LEAN_PATH
1:0:error: file '/library/init/wf.lean' not found in the LEAN_PATH
1:0:error: file '/library/init/wf.lean' not found in the LEAN_PATH
1:0:error: file '/library/init/wf.lean' not found in the LEAN_PATH
1:0:error: file '/library/init/wf.lean' not found in the LEAN_PATH
1:0:error: file '/library/init/wf.lean' not found in the LEAN_PATH
1:0:error: file '/library/init/wf.lean' not found in the LEAN_PATH
1:0:error: file '/library/init/wf.lean' not found in the LEAN_PATH
1:0:error: file '/library/init/wf.lean' not found in the LEAN_PATH
1:0:error: file '/library/init/wf.lean' not found in the LEAN_PATH
1:13:error: unknown identifier 'nat'
Done(0.039sec)

Is the configuration problem on my end? I don't think so, but I could be wrong.

Kevin

**Comment by leodemoura** [comment]
This problem seems to affect the Lean javascript version in some browsers.

Could you try to refresh? I never experienced this problem, but I know a user that fixed it by refreshing the page.

Best,
Leo

________________________________

**Comment by kevinsullivan** [comment]
That worked. I'm using Chrome Version 56.0.2924.87.

**Comment by kevinsullivan** [comment]
Problem solved per above.
