### ISSUE TITLE
wrong "value has metavariables" message

### ISSUE THREAD

**Issue by cipher1024** [leanprover/lean3#1369]
In the following code, trying to evaluate numerals using tactics fails if a meta-variable has been previously introduced and resolved.

```
open nat
open tactic

meta def match_le (e : expr) : tactic (expr × expr) :=
match expr.is_le e with
| (some r) := return r
| none     := tactic.fail "expression is not a leq"
end

meta def nat_lit_le : tactic unit := do
  (base_e, bound_e) ← tactic.target >>= match_le,
  base  ← tactic.eval_expr ℕ base_e,
  skip

   -- works
example : 17 ≤ 555555 :=
begin
  nat_lit_le,
  admit
end

  -- doesn't work
example : { k : ℕ // k ≤ 555555 } :=
begin
  refine subtype.tag _ _,
  exact 17,
  nat_lit_le,
end
```

**Comment by leodemoura** [comment]
Yes, `eval_expr` expects a term without metavariables (even if they are assigned). I will relax this restriction. In the meantime, you can use
```lean
meta def nat_lit_le : tactic unit := do
  (base_e, bound_e) ← tactic.target >>= match_le,
  base_e ← instantiate_mvars base_e,
  base  ← tactic.eval_expr ℕ base_e,
  skip
```

**Comment by cipher1024** [comment]
Thank you! Joe Hendrix also pointed out that:

```
tactic.target >>= trace
```

shows

```
?m_1 ≤ 555555
```

while emacs would display it as 

```
17 ≤ 555555
```

Is this the expected outcome? I would have thought that showing `17 ≤ 555555` would inform me that there are no more meta-variables in the formula.

**Comment by leodemoura** [comment]
> Is this the expected outcome?

Yes, the interactive mode instantiates the metavariables before pretty printing the current state.
Of course, it is debatable whether this is the right thing to do or not.

**Comment by leodemoura** [comment]
Here is a proposal:
- By default, we always instantiate metavariables before pretty printing.

- We rename the option `pp.instantiate_goal_mvars` to `pp.instantiate_mvars`, and make sure it also affects `trace`. So, it would address the mismatch between Emacs and `tactic.target >>= trace`.

- We make sure tactics such as `eval_expr` will instantiate assigned metavariables instead of failing.

**Comment by cipher1024** [comment]
I like that. I'm wondering if it would be possible to just eliminate the metavariables as soon as they are instantiated. I have a feeling you probably considered that already so I'm wondering what the downsides are.

**Comment by leodemoura** [comment]
> I have a feeling you probably considered that already so I'm wondering what the downsides are.

Yes, the issue is performance.
