### ISSUE TITLE
incorrect error position

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1377]
Here is a small repro
```lean
meta def f (x : nat) : nat :=
tt

check nat  -- type error is being reported here at the check
``` 
If we remove `meta`, then the error is reported in the correct place.

**Comment by gebner** [comment]
I think the `check` is misleading here, the error is reported at the next token, no matter whether check or eval or def or something else.

**Comment by leodemoura** [comment]
@gebner I used an arbitrary command. The type error is in the definition, but it is reported in the next command following the definition.

**Comment by gebner** [comment]
The problem is that we do not save the position for the fake equation we use to support general recursion.  I have a fix, but it still shows `equation type mismatch`.  Should I try to fix that?

**Comment by leodemoura** [comment]
> The problem is that we do not save the position for the fake equation we use to support general recursion. I have a fix, but it still shows equation type mismatch

Wow, this explains the weird behavior.

> Should I try to fix that?

I'm happy with the current message.
