### ISSUE TITLE
Hovers of the word following ^. doesn't print the type of the function

### ISSUE THREAD

**Issue by emberian** [leanprover/lean3#1384]
For example, in this snippet:

```
meta def foo := let m := rb_map.mk nat nat in m^.insert 0
```

Hovering over `insert` in vscode gives no information, but hovering over the `^.` prints the type of `rb_map.insert`

**Comment by Kha** [comment]
Does your Lean binary include https://github.com/leanprover/lean/commit/339713091f3bbd25a0cb51181c0ec0ed1bb551c2 (merged yesterday)? There was some problem with functions containing implicit parameters.

**Comment by emberian** [comment]
You're right, just updated and it's fixed. Nice!
