### ISSUE TITLE
lean --compile doesn't work on Windows (MSYS2)

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover/lean3#1393]
==== here's the program I'm compiling

$ cat hello.lean
import system.io

def main : io unit :=
    put_str_ln "Hello Lean!"

==== here's what happens ... sorry, I'm a newbie, can someone help

$ lean --compile hello.lean

processing app
inside cases on
processing app
processing app
processing app
inside cases on
processing app
processing app
inside cases on
processing app
inside cases on
processing app
inside cases on
processing app
inside cases on
processing app
inside cases on
processing app
processing app
processing app
processing app
inside cases on
processing app
inside cases on
processing app
inside cases on
processing app
inside cases on
processing app
inside cases on
processing app
inside cases on
processing app
processing app
processing app
processing app
processing app
processing app
processing app
processing app
processing app
processing app
inside cases on
processing app
processing app
processing app
processing app
processing app
processing app
processing app
processing app
processing app
processing app
processing app
inside cases on
processing app
processing app
processing app
processing app
processing app
processing app
processing app
inside cases on
processing app
processing app
processing app
<unknown>:1:1: error: process::run not supported on Windows

**Comment by jroesch** [comment]
```
Hello Kevin,

The native compiler is still under active development and not ready for end-users yet. 

We merged an initial version before our POPL tutorial so people could try it out, but it is alpha quality and importantly lacks Windows support. 

A more complete version is under development (https://github.com/leanprover/lean/pull/1241) but it still needs a few more 
things before we merge it.

If native compiler support is important for your use case, please let us know and we will factor that into our internal priorities.

Best,

- Jared
```

I sent the above message on the Google group, the native compiler is still under development if you want to experiment you can check out the work in progress branch (https://github.com/leanprover/lean/pull/1241). 

Let me know if you have other questions!

**Comment by leodemoura** [comment]
I pushed the following commit

https://github.com/leanprover/lean/commit/1da93c4d2834ac87408f5708b4542625b808a385

It disables any alpha feature (i.e., work in progress feature).  So, these features are not available to regular users. To have access to them, we need to compile lean from sources using `-D ALPHA=ON`.

So, I'm closing this issue.
