### ISSUE TITLE
Optional delay evaluation of default arguments

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean3#1395]
I’ve run into a use case where I think it would be useful if a function took default arguments that were evaluated in the calling context rather than the definition.  I wanted to see if this suggestion would be useful in Lean.

In some code, I introduced a vector split function that decomposes a single vector into a vector of vectors.  This function was inspired by a similar function in cryptol, and we also have the inverse join function

`def vector.split {α : Type} (m n : ℕ) : vector α (m * n) → vector (vector α m) n := sorry`

Unfortunately, expressions involving large values of m and n are slow to type check (I think the issue is the elaborator), e.g.,

```
check split 0x10 0x1 (100 : vector bool 0x10) — 0.5 seconds via time lean ...
check split 0x10 0x100 (100 : vector bool 0x1000) -- 1.32 seconds via time lean
check split 0x10 0x10000 (100 : vector bool 0x100000) -- deep recursion error.
```

I can solve this by generalizing vector.split to take an arbitrary length vector and an explicit proof the length is correct, e.g.,

```
open tactic

— Very simplify tactic that uses norm_num to efficiently discharge obligation (in non-example  code this would be more elaborate).
meta def nat_lit_eq : tactic unit := do
  tgt ← target,
  match expr.is_eq tgt with
  | option.some (lhs, rhs) := do
      (norm,pr) ← norm_num lhs,
      transitivity,
      exact pr,
      reflexivity
  | option.none := fail "Expected eq"
  end

def vector.split_gen {α : Type} (m n : ℕ) {r : ℕ} : vector α r → m * n = r → vector (vector α m) n := sorry

check vector.split_gen 0x10 0x10000 (100 : vector bool 0x100000) (by nat_lit_eq) -- 0.56 seconds
```

I think it would be most useful if we could use an explicit proof as in vector.split_gen, but with a sensible default so that users do not need to always specify it.  Perhaps something like:

```
def vector.split2 {α : Type}
                  (m n : ℕ)
                  {r : ℕ}
                  (x : vector α r)
                  (pr : m * n = r := by nat_lit_eq)
: vector (vector α m) n := sorry
```

This fails because "by nat_lit_eq" is evaluated when vector.split2 is defined.  I’m not sure how common this use case is, but it seems like it would be elegant if I could defer running the tactic until the actual use of vector.split2.  The downsides I see are that this would lead to more interaction between the elaborator and tactic mode in ways that are difficult to debug.  You also wouldn't always want this as it defers type checking default arguments.

**Comment by leodemoura** [comment]
Lean has "auto" parameters. We can use them to implement `split2`.

```lean
def vector.split2 {α : Type}
                  (m n : ℕ)
                  {r : ℕ}
                  (x : vector α r)
                  (pr : m * n = r . nat_lit_eq)
: vector (vector α m) n := sorry
```

The syntax for auto parameter is `(h : type . tac_id)` where `tac_id` is the name of a definition with type `tactic unit`.

Whenever using "auto" parameters, it is useful to wrap the definition of `tac_id` with an `abstract`.
Example:
```lean
meta def nat_lit_eq : tactic unit := abstract $ do
  tgt ← target,
  ...
```
The `abstract` tactic creates auxiliary definitions for the generated proofs, and prevent big proof terms from appearing in our context when we unfold definitions.
For example, try 
```
check vector.split_gen2 0x10 0x10000 (100 : vector bool 0x100000) 
```
with and without the `abstract`.

> Unfortunately, expressions involving large values of m and n are slow to type check (I think the issue is the elaborator), e.g.,

Yes, you are correct. The `elaborator` has support for solving unification constraints such as `?m + 1000 =?= 2000` and `1000 + 1000 = 2000` efficiently, and without using normalization (unary arithmetic in this case). We can also implement this kind of support for `*`.

**Comment by joehendrix** [comment]
Thanks I didn't know about auto parameters.  It sounds like they address this use case perfectly.

I'll close this ticket.
