### ISSUE TITLE
eval_expr errors

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#1401]
I'm having two problems with `eval_expr`. These might be related, but I'm not sure to what degree.

```lean
constant rat : Type
constant rof : linear_ordered_field rat
notation `ℚ` := rat

attribute [instance] rof
open tactic

run_command do
 e ← to_expr `([5] : list ℕ),
 eval_expr ℕ e,
 return ()

noncomputable meta def mk_list : tactic (list ℚ) := do
 e ← to_expr `([3, 3] : (list ℚ)),
 eval_expr (list ℚ) e

run_command 
 mk_list >> return ()
```

Issue 1: in the first `run_command`, Lean reports an error at the backtick following `to_expr`. I'd expect this to appear at `eval_expr` instead.

Issue 2: in `mk_list`, Lean again reports an error at the backtick.
```
type mismatch at definition '_eval_expr.18.794', has type
  list ℚ
but is expected to have type
  Prop
```
- This is triggered by the following `run_command`, there's no error with that commented out.
- The error location is unstable: when I add a new declaration below, it somtimes moves to `run_command`.
- The error message doesn't make sense, where did `Prop` come from?
- This is only triggered when the type is declared as a constant. There's no issue when `rat` is replaced with `nat`.

**Comment by robertylewis** [comment]
Note, the `list ℚ` in the second example is just an artifact, the following produces the same error:

```lean
constant rat : Type
constant rof : linear_ordered_field rat
notation `ℚ` := rat
attribute [instance] rof
open tactic

noncomputable meta def mk_list : tactic ℚ := do
 e ← to_expr `(3 : ℚ),
 eval_expr ℚ e

run_command  mk_list >> return ()
```

**Comment by leodemoura** [comment]
I will fix the error message position issue, and the bad error message. That being said, you cannot use `eval_expr` with `rat`. How would we be able to execute code that uses axioms `rat` and `rof`?

**Comment by robertylewis** [comment]
Thanks! I don't expect to be able to use `eval_expr` with `rat` like this. This example was pared down from a more complicated one, which also (in retrospect) shouldn't work, but the mistake wasn't as obvious and the error messages made it difficult to find what was wrong.

**Comment by leodemoura** [comment]
fixed by commits above.
