### ISSUE TITLE
RFC: argument order for `list.map`, `list.foldl`, etc

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1403]
We currently define `list.map` and `list.foldl` (and many others) using the standard argument order used in several programming languages.

```lean
def map (f : α → β) : list α → list β
def foldl (f : α → β → α) : α → list β → α
```

As pointed out by @cmr in the slack channel, we use a different order for types such as `rb_map`.
```lean
meta constant fold {key : Type} {data : Type} {α :Type} : rb_map key data → α → (key → data → α → α) → α
```
Moreover, the alternative order is more convenient for the `^.` notation. For example, given `m : rb_map nat nat`, we can write
```lean
m^.fold 0 $ λ k d r, r + k
```

We currently define alternative names such as `list.for` 
```lean
def for : list α → (α → β) → list β :=
flip map
```
to be able to use the `^.` notation. However, we do it only for a few of them. 

One option is to change the order for `list.map` and `list.foldl`. That is,
```lean
def map : list α → (α → β) → list β 
def foldl  : list β →(f : α → β → α) → α → α
```
and make sure we use the `^.` friendly order everywhere in the standard library.

**Comment by robertylewis** [comment]
Does anyone regularly use partial applications of `map` or `foldl`? I've done this on occasion (iirc, mapping `foldl f a` over a list of lists). I suspect that the convenience of being able to use the `^.` notation would far outweigh the minor inconvenience of having to change these!

**Comment by leodemoura** [comment]
Here is a related issue: elaboration order.

```lean
-- using current order
check map (λ ⟨a, b⟩, a + b) [(1, 2), (3, 4)]
            --^ error here, the expected type is not known

-- using new order
check map [(1, 2), (3, 4)] (λ ⟨a, b⟩, a + b)  -- works
```
The first one fails because we need the expected type to elaborate the anonymous constructor notation `⟨a, b⟩`. Recall that we elaborate arguments from left to right.

So, the change would prevent this error that seems to occur frequently. @rlewis1988 I believe you have experienced it based on files we have exchanged.

I think it would be a bad idea to change the elaborator and make it "guess" the right order. 
First, in general, there is no global optimal order, it depends on the application. Example:
```lean
-- using current order
check map (λ p : (Σ n, vector nat n), p.1) (⟨1, v⟩::[]) -- works

-- using new order
check map (⟨1, v⟩::[]) (λ p : (Σ n, vector nat n), p.1)
          --^ error here the expected type is not known
```

**Comment by johoelzl** [comment]
I prefer the point-free style, i.e. the current version of `map` and `fold`. 

Does it make sense to extend the `^.` syntax to place the parameter at the first explicit argument of the type? So `x^.f y z` when `x : T a` and `T.f : b -> T c -> d -> e` is translated to `T.f y x z`? Or is this too special/arbitrary?

**Comment by leodemoura** [comment]
@johoelzl This is an interesting suggestion. I like it.
