### ISSUE TITLE
RFC: Revising the monadic hierarchy

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1422]
Now that we have the power of field default values, we should use it to revise the monadic typeclasses. We can now do basically everything Haskell can (except for cyclic default values), and even simulate [default superclass instances + overriding superclass fields](https://ghc.haskell.org/trac/ghc/wiki/IntrinsicSuperclasses). So the following would be a translation of some Haskell classes using superclass defaults.

```lean
open function

universe variables u v

class functor (f : Type u → Type v) : Type (max u+1 v) :=
(map : Π {α β : Type u}, (α → β) → f α → f β)
-- ` <$ `
(map_const : Π {α : Type u} (β : Type u), α → f β → f α := λ α β x, map (const β x))

class applicative (f : Type u → Type v) : Type (max u+1 v) :=
(pure : Π {α : Type u}, α → f α)
(seq  : Π {α β : Type u}, f (α → β) → f α → f β)
-- defaulted seq_left, seq_right...
(map  : Π {α β : Type u}, (α → β) → f α → f β := λ _ _ x y, seq (pure x) y)
(map_const : Π {α : Type u} (β : Type u), α → f β → f α := λ α β x, map (const β x))

instance applicative_to_functor (f : Type u → Type v) [applicative f] : functor f :=
{map := @applicative.map f _, map_const := @applicative.map_const f _}
```

Of course, the other thing Haskell can't do is formalizing each typeclass's laws. We could either do that inline or, to make life easier for the meta level, in a separate subclass.

```lean
class functor' (f : Type u → Type v) extends functor f :=
(map_id : ∀ (α : Type u), map (id : α → α) = id)
(map_comp : ∀ {α β γ : Type u} (f : β → γ) (g : α → β), map (f ∘ g) = map f ∘ map g)
(map_const_eq : ∀ {α : Type u} (β : Type u) (x : α), map_const β x = map (const β x))
```

It would be nice if we could also supply "default proofs" for e.g. `map_const_eq`, for which we would need an `auto_param` equivalent for structures so that the proofs are synthesized only when instantiating the typeclass.

Some other unresolved questions I can see:
* Do we want as much customizability as Haskell? `<$`, for example, is overridden exactly twice in the GHC stdlib: in `Last`, and `ST`.
* Which namespace? I'm slightly opposed to using `init.category` for definitions not based on an actual category formalization.

**Comment by Kha** [comment]
PS: The above code won't work in Lean without https://github.com/leanprover/lean/pull/1420

**Comment by leodemoura** [comment]
> We could either do that inline or, to make life easier for the meta level, in a separate subclass.

For meta, we can "prove" the typeclass' laws using:
```lean
meta constant trust_me {a : Prop} : a 
```
It is like a meta `sorry`.

**Comment by leodemoura** [comment]
> Do we want as much customizability as Haskell? <$, for example, is overridden exactly twice in the GHC stdlib: in Last, and ST.

I think we should.

**Comment by leodemoura** [comment]
> Which namespace? I'm slightly opposed to using init.category for definitions not based on an actual category formalization.

These definitions are all in the top-level. Do you mean "which folder"?
Other systems use Control (e.g., Idris) or Category (e.g., Agda).

**Comment by Kha** [comment]
> These definitions are all in the top-level. Do you mean "which folder"?

Oh, of course. In that case I'm fine with the current location.

**Comment by Kha** [comment]
Small note: it seems that premonads are usually defined as functors with `return`. Is there another name for our definition? Do we actually make use of it somewhere?

**Comment by leodemoura** [comment]
> Small note: it seems that premonads are usually defined as functors with return. Is there another name for our definition? Do we actually make use of it somewhere?

Our `pre_monad` class provides only the `bind` operation. 
@joehendrix requested this feature because he wanted to use the `do`-notation with structures that do not have a `return`. 
I did a quick search looking if there is a name for this, but didn't find one.

**Comment by spl** [comment]
[Here](https://hackage.haskell.org/package/semigroupoids-5.1/docs/Data-Functor-Bind-Class.html) is one example of something related. I've seen “premonad” refer to a functor with a unit (as @Kha mentioned), which I've also seen called a pointed functor. A brief search turned up a few examples of this use of premonad: [(1)](http://web.cecs.pdx.edu/~mpj/pubs/RR-1004.pdf), [(2)](https://www.cs.ox.ac.uk/jeremy.gibbons/publications/trmon.pdf), [(3)](http://users.cecs.anu.edu.au/~jeremy/pubs/cmkc/cmkc.pdf).

**Comment by leodemoura** [comment]
@spl I meant I didn't find a name for a structure that has a `bind` but doesn't have a `return`.

**Comment by leodemoura** [comment]
@kha @spl What about renaming our `pre_monad` to `has_bind`? We already have `has_mem`, `has_append`, `has_add`. So we avoid the conflict with the use of `premonad` in the literature.

**Comment by spl** [comment]
@leodemoura That works.
