### ISSUE TITLE
request: updating the 'parsing' message

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1434]
When the parsing message appears in emacs or VS Code, it shows the line number at which Lean started parsing, and from this I can work out if snapshots are being used, and how many commands back it is rewinding before using a snapshot.

> Would it be possible for this parsing message to update at some interval, to tell me where it's currently up to?

I have by now many cases where files sometimes take minutes to compile, and it would be very helpful to quickly monitor where the slow compilation is. (I'm aware of the --profile flag on the command line, but it would be great to have some of this information readily available in the editor.)

**Comment by gebner** [comment]
It's on my to do list (see to do section of #1405).  We would update the in-progress range whenever a command is finished, so you would see the parsing message going down command by command (as usual with a delay of 100ms or so, to prevent flickering).  Is that fine-grained enough?

What kinds of commands are usually slow for you (definitions, lemmas, print, run_command, eval, ...)?  If it is something other than definitions, we might be able to it async.

**Comment by kim-em** [comment]
A delay of 100ms is no problem (I'm worried about definitions which take >30s)! For me it is definitions that are slow.

**Comment by kim-em** [comment]
Now that #1405 has been merged, I'm going to re-open this issue. It would be very helpful for me. 

(My reading of @gebner's todo list was that this can't happen until some rewriting of the parser has occurred?)

**Comment by gebner** [comment]
@semorrison I hope to land this some time during the next week.  I am still fixing some minor issues, but it  already works pretty well: https://github.com/leanprover/lean/compare/master...gebner:async_parsing
If I open `lean-category-theory/universal.lean`, I can see the parser hanging at the comma category definition. :smile:

This is not yet the big parser refactoring, just a change to the top-level loop which parses the commands.

**Comment by kim-em** [comment]
Closed by the merge of #1489.
