### ISSUE TITLE
request: inspect goal states while still parsing 

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1436]
If the Lean server is still parsing the tail end of a file, I can't inspect the goal state within a `begin ... end` block, even if it has finished parsing the section of the file containing that block. I can see what the final unmet goals are, because a red squiggle appears under the `end`, and hovering over it shows be the unfinished goals. Nevertheless cmd-shift-enter (in VS code, I didn't check this in emacs) won't display the goal state for (intermediate or final) steps in the output window until the file has completely finished parsing.

Is it possible to fix this?

**Comment by gebner** [comment]
Oh, it looks like we're waiting for the final environment to be produced before answering info commands in the server: https://github.com/leanprover/lean/blob/42e08cac36fc790f188838aadfb85505855e9a6c/src/shell/server.cpp#L484

@Kha Can we just skip that dependency?  Or will something break horribly if we don't have the environment yet?

**Comment by gebner** [comment]
This should work since we merged #1439.  @semorrison Please reopen if the bug is still there for you.
