### ISSUE TITLE
Support for multiple let in do notation

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1444]
Currently, multiple `let` does not work in `do` notation.

    meta example : tactic unit :=
    do let x := tactic.skip, y := x in y --fails

    meta example : tactic unit :=
    do let x := tactic.skip in let y := x in y --succeeds

**Comment by leodemoura** [comment]
We recently added support for Haskell-like `let`-decls in do-notation.
We can now have `let x := v,` in a `do`-block.
That is,
```lean
do a_1,
     let x := v,
     a_2
```
is sugar for
```lean
do a_1,
     let x := v in do,
     a_2
```
The drawback is that after the `,`, Lean is now expecting the rest of a `do`-block.

**Comment by leodemoura** [comment]
Note that, the following is accepted now:
```lean
meta example : tactic unit :=
do let x := tactic.skip,
   let y := x,
   y
```

**Comment by leodemoura** [comment]
Apparently, Haskell allows the following variant that may be useful for us too.
```lean
meta example : tactic unit :=
do let {x := tactic.skip,
        y := x},
   y
```

**Comment by leodemoura** [comment]
Here is a way to fallback into the regular `let`-expression in the current implementation
```lean
meta example : tactic unit :=
do (let x := tactic.skip,
        y := x in y)
```
