### ISSUE TITLE
tests/lean/inductive_resultant_level_inference.lean failing in clang release builds

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1450]
according to Travis

**Comment by Kha** [comment]
introduced by 7dcc36277ab179c23a22b9cc008b4689dc028a18 (edit: oh, the test file itself too)

**Comment by dselsam** [comment]
I know about this and will fix it tomorrow.

**Comment by leodemoura** [comment]
Fixed by
d37fd17725b450ea12
89d0f1773e9fb6
