### ISSUE TITLE
Recursive functions over n-ary tree

### ISSUE THREAD

**Issue by jldodds** [leanprover/lean3#1457]
I'm attempting to write functions over n-ary trees defined as follows:

```lean
inductive tree (α : Type ) : Type 
| node : α → list tree → tree
```

Any attempt to write such a function is running into well-formed recursion issues. In particular I want:

```lean
def treemap α β (f : α → β) : tree α → tree β
```

**Comment by leodemoura** [comment]
Support for well-founded recursion in the equation compiler has not been implemented.
