### ISSUE TITLE
segfault / lean assertion violation

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1459]
While playing with tactics I induced a segmentation fault (strangely, on one computer this code reliably segfaults, while on the other computer, the same code reliably produces a LEAN ASSERTION VIOLATION). I committed the code in case anyone feels like tracking down the source of the problem:

    git clone https://github.com/semorrison/lean-category-theory
    cd lean-category-theory
    git reset --hard 67facc4ddbf82e0962f577a76e135b90663cfc4e
    lean --make

The last edits I made were in tactics.lean.

**Comment by kim-em** [comment]
Another (likely independent) LEAN ASSERTION VIOLATION is available at

    git clone https://github.com/semorrison/lean-category-theory
    cd lean-category-theory
    git reset --hard 8b4476581027d0599fb791b6701b9c6fba4a0199
    lean --make

This one is caused by [changing](https://github.com/semorrison/lean-category-theory/commit/8b4476581027d0599fb791b6701b9c6fba4a0199) `Type` to `Sort` in my definition of a category.

**Comment by leodemoura** [comment]
Fixed by
b803377d5e598
37c69427b3d
00e836025cf
65bc3ca1eb26
