### ISSUE TITLE
equation compiler: non-exhaustive even with wildcard

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1466]
These equations may be invalid for some reason, but the error message does not make sense and it is not clear how to fix the equations:
```Lean
inductive op : ℕ → ℕ → Type
| mk : ∀ n, op n n

structure node : Type := (id₁ id₂ : ℕ) (o : op id₁ id₂)

def f : list node → true
| (⟨.m₁, .m₁, op.mk m₁⟩::⟨1, 1, op.mk 1⟩::rest) := trivial
| _ := trivial

/-
/home/dselsam/projects/lean/issues/non_exhaustive.lean:6:4: 
error: invalid non-exhaustive set of equations
-/
```

**Comment by leodemoura** [comment]
The wildcard currently does not guarantee we cover all cases when we use indexed families.
The equation compiler uses "complete transition" when we have mixed variables and constructors during pattern matching. In this transition, a variable is replaced with a constructor application and fresh variables. For example `x : node` would be replaced with `node.mk id1 id2 o` where `o : op id1 id2`.
Then, we get to a state where we have patterns `op.mk m_1 : op m_1 m_1` and `o : op id1 id2`. We have to apply "complete transition" again to `o`. However, we can't unify `op id1 id2` with `op ?n ?n`. So, this case is rejected. That is, the willdcard is just a dummy in your example. 

As I said in another issue you have opened, we need an equation validator. It will reject this kind of equation and generate reasonable error messages.

**Comment by theemathas** [comment]
I just ran into a bug that seems related to this and I reduced the test case to this:

```lean
inductive foo : bool → Prop
| bar : foo ff
| baz : foo ff

example : ∀ (x : bool), foo x → true
| .ff foo.bar := trivial
| _ _ := trivial
```

Error message:

```
.../bug_find.lean:5:8: error: invalid non-exhaustive set of equations (use 'set_option trace.eqn_compiler.elim_match true' for additional details)
```

**Comment by leodemoura** [comment]
See #1594
