### ISSUE TITLE
dsimp runs forever

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1480]
I have some code where dsimp seems to get stuck (I've left it running for an hour...). 

    git clone https://github.com/semorrison/lean-category-theory
    cd lean-category-theory
    git reset --hard 6524a1ab5ad72f2b6f8a60fd9b472f0b13bcc328
    lean --make

The problem occurs at line 75 of [examples/semigroups/monoidal_category_of_semigroups.lean](https://github.com/semorrison/lean-category-theory/blob/dsimp-runs-forever/examples/semigroups/monoidal_category_of_semigroups.lean#L75). Commenting out that line, Lean finishes in seconds.

(I've attempted to minimise this example at least a bit by creating a branch with everything obviously extraneous removed.)

**Comment by leodemoura** [comment]
Have you tried to investigate the problem using 
```lean
set_option trace.dsimplify true
```
and 
```lean
set_option trace.debug.dsimplify true
```
The repository above has many `reducible` definitions. `dsimp` will inline all of them.
You can get an exponential blowup.

**Comment by kim-em** [comment]
I didn't know about those, thanks @leodemoura. I'll close this for now while I investigate.

I've known that the `reducible` definitions were dangerous, and perhaps this is just the final straw... I don't know what I'd do without them, unfortunately.

**Comment by kim-em** [comment]
No one is going to be happy about this, but I think dsimp really is getting into a loop here. I turned on `trace.dsimplify` and `trace.debug.dsimplify`, and dumped the output to a file. If you ignore the first 400,000 or so lines, the output starts repeating itself exactly every 26,852 lines. I let it run for a 200 or so periods (takes 10 minutes or so), to confirm it's really stuck in a loop.

**Comment by kim-em** [comment]
In case it is useful, a 15mb compressed copy of the output is at http://tqft.net/misc/dsimp.out.gz.

**Comment by leodemoura** [comment]
@semorrison Bad `[simp]` lemmas will make `simp` and `dsimp` loop.
Here is a tiny example
```lean
def f (x : nat) := x
def g (x : nat) := f x

@[simp] lemma f_lemma (x : nat) : f x = g x := rfl
@[simp] lemma g_lemma (x : nat) : g x = f x := rfl

example (x y : nat) : f x = y :=
begin
  dsimp
end
```

**Comment by kim-em** [comment]
In the end I did a major rewrite of my library, to reduce the size of implicit arguments (avoiding `[reducible]`, and not using inheritance), and this problem went away, so we can close this issue.

I think it's a bit worrying, nonetheless, that I could have written so much code before even learning that it was possible for `simp` to loop! (I think because lean occasionally told me that something was an invalid simplification lemma, I assumed something sufficient to avoid this was being checked.)

Does it make sense for `simp` to cache results? The example I had above seemed to get into loops (or at least be repeating itself 1000s of times) that took about 20s (and over 20,000 lines of output!).

**Comment by leodemoura** [comment]
> Does it make sense for simp to cache results?

It does cache results. 
https://github.com/leanprover/lean/blob/master/src/library/tactic/simplify.cpp
