### ISSUE TITLE
Allow nested `case` distinction

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1483]
We can use a custom interactive parser to allow patterns such as
```lean
 -- ex : ∃ a, p₁ a ∧ p₂ a
cases ex with a ⟨h₁, h₂⟩
```

**Comment by Kha** [comment]
It would also be nice to support case distinction in `intro(s)`, in analogy to `λ`.

**Comment by spl** [comment]
Along with these suggestions (which are all great), it would be nice to support types in `intro` as in `∀`/`λ`, e.g. `intro x : A`, `intro (x : A) (px : ∃ y, y > x)`, etc.

**Comment by spl** [comment]
Oh, and it would also be nice to support types in `cases`.

**Comment by Kha** [comment]
@digama0 has implemented a "recursive cases" tactic in mathlib: https://github.com/leanprover/mathlib/commit/c5c5b504b918a6c5e91e372ee29ed754b0513e85
As such, I'm closing this issue. We can open focused issues for the other suggestions noted above.
