### ISSUE TITLE
Local infix notation for parameters (or variables) fails in tactic-mode

### ISSUE THREAD

**Issue by johoelzl** [leanprover/lean3#1495]
Currently `library_dev` fails in `data/list/sort` as the following local infix notation does not work anymore.
This was mentioned by @rlewis1988 on slack a couple of days ago. I guess it is related to the `pexpr` changes by @Kha ?

```
section
variables (r : ℕ → ℕ → Prop)
local infix `≼` : 50 := r

example {a b : ℕ} : a ≼ b → true :=
begin
  show a ≼ b → true,
    from λx, trivial
end
end
```
The the `show` somehow `r_1` is expected. 

This also fails if we use `parameter`.
```
section
parameters (r : ℕ → ℕ → Prop)
local infix `≼` : 50 := r

example {a b : ℕ} : a ≼ b → true :=
begin
  show a ≼ b → true,
    from λx, trivial
end
end
```

When we have an additional type parameter `α` it fails there.
```
section
parameters {α : Type} (r : α → α → Prop)
local infix `≼` : 50 := r

example {a b : α} : a ≼ b → true :=
begin
  show a ≼ b → true,
    from λx, trivial
end
end
```

**Comment by Kha** [comment]
I believe the bug was introduced by https://github.com/leanprover/lean/commit/fdadada.

**Comment by robertylewis** [comment]
@johoelzl FYI, I fixed this locally so library_dev would compile -- let me know if you need the updated files.

[Edit: by "fixed," I mean I replaced the `≼` notation with `r`.]

**Comment by johoelzl** [comment]
@Kha thanks for the pointer.

@rlewis1988 lets see what the resolution of this issue is. I hope we can keep this kind of notation.

**Comment by robertylewis** [comment]
> lets see what the resolution of this issue is. I hope we can keep this kind of notation.

Oh, of course, I didn't mean to suggest we should permanently replace what is in library_dev. But if you need a temporary version that works, I have one.
