### ISSUE TITLE
request: flag to ask dsimplify_core to leave implicit arguments alone

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1509]
I often have situations where I'd like to prove something by unfolding some definitions, and then doing some rewriting.

Sometimes I find that I need to unfold a definition which appears in both explicit arguments and implicit arguments of the expression I'm looking at. Unfortunately, unfolding the implicit arguments causes a big problem --- I now need to use `erewrite` (or get stuck entirely) to work with these expressions.

Could we have an extra flag on `dsimplify_core` that asked it to leave implicit arguments alone? (It seems there's already a flag for leaving instance implicit arguments alone, so I'm hoping that this might be relatively straightforward.)

**Comment by kim-em** [comment]
If it's helpful I can post some particular examples where I run into this problem; I've now run into it several times, and in a few places am stuck because of it.

**Comment by kim-em** [comment]
(I'd raised this previously on [lean-user](https://groups.google.com/d/msg/lean-user/mLRrhjNpj3U/4ylJilsrDQAJ). There @Kha said this would require going into the C++ code.)

**Comment by kim-em** [comment]
Ugh.. I successfully modified the C++ code so the existing flag for leaving instance implicits alone just left all implicits alone. (With that I could verify that I could unfold the way the way I want to, but it also broke the behaviour of dsimp; in particular it could no longer simplify coercions in implicit arguments.)

When I tried to actually add an extra flag, I ran into the problem that dsimplify_core would now have 9 arguments, and the VM really didn't like that. :-(

**Comment by Kha** [comment]
> When I tried to actually add an extra flag, I ran into the problem that dsimplify_core would now have 9 arguments, and the VM really didn't like that. :-(

If it's about declaring the VM builtin, you can use code like this: https://github.com/leanprover/lean/blob/09867fcfe0711dfe80d83d0d011a704800ff4a7f/src/library/tactic/simplify.cpp#L1301-L1302
That said, we should probably refactor all those parameters into a defaulted config structure.

**Comment by kim-em** [comment]
Thanks. I tried using that, and the c code now compiles, but the library won't compile, due to a long list of errors like:

`/Users/scott/projects/lean/library/init/data/string/lemmas.lean:17:66: error: vm check failed: is_simple(o) || is_constructor(o) (possibly due to incorrect axioms, or sorry)`

I'm guessing that I did something wrong when [making a varargs wrapper](https://github.com/semorrison/lean/commit/e1c369f91bda3f3fdf99f3573087ae12f1a19130#diff-4976b9eef4ba43a7e6af8c40be1a0ffeR332) for `tactic_dsimplify_core`.

**Comment by kim-em** [comment]
Thanks, that seems to be working! Let me verify that this flag actually improves matters in my development, and hopefully I'll make a pull request soon.

**Comment by kim-em** [comment]
I'm going to close this one, as it's no longer particularly relevant for me, and no one else seems interested. :-)
