### ISSUE TITLE
equal goals may be considered unequal

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1517]
It seems that some extraneous information is being used to compare goals, which isn't reflected in the pretty printing of the goal. (So in particular goals which I think should be equal are considered as unequal.)

This occurs particularly when we revert and then re-introduce hypotheses, even when this doesn't change the order of hypotheses, and when there are no dependencies between hypotheses and goals.

Consider the following example:

````lean
open tactic

meta def force { α : Type } (t : tactic α) : tactic α :=
  do gs ← get_goals,
     a ← t,
     gs' ← get_goals,
     guard (gs ≠ gs') <|> fail "force tactic failed",
     return a

namespace tactic.interactive
  meta def force (t : itactic) : tactic unit := _root_.force t
end tactic.interactive

set_option pp.all true

lemma a ( p q : nat ) : 1 = 1 :=
begin
  -- p q : nat
  -- ⊢ @eq.{1} nat (@one.{0} nat nat.has_one) (@one.{0} nat nat.has_one)
  force {
    revert q,
    intron 1
    -- p q : nat
    -- ⊢ @eq.{1} nat (@one.{0} nat nat.has_one) (@one.{0} nat nat.has_one)
  } -- ... but force succeeds here.
end
````

I would have hoped that `force` would fail here.

**Comment by kim-em** [comment]
This is important to me because for my automation strategy it's important to be able to tell whether a tactic made actual progress. For many tactics I can use the return value, but for simplification, and in particular simplification of hypotheses, I think I'm going to have to use a `force` tactic to compare the goals before and afterwards.

**Comment by kim-em** [comment]
`eblast` seems to have the same problem --- the pretty printed (even with `pp.all`) goal may not appear to change, but the `force` tactic I'm using says that something happened.

**Comment by kim-em** [comment]
(It occurs to me that it's unnecessary for me to complain about `eblast`: `focus eblast` has the effect I'm after, even though `force eblast` runs into trouble. The main problem, with reverting and reintroducing goals, is still there.)

**Comment by avigad** [comment]
What is going on here is that every goal (i.e. metavariable) has a local context, which is a list of local variables. Every local variable has a user-facing name for pretty-printing, and a unique internal name. When you revert an element of the local context and then `intron 1`, you are creating a new local constant with the same user-facing name, but it is not the same local constant. 

More to the point, the goals are not the same metavariable. The original goal was one metavariable, and by starting to prove it with tactics, you are building an assignment for it, which is an expression that involves the other metavariable (in this case, the first is assigned to an abstraction of the other followed by an application).

I don't see an easy way to compare two goals to see whether they are equivalent. (But that does not mean there isn't one....) Can you write your tactics in such a way that you can manually track whether they have made progress?

**Comment by robertylewis** [comment]
You can compare the types of the goals instead of the goal metavariables themselves:
```lean
meta def force { α : Type } (t : tactic α) : tactic α :=
  do gs ← get_goals >>= monad.mapm infer_type,
     a ← t,
     gs' ← get_goals >>= monad.mapm infer_type,
     guard (gs ≠ gs') <|> fail "force tactic failed",
     return a
```
This doesn't seem particularly robust, but it might work for your purposes. I agree with Jeremy that the ideal solution is to have the tactics keep track.

**Comment by kim-em** [comment]
Thanks for these explanation. I guess this goes back to my earlier issue https://github.com/leanprover/lean/issues/1449, where I asked that dsimp should fail if it didn't change anything. @leodemoura disagreed there, say that it was annoying when writing tactics to have sub-tactics fail. I still feel the opposite --- it's annoying to have sub-tactics "silently fail", i.e. succeed even when they do nothing.

I've just read through the chain of calls [`simp`](https://github.com/leanprover/lean/blob/master/library/init/meta/interactive.lean#L624) `--->` [`simp_core`](https://github.com/leanprover/lean/blob/master/library/init/meta/interactive.lean#L598) `--->`  [`simp_goal`](https://github.com/leanprover/lean/blob/master/library/init/meta/interactive.lean#L514) `--->` [`simplify_core`](https://github.com/leanprover/lean/blob/master/library/init/meta/simp_tactic.lean#L201) that result when we call `simp` in interactive mode. I'm struggling to see where the failure is actually generated when there is nothing to simplify.

If someone could explain that, I'll happily adopt the strategy of modifying tactics so they track progress themselves.

**Comment by Kha** [comment]
> I'm struggling to see where the failure is actually generated when there is nothing to simplify.

It's in the `simplify_core` implementation, using the same approach as `force`: https://github.com/leanprover/lean/blob/36c7d46c34f89a671b27c9ca31bcd86bc5d5ad7b/src/library/tactic/simplify.cpp#L1242
I'm not sure I understand your original issue yet. While `force { intro...dsimp...revert }` does not work, shouldn't `intro...force {dsimp}...revert` do what you want?

**Comment by kim-em** [comment]
Thanks, @rlewis1988  and @Kha, those are both very helpful solutions, that I think should solve my problem.
