### ISSUE TITLE
[RFC] Reference Manual

### ISSUE THREAD

**Issue by jroesch** [leanprover/lean3#1524]
I started work on a [reference manual](https://jroesch.gitbooks.io/the-lean-reference/content/) the other night. Rust has used a variant of Gitbook for maintaining their [reference](https://doc.rust-lang.org/nightly/reference/) manual for a long time, as well as books such as [Rust by Example](http://rustbyexample.com/). 

I propose we experiment with using Gitbook to develop the reference manual for a few reasons.

- search, gitbook implements full text search which is incredibly useful for a manual
- glossary support
- plugins, we can piggy back on other's code to add functionality to the book, as well as write our own (port the ability to run code snippets for example, just like Rust does)
- ease of maintenance, if it is an acceptable alternative, we should be able to reduce the infrastructure we must maintain as a project

To achieve feature parity with `mkleanbook` we would need to update Pygments highlighting, and add support for executing snippets (we should be able to just copy Rust by Example's plugin which does just this with playground).

**Comment by gebner** [comment]
I am also in favor of switching away from mkleanbook.  Gitbook also supports latex formulas and PDF export, so if everything goes well with the reference manual I think we should convert TPIL, PIL, and IL as well.

> we should be able to just copy Rust by Example's plugin which does just this with playground

We can definitely use it as a template for a `gitbook-plugin-lean`.  The actual code in mkleanbook that is responsible for the lean server integration and input method is maybe a hundred lines, this should be easy enough to port/reimplement.

**Comment by avigad** [comment]
Gitbook looks good. If things go well with the reference manual, I would be happy to move the tutorials there, and also the textbook for the logic and proof class. Latex support is important for the latter.

**Comment by leodemoura** [comment]
@jroesch I'm not familiar with gitbook. I went to their website and found this:
https://www.gitbook.com/pricing
Could you please clarify how gitbook works?
For example, if they go out of business, what does it happen with our books?
The free option allows only 5 collaborators.

**Comment by alashworth** [comment]
I quite like that gitbook now supports AsciiDoc markup as well as Markdown. Asciidoc already has many plugins to convert to DocBook -> Latex, html, etc, and has a well-defined syntax (AsciiDoc is XML under the hood) for adding extensions.

**Comment by Kha** [comment]
@leodemoura
> Could you please clarify how gitbook works?

While they don't seem to directly advertise it on their website (understandably :) ), building gitbooks locally is also possible: https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md

**Comment by jldodds** [comment]
How can I contribute to this reference? I'm running into issues that I would like documented daily, and have some time that I can put into doing so (or at least stubbing out places that I've wished documentation existed)

**Comment by jroesch** [comment]
@jldodds I'll post an update early next week, we need to migrate the rough prototype that I sketched up to an official repo, and then we will be happy to take pull requests :)

**Comment by jroesch** [comment]
@jldodds the reference is now live at https://github.com/leanprover/reference. Contributions are welcome, just drop by Gitter or post here and let me know what you are planning on doing so we can make sure not to duplicate any work.

**Comment by gebner** [comment]
See https://leanprover.github.io/reference
