### ISSUE TITLE
Can't use parameter (declared in section) in rewrite tactic

### ISSUE THREAD

**Issue by timjb** [leanprover/lean3#1527]
```lean
-- works
lemma foo (A : Type) (a b : A) (h : a = b) : a = b :=
  by rewrite h

section

  parameter (A : Type)
  parameters (a b : A)
  parameter (h : a = b)

  -- doesn't work, gives error "unknown identifier 'h'"
  lemma foo' : a = b :=
    by rewrite h

end
```

This parameter `h` should be in scope in the tactic call, right?

I'm using a recent HEAD version:

```
$ lean --version
Lean (version 3.1.1, commit 8ea2bc08cb03, Release)
```

**Comment by alashworth** [comment]
This is not a bug, but part of how Lean handles variable and parameter declarations.  See "Theorem Proving in Lean", page 54.

To fix, you can write "include h" below "parameter (h : a = b)".

**Comment by timjb** [comment]
@alashworth Thanks for pointing this out! I think the error message could be a little more helpful ("Did you mean the parameter 'h' in the section? To access it inside this tactic script, you have to include it before.").
