### ISSUE TITLE
Testing external packages

### ISSUE THREAD

**Issue by jroesch** [leanprover/lean3#1575]
A missing piece of moving code out of the standard library is package testing. For example I moved all code and tests for the `smt2` interface out of the standard library, but ended up disabling the tests because we don't provide a mechanism for checking tests beyond examples.

An issue with relying on examples is that their failure (even when intentional) stops the project from building, which is problematic when compared with traditional testing techniques. 

I wanted to chat about our wish list for such a feature and brainstorm potential designs, or discuss any issues that may exist. 

I know @leodemoura has some thoughts about asserting defn. equality about goals, but for non-tactics we might want to provide similar primitives. 

One feature on my wish list is a command in the style of `cargo/npm/bundler/etc test` which allows us to get a nice view of all test failures and successes.

cc @Kha @gebner

**Comment by Kha** [comment]
> An issue with relying on examples is that their failure (even when intentional) stops the project from building, which is problematic when compared with traditional testing techniques.

This seems to be an argument for having sources in `src/` by default - that way, errors in `test/` will not influence the standard build.

**Comment by Kha** [comment]
So in the most basic implementation, `leanpkg test` would just try to build `test/` (with `src/` added to LEAN_PATH).

**Comment by leodemoura** [comment]
@jroesch Is this still an issue?

**Comment by jroesch** [comment]
@leodemoura I think we resolved it for the time being with the current solution.
