### ISSUE TITLE
apply tactic takes 15 minutes to complete

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1582]
I have a very curious case where applying a lemma takes ~15 minutes to execute. I successfully apply the lemma almost instantaneously in many other places in my code, so I'm quite sad about this one!

It can be reproduced via:

````
git clone https://github.com/semorrison/lean-monoidal-categories
cd lean-monoidal-categories
git reset --hard 33a80e06b470162b78c4a74b939e1560c29a57ac
leanpkg configure
lean --make lemmas/pentagon_in_terms_of_natural_transformations.lean 
````

The offending line is at <https://github.com/semorrison/lean-monoidal-categories/blob/33a80e06b470162b78c4a74b939e1560c29a57ac/lemmas/pentagon_in_terms_of_natural_transformations.lean#L21>, and is `apply NaturalTransformations_componentwise_equal`. That lemma is defined at <https://github.com/semorrison/lean-category-theory/blob/master/natural_transformation.lean#L27>.

> Is something going wrong? I'm having trouble imagining how Lean can take 15 minutes to apply that lemma.

> If this is intended behaviour, does anyone have suggestions for identifying when this sort of slow-down while occur, and avoiding it?

**Comment by kim-em** [comment]
Okay, now that #1607 has been resolved, I have updated instructions for reproducing the problem:

````
git clone https://github.com/semorrison/lean-monoidal-categories
cd lean-monoidal-categories
git reset --hard e369984a689868fa65436453145b3795224b0d64
leanpkg configure
lean --make src/monoidal_categories/lemmas/pentagon_in_terms_of_natural_transformations.lean 
````

**Comment by leodemoura** [comment]
@semorrison We need a (small as possible) repro. That is, a small self contained `.lean` file that exposes the problem.

**Comment by kim-em** [comment]
The problem seems to have been resolved. The relevant `apply` now takes about 10 seconds, which is acceptable.
