### ISSUE TITLE
Enum types don't accept type annotations

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1593]
The type

    inductive foo : Type
    | bar | baz

does not compile, with error:

    universe level of type_of(arg #1) of 'foo.baz' is too big for the corresponding inductive datatype

If the type annotation is left off (as `inductive foo | bar | baz`), then it will compile and land in `Type` anyway.

**Comment by dselsam** [comment]
I cannot reproduce this problem. Both versions compile correctly on my machine.

**Comment by dselsam** [comment]
@digama0 What compiler are you using? Is this on current master?

**Comment by digama0** [comment]
Crap, now I can't reproduce it. Ah, whatever, I'll try to pin it down more precisely next time I see it.
