### ISSUE TITLE
bad error position on Emacs

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1597]
In the following example, we get the correct error position.
```lean
example : true := 
begin
    note h' := eq.refl _,
             --^ note_error.lean:4:15: error: don't know how to synthesize placeholder

end
```
This is fine. `note` is complaining it could not synthesize the `_`.
However, in the following one, the error is shown at `}`.
```lean
example : true := 
begin
  {
    note h' := eq.refl _,
   }
--^  error message moved here
end
```
We have experienced this problem in a much bigger proof where it is quite hard to diagnose the problem.

**Comment by gebner** [comment]
Fixed in https://github.com/leanprover/lean/commit/54114fd7bd8feb6826c54a5fdbef3a7935baa3af
