### ISSUE TITLE
`do 2 constructor` doesn't work when `constructor; constructor` does

### ISSUE THREAD

**Issue by JasonGross** [leanprover/lean3#1602]
I'm not sure if this is a bug, or just me not knowing how to use lean, but it seems that `constructor` is a tactic, because this works:
```lean
def some_lets : ℕ → ℕ → ℕ
| 0            v := v
| (nat.succ n) v := let k := v + v in some_lets n k

def some_unfolded_lets (n : ℕ) : ∃ v : ℕ , v = some_lets 20 n :=
begin
  unfold some_lets; constructor; constructor
end
```
The [quick reference](https://leanprover.github.io/tutorial/quickref.pdf) says that I should be able to do `do <num> <tac>`, but this does not work:
```lean
def some_lets : ℕ → ℕ → ℕ
| 0            v := v
| (nat.succ n) v := let k := v + v in some_lets n k

def some_unfolded_lets (n : ℕ) : ∃ v : ℕ , v = some_lets 20 n :=
begin
  unfold some_lets; do 2 constructor /- -*- mode: compilation; default-directory: "~/Documents/repos/lean-playgorund/" -*-
Compilation started at Thu May 25 14:01:13

/home/jgross/Documents/repos/lean/bin/lean  /home/jgross/Documents/repos/lean-playgorund/test.lean
/home/jgross/Documents/repos/lean-playgorund/test.lean:7:25: error: unknown identifier 'constructor'

Compilation exited abnormally with code 1 at Thu May 25 14:01:13
-/
end
```

**Comment by leodemoura** [comment]
The quick reference is outdated. The `do <num> <tac>` was only available in Lean 2. 
In Lean 3 (the current version), `do` is a keyword similar to the one available in Haskell.

**Comment by robertylewis** [comment]
`tactic.repeat_exactly` has the same behavior has the Lean 2 `do`, but it looks like there isn't an interactive mode version yet.

**Comment by avigad** [comment]
We now emphasize that the quick reference is for Lean 2: https://leanprover.github.io/tutorial/quickref.pdf. We can discuss whether we should have a quick reference for Lean 3 or whether the reference manual @jroesch is working on will be enough, but in the meanwhile, I suggest closing this issue.

**Comment by leodemoura** [comment]
@avigad Ok, I'm closing it.
