### ISSUE TITLE
[Bug] cc does not handle ne as goal

### ISSUE THREAD

**Issue by johoelzl** [leanprover/lean3#1608]
The congruence closure tactic `cc` does not work with `ne`. Surprisingly `begin [smt] end` works. Also a unfolded `¬ (b = a)` is also okay.

```lean
example {α : Type} {a b : α} (h : ¬ (a = b)) : b ≠ a :=
by cc -- fails

example {α : Type} {a b : α} (h : ¬ (a = b)) : ¬ (b = a) :=
by cc -- works

example {α : Type} {a b : α} (h : ¬ (a = b)) : b ≠ a :=
begin [smt] end -- works
```

**Comment by leodemoura** [comment]
This is expected. The [smt] tactic preprocess the goal. This is why the third version works.
We can add support to ne for users that are invoking cc from the regular tactic monad (first example).

**Comment by johoelzl** [comment]
Okay, I thought that there is a difference in how propagation works. I now see that the last example works as `dsimp` unfolds `ne` (`dsimp` is part of the `smt` preprocessing).

How would you add support? Also calling `dsimp`? Then the following example would also wotk:
```lean
example {α : Type} {a b : α} (h : a ≠ b) : b ≠ a :=
by cc -- fails
```

Another question: Is this kind of preprocessing also performed on new instances added by `ematch`?

**Comment by leodemoura** [comment]
> How would you add support? Also calling dsimp? 

I will add support for it in the `cc` module. 
In this way, it will work for hypotheses too.
Otherwise, we will have to apply `dsimp` to all of them.

> Another question: Is this kind of preprocessing also performed on new instances added by ematch?

Yes.
