### ISSUE TITLE
Macro applications

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1610]
I'm adding an issue to save a feature suggested by @kha in another thread.
For `printf` and even more complex applications, we could also implement a macro system that allows them to use the full power of the VM and the meta level.
```lean
@[macro]
meta def printf (s : string) : tactic expr := ...

#check printf "%d: %s" -- nat -> string -> string
```

**Comment by leodemoura** [comment]
Here is a possible way to implement it.
Whenever the elaborator finds a pre-term headed by a constant tagged with `[macro]`, it fully elaborates the macro arguments, makes sure they are closed terms, and then invokes the VM to get the resulting expression. 
Example: given`printf "%d: %s" t s`, we first elaborate `printf "%d: %s"`, and execute. Then we replace this pre-term with the resulting term. Then, we elaborate `t` and `s` using the information about their expected type.

**Comment by Kha** [comment]
Alternatively, this could be implemented via user-defined notations, which I believe we wanted to have anyway:

```lean
reserve prefix `printf`:100

@[notation]
meta def printf_macro (_ : parse $ tk "printf") (s : parse parser.string) : tactic pexpr := ...
```

The only downside I can see is that we lose namespacing. On the other hand, I think I'd prefer a nicer notation like `f"$x $y"` (that makes use of `to_format`) anyway.

**Comment by leodemoura** [comment]
@kha For `printf`, the nicer notation is indeed cool.
Both features seem to be useful: user-defined notations and macro applications.
Macro applications are processed by the elaborator. So, they are more flexible since they can access the local context (if we want). At parsing time, the local context is not really available (the types are missing or are pre-terms).

**Comment by Kha** [comment]
> So, they are more flexible since they can access the local context (if we want).

Ah, I overlooked that fact. Providing separate parsing mechanisms for the two seems redundant, so how about exposing a Lean API for creating new `macro_definition`s? They would come with a callback for elaborating them and could be inserted by user-defined notation parsers.

**Comment by leodemoura** [comment]
> how about exposing a Lean API for creating new macro_definitions? They would come with a callback for elaborating them and could be inserted by user-defined notation parsers.

This is cool, but it is not clear how much work would it be.
There is also a dependency problem. The `macro_definition` is defined in the Kernel. So, it is not clear how the elaboration callback would look like.
To expose the current `macro_definition`, we would also have to expose the `abstract_type_context` functionality.

**Comment by Kha** [comment]
These macros should be purely pre-elaboration, so I don't think they need to be expandable(?). The callback would be invoked by the elaborator, just like the current `visit_macroX` handlers.

**Comment by Kha** [comment]
Actually, can we just use `by` for that? Or could it be too "lazy" for some use cases?

```lean
meta def build_printf (s : string) : tactic expr := ...

reserve prefix `printf`:100
@[notation]
meta def printf_macro (_ : parse $ tk "printf") (s : parse parser.string) : tactic pexpr :=
pure ``(by build_printf %%(reflect s))
```

Btw. what do you think about splicing locals even into ``() quotations? I didn't implement it originally because it didn't "feel right", but the fewer `reflect` the merrier, imo.

**Comment by leodemoura** [comment]
I'm closing this issue. @kha has already implemented the approach described in the previous comment. Moreover, issue #1674 subsumes the rest.
