### ISSUE TITLE
leanprover/homebrew-lean is out of date wrt lean versions

### ISSUE THREAD

**Issue by cartazio** [leanprover/lean3#1618]
i opened a ticket there too  https://github.com/leanprover/homebrew-lean/issues/11

**Comment by jroesch** [comment]
We have been in a period of heavy of development and the person who maintained the formula is no longer actively working on the project. The current install options are either the tarball provided from the main repository or building from source. We intend to update the formula soon ™️, just need to allocate some man hours for it.

**Comment by Josh-Tilles** [comment]
@jroesch I’ve actually got an updated version of the formula that I’ve been meaning to publish. I’ll have a PR against the other repo later today.

**Comment by Josh-Tilles** [comment]
Alright, well, my earlier stated timeline was optimistic, but I have indeed opened a PR: https://github.com/leanprover/homebrew-lean/pull/12.

**Comment by jroesch** [comment]
Thanks to @MerelyAPseudonym @soonhokong plus a little glue work from me it should be working again, even bottled for Sierra.
