### ISSUE TITLE
lean 3.1.0 fails to build on mac osx with gcc/g++ version 7 

### ISSUE THREAD

**Issue by cartazio** [leanprover/lean3#1619]
the error in the build is 
```In file included from /Users/carter/Desktop/repoScratcher/lean-3.1.0/src/frontends/lean/token_table.h:10:0,
                 from /Users/carter/Desktop/repoScratcher/lean-3.1.0/src/frontends/lean/scanner.h:16,
                 from /Users/carter/Desktop/repoScratcher/lean-3.1.0/src/frontends/lean/parser_state.h:12,
                 from /Users/carter/Desktop/repoScratcher/lean-3.1.0/src/frontends/lean/parser.h:24,
                 from /Users/carter/Desktop/repoScratcher/lean-3.1.0/src/library/module_mgr.h:18,
                 from /Users/carter/Desktop/repoScratcher/lean-3.1.0/src/library/module.cpp:31:
/Users/carter/Desktop/repoScratcher/lean-3.1.0/src/util/trie.h: In lambda function:
/Users/carter/Desktop/repoScratcher/lean-3.1.0/src/util/trie.h:69:70: error: 'this' was not captured for this lambda function
                     new_t1->m_children.insert(k, merge(n1.steal(), c2));
                                                                      ^
/Users/carter/Desktop/repoScratcher/lean-3.1.0/src/util/trie.h: In lambda function:
/Users/carter/Desktop/repoScratcher/lean-3.1.0/src/util/trie.h:82:38: error: 'this' was not captured for this lambda function
                 for_each(f, c, prefix);
```

**Comment by leodemoura** [comment]
Could you please check whether the commit above fixes the problem?

**Comment by cartazio** [comment]
it fixes that problem/build error, though  then get about 4 thousand duplicate linker symbol errors 
along with some case coverage/fall through warnings (attached both)

should those be split into new tickets?

[lean-build-linker-dup-errors.txt](https://github.com/leanprover/lean/files/1039992/lean-build-linker-dup-errors.txt)
[lean-build-warnings.txt](https://github.com/leanprover/lean/files/1039993/lean-build-warnings.txt)

**Comment by leodemoura** [comment]
@cartazio I installed gcc 7 on a Mac, and managed to reproduce the problems.
I just pushed a series of fixes. With these fixes, I managed to compile Lean using gcc 7 without warnings and/or errors.

**Comment by cartazio** [comment]
just did a build myself on master commit 24048c42584f12c476377ddda752fe5178271b87 to check right now. Looks all green!

I'm glad my bug report was helpful and thankyou for being so responsive!

I suppose I can/should close the ticket now :)
