### ISSUE TITLE
Coinductive predicates

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1621]
Coinductive predicates are useful in practice and are used in projects such as CompCert. 
We can define coinductive predicates using an impredicative fixpoint in `Prop` without any kernel extension.
@gebner has manually defined a few examples using the approach: https://gist.github.com/66bab9997d4b37fdb0884f7bcab95418#file-coindpred-lean
He used an auxiliary inductive predicate to define the functional and minimize the amount of boilerplate code.
However, it would still be useful to automate the process and automatically generate the construction in the example above.

**Comment by Kha** [comment]
In case someone wants to implement this purely in Lean, I'd be happy to implement user-defined commands for that. I didn't yet because I didn't see any need for them, but it shouldn't be very different from #1617.

**Comment by johoelzl** [comment]
I want to see coinductive predicates in Lean. I will take a look at it.

**Comment by leodemoura** [comment]
@kha @johoelzl The parser for `coinductive` command is similar to the one for the
`inductive` command. The drawback is that you will need to do it in C++.
The advantage is that we will make sure the syntax for the two commands is similar.
One possibility is to do the parsing in C++, and invoke tactics written in Lean.
This is not feasible for the inductive command since we need it before the tactic framework is defined, but this should not be a problem for `coinductive`.

**Comment by leodemoura** [comment]
@johoelzl Can we close this issue? Or, is there something missing in the implementation?

**Comment by johoelzl** [comment]
We can close it. I think it make sense to open separate issues when there are problems with `coinductive` or the `coinduction` tactic.
