### ISSUE TITLE
Scanner thinks 0xFF is the end of the file

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1624]
I've managed to pare this example down to:

`parent.lean`:

    namespace parent
    def test : list nat → list nat := id
    end parent

`child.lean`:

    import .parent
    namespace child
    open parent
    end child

The whole project has the layout

    /
        /parent.lean
        /child.lean

Now when you run `lean child.lean` you get:

    /child.lean:3:5: error: invalid namespace name 'parent'

In server mode, if `parent.lean` is loaded first there will be no namespace errors.

**Comment by gebner** [comment]
I am unable to reproduce this bug here:
```
[gebner:~/leanscratch] $ head parent.lean child.lean
==> parent.lean <==
namespace parent
def test : list nat → list nat := id
end parent

==> child.lean <==
import .parent
namespace child
open parent
end child
[gebner:~/leanscratch] $ lean child.lean
[gebner:~/leanscratch] $
```

Have you saved both files?  Are you on windows maybe?

**Comment by digama0** [comment]
Both files are saved, and I am on windows.

`head` gives me this:

    $ head parent.lean child.lean
    ==> parent.lean <==
    ▒▒namespace parent
    def test : list nat ▒! list nat := id
    end parent
    
    ==> child.lean <==
    import .parent
    namespace child
    open parent
    end child
 
What catches my eye, besides the unicode mangling, is the unicode marker at the beginning of `parent.lean`, probably a BOM. Would this cause lean to have difficulty reading the file?

**Comment by digama0** [comment]
That turned out to be the case. The file had been saved as `UTF-16`, and re-saving it as `UTF-8` caused the error to go away. What is lean's position on non-`UTF-8` files?

**Comment by gebner** [comment]
> What is lean's position on non-UTF-8 files?

They don't exist, everything is UTF-8. :smile:  Though I wonder why we didn't fail more loudly on the UTF-16 file.

**Comment by digama0** [comment]
At least UTF-16 marks itself so that you can tell (using the BOM). If it was encoded using Windows-1252 or something you wouldn't even know until you found a mangled character.

**Comment by gebner** [comment]
What happens is that we internally use `(char) -1` as the code for end-of-file.  And guess how the UTF-16 BOM looks like?  Yes, `ff fe`...

So we can easily fix this problem by adding `ff` as the first byte to `child.lean` as well. /s
