### ISSUE TITLE
Using non-computable constants in reflected terms fails due to check for meta definitions

### ISSUE THREAD

**Issue by johoelzl** [leanprover/lean3#1631]
The following definitions fails. Is this an inherent problem how reflection works, or is it possible to work around it? Is it possible to ignore `reflected` when checking computability?

```lean
/- using non-computable function -/
constant c : ℕ
meta def t : expr := `(c)
```

**Comment by leodemoura** [comment]
I started to investigate the problem, and I found a related problem with the `reflected` approach.
At runtime,
```
`(t)
```
evaluates `t`. For example, the quotation for `(fib 1000000)` will evaluate it and throw the result away. Here is an extreme example:
```lean
meta def loop : nat → nat
| n := loop n

meta def tst : expr := `(loop 1)

#eval tst -- loops
```

**Comment by leodemoura** [comment]
I fixed the problem described in the previous comment.
The original issue was not fixed.
We need to refine the `noncomputable` check.

**Comment by Kha** [comment]
Using `inline` is a nice hack, but I get the feeling we would need something like erasure annotations on parameters for a full fix. I'm ready to change \`() back to `expr` to solve this particular problem, but it does sound like an issue that may be reoccurring in the future.

**Comment by leodemoura** [comment]
@kha We should not implement erasure annotations right now. We want to refactor the code generator to be able to generate efficient native code. We will need a new representation for builtin procedures.
