### ISSUE TITLE
tac ; [tac_1 | ... | tac_n] notation in interactive mode

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1634]
@gebner @kha: I was talking with @Armael today, and he asked if we had support for the Coq 
```
tac ; [tac_1 | ... | tac_n]
```
notation.
First, I implemented the tactic `seq_focus`
```lean
meta def seq_focus (tac1 : tactic unit) (tacs2 : list (tactic unit)) : tactic unit :=
do g::gs ← get_goals,
   set_goals [g],
   tac1, focus tacs2,
   gs' ← get_goals,
   set_goals (gs' ++ gs)
```
Then I added a heterogeneous `andthen` type class and used `;;` as notation for it.
```lean
meta instance : has_handthen (tactic unit) (list (tactic unit)) (tactic unit) :=
⟨seq_focus⟩
```
I think this is a reasonable solution for regular tactic mode, and we can write
```lean
 tac ;; [tac_1, ..., tac_n]  
```
Here is an example:
```lean
open tactic

lemma ex (a b c : nat) : a + 0 = 0 + a ∧ b = b :=
begin
  (constructor;; [skip, constructor]),
  -- Remaining goal is
  -- |- a + 0 = 0 + a
end
```
We can make it nicer by making the regular `andthen` type class heterogeneous.
If we do this, we will be able to write `tac; tac_1` and `tac; [tac_1, ..., tac_n]`.

Note that I had to use `(...)` to drop from interactive tactic mode.
I didn't find a nice way to support this notation in interactive mode.
For example, we do not have support for a list of `itactic` in the parser extension module.
What do you think?

**Comment by Kha** [comment]
More heterogeneity sounds good. If we can make it work without the homogeneous one, even better.

> I didn't find a nice way to support this notation in interactive mode. For example, we do not have support for a list of itactic in the parser extension module.

Wouldn't we need to be special-case this at `parse_tactic_fn::parse_andthen`? I don't see how `itactic` comes into play then, but perhaps we should change it to use `parse_elem` instead of `parse_nested_interactive_tactic` so that we can use `repeat constructor`, declare a `list_of_itactic` parser, etc.?

**Comment by Kha** [comment]
> declare a `list_of_itactic` parser

I forgot that `itactic` isn't actually a parser right now; we may want to remedy that at some point. But as said, I think this is an unrelated issue.

**Comment by leodemoura** [comment]
> Wouldn't we need to be special-case this at parse_tactic_fn::parse_andthen ?

Yes, we can add support for it in C++. 
I didn't find a pure Lean solution.

> I forgot that itactic isn't actually a parser right now

Yes, it is not. I knew it was not, but I had forgot :)
I found out (again) yesterday, when I tried to implement this feature for @Armael.
