### ISSUE TITLE
Confusing error message "unknown identifier 'constructor'"

### ISSUE THREAD

**Issue by JasonGross** [leanprover/lean3#1637]
What's causing Lean to not know what `constructor` means?
```lean
meta def foo : tactic unit :=
  do [g] <- tactic.get_goals,
     tactic.refine (pexpr.of_expr g)

lemma bar : 0 = 0 :=
begin
 transitivity, { foo; constructor }
end
```
gives
```
-*- mode: compilation; default-directory: "~/Documents/repos/lean-playgorund/" -*-
Compilation started at Fri Jun  2 01:42:31

/home/jgross/Documents/repos/lean/bin/lean  /home/jgross/Documents/repos/lean-playgorund/test2.lean
/home/jgross/Documents/repos/lean-playgorund/test2.lean:7:22: error: unknown identifier 'constructor'
/home/jgross/Documents/repos/lean-playgorund/test2.lean:8:0: error: tactic failed, there are unsolved goals
state:
⊢ ?m_1 = 0

Compilation exited abnormally with code 1 at Fri Jun  2 01:42:32
```

**Comment by leodemoura** [comment]
In `begin ... end` blocks, we are in "tactic interactive mode" by default.
In this mode, we use "auto quotation" for any tactic in the namespace `tactic.interactive`.
For example, in this mode, `apply H` is notation for
```lean
tactic.interactive.apply ``(H)
```
Lean drops from interactive mode whenever a `(`, `do` or an identifier that is not in `tactic.interactive`. `foo` is not in `tactic.interactive`. Thus, Lean goes to regular mode.
The following works:
```lean
meta def foo : tactic unit :=
  do [g] <- tactic.get_goals,
     tactic.refine (pexpr.of_expr g)

open tactic
lemma bar : 0 = 0 :=
begin
 transitivity, { foo; constructor }
end
```
Another option is to put `foo` in the namespace `tactic.interactive`.
```lean
namespace tactic
namespace interactive

meta def foo : tactic unit :=
  do [g] <- tactic.get_goals,
     tactic.refine (pexpr.of_expr g)

end interactive
end tactic

lemma bar : 0 = 0 :=
begin
 transitivity, { foo; constructor  }
end
```
BTW, in Emacs, we can use `M-.` to jump to definition.

**Comment by JasonGross** [comment]
Ah, thanks!  (By the way, if there's a better place to ask questions that I'm not sure are bugs, feel free to point me there.)

**Comment by alashworth** [comment]
There is a chat room available for Lean discussion at https://gitter.im/leanprover_public/Lobby

**Comment by leodemoura** [comment]
@gebner @Kha I found the behavior described in this issue quite confusing. 
The main issue is that Lean will fallback to regular tactic mode if the current identifier is `id` and there is no `tactic.interactive.id`. I want to change this behavior and report an error. Then, if the user wants to fallback into regular tactic mode to invoke a tactic `foo`, they will have to use `(` or a `do`, and make it clear the intention. Do you agree?
