### ISSUE TITLE
Emacs mode: goal buffer flickering

### ISSUE THREAD

**Issue by Armael** [leanprover/lean3#1643]
This is an issue related to the emacs mode. When in tactic mode, with a buffer (spawned using `C-c C-g`) displaying the current goal, this buffer becomes empty as soon as one starts typing a new tactic. It only displays something again once the new tactic has been completely written and appended with a `,`.

This behavior becomes quickly annoying: I'm often looking at the current goal while typing the next tactic, potentially copying out part of it (e.g. `assert`ing it); but then at soon as I start typing the buffer becomes empty and the goal disappears.  
An example of proof I'm working on is https://github.com/FStarLang/kremlin/blob/verified/verified/lowstar_to_cstar_proof.lean#L242 , and because lean also takes some time (~1s) to re-check the proof after each modification, it becomes quickly tiring to edit the proof.

It would be nice if the buffer could just stay the same until I finished writing the new tactic and typed `,`.

I personally would also be very happy with a mode where the currently displayed proof state isn't necessarily where my cursor is. This would be somewhat similar with how proof general works, where one manually moves the proof state with a keybind. Having instant refresh of the proof state is neat, but I find it also quite visually distracting/annoying to have the goal/error buffer to constantly flicker when typing a definition/proof.

**Comment by Kha** [comment]
The VS Code extension has a command for pausing updates to the info window. We could add it to the emacs extension, would that help you?

**Comment by gebner** [comment]
@Kha The vscode extension also remembers the the last tactic state, so it doesn't disappear when typing.  In emacs, we can probably just skip the update if the tactic state is empty.

**Comment by Armael** [comment]
> The VS Code extension has a command for pausing updates to the info window. We could add it to the emacs extension, would that help you?

Yes, that would help. It doesn't feel like a fully satisfactory solution, though; basically my workflow would become: freeze buffer, type new tactic, unfreeze buffer...

**Comment by Kha** [comment]
@Armael I've implemented @gebner's suggestion and additionally made sure that the goal view is always up to date. Does this work for you?

**Comment by robertylewis** [comment]
@Kha The Lean Goal buffer isn't working for me at all after the latest commits. I enter
```lean
example : true :=
begin

end
```
and type `C-c C-g`, and I see an empty Lean Goal buffer and the error message
```
error in lean-server command handler: (void-function s-blank-str?)
Server response was:
```
That error message persists even when the cursor is not in a tactic block, and even when there are no tactic blocks in the file. It goes away when I close the Lean Goal buffer.

This is in Emacs 24.5.1 on Kubuntu.

**Comment by Armael** [comment]
It seems to work well  on my computer, thanks! (I'm using Emacs 25.2.1)

**Comment by Kha** [comment]
@rlewis1988 Hm, I see the function is not included in MELPA stable yet. I'll replace it.
