### ISSUE TITLE
Issues with shadowed parameter names

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#1649]
These two issues both show up when parameter names are reused in declarations. The universe polymorphism in the first example seems to be necessary to make `#check` produce an error.

To me, the optimal solution would be to forbid shadowing parameter names completely, and throw an error at the declaration of `blah`.

```lean
section
def {u} typer (α : Type u) := α 
parameter n : ℕ

meta def blah (n : typer ℕ) : ℕ := n

#check blah
/-
type mismatch at application
  blah
term
  n
has type
  typer nat
but is expected to have type
  typer.{0} nat
-/

end
```

```lean
section

parameter n : false
def blah (n : false) : false := n
#check @blah -- blah : false

end

#check @blah -- blah : false

theorem fs : false := blah -- failed to add declaration to environment, it contains local constants

#print blah -- error: invalid #print command (reported at a line below)
```

Note: lean-server was crashing intermittently as I put together these examples (Emacs 25.1.1 on Windows). I can't pinpoint what changes were triggering the crash, though.

**Comment by leodemoura** [comment]
Closed by https://github.com/leanprover/lean/commit/748eb856c3e44924c6b707494293e0a764937086
