### ISSUE TITLE
dependent sorry causes type mismatch

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1650]
Sometimes `sorry` produces a type mismatch error, which I think should never happen.

When we use `sorry` instead of proving a proposition, it seems Lean generates an auxiliary definition, but later uses of `sorry` that depend on the first `sorry` don't use that definition, and so we get a type mismatch.

I haven't managed to minimise an example. Here's my current (non-standalone) code:

````
definition Fubini_for_Limits
  { J K : Category }
  { C : Category }
  { F : Functor (J × K) C }
  ( lim : Limit F ) : iterated_limit_for_bifunctor F := {
      limitFunctor := {
          object     := {
              limit         := {
                  onObjects     := sorry,
                  onMorphisms   := sorry,
                  identities    := sorry,
                  functoriality := sorry
              },
              maps          := sorry,
              commutativity := sorry
          },
          morphisms  := sorry,
          uniqueness := sorry
      },
      limitObject  := sorry
  }
````

which produces the error message 

````
file: 'file:///Users/scott/projects/lean-category-theory/src/category_theory/universal/fubini.lean'
severity: 'Error'
message: 'type mismatch at application
  {limit := {onObjects := sorry,
             onMorphisms := sorry,
             identities := Fubini_for_Limits._proof_1 K C,
             functoriality := Fubini_for_Limits._proof_2 K C},
   maps := sorry,
   commutativity := Fubini_for_Limits._proof_3 J K C F}
term
  Fubini_for_Limits._proof_3 J K C F
has type
  ∀ {j k : J.Obj} (f : J.Hom j k),
    (FunctorCategory K C).compose
        (@Functor.mk K C sorry sorry sorry sorry)
        (@Functor.onObjects J (FunctorCategory K C) (⇑(Curry_Functors J K C) F) j)
        (@Functor.onObjects J (FunctorCategory K C) (⇑(Curry_Functors J K C) F) k)
        (sorry j)
        (@Functor.onMorphisms J (FunctorCategory K C) (⇑(Curry_Functors J K C) F) j k f) =
      sorry k
but is expected to have type
  ∀ {j k : J.Obj} (f : J.Hom j k),
    (FunctorCategory K C).compose
        (@Functor.mk K C sorry sorry (Fubini_for_Limits._proof_1 K C) (Fubini_for_Limits._proof_2 K C))
        (@Functor.onObjects J (FunctorCategory K C) (⇑(Curry_Functors J K C) F) j)
        (@Functor.onObjects J (FunctorCategory K C) (⇑(Curry_Functors J K C) F) k)
        (sorry j)
        (@Functor.onMorphisms J (FunctorCategory K C) (⇑(Curry_Functors J K C) F) j k f) =
      sorry k'
at: '32,25'
source: ''
````

You can see that the `sorry` definitions for both `identities` and `functoriality` have been replaced by 
`Fubini_for_Limits._proof_1 K C` and `Fubini_for_Limits._proof_2 K C` respectively.

However when I use `sorry` for `commutativity` it generates `Fubini_for_Limits._proof_3 J K C F`, which is not typed correctly, as it still has `sorry` instead of the earlier generated auxiliaries.

**Comment by kim-em** [comment]
The code above is testable via:

````
git clone https://github.com/semorrison/lean-category-theory
cd lean-category-theory
git reset --hard f86de235babad68f74acb8087a6fb9127105f436
lean --make universal/fubini.lean
````

**Comment by digama0** [comment]
I don't think the auxiliaries are causing the type mismatch error, because of proof irrelevance. (This is why the auxiliaries are generated in the first place.) What happens if you use `sorry` for the `limit :=` field?

**Comment by kim-em** [comment]
It compiles without an error with `limit := sorry`.

**Comment by digama0** [comment]
What if you replace `onObjects` and `onMorphisms` fields with constants instead of `sorry`?

**Comment by kim-em** [comment]
Notice in the type mismatch error the different between the two types is the following:

found type = `... (@Functor.mk K C sorry sorry sorry sorry) ...`
expected type = `... (@Functor.mk K C sorry sorry (Fubini_for_Limits._proof_1 K C) (Fubini_for_Limits._proof_2 K C)) ...`

**Comment by digama0** [comment]
Try viewing it with `pp.all` - I think the actual issue is in the other `sorry`s such as `sorry j` and `sorry k` in the message

**Comment by digama0** [comment]
Also, I just tried your test, and was unable to reproduce.

**Comment by digama0** [comment]
After playing with your example, it seems the issue is in fact the `maps := sorry` field. Replacing it with a constant (such as `sorry' : ∀ {A : Sort u}, A`) fixes the error.

**Comment by digama0** [comment]
Here's my attempt to cut down the example to only one `sorry`:

    def A : inhabited true → Type | ⟨t⟩ := inhabited (t = t)
    def B (T : Type) (t : T) : Prop := t = t
    def C {T x} : B T x := rfl

    structure X :=
      ( x : inhabited true )
      ( y : A x )
      ( z : B _ y )

    def test : X := {
        x := ⟨let t := trivial in t⟩,
        y := sorry,
        z := C
    }
>
    type mismatch at application
      {x := {default := test._proof_1}, y := sorry, z := test._proof_2}
    term
      test._proof_2
    has type
      B (A {default := let t : true := trivial in t}) sorry
    but is expected to have type
      B (A {default := test._proof_1}) sorry

**Comment by kim-em** [comment]
Looks good! I can't find much more to minimise; you can replace `Sort u` with `Type` and drop `universe u`, to make it clearer the problem isn't about universes.

**Comment by digama0** [comment]
Interestingly, if `A` is defined to not depend on its value, for example `def A : inhabited true → Type := λ i, nat`, the structure command fails with the error

    type mismatch at application
      and.intro x_eq y_eq
    term
      y_eq
    has type
      y = y_1
    but is expected to have type
      y == y_1

I think this is an unrelated bug though.

**Comment by leodemoura** [comment]
We encode `sorry` using macros. The type checker uses the following approach to check wether the macro applications `M a_1 ... a_n` and `M b_1 ... b_n` are definitionally equal.
- If the two applications are structurally equal, return true.
- Otherwise, expand them and check whether the expand terms are definitionally equal.

This correct for macros that can be expanded, but it fails for macros such as `sorry` which are placeholders and cannot be expanded.

We should check this kind of macro by checking whether every `a_i` is definitionally equal to `b_i`.

This new case must be supported in the kernel and type_context.

The other possible solution is to go back to the old approach for encoding `sorry` where we dynamically add a constant `sorry`.

Here is a minimal example that exposes the problem:
```lean
example : true :=
by do
  let t1 : expr := `(sorry : T (1+1)),
  let t2 : expr := `(sorry : T 2),
  is_def_eq t1 t2,  -- Should not fail
  constructor
```

**Comment by leodemoura** [comment]
@digama0 Thanks for creating a small example that exposes the problem. It helped a lot!
