### ISSUE TITLE
Issue with using noncomputable definitions inside defs that return Prop

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1658]
If we (a) create a noncomputable definition that doesn't get inlined and (b) use that definition inside another definition that returns `Prop`, then the noncomputable-checker thinks the second definition is computable, but the compiler throws an error when it finds the occurrence of the first definition.

Note: in the example below it is only a warning, but if `foo` itself is defined using the equation compiler, then the warning becomes an error with no obvious workaround.

```Lean
constant p : bool → bool
constant P : bool → Prop

noncomputable def lp : bool → bool
| ff := p ff
| tt := p tt

noncomputable def foo (b : bool) := P (lp b)
/-
warning: definition 'foo' was incorrectly marked as noncomputable
warning: failed to generate bytecode for 'foo'
failed to generate bytecode, expression depends on noncomputable definition 'lp._main'
-/
```
Note: I can probably fix this one pretty easily but I don't have time tonight.

**Comment by Kha** [comment]
Were you thinking about removing the `Prop` special-casing in computablity checking or making sure that the special case doesn't break the other parts? The former certainly sounds easier, and I don't see much of a point in the special case.

**Comment by dselsam** [comment]
For now I just replaced the following two lines with `return true;` on my fork:
https://github.com/leanprover/lean/blob/master/src/library/noncomputable.cpp#L121-L122
I am not sure what Leo had in mind with the noncomputable book-keeping, or why the compiler compiles a function that returns a Prop at all.

**Comment by leodemoura** [comment]
> I am not sure what Leo had in mind with the noncomputable book-keeping

`blame` will show the issue that motivated the book-keeping.

> why the compiler compiles a function that returns a Prop at all.

This seems to be a bug. I will investigate.
