### ISSUE TITLE
First book example doesn't work

### ISSUE THREAD

**Issue by abliss** [leanprover/lean3#1662]
I started reading the book at https://leanprover.github.io/theorem_proving_in_lean/index.html#01_Introduction.html.
When I clicked on the first "Try it yourself" button, I got a red "X" in the editor:

```
file '/library/init/wf.lean' not found in the LEAN_PATH
invalid import: init
could not resolve import: init
unknown identifier 'Prop'
unexpected token
```
The text in the editor seems to match the example, and the output window says "Done (0.087 sec)".
This is in chrome on android.

**Comment by Kha** [comment]
There is some loading race condition in the online version we haven't figured out yet. Reloading the website usually fixes it.

**Comment by gebner** [comment]
This error should be fixed as we move to the new [web editor](https://gebner.github.io/lean-web-editor).  Right now it used only by the [reference manual](https://leanprover.github.io/reference), but we plan to move the other manuals to it as well.
