### ISSUE TITLE
simp with hypotheses issue

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1675]
The following example describes a problem reported by @Armael.
```lean
def foo (a b : nat) : Prop := 
a = 0 ∧ b = 0

@[simp] lemma foo_def (a b : nat) : foo a b = (a = 0 ∧ b = 0) :=
rfl

example (p : nat → Prop) (a b : nat) : foo a b → p (a + b) → p 0 :=
begin
  intros h₁ h₂,
  simp [h₁] at *,
   -- h₂ is not being simplified to `p 0` here.
  assumption  
end
```

**Comment by leodemoura** [comment]
@Armael I have investigated this issue. This one doesn't work because we build the `simp_set` (simplification set) using `h₁` before it is simplified. Lean adds the simp rule
```lean
foo a b ↦ true
```
So, this is actually the intended behavior.
However, the following variant doesn't work either.
```lean
example (p : nat → Prop) (a b : nat) : foo a b → p (a + b) → p 0 :=
begin
  intros h₁ h₂,
  simp at h₁,
  -- After the tactic above, we have 
  -- h₁ : a = 0 ∧ b = 0
  -- as expected 
  simp [h₁] at *,
  assumption
end
```
In this tactic, Lean correctly builds a `simp_set` containing the simp rules
```lean
a ↦ 0
b ↦ 0
```
However, it doesn't work, because the implementation of `simp at *` first reverts all hypotheses (including `a` and `b`), and then incrementally reintroduces them. That is, the `a` re-introduced is different from the `a` in the `simp_set`.
@jroesch @avigad This is a bug in `simp at *`. The approach doesn't work when the simp_set contains references to the local context. An easy fix is: we check whether we are referencing hypotheses and report the error `'simp at *' does support local hypotheses`

@Armael I will add the `simp_all` tactic that simplifies all hypotheses, add simp rules for them when possible, and then simplify the target.

**Comment by leodemoura** [comment]
@jroesch @avigad Another possible fix: we revert only propositions. This may still produce counterintuitive behavior when we have data `d : A` that depends on a proposition `h_1 : p_1` (it would be reverted when we revert `h_1`, and we have another proposition `h_2 : p_2` which depends on `d`. To be totally safe, we would have to perform a dependency analysis, and check whether some of the propositions used to build the `simp_set` contains a `d` that was reverted.

**Comment by avigad** [comment]
I am on a family vacation this week with limited time, but I would be happy to work on this next week. Is that o.k.?

**Comment by leodemoura** [comment]
`simp_all` has been implemented: 14d768ffa2

**Comment by leodemoura** [comment]
@Armael Contextual rewriting is yet another way of solving the example above.
In contextual rewriting, when we visit `t = s -> p`, we simplify `p` using the equality `t = s`.

```lean
def foo (a b : nat) : Prop :=
a = 0 ∧ b = 0

attribute [simp] foo

example (p : nat → Prop) (a b : nat) : foo a b → p (a + b) → p 0 :=
by simp {contextual := tt}
```

**Comment by leodemoura** [comment]
@Armael We can make contextual rewriting more powerful by adding custom congruence rules.
Example: 

```lean
@[congr] lemma and_ctx_congr {a b c d : Prop}
    (h₁ : a = c)
    (h₂ : c → (b = d)) : (a ∧ b) = (c ∧ d) :=
propext $ iff.intro
  (λ ⟨ha, hb⟩, begin rw [-h₁, -h₂ $ eq.mp h₁ ha], assumption end)
  (λ ⟨hc, hd⟩, begin rw [h₁, h₂ hc], assumption end)

example (p q : Prop) : p ∧ (¬p ∨ q) ↔ (p ∧ q) :=
by simp {contextual := tt}; apply iff.refl
```

**Comment by avigad** [comment]
I am sorry, I didn't read the earlier message carefully enough. I had implemented something similar in `library_dev`: https://github.com/leanprover/library_dev/blob/master/tools/tactic/simp_tactic.lean#L84-L89.

I also have a tactic that uses all the other hypothesis to simplify each other: https://github.com/leanprover/library_dev/blob/master/tools/auto/finish.lean#L225-L241
I am not sure how robust it is. There may be situations that make it loop. But we have been using it in a `finish` tactic, and it seems to work o.k.

**Comment by leodemoura** [comment]
> I am sorry, I didn't read the earlier message carefully enough. I had implemented something similar in library_dev: 

No problem, `simp_all` is just a few lines on top of `simp_intros_aux`. The main problems I had were due to bugs in `simp` and `simp_intros_aux`.

> I also have a tactic that uses all the other hypothesis to simplify each other: https://github.com/leanprover/library_dev/blob/master/tools/auto/finish.lean#L225-L241
I am not sure how robust it is. There may be situations that make it loop. But we have been using it in a finish tactic, and it seems to work o.k.

I think this one has two problems. One is performance, it keeps re-building `simp_sets` and each step uses a revert/intro idiom. The other problem is that `simp_at_using_hs` suffers from the same problem I have described above. I'm working on this problem. I will push fixes soon.

**Comment by avigad** [comment]
As far as rebuilding the simp set, I made a note to myself that we need a version of `simp_at_using_hs` that takes a simp set as an argument, so that we can build it once and keep sending it. Would that solve that problem?

**Comment by leodemoura** [comment]
> As far as rebuilding the simp set, I made a note to myself that we need a version of simp_at_using_hs that takes a simp set as an argument, so that we can build it once and keep sending it. Would that solve that problem?

It would solve one of the problems. There is a more critical performance problem on the main loop. For goals with many hypotheses (e.g., > 100), the procedure will be very inefficient because each `simp_at*` invocation will use the revert/intro idiom.

The main issue for me is not performance, but the one I described above. It affects the whole `simp_at_*` tactics. The issue happens when we provide a lemma that depends on hypotheses that are reverted by the revert/intro idiom. For non-dependent propositions (i.e., propositions without forward dependencies), I have a solution, we don't revert anything, prove the derived/simplified proposition, add it, and delete/clear the old one.

**Comment by avigad** [comment]
> It would solve one of the problems. There is a more critical performance problem on the main loop. For goals with many hypotheses (e.g., > 100), the procedure will be very inefficient because each simp_at* invocation will use the revert/intro idiom.

`finish` is designed to kill small, straightforward goals with just a few hypotheses. That expensive operation is only called once, in a preprocessing phase. So maybe it is not too bad. But when you are in Cambridge, we can talk about it.

> For non-dependent propositions (i.e., propositions without forward dependencies), I have a solution, we don't revert anything, prove the derived/simplified proposition, add it, and delete/clear the old one.

It sounds like this will cover 99% of use cases. Thanks for doing this.
