### ISSUE TITLE
Allow passing lean options to leanpkg

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#1684]
Motivation: Lean can consume huge amounts of memory, and building a Lean project with all the available threads can crash a system that might otherwise be able to build when only using one thread.

Example:
```
leanpkg build -- -j 1
```
could call `lean` with the extra argument `-j 1`.

Note: I understand the label system but I am not authorized to create this with the `feature` label, so I added it to the title as a placeholder.

**Comment by leodemoura** [comment]
@dselsam `leanpkg` is implemented in Lean ;)
https://github.com/leanprover/lean/tree/master/leanpkg/leanpkg

**Comment by dselsam** [comment]
If you agree with the feature you can assign it to me.

**Comment by leodemoura** [comment]
@dselsam I agree it is useful, and assigned it to you :)

**Comment by leodemoura** [comment]
@dselsam Did you implement this feature? I'm having memory consumption problems when I try to build Certigrad in my notebook.

**Comment by dselsam** [comment]
I'll implement it this morning, but I doubt it will help you. Note: I only needed it when the seven sub-proofs were in separate theorems in the same file. Since they are now part of one theorem, all seven are done with a single-thread even when using `leanpkg build`.

**Comment by dselsam** [comment]
See PR #1707.
