### ISSUE TITLE
`simp` is nondeterministic

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1685]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifially, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The `simp` tactic reorders variables based on internal names, which makes it nondeterministic depending on the order the names are created.

### Steps to Reproduce

Add a bunch of identical theorems like this:

    example (m : ℕ) : ∀ n k, m + n = k → n + m = k := by intros; simp; assumption
    example (m : ℕ) : ∀ n k, m + n = k → n + m = k := by intros; simp; assumption
    example (m : ℕ) : ∀ n k, m + n = k → n + m = k := by intros; simp; assumption
    example (m : ℕ) : ∀ n k, m + n = k → n + m = k := by intros; simp; assumption
    example (m : ℕ) : ∀ n k, m + n = k → n + m = k := by intros; simp; assumption
    example (m : ℕ) : ∀ n k, m + n = k → n + m = k := by intros; simp; assumption
    example (m : ℕ) : ∀ n k, m + n = k → n + m = k := by intros; simp; assumption

**Expected behavior:** They should either all fail or all succeed.

**Actual behavior:** The example theorems will sometimes fail and sometimes succeed. (Typing at the start of the file will also regenerate the names and possibly change which pass and which fail.)

**Reproduces how often:** By the very nature of the nondeterminism, it isn't guaranteed, but usually it is seen with fewer than 20 of the above theorem

### Versions

Windows 10, master branch `c7e68e`

**Comment by leodemoura** [comment]
We can minimize the problem by comparing the user facing name first.
It would still be non deterministic if there are use facing name clashes.

I'm not sure what would be the ideal solution. We can impose stronger invariants in the fresh name generator. Example: in an execution thread, if we create a sequence of fresh names `n_1`, `n_2`, ... `n_i`, ... we have that `n_1 << n_2 << ... << n_i << ...`, where `<<` is the total order on names. We currently do **not** have this property (because of tagged fresh names). We can move to a new design for fresh names which enforces this property.  

This should fix the nondeterminism, but it will not prevent counterintuitive behavior. Example, if the user changes `∀ n k` to `∀ k n` the proof will break. Similarly, adding an irrelevant hypothesis may break the proof.

Remark: tagged fresh names is probably a bad idea, and it is the main source of the problem.

**Comment by digama0** [comment]
I am confused why the fresh names are *so* unique. Why can't they just be distinct from everything in the local context, and generated in increasing order like the `a_1` naming style?

**Comment by leodemoura** [comment]
> I am confused why the fresh names are so unique. Why can't they just be distinct from everything in the local context, and generated in increasing order like the a_1 naming style?

There are several reasons. Here are two of them:
1- Performance.
2- We create fresh names in places where we don't have a local context.

**Comment by digama0** [comment]
Correct me if I'm wrong, but given a local context, there is already an imposed order on all local constants, and of course de Bruijn variables are also ordered. This order depends on how `intros` are applied, so should be deterministic. The issue only arises not because of the internal names themselves, but because the simplifier uses them for perm rules. So we could have `simp` pass this ordering to the `expr.lt` function, or roll its own version of `expr.lt` that uses the alternate order. I don't think that perm rules are so common that the slowdown will be a big hit, but an alternative method is to rename all the variables with anonymous ones ordered according to this, and then reverse the rename afterwards.

**Comment by leodemoura** [comment]
> So we could have simp pass this ordering to the expr.lt function, or roll its own version of expr.lt that uses the alternate order.

@digama0 An alternate `expr.lt` for `perm` based on the local context is a viable and efficient solution. It is easier to implement than refactoring the fresh name generation.

> alternative method is to rename all the variables with anonymous ones ordered according to this, and then reverse the rename afterwards.

This is to expensive. The first solution is much more efficient. Note that, even on simple rules such as `x + y = y + x`, the terms bound to `x` and `y` may be arbitrarily big.

**Comment by digama0** [comment]
The rename work would only have to be done once, at the beginning of a call to `simp`, and its evaluation time is proportional to the size of the incoming tactic state + the outgoing tactic state if it completes successfully. It doesn't need to be done on each perm rule.

**Comment by leodemoura** [comment]
@digama0 We create fresh names inside of `simp` when we go inside of binders. We would have to make sure the new names use the same approach (note that they may be created by procedures invoked by `simp`). This is error prone. Performance is a big issue. The tactic state may be much bigger than the term being simplified. Solution 1 is much more robust and efficient.
