### ISSUE TITLE
[RFC] Dependent rewrite / generalize

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1698]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifially, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

There is a way to avoid the `motive is not type correct` error that occurs in examples like:

    theorem test (f : nat → Type) (n) (g : f 1 → Type) (e : n = 1) :
      ∀ (h : f 1), g h :=
    by rw -e

Internally, the reason this fails is because the computed motive for the `eq.rec` application is `C := λ a : nat, ∀ (h : f a), g h` which is not type correct at `g h` since `g : f 1 -> Type` and `h : f a`.

The same issues apply to `generalize`, but there they are a bit simpler because there is only the motive itself to worry about, not the `eq.rec` application.

There is another equality recursor, `eq.drec`, which can handle these types of situations. The motive is provided a proof `p : a = 1`, and we can use this to fix the applications.

Suppose we have a well-typed term `T(A) : Type` containing a term `A` that we want to replace, and we wish to generate a motive `C :  Π (a : α) (p : A = a), Type` for use with `eq.drec`. We traverse the term bottom-up producing a term `repl T : expr` with the invariant being that `infer_type (repl T) = repl (infer_type T)`.

Whenever we get a mis-typed application `f x` where `f : P a` and `x : Q a`, we know that `P A := Q A -> ...`, so we can repair the application with `(eq.drec f p : P A) (eq.drec x p : Q A)` (where the motive for these applications, i.e. the transformation `P a => P A` is calculated recursively using `repl`). In most cases the casts will not be necessary, and they may need to be dependent casts because we may be inside a binder which also changed, hence why the whole process is recursive.

What is the community feeling about such a plan? Are there any existing tools which have attempted this to some degree? `generalize2` was an attempt at dependent generalization, but it's not recursive so it suffers the same `motive is not type correct` issues as `rw`.

**Comment by leodemoura** [comment]
We can revert `g` before we rewrite with `e`. 
```lean
theorem test (f : nat → Type) (n) (g : f 1 → Type) (e : n = 1) :
  ∀ (h : f 1), g h :=
begin
  revert g,
  rw [-e],  -- works
  ...
end
```

**Comment by digama0** [comment]
This doesn't always work, for example if `g` is a constant instead of a local constant.

**Comment by leodemoura** [comment]
@digama0 If `g` was a constant, I would use `generalize`:
```lean
constant f : nat → Type
constant g : f 1 → Type

theorem test1 (n) (e : n = 1) : ∀ (h : f 1), g h :=
begin
   generalize g g',
   rw [-e]  -- works
end
```

We can also generalize "by hand"
```lean
theorem test2 (n) (e : n = 1) : ∀ (h : f 1), g h :=
have ∀ (g : f 1 → Type) (h : f 1), g h, 
  begin
    rw [-e], -- works
  end,
this g 
```

**Comment by digama0** [comment]
This certainly changes the meaning of the term, as we have forgotten the definition of `g` by this transformation. In many cases it is appropriate, but this isn't the sort of transformation that `rw` should be allowed to do automatically. A possible middle ground is to use `generalize2` with heterogeneous equality, so that the final goal includes `g' : f n -> Type`, `a : g == g'`.

I recently learned that `simp` is already doing dependent rewrite, so rather than trying to invent my own algorithm I will just ask that we reuse this algorithm in `rw` and `generalize`. I'm not certain of the scope of it, though, and it does not work on the above example. It works on this one:

    constants (α β : Type) (P : α → Prop) (g : Π (x : α), P x → Prop)
    example (x y : α) (H : x = y) (px : P x) : g x px :=
    begin
      simp [H]
    end -- goal: g y (eq.rec px H)

**Comment by leodemoura** [comment]
> This certainly changes the meaning of the term, as we have forgotten the definition of g by this transformation. 

Yes, in any generalization step, we will forget the definition. There are many tricks to workaround this. For example, when generalizing, we can provide propositions stating the `g` properties we need.

> In many cases it is appropriate, but this isn't the sort of transformation that rw should be allowed to do automatically. 

I was not proposing we change `rw`. I was questioning the RFC (adding dependent rewrite to `rw`). 
If we want to make `rw` more useful, we need to add support for patterns, occurrences (in the interactive version), Lean 0.2 modifier, etc. 

> I recently learned that simp is already doing dependent rewrite, so rather than trying to invent my own algorithm I will just ask that we reuse this algorithm in rw and generalize.

`simp` and `rw` build proofs using very different approaches. `rw` uses `eq.rec`. It tries to locate instances of the left-hand-side, computes a motive for simultaneously replacing all of them, and create a single `eq.rec` application. `simp` uses congruence and simplification lemmas. It can only rewrite a sub-term if there are congruence lemmas that allow us to "reach" this sub-term.
Moreover, `simp` supports different relations. We just need to provide the appropriate congruence and simplification lemmas for it.
The general purpose congruence lemmas (`congr`, `congr_arg` and `congr_fun`) for equality are very restrictive, they provide very poor support for dependent functions. I tried to minimize the problem by implementing a procedure that automatically generates congruence lemmas for a class of dependent functions. I described this approach in one of the old Lean google groups.
This class contains functions where dependent arguments are propositions or subsingletons. Every proposition is a subsingleton, but the procedure relies on proof irrelevance to take care of several levels of dependencies. This class subsumes many applications we have in mind, almost every one that I care. 

> I'm not certain of the scope of it, though, and it does not work on the above example. It works on this one

As I said above,`simp` cannot reach every possible sub-term, only the ones that can be reached using the congruence lemmas available.

That being said, I have a plan for writing a simplifier that uses heterogenous equality, but I don't have time to work on it.

**Comment by digama0** [comment]
> simp and rw build proofs using very different approaches. rw uses eq.rec. It tries to locate instances of the left-hand-side, computes a motive for simultaneously replacing all of them, and create a single eq.rec application. simp uses congruence and simplification lemmas. It can only rewrite a sub-term if there are congruence lemmas that allow us to "reach" this sub-term.

If you think that preserving the guaranteed `eq.rec` result of `rw` is important, the proposal here could be  met by a different tactic like `drw` or something. As you say, `simp` is built on a general method for rewriting in dependent functions, and my proposal here is essentially to separate this from the other parts of `simp` that make it less predictable. I suspect this might be possible simply by setting the options of `simp` appropriately so that it acts more like `rw` (without multiple passes, application of other `simp` lemmas, etc).

It's a shame that `simp` has so many innovations in it which are not accessible (to the end user) without accepting all the other stuff like AC rewriting which may be actively harmful in some cases.

**Comment by leodemoura** [comment]
> If you think that preserving the guaranteed eq.rec result of rw is important

I think it is very important to have a tactic that is based on `eq.rec`. As I said in the previous comment, it can do things that the approach based on `simp` cannot. 

> It's a shame that simp has so many innovations in it which are not accessible (to the end user) without accepting all the other stuff like AC rewriting which may be actively harmful in some cases.

They are available. See the following tactic:
https://github.com/leanprover/lean/blob/master/library/init/meta/simp_tactic.lean#L214

We also have `simp only [h]` which will apply lemma `h` without using the default simp set (which includes all the AC stuff).

**Comment by digama0** [comment]
What `simp only [h]` cannot do is directed rewriting or guaranteed rewriting (simp gets to choose how and what order to apply the given lemmas). I want something that acts just like `rw` to the end user, but is implemented using the `simp` framework. Is there a way to do this with `simp` options?

**Comment by leodemoura** [comment]
You can use this tactic:
https://github.com/leanprover/lean/blob/master/library/init/meta/simp_tactic.lean#L214

`unfold` and `unfold_occs` were implemented using them:
https://github.com/leanprover/lean/blob/3140243bada8b57da26180bd013af0d44cd8c5c0/library/init/meta/simp_tactic.lean#L123-L131
They were rewritten in C++ due to performance issues.

CORRECTION: they were implemented using the dsimplify primitive, but the idea is similar.
