### ISSUE TITLE
[RFC] Emigrating the standard library

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1710]
This is a continuation of #1523. Currently, the `lean` repository contains the C++ tool, but also contains a large amount of lean code. Most of the pure math has already been moved out to `library_dev`, but what remains can be broadly construed as "things that make lean a nice programming language". Because development and maintenance in lean and C++ require different skillsets, and the issues are of different varieties, I think we can agree that this repository should be as minimal as possible on the lean side, and development can continue in parallel on another repository.

But how minimal is possible? It is possible to skip compiling the library altogether, and just start from square zero in another repository, but I believe that some lean functionality will break (badly) if definitions in `init.core` don't exist. More broadly, if a VM extension point is left undefined, this can produce strange behavior or segfaults if the user uses the same name with an unexpected type. So I would argue that VM extension points must all be defined here, and this also makes sense given that VM extension points are intimately connected to the corresponding C++ code that defines the extension.

My "radical idea" is that these definitions are _all_ that need to stay here. That is, `init.core`, any definitions referred to by name in the C++, and VM meta constants (or overridden defs like `nat.add`) must be defined here, as well as any dependencies of these (i.e. the `tactic.env` meta constant necessitates `environment` to be defined, which needs `name` and `declaration` and `format` etc.). Anything which does not meet this criterion is to be shipped out to a sister repository.

This is a fairly harsh cutoff, but because of its simple form this makes it easy to determine where an extension should go, and so avoid the problem of a bloated library which we have had to contend with in earlier versions.

The plan:

* Replace the `library/` directory with a new directory `core/core/` (the doubling is so that `core/` can be designated as a `LEAN_PATH` root, exporting into import-namespace `core.*`).
* Roughly, we map `init.core` => `core.init`, `init.meta.*` => `core.vm.*` and `init.*` (other) => `core.defs.*`, where the latter two are separated based on whether the definition is `meta` or not (or VM extension points vs. dependencies of VM extensions).
* Remove everything that is not a dependency. This means almost all `theorem` and `lemma` definitions will be removed, so the files will shrink quite a bit.
* There should be a command to print all unbound VM extension points, so that testing will reveal if `core` is missing a definition.
* A non-prelude file will act as though it begins with `import core init`, except that the `init` import will not cause an error if it does not exist (instead it will do nothing). This way an external library can still provide an `init` file in order to supply a custom initialization set, which will be loaded as long as `init` is in the user's `LEAN_PATH`.
* The rest of the library will be moved to a new repository, called `stdlib` or something TBD. This will include everything which was not moved to `core/`, with the present folder layout.

A downside of this is that `leanpkg` will not be able to stay in the `lean` repository, since the tactic framework coming out of `core/` will be too raw to use effectively. (One may ask what is the purpose of making `core/` so minimal that no one can use it, and the response is that `core/` is what it needs to be to _avoid a crash_ and provide all the actually built-in functionality, not the full programming language, which is the purpose of the `stdlib` library.) In this case, it may as well land in its own repository, facilitating the "little theories" approach we have tried to cultivate with `super` and `smt2_interface`. The standard `lean` distribution should include the contents of all three repos `lean`, `stdlib` and `leanpkg` though, and maybe `cmake` can pull these in for convenience, although of course `lean` should still be able to build on its own.

**Comment by gebner** [comment]
> A downside of this is that leanpkg will not be able to stay in the lean repository, since the tactic framework coming out of core/ will be too raw to use effectively.

This is my main concern.  (Although the dependency is on `hash_map` and maybe `buffer.parser`, I don't think leanpkg uses any tactics.  I assume that the tactics for well-founded definitions would stay.)

I think that *you should always be able to build lean from git, and get a working `leanpkg` executable afterwards*.

If we require external dependencies, then `leanpkg` will be broken much of the time:
 1. We make a breaking change in `lean`
 2. We fix the fallout in `stdlib`
 3. We fix `leanpkg`.
 4. We update the `leanpkg` reference in `lean`.

`leanpkg` will be broken at steps 2 and 3., you can't even use it to update the dependencies in the `stdlib` and `leanpkg` packages.

Potential solutions:
 1. We keep `leanpkg` self-contained enough so that it doesn't need external dependencies (the copy-paste approach).
 2. We make `leanpkg` support multiple lean versions, and compile leanpkg using the native compiler into a self-contained executable.  We can commit the generated C++ code, and/or use the leanpkg executable from the last Lean version.

**Comment by gebner** [comment]
> A non-prelude file will act as though it begins with import core init

I think we would get most of the benefits of this proposal by only removing everything that is outside of `init` at the moment.  (That is, streams, bitvectors, etc.)  Then we would not need to rename anything, or modify the import syntax.

**Comment by digama0** [comment]
@gebner I recently noticed `environment::replace()`, and I wonder if it can be of use here. The problem with importing things like `hash_map` is that the proofs are rather involved, and indeed this appears to be the hardest part of my proposed untangling of the bloated `init` folder. For example, `char.of_nat_ne_of_ne` is referenced by name in the C++, so by my criterion it should be included in `core/`, but the proof uses tactics which requires the whole rest of the tactic framework, which I'm trying to avoid. In small cases like this we can fix it by proving it directly, but not all cases are as easy.

An alternative is to declare the types of these proofs by making them `constant` definitions, and `env.replace` them later. This approach is much more versatile, although it requires guarding against circular references (I don't know if `env.replace` does this check). In fact, it would be good to have a built in notation for doing `constant => def` replacement without pulling out the tactic framework, since there could be a lot of these and I'd rather not use tactics to define them all like `id_locked`.

This would solve the `leanpkg` issue, since `hash_map` can be defined in `core` as long as the proofs are stubbed out, although it would probably still be a bit of a squeeze to get `leanpkg` working without dragging everything into `core`. I wonder if it would pay to look at other implementations of this idea, e.g. `rustc` / `cargo`. It is clear to me that `leanpkg` _should_ be in a separate repository based solely on its status as a lean program independent of the lean tool itself, but these sort of bootstrapping issues get in the way of this ideal.

I think some variety of your # 2 is the most reasonable long term strategy. If `leanpkg` is built into its own exe, it shouldn't break immediately if the source stops compiling. You use an old, working version of `leanpkg` while fixing the error. Another way to put it is that building `lean.exe` and `leanpkg.exe` are separate activities, and they can be developed and rebuilt independently.

**Comment by digama0** [comment]
> I think we would get most of the benefits of this proposal by only removing everything that is outside of init at the moment. (That is, streams, bitvectors, etc.) Then we would not need to rename anything, or modify the import syntax.

The reason I think it is important to separate `core` and `init` is because they serve different purposes, and the pressures that encourage minimizing `core` don't necessarily apply to `init`. `core` is in effect an API for lean, with everything the C++ tool provides given as-is. `init` is a user-facing collection of definitions and theorems that we feel are worth importing without preamble, like the `java.lang` package.

By the way, I took a look at Rust's approach, and it's wonderfully circular. Both `rustc` and `cargo` require themselves to compile, since `rustc` is written in Rust and `cargo` I guess uses itself to pull in its dependencies. Of course they use earlier pre-built snapshot versions for this purpose.

**Comment by gebner** [comment]
> I recently noticed environment::replace(),

This replace function only really works in the same file.  I believe it was introduced to support delayed theorems in Lean 2.  Basically, in order to use the function, you need to remember the environment at the point where you added the axiom, and then type-check the corresponding theorem using the *same* environment.

We could make a similar function available across imports by marking some axioms as "replaceable", and storing their declaration environment when importing.

Practically speaking, I think the biggest problem lies in how to produce these proofs.  The proofs need to be valid in the environment of the stand-in axiom (otherwise we get cyclic proofs, and not the ones of the sound kind).  Maybe we can just run the current tactics with a tactic_state containing the old environment.  Not sure how much would break.

**Comment by digama0** [comment]
I would approach a `phantom constant foo : type` ... `redefine foo : type := proof` pair from the other direction. Rather than checking the proof in the environment of the first definition (which will probably be quite bare), we note whenever a definition depends on a replaceable constant. (A good data structure for this is a forest of forward references - a list of all replaceable constants, each with a list of their direct users, which in turn point to their users, and so on. The subtrees can then be shared between different replaceable constants.) Any definition that depends on a replaceable constant gets a special status `phantom`, which has similar viral status as the `meta` status. These definitions can be referred to by `meta` defs (causing a `evaluating sorry` error if called), but at low trust level they are not given to the kernel at all. After a `redefine` command (the proof of which cannot depend on any `phantom`s), the `phantom` status is cleared on any dependencies that do not depend on any other `phantom`s, and all these newly proven backlogged non-meta theorems are sent to the kernel.

**Comment by gebner** [comment]
Closed as per the discussion on Thursday.
