### ISSUE TITLE
`unfold_projs` fails with `dsimplify tactic failed to simplify` when it should succeed

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1725]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifially, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The code at https://gist.github.com/semorrison/0f3ffb276018c343ba288022f521f849 should result in `unfold_projs` at line 42 successfully rewriting `(FunctorComposition F H).onMorphisms f` as `H.onMorphisms (F.onMorphisms f)` (and doing another similar rewrite later).

Instead it fails with `dsimplify tactic failed to simplify`.

### Versions

Lean (version 3.2.1, commit d0242a363195, DEBUG)

**Comment by leodemoura** [comment]
@semorrison This is not a bug. `FunctorComposition F H` is not a constructor. 
So, `unfold_projs` will not reduce `(FunctorComposition F H).onMorphisms f`. 
By default, `unfold_projs` will only reduce `FunctorComposition` if it is marked as `[reducible]` or it is an instance.

That being said, I will add support for the following syntax `unfold_projs {md := semireducible}`

**Comment by kim-em** [comment]
Oh, I see. I agree, this is not a bug. I'd forgotten that my hand-rolled version of `unfold_projs` called  `unfold_projection_core` with `semireducible`, and mistakenly expected that behaviour to be preserved when I switched to the built-in `unfold_projs`. Sorry about that.
