### ISSUE TITLE
Assertion violation

### ISSUE THREAD

**Issue by johoelzl** [leanprover/lean3#1727]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reduced the issue to a self-contained, reproducible test case.

I'm not sure how to reproduce this exactly...

### Description
Similar to a problem recently reported by @dselsam on slack. w.r.t some errors / segmentation faults. I got the following errors in the Output channel in VS code:

```LEAN ASSERTION VIOLATION
File: /home/hoelzl/Projects/lean/src/frontends/lean/local_context_adapter.cpp
Line: 59
!has_regular_local(r)
```

I run a debug build. I was just browsing through the `uniform_spaces.lean` file in `library_dev`, at this point it was fully checked. With the goal state active (i.e. the vs code plugin requests data from Lean)

**Reproduces how often:**
I think I had this seen already, but I ignored it...

### Versions
Lean (version 3.2.1, commit 9645e7588eab, DEBUG)

**Comment by leodemoura** [comment]
Could you please try to create a self contained (and small) repro?

**Comment by johoelzl** [comment]
This reports a different `ASSERTION VIOLATION` but I get this a lot currently:
```lean
class A := (t : true)

t2_space.t1_space

class B extends A := (p : true)
```

results in:
```
$ lean --version
Lean (version 3.2.1, commit 6d0a7a80af6f, DEBUG)

$ lean --make topological_space.lean 
.../topological_space.lean:3:0: error: invalid field, atomic identifier expected
.../topology/topological_space.lean:5:0: error: invalid field, ':' expected
LEAN ASSERTION VIOLATION
File: /home/jholzl/Projects/lean/src/kernel/expr.h
Line: 151
m_value.m_ptr
```

If this is not reproducable on Ubuntu, I'm running Fedora 26:
```
$ gcc --version
gcc (GCC) 7.1.1 20170622 (Red Hat 7.1.1-3)
```
