### ISSUE TITLE
Using a hole command leads to "unknown exception"

### ISSUE THREAD

**Issue by theemathas** [leanprover/lean3#1729]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifially, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Using a hole command sometimes leads to an error when it probably shouldn't.

Code:

```
meta def foo : expr → expr → tactic unit := λ hole_type test_type, do
  match test_type with
  | (expr.pi arg_name _ arg_type body) := do
      arg_mvar ← tactic.mk_meta_var arg_type,
      let substituted_expr := body.instantiate_var arg_mvar,
      foo hole_type substituted_expr
  | _ := return ()
  end

@[hole_command]
meta def my_command : hole_command :=
{ name   := "Dummy",
  descr  := "Dummy command for demonstrating problem",
  action := λ _, do
    env ← tactic.get_env,
    env.fold (return []) $ λ decl accum, do
      accum,
      foo `(ℕ) decl.type,
      return []
}

example : ℕ := {! !}
```

### Steps to Reproduce

1. Open the above code in VsCode
2. Use the "dummy" hole command

**Expected behavior:** Nothing happens

**Actual behavior:** After a few seconds, sometimes there will be an error displayed: "Error while executing hole command:" (with nothing after the colon). I cannot reproduce it reliably, but using the hole command twice quickly appear to make the problem more likely to happen. 

The corresponding output from the Lean server is:
```{"message":"unknown exception","response":"error","seq_num":17}```

**Reproduces how often:** If the hole command is used once, at least 80%. If it's used twice, nearly 100%.

### Versions

```Lean (version 3.2.1, commit 5fd113f50f70, Debug)```
MacOS Sierra version 10.12.5

**Comment by gebner** [comment]
> but using the hole command twice quickly appear to make the problem more likely to happen.

I think I know what's happening.  The server only allows one hole command to execute at a time.  Hence if you run the dummy command twice in rapid succession, the first one will be cancelled.  I'll make the server return a better error message.
