### ISSUE TITLE
inconsistent `simp` behaviour

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1732]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifially, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I can produce a goal for which
* `simp {single_pass := tt}` fails with 'simplify tactic failed to simplify', whereas
* `simp {max_steps := 20}` fails with 'simplify failed, maximum number of steps exceeded'

(and similarly for any value of `max_steps`).

I would hope that
1) `simp` doesn't loop in this example, and
2) `single_pass` can be used to diagnose the looping.

### Steps to Reproduce

Run the code at https://gist.github.com/semorrison/f304a72c70bd705b7b454311f40f0104.

### Versions

Lean (version 3.2.1, commit f55d10bb5095, DEBUG)

**Comment by kim-em** [comment]
(I'm seeing this problem all across my library today.)

**Comment by leodemoura** [comment]
This is not a bug. The option `max_steps` limits the number of nodes that are visited by `simp`.
```
simp {max_steps := 2000}
```
will also return `simplify tactic failed to simplify`.

**Comment by leodemoura** [comment]
The counter `num_steps` is incremented in the simplifier main loop.
https://github.com/leanprover/lean/blob/master/src/library/tactic/simplify.cpp#L645

**Comment by kim-em** [comment]
Thanks. Sorry, I was confused.
