### ISSUE TITLE
lean server  (via lean-mode) seems to expect lookup info in home dir despite being otherwise configed

### ISSUE THREAD

**Issue by cartazio** [leanprover/lean3#1740]
not sure if this a a lean / lean-mode / lean homebrew problem, so reporting here and hoping 
@jroesch  or someone can help 

### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
 ... 
    * Reduced the issue to a self-contained, reproducible test case.

### Description

as per the brew installer directions
```
14:50:14 ~/W/p/a/s/model-lean (master|…) $ brew install lean
==> Installing lean from leanprover/lean
==> Downloading https://dl.bintray.com/lean/lean/lean-3.2.0.sierra.bottle.tar.gz
Already downloaded: /Users/carter/Library/Caches/Homebrew/lean-3.2.0.sierra.bottle.tar.gz
==> Pouring lean-3.2.0.sierra.bottle.tar.gz
==> Caveats
To use the Lean Emacs mode, you need to put the following lines in
your .emacs file:

  ;; Set up lean-root path
  (setq lean-rootdir "/usr/local")
  (setq-local lean-emacs-path "/usr/local/share/emacs/site-lisp/lean")
  (add-to-list 'load-path (expand-file-name lean-emacs-path))
  (require 'lean-mode)

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/lean
```
i've suitably configured my emacs as directed

I think get the following lovely error which baffles me 
![screen shot 2017-07-07 at 2 54 30 pm](https://user-images.githubusercontent.com/4290/27972496-991d92e6-6324-11e7-937c-06ab47a55f15.png)

whats especially baffling is i can confirm the root dir is set correctly, but maybe something has changed?
![screen shot 2017-07-07 at 3 00 02 pm](https://user-images.githubusercontent.com/4290/27972663-24251db4-6325-11e7-9e58-9b9dcdd6aff5.png)

### Steps to Reproduce

see above  (on sierra osx )
**Expected behavior:** lean  to do anything as i'm writing a file 

**Actual behavior:**  lean server seems to barf because i dont have a magic directory in homedir?

**Reproduces how often:** [What percentage of the time does it reproduce?]
always 

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

current osx sierra 
` lean --version
Lean (version 3.2.0, Release)` 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cartazio** [comment]
it seems to be something related to the tool leanpkg,
which seems to error out when i try to do `leanpkg -h` or `leanpkg --help`

**Comment by gebner** [comment]
> which seems to error out when i try to do leanpkg -h or leanpkg --help

Can you post the error message?

**Comment by cartazio** [comment]
Something about readline? Im afk at the moment but I'll post it later.

It seems like it's possibly because that cli command wraps the lean make
command without any cli parsing? But I'll post it later

**Comment by cartazio** [comment]
heres the error
```
18:08:45 ~/W/p/a/s/model-lean (master|…) $ leanpkg -h
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
readlink: illegal option -- f
usage: readlink [-n] [file ...]
<unknown>:1:1: error: file '/leanpkg/leanpkg/main.lean' not found
```

**Comment by cartazio** [comment]
one other detail that probably doesn't matter is i'm using fish shell

**Comment by jroesch** [comment]
@gebner is probably asleep, I believe the issue is that `leanpkg` depends on the `coreutils` version of `readlink`. Can you try `brew install coreutils`?

**Comment by jroesch** [comment]
I was just able to reproduce it on my Mac. I'll push a fix to the hombrew formula.

**Comment by jroesch** [comment]
I pushed a fix to the homebrew formula. Let me know if you have any other issues.

**Comment by cartazio** [comment]
@jroesch  i seem to still be getting these errors ... 

attached is a screen shot with an example 
![screen shot 2017-07-08 at 11 35 08 am](https://user-images.githubusercontent.com/4290/27986783-a6ff66de-63d1-11e7-98fb-3178fbfbcf0e.png)

**Comment by cartazio** [comment]
(using a small example file from lean as the demonstrator )

also how do i setup that ~/.lean path stuff?

at the very least `leanpkg` doesn't crash on me anymore ..

```
11:37:45 ~/W/p/a/s/model-lean (master|●1✚4…) $ leanpkg install

Usage: leanpkg <command>

configure       download dependencies
build           download dependencies and build *.olean files
test            download dependencies and run test files

new <dir>       creates a lean package in the specified directory
init <name>     adds a leanpkg.toml file to the current directory, and sets up .gitignore

add <url>       adds a dependency from a git repository (uses current master revision)
add <dir>       adds a local dependency
upgrade         upgrades all git dependencies to the latest upstream version

install <url>   installs a user-wide package from git
install <dir>   installs a user-wide package from a local directory

dump            prints the parsed leanpkg.toml file (for debugging)
```

**Comment by jroesch** [comment]
@cartazio Hey sorry for being slow to get back to you. I am on a month long vacation and less plugged in. I think this question is best suited for @gebner I haven't used `leanpkg` with Emacs, I can try it out when my flight lands.

**Comment by gebner** [comment]
> @gebner I haven't used leanpkg with Emacs, I can try it out when my flight lands.

Please do so.  I think this might be a mac-specific issue, I couldn't reproduce it on linux (after removing `~/.lean`)

**Comment by jroesch** [comment]
I also removed `~/.lean` and can't seem to reproduce either. I'll see if I can reproduce in some other way.

**Comment by jroesch** [comment]
@cartazio What version of Emacs are you running? A friend just got setup with Lean after OPLSS on a Mac and he had zero issues, just trying to figure out what variables are involved.

**Comment by cartazio** [comment]
I was using aquamacs.  I can try out vanilla emaacs I guess.  Will
investigate later today / tomorrow.

**Comment by cartazio** [comment]
also have it with emacs for osx ... ,

did you friend build himself or use your brew formula? perhaps i should try building from source..

**Comment by cartazio** [comment]
any suggestions on what i can do for debugging this, such as seeing what happens if i use vs-code or atom, would be welcome

**Comment by cartazio** [comment]
ok, the vs-code plugin seems to work!

this doesn't help debug the aquamacs/emacs error though :(

**Comment by Kha** [comment]
@cartazio Do you get the same error if you eval `(lean-server-ensure-alive)`? If yes, can you get a stack trace by executing `M-x toggle-debug-on-error` first?

**Comment by Kha** [comment]
Closing stalled issue, feel free to reopen with more information.

**Comment by cartazio** [comment]
Didn't see this message. I'll see if I'm still reproducing that issue and
try those out
