### ISSUE TITLE
lists with trailing comma give an unhelpful warning

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1745]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifially, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

`def foo: list nat := [ 1,2, ]` results in the somewhat unhelpful warning `declaration 'foo' uses sorry`. (Notice the trailing comma in `1,2,`.)

I noticed that recently Lean has started allowing a trailing comma when creating structures. Can we allow the same flexibility here?

### Versions

Lean (version 3.2.1, commit 3392aa90b5ec, DEBUG)

**Comment by leodemoura** [comment]
@gebner The issue is here:
https://github.com/leanprover/lean/blob/master/src/frontends/lean/parser.cpp#L1383
Is this a typo, or did you have a reason for not reporting an error on the empty case?

**Comment by gebner** [comment]
@leodemoura This is a terrible hack, and I'm not happy with it either.  To recap, the problem this line tries to solve is the following:
 * We expose a pexpr parser to the VM.  This parser is supposed to fail (without reporting an error) if there is no expression.  If there is no expression, we hit this line.
 * On the other hand, if we parse an expression from C++, we never backtrack and always want an expression.  In this case, we want an error though.

I see multiple solutions:
 1. Report the errors, but store them in a list first.  On backtracking in the VM pexpr parser, we can revert the error messages.
 2. Remember the last backtracking point.  The VM pexpr parser stores the current position before parsing an expression.  Then we know whether to backtrack without an error (say via an exception), or report an error and continue.

I had hoped that nobody would notice until we refactored the parser in #1674.  I'll try option 2 now.
