### ISSUE TITLE
Build failure on Ubuntu

### ISSUE THREAD

**Issue by PatrickMassot** [leanprover/lean3#1748]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Lean fails to build on Ubuntu 16.04.2

### Steps to Reproduce

1. Follow the [Ubuntu build instruction](https://github.com/leanprover/lean/blob/master/doc/make/ubuntu-16.04.md) up to ``make``

**Expected behavior:** Successful build

**Actual behavior:**
```bash
[ 94%] Linking CXX executable head_map
collect2: error: ld returned 1 exit status
tests/library/CMakeFiles/head_map.dir/build.make:799 : la recette pour la cible « tests/library/head_map » a échouée
make[2]: *** [tests/library/head_map] Erreur 1
CMakeFiles/Makefile2:4466 : la recette pour la cible « tests/library/CMakeFiles/head_map.dir/all » a échouée
```

**Reproduces how often:** 100%

### Versions

This is using ``git clone`` at commit 573525fb9f7a8cb8bae777293579c5c8e6efb947

**Comment by Kha** [comment]
`ld` fails without output? I don't think I've ever seen this before, and I'm using the same Ubuntu version :| .
Not sure if it helps, but could you attach the `CMakeFiles/CMakeOutput.log` file from the build directory?

**Comment by PatrickMassot** [comment]
Sure:
[CMakeOutput.log.zip](https://github.com/leanprover/lean/files/1152622/CMakeOutput.log.zip)

I should have mentioned I know nothing about compilation (doing python only...) so maybe I missed some obvious implicit task.

**Comment by Kha** [comment]
Just to be sure, does the problem persist after a `make clean`? If so, could you also post the output of `make VERBOSE=1`?

**Comment by PatrickMassot** [comment]
Yep ``make clean`` fixed the issue! I did ``make clean && make`` and everything compiled fine. I'll be able to play a bit with lean.

**Comment by PatrickMassot** [comment]
Thank you for your help!

**Comment by PatrickMassot** [comment]
Maybe you could add a comment to [build instructions](https://github.com/leanprover/lean/blob/master/doc/make/ubuntu-16.04.md)?
