### ISSUE TITLE
segfault with incorrect let expression

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#1749]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Lean segfaults when an incorrect and overloaded `let` expression is given. (originally found by Tom Hales)

### Steps to Reproduce

```lean
import data.vector
open vector

example (u : vector ℕ 2) : vector ℕ 2 :=
let [u1, u2] := u in
u
```

**Expected behavior:** Lean exits with error

**Actual behavior:** Segfault:
```
5:4: error: invalid pattern, 'choice (vector.cons u1 (vector.cons u2 vector.nil)) (list.cons u1 (list.cons u2 list.nil))' is overloaded, and this kind of overloading is not currently supported in patterns

Compilation segmentation fault (core dumped) at Mon Jul 17 13:07:10
```

**Reproduces how often:** 100%
### Versions

Lean (version 3.2.1, commit 0579e68ab80b, Release). Ubuntu 16.04

### Additional Information

The following does not give a segfault:
```lean
example (u : vector ℕ 2) : vector ℕ 2 :=
let (vector.cons u1 (vector.cons u2 nil)) := u in
u
```

A different question: is there a way to do something like this?

**Comment by Kha** [comment]
> A different question: is there a way to do something like this?

We do not have any type information to disambiguate the choice expression at that point of processing. This could reasonably change with #1674.
