### ISSUE TITLE
confusing error message on simple inductive definition

### ISSUE THREAD

**Issue by cartazio** [leanprover/lean3#1750]
Hello 

i've a teeny inductive data type (part of trying to do a little curry/church lambda calculus)

```
inductive types (fv : nat)   : Type 
    | tyvar : fin fv  -> types fv 
```

i get two errors

on *inductive* i get `invalid return type for types.tyvar`

on the return expression for `tyvar`  i get the error `function expected at types`

**Comment by avigad** [comment]
When defining an inductive type, omit the parameters in the return type (in this case, `fv`):
```lean
inductive types (fv : nat)   : Type 
    | tyvar : fin fv  -> types
```

**Comment by cartazio** [comment]
that solves it for me, thanks!
... also explains why i wrote too many things as indices rather than parameters last time i wrote lean code.

a) should there be / could there be a better error message here?
b) is this clearly talked about in any of the basic docs or example developments? :)

**Comment by Kha** [comment]
By coincidence, I'm working on a set of changes that will expand the error message to
```
2:26: function expected at
  types
term has type
  Type
```
It still doesn't tell you what's going on with the inductive specifically, but do you think that might have made things slightly more clear?

**Comment by digama0** [comment]
I think that we should have a hint like (Lean does not write parameters in
the result type). This is a common error from Coq users.

On Tue, Jul 18, 2017 at 9:22 AM, Sebastian Ullrich <notifications@github.com

**Comment by cartazio** [comment]
@Kha  .... that or the current error message are only helpful if you already know / understand the lean difference in notation.

I agree with @digama0 ,

**Comment by Kha** [comment]
Unfortunately, I don't see a good way at all for how to bring inductive compiler and elaborator together to produce such a message. We could implement a crude but simple approximation by inspecting each intro rule preterm before elaboration.

**Comment by avigad** [comment]
@cartazio In response to your other question, this is mentioned in Theorem Proving in Lean, e.g. in Section 7.2: https://leanprover.github.io/theorem_proving_in_lean/#07_Inductive_Types.html. Maybe we can make it more prominent. We have also started working on a reference manual, which, I think, will help in situations like this. (At least, it will provide an obvious place to look when something goes wrong.)

**Comment by cartazio** [comment]
i cant speak to the best path for discoverability :) 

but YES, a reference manual that i can look at would be a better condensed discovery tool :) 

hrmm, shame about the error message ux puzzle 

should i leave this ticket open till those action items happen, or does it make sense to close it atm?

**Comment by avigad** [comment]
I think it makes sense to close it.
