### ISSUE TITLE
Make error message from universe mismatch more informative

### ISSUE THREAD

**Issue by bmsherman** [leanprover/lean3#1760]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Consider the following code:
```lean
section
parameter big_type : Type 1
parameter x : big_type
parameter f {A : Type} : A → bool

def foo : bool := f x
end
```
The reported error at the definition of `foo` is
```
type mismatch at application
  f x
term
  x
has type
  big_type
but is expected to have type
  ?m_1
```
which is confusing, because we wonder why we cannot instantiate `?m_1` to `big_type`. The reason is that this would cause a universe inconsistency.

It would be desirable if the error message hinted at the universe mismatch.
Compare with Coq, where the equivalent code
```Coq
Section Test.
Variable big_type : Type.
Variable x : big_type.
Variable f : forall (A : Set), A -> bool.

Definition foo : bool := f _ x.
End Test.
```
gives the error message
```
Error: In environment 
  big_type : Type 
  x : big_type 
  f : forall A : Set, A -> bool
The term "x" has type "big_type" while it is expected to have type "?P" 
(unable to find a well-typed instantiation for "?P": cannot ensure that "Type" is a subtype of "Set").
```
### Versions
I am using HEAD version of Lean, Lean (version 3.2.1, commit ae5bc52d9762, Release).

**Comment by joehendrix** [comment]
I've run into this before.  I think it would be good if the expressions printed out as though pp.universes was true when type unification fails due to universe constraints.

**Comment by bmsherman** [comment]
In the case of this particular example, at least, it doesn't seem that setting `pp.universes` to `true` affects the error message.

**Comment by leodemoura** [comment]
Yes, `pp.universes` does not help here. I think one possible way to improve the error message is to show the type of the types. That is, we would display it as:
```lean
type mismatch at application
  f x
term
  x
has type
  big_type : Type 1
but is expected to have type
  ?m_1 : Type 0
```

**Comment by Kha** [comment]
@leodemoura That's a much more general solution, I like it!
