### ISSUE TITLE
Destruct tactic allows elimination from Prop to Type

### ISSUE THREAD

**Issue by bmsherman** [leanprover/lean3#1766]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Consider the following example:

```lean
inductive is_some (x : option nat) : Prop
  | mk : ∀ value : nat, x = some value → is_some

def value (x : option nat) (H : is_some x)
   : nat :=
   begin
   destruct x; intros,
   { destruct H; intros,
     rw a at a_1, contradiction
   },
   { assumption }
   end
```
**Actual behavior:** While the tactics successfully build a term, the term is not well-typed, resulting in the error at the definition of `value`,
```
type mismatch at application
  _ ℕ
term
  ℕ
has type
  Type
but is expected to have type
  Prop
```

The issue is that the `destruct H` tactic is used on an `is_some` value, which is a `Prop` to eliminate into `nat`, which is a `Type`.

**Expected behavior:** This should not be allowed. `destruct H` should fail with an appropriate error message indicating that elimination from Type to Prop is disallowed. If one uses `cases H` rather than `destruct H`, the tactic fails appropriately with the error message
```
induction tactic failed, recursor 'is_some.dcases_on' can only eliminate into Prop
state:
x : option ℕ,
H : is_some x,
a : x = none
⊢ ℕ
```

### Versions

Lean HEAD from July 21, 2017, Lean (version 3.2.1, commit 667e1e138162, Release)

**Comment by jroesch** [comment]
I'll take a look today or tomorrow and get back to you, thanks for reporting!
