### ISSUE TITLE
[RFC] Enforcing .olean versions

### ISSUE THREAD

**Issue by Kha** [leanprover/lean3#1770]
We already save the current Lean version in .olean files, but don't do anything with it. Since we now have some users like the fabstracts contributers that update frequently (via git or nightlies), we should make sure that they don't have to worry about outdated .olean files.

* We should silently ignore outdated .olean files and recompile them, just as if there was no .olean file
* To disambiguate nightlies, we should use the git hash, if available, with the Lean version as fallback
* For developers, we can add a `LEAN_IGNORE_OLEAN_VERSION` switch

**Comment by jroesch** [comment]
I agree, the fact that we silently load bad `.olean` files has always been frustrating, the nightly version should definitely include the SHA of the commit.
