### ISSUE TITLE
existsi tactic fails after if branch

### ISSUE THREAD

**Issue by bmsherman** [leanprover/lean3#1771]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Consider the following example code:
```lean
inductive is_some {A : Type} (mx : option A)  : Prop
  | mk : ∀ x : A, mx = some x → is_some

lemma foo {A : Type} (x : A) (mx : option A)
  (H : mx = some x)
  : is_some mx
:= begin
existsi x, assumption
end

-- same lemma as above
lemma foo' {A : Type} (x : A) (mx : option A)
  (H : mx = some x)
  : is_some mx
:= begin
apply (if true then _ else _), -- in this case, we branch first
{ existsi x },                 -- error on this line
{ admit }
end
```

**Actual behavior:** The tactic `existsi x` fails in the definition of `foo'` with the error
```
constructor tactic failed, target is not an inductive datatype
state:
A : Type,
x : A,
mx : option A,
H : mx = some x
⊢ is_some mx
```
This is erroneous, as `is_some` *is* an inductive datatype, as demonstrated by the success of `existsi` in the definition of `foo`.

**Expected behavior:** Like in the definition of `foo`, where the `existsi` tactic works, it should also work in `foo'`.

### Versions

Lean HEAD from July 21, 2017, Lean (version 3.2.1, commit 667e1e138162, Release)

**Comment by digama0** [comment]
Note that this proof works if `apply` is replaced by `refine`. This is a bug in `apply_core`: tactics should always `instantiate_mvars` before passing control to another tactic. This proof works:

    lemma foo' {A : Type} (x : A) (mx : option A)
      (H : mx = some x)
      : is_some mx
    := begin
    apply (if true then _ else _),
    tactic.target >>= tactic.instantiate_mvars >>= tactic.unsafe_change,
    { existsi x, assumption },
    { admit }
    end

**Comment by digama0** [comment]
More mysteries: `apply_core` is in fact instantiating metavars before adding new goals (https://github.com/leanprover/lean/blob/master/src/library/tactic/apply_tactic.cpp#L141). Also partial application affects the result: `apply (@ite true decidable.true _)` works but `apply (@ite true decidable.true _ _ _)` doesn't.

Here is a self-contained example using only `apply_core`:

    example (p : Prop) (f : ∀ q : Prop, q → q) : p :=
    by do
      e ← i_to_expr ```(f _ _),
      apply_core e,
      t ← target,
      fail_if_success (get_assignment t) -- error! t is an assigned metavar
