### ISSUE TITLE
refine leaves instantiated metavariables in the context

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1772]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

A minimal example:

    example (x : nat) : x ≠ 0 :=
    by refine λ h, _; subst x

Here the `refine` tactic produces the context

    x : ℕ,
    h : [&m_1 := x = 0]
    ⊢ false

containing an instantiated metavar, and the `subst` tactic can't handle it. Unlike #1771, this can't easily be addressed by adding `instantiate_mvars >>=` somewhere in the `subst` pipeline, because the type lookup is done directly in the native `tactic.subst`.

These issues will continue to crop up unless we have a consistent story for how to deal with instantiated metavars. There are two options:

1. All tactics try to preserve the invariant that instantiated metavars do not appear in any goals. (It is sufficient for the builtin tactics to preserve this invariant.)
2. No guarantees are made about instantiated metavars in the goal; any tactic which inspects the type of anything in the local context or the target must first `instantiate_mvars` on the result.

I was under the impression that we are trying to do (1), since there are obvious places in core tactics like `apply` and `change` that ensure this behavior. Furthermore, (2) is a bit problematic for "read-only" tactics that are now forced to change the state just to look at it. However, 870ce5c implements method 2. Whichever approach we take must be done consistently, because otherwise you can feed a tactic using method 2 to one using method 1 to get an error, as in the above example. That is, 870ce5c does not really fix #1771 since you can modify the example to any number of similar tactics that don't check metavars.

    example (p : Prop) (f : ∀ q : Prop, q → q) : p = p :=
    by apply f _ _; refl

    example (p : Prop) (f : ∀ q : Prop, q → q) : p = p :=
    by apply f _ _; transitivity

    example (p : Prop) (f : ∀ q : Prop, (q = q → q) → q) : p :=
    by apply f _ (λ h, _); subst h

**Comment by leodemoura** [comment]
> All tactics try to preserve the invariant that instantiated metavars do not appear in any goals. (It is sufficient for the builtin tactics to preserve this invariant.)

This option may produce performance issues.

> No guarantees are made about instantiated metavars in the goal; any tactic which inspects the type of anything in the local context or the target must first instantiate_mvars on the result.

This is reasonable for user level tactics used in interactive mode. For low level tactics, this may introduce performance issues.

**Comment by leodemoura** [comment]
> >  All tactics try to preserve the invariant that instantiated metavars do not appear in any goals. (It is sufficient for the builtin tactics to preserve this invariant.)

> This option may produce performance issues.

For option 1, we may also ensure it at user level tactics used in interactive mode. However, all of them should have low level versions that do not perform the checks.

**Comment by leodemoura** [comment]
> That is, 870ce5c does not really fix #1771 since you can modify the example to any number of similar tactics that don't check metavars.

Yes, it does fix a particular instance of the problem. The one reported at  #1771.
You may claim it does not fix the more general problem, but it does fix the problem reported.

**Comment by digama0** [comment]
Fair enough. If you like, you can treat this issue as different from #1771, but please don't fix it by patching just the three examples given, since they are intended to be exemplary of a general problem.

It is not necessary to ensure that metavariables are always instantiated in every tactic, just in the post-processing stage of builtin tactics on creation of a new vm `tactic_state` object for the user-facing tactics. But I do mean to include `tactic.apply` and `tactic.refine` in this list (not just the interactive `apply` and `refine`).

If this is too much of a performance hit, alternatively we could expose a more general `instantiate_all_mvars` that instantiates metavars in the local context of every goal (or just one given goal, letting the glue code use it on the appropriate goals), and call it in `interactive.apply` and `interactive.refine` as a post-processing step. (Note: currently there is no way to instantiate metavars in the local context without revert/intro, which I would like to avoid as it changes the internal names, which could affect some tactics.)

**Comment by leodemoura** [comment]
> Fair enough. If you like, you can treat this issue as different from #1771, but please don't fix it by patching just the three examples given, since they are intended to be exemplary of a general problem.

I will fix it where I think it is appropriate. My goal is to minimize the number of potential performance issues.

> It is not necessary to ensure that metavariables are always instantiated in every tactic, just in the post-processing stage of builtin tactics on creation of a new vm tactic_state object for the user-facing tactics. But I do mean to include tactic.apply and tactic.refine in this list (not just the interactive apply and refine).
...

I will think about it. Right now, I prefer to fix particular instances of the more general problem. They are easy to fix.
