### ISSUE TITLE
cannot import file whose name starts with a digit

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#1780]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Minor issue (found in Lean 2): if you have a file which starts with a digit, like `1a.lean`, you cannot import it.

### Steps to Reproduce
Create a file which starts with either `import 1a` or `import .1a`.

**Expected behavior:** [What you expect to happen]
Import the file / give an import error

**Actual behavior:** [What actually happens]
Get error `command expected`

**Comment by digama0** [comment]
Not sure whether "import the file" or "give an import error" is better in this situation, but I can explain why this error happens: `1a` is not a valid identifier (i.e. does not form the segments of a hierarchical name), so the scanner does not consider this to be part of the import command. So nothing is imported, and then the next expected token is a command like `def` or `inductive`, but it finds `1a` instead, hence the error.

**Comment by fpvandoorn** [comment]
@digama0 and @gebner note that I can import the file using `import .«1a»`. 
Maybe it's possible to improve the error message to indicate this? Or just close this issue.

**Comment by leodemoura** [comment]
I'm closing the issue. The notation `«...»` is meant to address this kind of issue.
Note that we also need to use to import files containing spaces.
