### ISSUE TITLE
strange warnings from trace.simp_lemmas

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#1785]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

`trace.simp_lemmas` reports strange error messages. It is not a serious problem, but I am mentioning it in case it indicates something wrong.

### Steps to Reproduce

Run this.
``` lean
set_option trace.simp_lemmas true

example (x : ℕ) : x = x := 
by simp
```
We get the following information:
```
[simp_lemmas.invalid] rule derived from 'list.nil_subset' contains argument that is (a) not a Prop, (b) not an instance, and (c) not in the LHS of the rule
[simp_lemmas.invalid] LHS of rule derived from 'list.subset.refl' occurs in RHS
[simp_lemmas.invalid] rule derived from 'list.subset_cons' contains argument that is (a) not a Prop, (b) not an instance, and (c) not in the LHS of the rule
[simp_lemmas.invalid] rule derived from 'list.subset_append_left' contains argument that is (a) not a Prop, (b) not an instance, and (c) not in the LHS of the rule
[simp_lemmas.invalid] rule derived from 'list.subset_append_right' contains argument that is (a) not a Prop, (b) not an instance, and (c) not in the LHS of the rule
```
But e.g. the simplifier seems to be using `list.nil_subset` correctly:
``` lean
set_option trace.simplify true

example (l : list ℕ) : list.nil ⊆ l := by simp
```

**Reproduces how often:** 100%

### Versions

current lean master.

**Comment by avigad** [comment]
The error message comes from `is_ceqv` in `simp_lemmas.cpp`. But it does not seem to be causing problems, so I will close this.

**Comment by dselsam** [comment]
These warnings make sense, since `⊆` is technically a `simp` relation over lists (i.e. it is `[refl]` and `[trans]`). The rule `list.nil_subset : [] ==> l` over `⊆` is invalid since `l` is a new variable on the RHS, and that is what the warning is saying. However, the rule `list.nil_subset : [] ⊆ l ==> true` over `iff` is still a valid `simp` rule, and is still being generated.

**Comment by avigad** [comment]
@dselsam Thanks, that is helpful.
