### ISSUE TITLE
leanpkg on MacOS X does not use the right readlink

### ISSUE THREAD

**Issue by cipher1024** [leanprover/lean3#1788]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

[Description of the issue]

When I call `leanpkg` on Mac OS X, the `leanpkg` main file is not found.

### Steps to Reproduce

1. clone the `lean` repo at revision b3bc4b73fa4b (the 3.2.1 release)
2. build using ninja
3. in a terminal, type `leanpkg`

**Expected behavior:** [What you expect to happen]

Should print:

```
Usage: leanpkg <command>

configure              download dependencies
build [-- <lean-args>] download dependencies and build *.olean files
test  [-- <lean-args>] download dependencies and run test files

new <dir>              creates a lean package in the specified directory
init <name>            adds a leanpkg.toml file to the current directory, and sets up .gitignore

add <url>              adds a dependency from a git repository (uses current master revision)
add <dir>              adds a local dependency
upgrade                upgrades all git dependencies to the latest upstream version

install <url>          installs a user-wide package from git
install <dir>          installs a user-wide package from a local directory

dump                   prints the parsed leanpkg.toml file (for debugging)
```

**Actual behavior:** [What actually happens]

Prints:

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
readlink: illegal option -- f
usage: readlink [-n] [file ...]
<unknown>:1:1: error: file '/leanpkg/leanpkg/main.lean' not found
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time

### Versions

```
Lean (version 3.2.1, commit b3bc4b73fa4b, RELEASE)
```

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by leodemoura** [comment]
@cipher1024 I think I had this problem, and fixed it using https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Comment by cipher1024** [comment]
Thanks! That solved it! Could add a line to that effect in the documentation? Specifically that installing `coreutils` is necessary on Mac.
