### ISSUE TITLE
Failed to generate equational lemmas in the front-end

### ISSUE THREAD

**Issue by bmsherman** [leanprover/lean3#1790]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Consider the definition `foo` in this code snippet:
```lean
universes u
def foo (A : Type u) : unit → unit
| star := star
```

**Actual behavior:** The definition of `foo` fails with the following error:
```
unexpected error, failed to generate equational lemmas in the front-end
```
If the universe of `A` is made such that it is not universe-polymorphic (e.g., `A : Type 3`), then the error goes away, and the definition succeeds.

**Expected behavior:** The definition of `foo` should compile correctly and generate the appropriate equational lemma.

### Versions

I am using Lean version from August 12, 2017, Lean (version 3.2.1, commit 32ddac5f40a7, Release).

**Comment by digama0** [comment]
By the way, it should be noted that `star` is being parsed as a variable, not `unit.star` (unless you also `open unit` first). Both variants cause an error and are tested in Leo's fix.
