### ISSUE TITLE
simp not rewriting under binder

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1791]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Consider the following:

    @[simp] theorem {u} forall_true_iff {α : Sort u} : (α → true) ↔ true :=
    iff_true_intro (λ h, trivial)

    example : nat → nat → true := by simp

If I understand `simp` correctly, it should go under the first (anonymous) binder using either `forall_congr` or `imp_congr`, then the `forall_true_iff` lemma should apply to simplify to `nat → true`, and then to `true` by another application of `forall_true_iff`, finally closing the goal by `trivial` at the end. However, nothing happens, and the trace indicates that no `funext`-like congruence lemma is applied to enter the first binder.

Version: current master 6315136

**Comment by dselsam** [comment]
The simplifier currently goes under all binders at once when processing a `forall_congr`, and does not try to rewrite at each successive binder. See:

https://github.com/leanprover/lean/blob/master/src/library/tactic/simplify.cpp#L934-L949

Here is a workaround:

```Lean
@[simp] theorem {u} forall_true_congr {α : Sort u} {β : Prop} 
  : (β ↔ true) → ((α → β) ↔ true) := 
sorry

example : nat → nat → true := by simp
```
