### ISSUE TITLE
`#check (rfl : powmod 2 1 1 = 1)` exhausts 8GB RAM

### ISSUE THREAD

**Issue by andres-erbsen** [leanprover/lean3#1799]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I took two attempts at implementing the standard algorithm for `x^n mod m` in Lean, neither of which sufficed for executing `#check (rfl : powmod 2 1 1 = 1)` in 8GB of RAM.

### Steps to Reproduce

~~~~~~
import init.data.nat.bitwise.

section powmod
  variables (m : nat)
  definition powmod (x:ℕ) : ℕ → ℕ :=
    nat.binary_rec 1 (λ b _ r,
      let rr := r*r % m in
      if b = tt 
      then rr*x % m
      else rr)
end powmod

#reduce powmod 2 0 0
#check (rfl : powmod 2 0 0 = 1)
#reduce powmod 2 0 1.
#check (rfl : powmod 2 0 1 = 0)
#reduce powmod 2 1 1   ---------------------------- OOM
#check (rfl : powmod 2 1 1 = 1)
#reduce powmod 17 2 4
#reduce powmod (2^7-1) 2 (2^7-1-2)
#reduce powmod (2^31-1) 2 (2^31-1-2)
#reduce powmod (2^127-1) 2 (2^127-1-2)
#check (rfl : powmod (2^127-1) 2 (2^127-1-2) * 2 mod (2^127-1) = 1)
~~~~~~

**Expected behavior:** the file is processed with no errors

**Actual behavior:** The third `#reduce` runs out of memory in roughly two minutes.

**Reproduces how often:** always

### Versions

- Lean Lean (version 3.2.1, commit b50597228b42, Release)  (from Aug 6)
- Linux 4.12.4-1-ARCH

### Additional Information

Using `eval` instead of reduce generates correct answers (but as far as I understand, there is no way to prove a lemma using `eval`).

Alternative attempt in lean, same issue: https://gist.github.com/andres-erbsen/b31b9ea61c833e6fa66bbe1f07624bda
Similar attempt in Coq, completes in four seconds: https://gist.github.com/andres-erbsen/8660a0dbcea22fb5fb4434d63ef4951a

**Comment by digama0** [comment]
I will let others comment on the performance problem with the `#reduce`. As for proving theorems, definitions by well-founded recursion come with equation lemmas which can be selectively applied to prove (propositionally) the value of an expression. Here is a proof of the given value:

    section powmod
      variables (m x : nat)
      def powmod : ℕ → ℕ :=
        nat.binary_rec (1 % m) (λ b _ r,
          let rr := r*r % m in
          cond b (rr*x % m) rr)
    
      theorem powmod_zero : powmod m x 0 = 1 % m := rfl
    
      theorem powmod_bit (b n) : powmod m x (nat.bit b n) =
        let rr := (powmod m x n * powmod m x n) % m in
        cond b (rr*x % m) rr :=
      begin
        simp [powmod]; rw nat.binary_rec_eq; simp,
        cases m with m, refl,
        cases m with m, refl,
        simp [nat.mod_eq_of_lt (dec_trivial : 1 < nat.succ (nat.succ m))]
      end
    end powmod
    
    example : powmod 2 1 1 = 1 :=
    show powmod 2 1 (nat.bit tt 0) = 1, by rw powmod_bit; refl

Reduction of large nats in the kernel has horrible performance, so there is no hope of evaluating `2^127-1` let alone `powmod (2^127-1) 2 (2^127-1-2)` by `#reduce`. Instead tactics like `norm_num` are used to produce short proofs showing equality to the expected evaluation result. (The reason why Coq has so much better performance is because Lean's `nat` uses *unary* representation. I'm guessing you will get similar results in Coq if you try to use `Peano` instead of `N`.)

It should not be difficult to prove that `powmod m x n = x^n % m`, and this latter expression is easier to reason with, if you want to prove theorems about it.

**Comment by andres-erbsen** [comment]
Thank you for the tutorial. I take that `norm_num` is the supported way for dealing with large numbers. It seems to do the trick on examples that are large enough for unary arithmetic to be useless (but still much smaller than the powmod I tried). If I wanted to teach `norm_num` about `powmod` to carry out a less unfair large-scale benchmark, how would I go about it? It seems that it does not evaluate normal pow right now either:

~~~~~
open tactic

meta def eval_num_tac : tactic unit :=
do t ← target,
   (lhs, rhs) ← match_eq t,
   trace lhs,
   trace rhs,
   (new_lhs, pr1) ← norm_num lhs,
   trace new_lhs,
   (new_rhs, pr2) ← norm_num rhs,
   trace new_rhs,
   is_def_eq new_lhs new_rhs,
   `[exact eq.trans %%pr1 (eq.symm %%pr2)]
   
example : 10 - 5 * 5 + (7 - 3) * 6 = 27 - 3 := by eval_num_tac
example : 999999999999 = 999999999999 := by eval_num_tac
example : 9999999999999999998+1 = 9999999999999999999 := by eval_num_tac
example : 999999999999999999999999999999999999999999999998+1 = 3*3*3*7*11*13*17*37*73*101*137*9901*5882353*99990001*9999999900000001 := by eval_num_tac
example : 2^127-1 = 170141183460469231731687303715884105727 := by eval_num_tac
-- 19:67: failed to evaluate arithmetic expression
-- state:
-- ⊢ 2^127 - 1 = 170141183460469231731687303715884105727
~~~~~~

Edit: Or maybe the more appropriate thing to do would be to teach `norm_num` about `x^n % m` and forget about `powmod` altogether?

**Comment by dselsam** [comment]
The Lean kernel is not currently designed for efficient computing. There may be other options for fast, trusted evaluation in the future. Until then, you need to use rewriting, as @digama0 showed. Sometimes just writing a more efficient algorithm suffices though. The following is nearly instantaneous on my machine:
```Lean
def modular_power_core (m b : ℕ) : Π (e c : ℕ), ℕ
| 0     c     := c
| (e+1) c     := modular_power_core e ((c * b) % m)

def modular_power (m b e : ℕ) : ℕ := modular_power_core m b e 1

#reduce modular_power 2 0 0
#check (rfl : modular_power 2 0 0 = 1)
#reduce modular_power 2 0 1
#check (rfl : modular_power 2 0 1 = 0)
#reduce modular_power 2 1 1
#check (rfl : modular_power 2 1 1 = 1)
```

**Comment by digama0** [comment]
@dselsam The difference between your implementation and Andres' is that the exponent `e` is treated in unary by your implementation but in binary by Andres'. His implementation is the most efficient you can reasonably write if your goal is fast `#eval`. If your goal is fast `#reduce` (for small inputs), your version is probably the best within the constraints of `nat`. If you really really need fast `#reduce` / `rfl` for larger inputs, you will have to go the Coq route and use `num` instead (which is a binary representation of natural numbers found in `mathlib`).

It is unfortunate that the goals of fast VM evaluation vs fast kernel reduction pull in opposite directions, but this is a side effect of the emphasis on tactic evaluation over definitional reduction in modern Lean. `binary_rec` is a great option for writing functions on `nat` that inspect the underlying binary representation in the hardware, but it's going against the grain from the kernel's point of view, which only sees the unary representation.

PS: `modular_power_core` sounds more interesting than it is. :)

**Comment by andres-erbsen** [comment]
Let's assume I do not need `reduce` or `rfl`, but would still want to directly prove equations about large numbers, for example the last check in the first code snippet I posted (I know there is a number-theoretic proof for that one that would not require manipulating large numbers, I'm just using it just as an easy-to-check example). It seems that the thing to do in lean would be to prove equations about `_ ^ _ % _ ` that when used for rewriting specify the same system as executed in the Coq N version during reduction.

So the question I have left is how the performance of rewrite in this style would compare to reduction in the Coq kernel (Coq's kernel is pretty fast, but OTOH Lean tactics have been faster than Coq kernel for implementing non-verified procedures). This is not trivial to measure, because in small examples additive-constant overhead dominates, and if I just wrote down a huge multiplication, I'm worried that I would be benchmarking the parser and memory allocator more than the arithmetic implementation. This is why I chose modular exponentiation: it can require measurable amounts of time while using a "small" amount of memory (a couple hundred digits). For this to be possible, `norm_num` (or something similar) would need to support raw `%` and `^` first. I don't know from the top of my head how to implement `%`, so even though I would be willing to code it in principle, some reading would be required first.

Are there currently any benchmarks for computation-by-rewriting in Lean, and regardless, would there be interest in the one I am proposing here?

**Comment by dselsam** [comment]
@digama0 Yes, "more efficient" was clearly the wrong choice of words. 

> It seems that the thing to do in lean would be to prove equations about _ ^ _ % _ that when used for rewriting specify the same system as executed in the Coq N version during reduction.

You could (in addition) use binary natural numbers everywhere, like you do in Coq.

> So the question I have left is how the performance of rewrite in this style would compare to reduction in the Coq kernel 

There are two issues: (a) how fast it takes for the simplifier to do the computation (building up a proof certificate in the process), and (b) how long it takes the kernel to check the proof certificate. I do not know off-hand how Coq would check such a reflexivity proof by default: if you prove a goal by `compute` , will the kernel just re-run the computation during `QED` or would it resort to lazy unfolding?

In general, if the simplification lemmas are mimicking the definitional reduction rules used in Coq, I would expect the simplifier to be noticeably slower since there is extra work being done. Each time a head-symbol is encountered, all rules for the head-symbol will be tried in order, and each time, the unifier needs to check if the left hand sides match. Also, constructing the proof object itself takes some time and space as well. 

Anecdotally, I have found that checking the proof certificates in the Lean kernel is relatively fast and not a bottleneck.

**Comment by leodemoura** [comment]
I'm closing this issue. As pointed out by @dselsam, the Lean kernel is not designed for efficient computing.
We use the simplifier and tactics for normalizing numeric expressions.
For example, `norm_num  : expr → tactic (expr × expr)` normalizes `m` a numerical expression, returns a pair `(n, pr)` where `n` is the resultant numeral, and `pr` is a proof that the input argument is equal to `n`. 
In our experiments, the kernel can check `pr` very efficiently. 
Moreover, the reference type checkers can also check these proofs without any fancy reduction engine.

**Comment by digama0** [comment]
@leodemoura Andres makes a good point regarding non-extensibility of `norm_num`. Is there a way to make `norm_num` evaluate other kinds of numeric functions, given the appropriate set of rewriting lemmas?

**Comment by leodemoura** [comment]
@digama0 The plan is to integrate `norm_num` with the simplifier. It will happen as part of the algebraic normalizer we have been talking about.
