### ISSUE TITLE
Equation compiler loses the pp-name of a variable and introduced a unique-name

### ISSUE THREAD

**Issue by johoelzl** [leanprover/lean3#1801]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

When using a `match`-expression to eliminate two variables using `rfl` a new variable appears with a unique, non pp-name. 

It looks like the problem was introduced with:
https://github.com/leanprover/lean/commit/d4f2bb77b80ecbe05b1fee9cd7ce9b505d33f795
The example below works before and fails with this commit.

Due to this issue `mathlib` fails in `data/seq/computation.lean`.

### Steps to Reproduce

Run: 
```lean
example (c d : ℕ) (h : c = d) : c = d :=
match c, d, h with
| x, ._, rfl := begin show x = x, exact rfl end
end
```

Observer the tactic state at `begin`.

**Expected behavior:**

The tactic state should be 

```lean
c d : ℕ,
h : c = d,
_match : ∀ (_a _a_1 : ℕ), _a = _a_1 → _a = _a_1,
x : ℕ
⊢ x = x
```

**Actual behavior:**

```lean
c d : ℕ,
h : c = d,
_match : ∀ (_a _a_1 : ℕ), _a = _a_1 → _a = _a_1,
3.461.1265 : ℕ
⊢ 3.461.1265 = 3.461.1265
```

**Reproduces how often:** 100%

### Versions

Works before d4f2bb77b80ecbe05b1fee9cd7ce9b505d33f795 fails afterwards.

### Additional Information
--

**Comment by leodemoura** [comment]
You should use the following workaround.
```lean
example (c d : ℕ) (h : c = d) : c = d :=
match c, d, h with
| _, _, eq.refl x := begin show x = x, exact rfl end
end
```
The new preprocessor uses meta-variables to refine patterns.
The first `x` is being unified with the implicit argument at `rfl` which doesn't have a name.
The workaround fixes the issue by giving a name to the implicit.
I don't see a good solution for the problem, only hacks. 
One hack is to refine the names of anonymous metavariables (`3.461.1265`) if there is a named one (e.g., `x`) such that `x := 3.461.1265`.

**Comment by leodemoura** [comment]
Another hack is when solving constraints `?m_1 =?= ?m_2` we use `?m_1 := ?m_2` (if `?m_2` has an explicit name) and `?m_2 := ?m_1` otherwise.

**Comment by johoelzl** [comment]
Ah okay. I will use the `eq.refl x` workaround.

I guess what confused me was that suddenly there is a `3.461.1265` number instead of at least `_pp` or similar.

The second solution with preferring the meta variable which has a explicit name sounds good to me. Or, if possible, keep the existing behaviour, but copy the name?
