### ISSUE TITLE
Simplification impossible for anonymous match statements in sections

### ISSUE THREAD

**Issue by bmsherman** [leanprover/lean3#1804]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Consider the following example:

```lean
section
parameter P : match unit.star with
  | unit.star := true
  end

include P
lemma foo : false :=
begin
dsimp at P,
end

end
```

Just after the `begin` in the lemma `foo`, the proof state looks like this:
```
P : _match_1 ()
⊢ false
```

**Actual behavior:** The `dsimp` tactic fails to progress. The anonymous match statement is compiled to some function that has the form `_match_X` (for some number `X`). However, it is impossible to use either the `simp` or `dsimp` tactics to simplify the match statement. Usually, to simplify an anonymous match statement like this, you would use `simp` or `dsimp` with the name of the definition whose body contains that anonymous match. However, in the case of a section variable such as above, there is no such definition, and thus no such name, and it is impossible to simplify accordingly. Since `_match_X` isn't a valid name, it is difficult to manipulate. Reduction/unification does appear to work, as using `apply P` in the lemma `foo` above will solve the goal.

**Expected behavior:** I would like to be able to use `dsimp` or `simp` to simplify a match statement such as the one in the example above. Even better, it would be nice if the proof goal mode displayed the match body (such as is done in Coq), so that it is possible to see which argument is being scrutinized. Perhaps there could be some modifier for `dsimp` or `simp` to simplify anonymous match statements, or they could just simplify anonymous match statements by default, just like they simplify recursor applications.

### Versions

I am using Lean version from August 12, 2017, Lean (version 3.2.1, commit 32ddac5, Release).

**Comment by digama0** [comment]
>Since `_match_X` isn't a valid name, it is difficult to manipulate.

`_match_X` is a perfectly valid name, it just can't be used by the user when naming new local variables or definitions. If we didn't let users even refer to underscore names we'd have a much bigger problem.

That said, it's still a usability issue, but you should be able to work around it by referring to it by its internal name.

**Comment by bmsherman** [comment]
What is its internal name? If I try something like `dsimp [_match_1] at P`, I get the error `unknown identifier '_match_1'`.  If I try to refer to `_match_1` in any code that follows declaration of `P`, I am also told it is an unknown identifier. This is what I meant when I said that `_match_X` isn't a valid name. (I wasn't referring to the fact that users aren't allowed to create names of that form.)

**Comment by digama0** [comment]
Oh, I see. The internal name is `_private.12345._match_1`, which is indeed difficult to reference. I think this is a general problem with referencing private names - we need a mechanism for resolving private names within the context of definition (in this case inside the section). I suspect such a mechanism already exists and may even be exposed to the tactic framework, but we haven't closed the loop to `dsimp` resolution yet. Anyway, this is not my area of expertise so hopefully someone can use the info here to work up a solution.

**Comment by Kha** [comment]
If we set up a `declaration_info_scope` for parameters, the generated name should be `P._match_1` and `simp [P]` should work just like it does for definitions and theorems.

**Comment by gebner** [comment]
@Kha This would be a problem if you had the the parameter `P` in two different sections.  The name needs to be private (well, unique at least).

**Comment by Kha** [comment]
@gebner We can use a private `declaration_info_scope`. But I see now that `simp [f]` doesn't work for private definitions `f` either right now, presumably because nested private definitions do not generate nested names: https://github.com/leanprover/lean/blob/9afb53fad584577501d0473db3109c7368476d8e/src/frontends/lean/decl_util.cpp#L373-L373

(Ooh, is that a new Github feature?)

Edit: In any case, it's not clear how we would resolve the local_const P to the private names of its nested declarations.

**Comment by gebner** [comment]
@Kha That line should only affect the namespace.  I think you're looking for `declaration_name_scope`, and there we don't special-case private definitions.

I guess one of the reasons we don't find the equation lemmas is because they're doubly-private (although they should be stored in an environment extension AFAIK):
```lean
private def foo : ℕ → ℕ
| 0 := 10
| (n+1) := 3

open tactic
#eval do
ls ← get_eqn_lemmas_for tt ``foo, trace ls,
env ← get_env,
env.fold skip (λ d t, do t, when (env.decl_olean d.to_name).is_none $ trace d.to_name)
```

The relevant output is:
```
_private.601341774._private.598148466.foo._main.equations._eqn_2
_private.598148466.foo._main
_private.1019423003._private.598148466.foo._main.equations._eqn_1
_private.1399211358.foo
```

EDIT: there are too many de*_info_scopes

**Comment by leodemoura** [comment]
@kha @gebner I've investigated this problem yesterday. It exposes a problem on how private names are managed. The equational lemma management assumes auxiliary definition names share a prefix with the main definition. This is not the case for private definitions. This problem also affects private definitions such as
```lean
private def foo (x : nat) : nat :=
match x with
| 0 := 1
| _ := 2
end
```
Tactics such as `simp [foo]` will fail to unfold the auxiliary definition created for the nested match.
There is also the double private issue described by @gebner. This one is easy to fix, but it will not solve this PR. 
Another problem is collision of temporary user names for private names. This is a problem if we have two parameters using `match`.
@kha suggestion of using section names is useful for avoiding this collision problem.
