### ISSUE TITLE
nat.pow

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean3#1806]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

This is an issue for my own code rather than Lean.  The current nat.pow function is defined in terms of zero and succ, and consequently will not perform well on large exponents.

I have a [binary implementation](https://github.com/GaloisInc/lean-protocol-support/blob/master/galois/nat/exp.lean) that's also generalized to arbitrary monoids for the value.  I could submit a PR, but the lean library may be a better long-term place.  I haven't done extensive benchmarking, but 2048-bit modular arithmetic with a large exponent evaluates in a second or so with the binary implementation.

Would it be preferred to submit this to the Lean itself, Lean's library (as a replacement to the group_power.lean definition), or neither?
 
### Versions

N.A.

### Additional Information

N.A.

**Comment by digama0** [comment]
The `nat.pow` implementation in Lean should ideally be overwritten with a fast implementation in C. The Lean implementation is only a specification, and is not expected to perform well under kernel reduction anyway. I think your alternate implementation will be welcomed in `mathlib`, but not here, because there are better approaches for performant pow in the core anyway.

**Comment by joehendrix** [comment]
Ok, I'm going to close this.
