### ISSUE TITLE
Unifications with constants fail

### ISSUE THREAD

**Issue by koba-e964** [leanprover/lean3#1810]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
Consider the following code:
```
universe u
constant t: Sort u
constant f: t -> t
constant x: t
lemma test: x = x := by reflexivity
lemma test2: f x = f x := by reflexivity
```
**Expected behavior:** 
The lemma `test2` compiles without any errors as well as `test`.

**Actual behavior:** 
Unification fails. `lean` emits the following error message:
```
$ lean test2.lean
/Users/koba_mac/srcview/lean-work/test2.lean:6:29: error: invalid apply tactic, failed to unify
  f x = f x
with
  ?m_2 = ?m_2
state:
⊢ f x = f x
```
**Reproduces how often:** 100%

### Versions
I'm using Lean 3.2.0.
```
kobas-MacBook-Air:lean-work koba_mac$ lean --version
Lean (version 3.2.0, Release)
```
OS: macOS Sierra (Version 10.12.6)
### Additional Information

If `t` is not a `constant`, this issue seems not to happen.

**Comment by gebner** [comment]
The way you usually debug these kinds of errors is by using `set_option pp.all true`.  Then you get this more informative error message:
```
invalid apply tactic, failed to unify
  @eq.{u_1} t.{u_1} (f.{u_2 u_1} x.{u_2}) (f.{u_3 u_1} x.{u_3})
with
  @eq.{?l_1} ?m_2 ?m_3 ?m_3
state:
⊢ @eq.{u_1} t.{u_1} (f.{u_2 u_1} x.{u_2}) (f.{u_3 u_1} x.{u_3})
```

The crucial point here is that all of the constants you defined are *universe-polymorphic*.  Note that `universe u` declares a universe variable, which is implicitly added to every declaration that uses it (very similar to a variable in a section).

That is, `t` takes a universe parameter `u`, such that for every universe level `u` there is a different type `t.{u} : Sort u`.  And `f.{u v} : t.{u} -> t.{v}` is a function between two possibly different `t`.  There is also no way to prove that `x.{u}` and `x.{v}` are in any way equal (if `u` and `v` are different universe levels).  Hence, lemma `test2` is false (or at least unprovable) the way it is stated.

My suggestion is to pick a concrete universe level for `t`, for example `t : Type`.

**Comment by koba-e964** [comment]
Thank you for your helpful explanation about it. Using `constant t: Type` solved the problem.
