### ISSUE TITLE
Segfault on missing case for nested inductive defined with `sorry`

### ISSUE THREAD

**Issue by kenmcmil** [leanprover/lean3#1812]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Dumps core on this example

### Steps to Reproduce

1. lean dumpcore.lean

**Expected behavior:** 

Not dump core.

**Actual behavior:** 

Dump core.

**Reproduces how often:** 

always

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

Lean (version 3.2.1, commit 2d69fc9cd71f, Release)
Ubuntu 14.04

### Additional Information

[dumpcore.zip](https://github.com/leanprover/lean/files/1275789/dumpcore.zip)

**Comment by digama0** [comment]
You should not have checked that box. This example has not been minimized in any way, and you have made no attempt to isolate the problem.

**Comment by digama0** [comment]
Minimized:

    def bndng (α : Type) : Type := sorry
    
    inductive pterm : Type
    | star : pterm -> pterm 
    | letrec : bndng pterm -> pterm 
    
    def weaken : pterm → pterm 
    | (pterm.star p) := pterm.star (weaken p)

The issue has something to do with the missing inductive case in `weaken` for `letrec`, and the nested inductive defined via `sorry`.

**Comment by gebner** [comment]
The `sorry` is a bit of a red herring.  This causes an assertion violation as well:
```lean
def bndng (α : Type) : Type := string

inductive pterm : Type
| star : pterm -> pterm 
| letrec : bndng pterm -> pterm 

def weaken : pterm → pterm 
| (pterm.star p) := pterm.star (weaken p)
| (pterm.letrec _) := pterm.letrec ""
```
This is the assertion violation:
```
File: /home/gebner/lean/src/library/compiler/elim_recursors.cpp
Line: 216
is_lambda(minor)
```
EDIT: the missing case is a red herring as well.
