### ISSUE TITLE
[RFC] warning for name collision when using `intro`

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#1814]
@kenmcmil suggested we produce a warning whenever `intro h` shadows an existing hypothesis.
What do you think?

Motivation: he was debugging an error message of the form:
```
invalid type ascription, term has type
  t c 
but is expected to have type
  t c
```
where there were two `c`s in the local context. The error message look bogus since the terms look identical. Another option, we list the hypotheses with name classes in this kind of error message.

**Comment by avigad** [comment]
I am not sure. Producing a warning will clutter up the editor with squiggles if that is what the user really meant to do.

**Comment by digama0** [comment]
Why not warn at the point of the error message? i.e.:

    invalid type ascription, term has type
      t c 
    but is expected to have type
      t c
    Aliased variables at this point: (c : T1) (c : T2)

Another possibility is to simply deduplicate all names involved in the error (so it prints `t c` / `t c_1`), although this may lead to confusion since these won't match the names in the tactic state immediately prior to the error. If there was a public `dedupe *` / `dedupe c` tactic for renaming all variables to `_1` forms (I think this is equivalent to revert all and intro?) it would be easier to explain this behavior by telling users to call `dedupe *` before the error to see the variables used in the printed form of the error.

**Comment by bmsherman** [comment]
I have regularly confused myself with name shadowing errors like this, turning on all the `pp` options to see if there was a universe error or error in implicit arguments or something like that, only to find that I have two variables with the same name (and often the same type) in context. We had a small discussion of name shadowing issues on the Lean Gitter [here](https://gitter.im/leanprover_public/Lobby?at=59961d69162adb6d2e0878b7).

One option would be to introduce a `pp` option called `unique_names` or something like this that would print actual unique names of identifiers. I don't know how names are represented internally, so I don't know how this display might look. What I might even prefer to this is to only display the "unique names" version of things when they are not already unique.

Similarly, Lean could conceivably be more tactful about displaying type mismatch errors. When lean says `cannot match X with Y`, ideally it the printed string `X` should never be identical to the printed string `Y` (see [this resolved issue](https://github.com/leanprover/lean/issues/1760), where universes cause a type mismatch, and printing was added to print universes so one can determine that this was the issue). If the two are identical, it could make sense to turn on printing of implicit arguments or universes, until there is a visible difference in the printed strings.

In my opinion, introducing such a warning when `intros` causes name shadowing wouldn't address most of the cases in which I find myself confused by name shadowing.

**Comment by digama0** [comment]
>One option would be to introduce a pp option called unique_names or something like this that would print actual unique names of identifiers. I don't know how names are represented internally, so I don't know how this display might look. What I might even prefer to this is to only display the "unique names" version of things when they are not already unique.

The unique names are hierarchical with big numbers like `1.9594.2549`. No one wants to see that. I think that the `dedupe` approach I mentioned should be just as good, if the goal is unambiguous naming, and it still preserves some of the printed name so it's not unreadable.

**Comment by leodemoura** [comment]
> Similarly, Lean could conceivably be more tactful about displaying type mismatch errors. When lean says cannot match X with Y, ideally it the printed string X should never be identical to the printed string Y (see this resolved issue, where universes cause a type mismatch, and printing was added to print universes so one can determine that this was the issue). If the two are identical, it could make sense to turn on printing of implicit arguments or universes, until there is a visible difference in the printed strings.

Lean already tries to do that. Consider the following example
```lean
def f {a : nat} : nat := a

example : @f 2 = @f 2 :=
eq.refl (@f 1)
```
It produces the error message.
```
ex.lean:4:0: error: type mismatch, term
  eq.refl f
has type
  @f 1 = @f 1
but is expected to have type
  @f 2 = @f 2
```
`pp.implicit` was automatically set to `true`.  Note that, if the terms cannot be distinguished by exposing additional information, then Lean will use the default setting.

**Comment by digama0** [comment]
> Note that, if the terms cannot be distinguished by exposing additional information, then Lean will use the default setting.

This should never happen. That is, we should ramp up the explicitness until it is impossible for this situation to occur, up to and including showing unique names if necessary. It's a giant waste of time for the user to analyze two expressions that are in fact identical strings looking for differences.

At the very least, print `(identical)` afterward if you already know the user's search will be in vain.

**Comment by leodemoura** [comment]
> This should never happen. That is, we should ramp up the explicitness until it is impossible for this situation to occur, up to and including showing unique names if necessary. It's a giant waste of time for the user to analyze two expressions that are in fact identical strings looking for differences.

You are stating the obvious. We are aware this is a problem, and are trying to find ways to improve the error messages (example: https://github.com/leanprover/lean/issues/1760).

**Comment by digama0** [comment]
Is it? One thing which clearly does not hold, but should, is that with all printing options enabled, two expressions which print the same (in the same context) cannot have different types. Use `to_raw_fmt` if you have to, but never print the same string twice. This isn't so much about improving error messages (the result will be horrible without more nuanced work to make the printout readable *and* unambiguous) as ensuring Pollack consistency by an easy method.

How hard would it be to replace your fallback (if pp.all fails to distinguish, then print normally) with using `to_raw_fmt` or an equivalent that shows all data contained in an `expr` (or at least all data that can affect definitional equality)?

**Comment by leodemoura** [comment]
> Is it? One thing which clearly does not hold, but should, is that with all printing options enabled, two expressions which print the same (in the same context) cannot have different types. 

The property above is obviously desirable. My point is that it is easy to state properties like this one, but much harder to ensure they hold. In many cases, may changes would have to be done in the system.
As I said before, if you are not happy with the current system, you can always fork it and build your own version, or switch to another system.

> Use to_raw_fmt if you have to, but never print the same string twice. This isn't so much about improving error messages (the result will be horrible without more nuanced work to make the printout readable and unambiguous) as ensuring Pollack consistency by an easy method.

Using `to_raw_fmt` is a bad idea, and I am not interested in discussing it.
