### ISSUE TITLE
Pretty-printer prints invalid expressions (additional parentheses need around negation)

### ISSUE THREAD

**Issue by bmsherman** [leanprover/lean3#1817]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The following Lean directive
```lean
#check int.add (-1) 1
```
returns the result
```lean
int.add -1 1 : ℤ
```
which does not parse to a valid Lean expression, because the `-` is interpreted as (binary) subtraction rather than unary negation. The pretty-printer should include parentheses around the `-1`.

Likely this is one instance of a more general issue of the pretty-printer not inserting parentheses in enough places.

### Versions

Lean Git version from August 12: Lean (version 3.2.1, commit 32ddac5f40a7, Release)

**Comment by leodemoura** [comment]
I will push a fix soon.
