### ISSUE TITLE
[RFC] Support { s with } syntax

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1820]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

This is a feature request, for logging and/or RFC purposes (i.e. there is no need to act on it immediately, and it may need to wait on #1674 anyway).

1. The structure command `{ s with f1 := t1, f2 := t2, ... }` does not support the nullary case, which naturally would be written `{ s with }`. This kind of construction is useful for copying all the fields of one structure over to another structure with the same names, or even more commonly, a structure that contains all the fields of the target and more, from which we want to extract just the applicable fields.

2. Additionally, because the structure syntax operates simply by copying applicable fields from the source structure (`s` in this case) to the target when the names match up, there is no reason why this can't be extended to copies from multiple structures, with the proposed syntax `{ s1 with s2 with ... with f1 := t1, f2 := t2, ... }`. This would be useful for doing "structure union" type operations, or filling the fields of a new structure using several typeclasses - currently we have to just pick the biggest of the source structures for the `s with` position and manually copy over the others.

   If both `s1` and `s2` have an applicable field with the same name, then `s1` takes precedence (i.e. `s1` copies all its fields, then `s2` covers any remaining fields, and so on, and then any remaining fields must be given with `f1 := t1` clauses).

3. One last suggestion, which may be more debatable now that all missing field errors are reported (rather than just the first): If a field is omitted from a structure builder, it should be treated as a `mk` with a placeholder rather than being ill-formed. The debatable part of this is that this may make the error reporting worse, since if it is reported like a usual placeholder, the field name will not be mentioned in the error message. How difficult would it be to support incomplete structures only in `refine` or other contexts where undetermined placeholders are acceptable?

**Comment by Kha** [comment]
Note for posterity's sake: The option implemented was 1), i.e. the title of the issue.

**Comment by Kha** [comment]
The remaining suggestions have now been implemented in #1869
