### ISSUE TITLE
Confusing notation disambiguation in the absence of local

### ISSUE THREAD

**Issue by shlevy** [leanprover/lean3#1834]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

This compiles fine:

```lean
universe u

private class has_compose {object} (arrow : object → object → Sort u) :=
  (compose : Π {a b c}, arrow a b → arrow b c → arrow a c)

local notation g ∘ f := has_compose.compose _ f g

class category {object} (arrow : object → object → Sort u) extends has_compose arrow :=
  (identity : Π {a}, arrow a a)
  (compose_left_identity : ∀ {a b} {f : arrow a b}, identity ∘ f = f)
  (compose_right_identity : ∀ {a b} {f : arrow a b}, f ∘ identity = f)
  (compose_associative : ∀ {a b c d} {f : arrow a b} {g : arrow b c} {h : arrow c d}, h ∘ (g ∘ f) = (h ∘ g) ∘ f)
```

But if I remove the `local` from the notation definition, lean seems to pick the `function.comp` overload instead:

```lean
/home-persistent/shlevy/src/awodey/category.lean:10:61: error: type mismatch at application
  function.comp identity
term
  identity
has type
  arrow ?m_1 ?m_1 : Sort u
but is expected to have type
  ?m_1 → ?m_2 : Sort (imax ? ?)
Additional information:
/home-persistent/shlevy/src/awodey/category.lean:10:61: context: overload was disambiguated using expected type
(overloads: λ (x_1 : _) (x_2 : _), has_compose.compose _ x_2 x_1, function.comp)
the only applicable one seemed to be: function.comp

type mismatch at application
  has_compose.compose ?m_1 x_2
term
  x_2
has type
  ?m_1 : Sort ?
but is expected to have type
  ?m_1 ?m_2 ?m_3 : Sort ?
```

Is this expected? Is there any way I can use `∘` in this context? Note that removing the `local` and replacing `∘` with `●` works just fine.

### Versions

Lean (version 3.3.0, Release)
Linux 4.13.0, NixOS 18.03.git.65e6a7e

**Comment by Kha** [comment]
Lean tries to elaborate applications using the expected type first, then falls back to a simpler procedure if that fails. For overloaded applications, it only does that if all overloads fail to elaborate. I suspect that `function.comp` can be elaborated with the expected type, but your overload cannot. I'm not sure whether we want to change this behavior.

Curiously, the overload seems to work if you prevent Lean from inserting those placeholder lambdas:
```
infixr ∘ := flip (has_compose.compose _)
```

**Comment by Kha** [comment]
By the way, it works with local notations because they hide global notations instead of overloading them.

**Comment by shlevy** [comment]
Ah, I see. It's strange to me that in the absence of `function.comp` this typechecks fine. But I know next to nothing about the elaborator so I don't know if that's expected.
