### ISSUE TITLE
Missing assumption for congr tactic

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#1835]
When applying `congr` in a situation where the the equality `A = B` of two types has to be shown before showing `a == b` for some `a : A` and `b : B`, `congr` should add `A = B` as an assumption for the latter goal, since it has already been shown. Might be related to #1830. Small example:
```lean
structure foo :=
  (A : Type)
  (a : A)

example (x y : foo) : x = y :=
begin
  cases x with A a, cases y with B b, congr,

end
```

**Comment by fpvandoorn** [comment]
I think not adding the assumption is a fine default (maybe there are independent reasons that `a == b` is true; in this particular case, `a == b` actually implies `A = B`). Fortunately, you can define your own `congr` tactic which does what you request.

**Comment by javra** [comment]
I guess I'll close this until we have a few more cases than just mine.
