### ISSUE TITLE
The wiki page on HoTT should redirect to Lean2

### ISSUE THREAD

**Issue by guillaumebrunerie** [leanprover/lean3#1846]
The wiki page on the HoTT library (https://github.com/leanprover/lean/wiki/HoTT-Library, which is currently the first Google result for "lean hott") is obsolete as it refers to https://github.com/leanprover/lean/blob/master/hott/hott.md which does not exist anymore.

There should be a note saying that Lean 3 does not support HoTT anymore, and redirecting to Lean2.

**Comment by fpvandoorn** [comment]
I updated the wiki again. Although Lean 3 indeed doesn't support HoTT, we are currently working on a [new HoTT library](https://github.com/gebner/hott3) in Lean 3 which doesn't require any kernel modification. See the readme there for more information.
