### ISSUE TITLE
Can't build package with lean checkout: file 'leanpkg/lean_version' not found in the LEAN_PATH

### ISSUE THREAD

**Issue by spl** [leanprover/lean3#1848]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC), or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I'm trying to build a package with a local `git` checkout of the `lean` repository on macOS.

### Steps to Reproduce

1. Build `lean` as instructed:
    ```sh
    $ mkdir tmp && \
    pushd tmp && \
    git clone https://github.com/leanprover/lean.git lean && \
    mkdir -p build/release && \
    pushd build/release && \
    cmake ../../src && \
    make && \
    popd && \
    popd
    ```
2. Create a `leanpkg.toml`:
    ```sh
    $ cat > leanpkg.toml
    [package]
    name = "mypackage"
    version = "0.1"

    [dependencies]
    mathlib = {git = "https://github.com/leanprover/mathlib.git", rev = 
    "5ad8020f67eb13896a41cc7691d072c9331b1f76"}
    ^D
    ```
3. Build the (empty) package:
    ```sh
    $ ./lean/bin/leanpkg build
    ```

**Expected behavior:**

I expect the `mathlib` `.olean` files to be built.

**Actual behavior:**

I get the following errors:

```
~/tmp/lean/leanpkg/leanpkg/git.lean:1:0: error: file 'leanpkg/lean_version' not found in the LEAN_PATH

<unknown>:1:1: error: file 'leanpkg/lean_version' not found in the LEAN_PATH
external command exited with status 1
```

**Reproduces how often:**

Every time.

### Versions

```sh
$ uname -rs  # macOS Sierra 10.12.5
Darwin 16.6.0
$ ./lean/bin/lean --version
Lean (version 3.3.1, commit 5efa1b829cfb, Release)
```

### Additional Information

I thought it might be a `$PATH` issue, but the following did not remove the errors.

```sh
$ export PATH=$PWD/lean/bin:$PATH
$ leanpkg build
```

I thought perhaps there was a problem with the absolute import locations. I tried removing the `leanpkg.` prefix from the `import`s in the `leanpkg` directory, as shown in the diff below. That “fixed” a successive list of errors in the `lean/leanpkg/leanpkg` directory, but many more showed up in other locations after that.

```diff
diff --git a/leanpkg/leanpkg/git.lean b/leanpkg/leanpkg/git.lean
index db746f8b9..ab69b0f15 100644
--- a/leanpkg/leanpkg/git.lean
+++ b/leanpkg/leanpkg/git.lean
@@ -3,7 +3,7 @@ Copyright (c) 2017 Microsoft Corporation. All rights reserved.
 Released under Apache 2.0 license as described in the file LICENSE.
 Author: Gabriel Ebner
 -/
-import leanpkg.lean_version system.io
+import .config_vars .lean_version system.io
 variable [io.interface]

 namespace leanpkg
@@ -29,4 +29,4 @@ def git_latest_origin_revision (git_repo_dir : string) : io string := do
 io.cmd {cmd := "git", args := ["fetch"], cwd := git_repo_dir},
 git_parse_origin_revision git_repo_dir upstream_git_branch

-end leanpkg
\ No newline at end of file
+end leanpkg
diff --git a/leanpkg/leanpkg/lean_version.lean b/leanpkg/leanpkg/lean_version.lean
index c1a7eddf6..024da8a3f 100644
--- a/leanpkg/leanpkg/lean_version.lean
+++ b/leanpkg/leanpkg/lean_version.lean
@@ -3,7 +3,7 @@ Copyright (c) 2017 Microsoft Corporation. All rights reserved.
 Released under Apache 2.0 license as described in the file LICENSE.
 Author: Gabriel Ebner
 -/
-import leanpkg.config_vars
+import .config_vars

 namespace leanpkg

@@ -24,4 +24,4 @@ if is_release then
 else
     "master (" ++ lean_version_string_core ++ ")"

-end leanpkg
\ No newline at end of file
+end leanpkg
diff --git a/leanpkg/leanpkg/main.lean b/leanpkg/leanpkg/main.lean
index bb10c0f9d..b1ce9a59a 100644
--- a/leanpkg/leanpkg/main.lean
+++ b/leanpkg/leanpkg/main.lean
@@ -3,7 +3,7 @@ Copyright (c) 2017 Microsoft Corporation. All rights reserved.
 Released under Apache 2.0 license as described in the file LICENSE.
 Author: Gabriel Ebner
 -/
-import leanpkg.resolve leanpkg.git
+import .resolve .git
 variable [io.interface]

 namespace leanpkg
diff --git a/leanpkg/leanpkg/manifest.lean b/leanpkg/leanpkg/manifest.lean
index 2836532cb..5d760f360 100644
--- a/leanpkg/leanpkg/manifest.lean
+++ b/leanpkg/leanpkg/manifest.lean
@@ -3,7 +3,7 @@ Copyright (c) 2017 Microsoft Corporation. All rights reserved.
 Released under Apache 2.0 license as described in the file LICENSE.
 Author: Gabriel Ebner
 -/
-import leanpkg.toml leanpkg.lean_version system.io
+import .toml .lean_version system.io

 namespace leanpkg

diff --git a/leanpkg/leanpkg/proc.lean b/leanpkg/leanpkg/proc.lean
index 82c61ff83..0659e6667 100644
--- a/leanpkg/leanpkg/proc.lean
+++ b/leanpkg/leanpkg/proc.lean
@@ -3,7 +3,7 @@ Copyright (c) 2017 Microsoft Corporation. All rights reserved.
 Released under Apache 2.0 license as described in the file LICENSE.
 Author: Gabriel Ebner
 -/
-import system.io leanpkg.toml
+import system.io .toml
 open io io.proc
 variable [io.interface]

diff --git a/leanpkg/leanpkg/resolve.lean b/leanpkg/leanpkg/resolve.lean
index 60a1bc0d1..bff0853be 100644
--- a/leanpkg/leanpkg/resolve.lean
+++ b/leanpkg/leanpkg/resolve.lean
@@ -3,7 +3,7 @@ Copyright (c) 2017 Microsoft Corporation. All rights reserved.
 Released under Apache 2.0 license as described in the file LICENSE.
 Author: Gabriel Ebner
 -/
-import leanpkg.manifest system.io leanpkg.proc leanpkg.git
+import .manifest system.io .proc .git
 variable [io.interface]

 namespace leanpkg
```

**Comment by gebner** [comment]
> `$ ./lean/bin/leanpkg build`

Do you have the following directory structure?
 * `./leanpkg.toml`
 * `./lean` is the cloned lean repository

This is not supported.  You cannot have any other lean code or packages inside a package (i.e., the directory with the `leanpkg.toml`).  Just make another separate directory `mypackage` that contains the new `leanpkg.toml` file.

To explain, `leanpkg build` recursively looks for all `*.lean` files in the current package.  Now there are many lean files in the `lean` directory, and `leanpkg` treats them as part of `mypackage`.  The imports then fail because `leanpkg` does not know about them, and hence does not configure the import search path appropriately.

**Comment by spl** [comment]
@gebner:

> Do you have the following directory structure?
> 
> * `./leanpkg.toml`
> * `./lean` is the cloned lean repository

Yep.

> This is not supported. You cannot have any other lean code or packages inside a package (i.e., the directory with the `leanpkg.toml`). Just make another separate directory `mypackage` that contains the new `leanpkg.toml` file.

Got it.

It looks like adding the `path = "mypackage"` option (along with creating the new `mypackage` directory) in the `leanpkg.toml` would also solve this.

A potential `leanpkg.toml` feature that may or may not be worth considering is to allow path exclusions.

Thanks!
