### ISSUE TITLE
Nice introduction/elimination syntax for inductive types not supported by the inductive compiler

### ISSUE THREAD

**Issue by shlevy** [leanprover/lean3#1849]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I have a nested inductive type that the `inductive` compiler can't handle, so I've manually unrolled it and defined the relevant smart constructor and eliminator that I wanted to write directly. It would be awesome if I could somehow wire things up to use ⟨⟩ construction syntax (or even record syntax, since in this case I have a single "exposed" constructor with named fields) and pattern matching based on my custom defined functions, instead of just the ones the inductive definition provides.

**Comment by dselsam** [comment]
> I have a nested inductive type that the inductive compiler can't handle

Can you post the example?

**Comment by shlevy** [comment]
Sure:

```lean
reserve infixr ` ⊕' `:30
notation α ⊕' β := psum α β

/- What I'd like to write
inductive foo : Type → Type
| mk : Π {t} (pred : Type → Prop)
      , (Π {t'}, pred t' → t = t' ⊕' foo t')
      → foo t
-/

inductive foo_impl_selector
| eq_or_foo
| foo

@[reducible] def foo_impl_param : foo_impl_selector → Type 1
| foo_impl_selector.eq_or_foo := Type × Type
| foo_impl_selector.foo := Type

inductive foo_impl : Π (f : foo_impl_selector), foo_impl_param f → Type 1
| eq_or_foo_inl : Π {x}, foo_impl foo_impl_selector.eq_or_foo (x, x)
| eq_or_foo_inr : Π {x y}, foo_impl foo_impl_selector.foo y → foo_impl foo_impl_selector.eq_or_foo (x, y)
| foo_mk : Π {x} (p : Type → Prop)
         , (Π {y}, p y → foo_impl foo_impl_selector.eq_or_foo (x, y))
         → foo_impl foo_impl_selector.foo x

def foo (t : Type) := foo_impl foo_impl_selector.foo t

namespace foo
  universe l

  def mk : Π {x} (p : Type → Prop), (Π {y}, p y → x = y ⊕' foo y) → foo x :=
    λ x p a, foo_impl.foo_mk p (λ y py, @psum.rec (x = y) (foo y) (λ _, foo_impl foo_impl_selector.eq_or_foo (x, y)) (@eq.rec _ _ (λ y, foo_impl foo_impl_selector.eq_or_foo (x, y)) (foo_impl.eq_or_foo_inl) _) (foo_impl.eq_or_foo_inr) (a py))

  def rec {C : Π (t), foo t → Sort l} : (Π {x} (p : Type → Prop) (a : Π {y}, p y → x = y ⊕' foo y), (Π {y} (a_1 : p y), @psum.rec (x = y) (foo y) (λ _, Sort l) (λ _, punit) (C y) (a a_1)) → C x (mk p @a)) → Π {t} (n : foo t), C t n := sorry /- haven't gotten here yet -/
end foo
```
I'm not sure I have the type of my hand-written recursor exactly right/as general as it could be, but it seems in the right ballpark

**Comment by dselsam** [comment]
Early drafts of the inductive compiler supported your case, since they would allow a nested occurrence to include local variables that were not parameters. However, it made the internal bookkeeping more complicated since we needed to add phantom indices to the newly introduced mutual inductive types. Since we couldn't envision a compelling need for the feature, we did not support it in the final version.

Here is what the encoding would have looked like:
```Lean
mutual inductive foo, bar
with foo : Type → Type 1
| mk : Π {t : Type} (pred : Type → Prop), (Π {t' : Type}, pred t' → foo_psum t t') → foo t
with foo_psum : Type → Type → Type 1
| inl : Π {t t' : Type}, t = t' → foo_psum t t'
| inr : Π {t t' : Type}, foo t' → foo_psum t t'
```
(Note the extra index for `foo_psum`).

**Comment by shlevy** [comment]
Sure, that's basically what I have, except I've inlined the definition of `=` and unfolded the mutual definition.

What would the recursor have looked like? And is there any way to recover pattern matching and nice construction syntax?

**Comment by shlevy** [comment]
Ah, looks like it just doesn't let you recurse on the return value of the second arg.
