### ISSUE TITLE
tactic.exact doesn't unify in types of terms when called directly

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1855]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

This piece of code is supposed to mimic the interactive command `refine nat.succ _`:

```lean
open tactic
example : ℕ := by do
  t ← mk_meta_var (expr.sort $ level.succ level.zero),
  m ← mk_meta_var t,
  c ← mk_const `nat.succ,
  exact $ c m, tactic.set_goals [m, t]
  -- apply $ c m, tactic.set_goals [m, t]
  -- refine $ to_pexpr $ c m
```

Output:
```
tactic failed, there are unsolved goals
state:
⊢ ?m_1

⊢ Type
```

Expected output:
```
tactic failed, there are unsolved goals
state:
⊢ ℕ
```

The issue appears to be that the metavariable `t` has not been unified with `nat` as it should have. Adding ``cn ← mk_const `nat, unify cn t`` at the end performs the unification and produces the expected output, but `result >>= type_check` apparently does not perform any unification of the term (the result is `nat.succ ?m` where `?m : ?t`, even though we should already have `?t := nat`). Another workaround to trigger unification of the result is `r ← result, unify r r`.

**Comment by leodemoura** [comment]
This is not a bug. The sequence of commands is not mimicking `refine nat.succ _`.
The tactic `refine nat.succ _` elaborates the (pre-)term `nat.succ _` and produces `nat.succ ?m1` where `?m1 : nat`.
Even if it had created `?m1 : ?m2`, the elaborator would generate the constraint `?m2 =?= nat` imposed  by the application `nat.succ ?m1`. The sequence of commands above creates the application `nat.succ ?m1` by using the constructor `expr.app` and a coercion, and the constraint `?m2 =?= nat` is not created.

> The issue appears to be that the metavariable t has not been unified with nat as it should have

It should not. You are misunderstanding how `exact` works.
`exact t` infers the type of `t`, and then tries to unify it with the goal. If it succeeds, then it closes the goal.
In this case, the inferred type is `nat`, and the constraint `nat =?= nat` is trivially solved.
The tactic `exact` will *not* traverse `t` and (re-)generate typing constraints. This would be inefficient.

> result >>= type_check apparently does not perform any unification of the term (the result is nat.succ ?m where ?m : ?t, even though we should already have ?t := nat). 

The tactic `type_check` is currently just for sanity checking. It does not update the state.
https://github.com/leanprover/lean/blob/master/src/library/tactic/tactic_state.cpp#L912

**Comment by digama0** [comment]
@leodemoura That's all fine, but it leaves open the question of exactly *how* to achieve the effect of `refine nat.succ _` without using pre-terms, which are not well developed in the tactic framework. How would I explicitly create the necessary metavariables and unification conditions for this?

> The tactic exact will not traverse t and (re-)generate typing constraints. This would be inefficient.

In that case, it seems that there is a missing tactic: How do I say "check this term and generate unification constraints", or (perhaps more reasonably) "apply this to that and generate unification constraints"? This might be `mk_app` or `mk_mapp`, but I'd like a version that doesn't bother with implicits and typeclass inference, just pure typechecking of an application.
