### ISSUE TITLE
leanpkg should indicate segmentation fault

### ISSUE THREAD

**Issue by spl** [leanprover/lean3#1868]
I did not immediately discover a segmentation fault in `lean` (#1867) because `leanpkg` did not pass it through. Instead, `leanpkg` ended with a line like:

```
> lean --make src
<file path>: <theorem name>
```

when it would normally not have that last line. I thought it was kind of strange, but I didn't immediately look into it.

Only when I realized that changes I expected to result in errors were not producing errors did I suspect there was a problem. First, I looked at `echo $?` to see if there was a error code: there was not. Then, I tried running `lean` directly and discovered the segfault.

To avoid this kind of confusion, I think `leanpkg` should handle a `SIGSEGV`. Perhaps the solution would look something like [this](https://unix.stackexchange.com/questions/24307/how-can-i-trap-a-program-that-returns-139-segmentation-fault-in-bash).

**Comment by spl** [comment]
👍

Now I see:

```
> lean --make src
<file path>: <theorem name>external command exited with status 11
```
Note that there is no space between the end of `<theorem name>` and `external`, leading them to momentarily confusing things like `acie.aeq.subst_comp.fresh_not_memexternal`. Would it help to put a newline (`"\n"`) in the `fail` message in `leanpkg/leanpkg/proc.lean`?

**Comment by Kha** [comment]
I tried to emulate my shell's behavior :smile: 
```
> lean --make

/data1/ullrich/lean/alpha-conversion-is-easy/src/aeq/properties.lean: acie.aeq.subst_comp.fresh_not_mem[1]    8217 segmentation fault (core dumped)  lean --make
```
I think most cmdline people are used to seeing mangled output on abnormal termination. The added newline would produce an empty line if Lean terminates normally (successfully or not), but I wouldn't mind that much either.
