### ISSUE TITLE
User attribute olean inconsistency causes segfaults

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1871]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

This is a tricky one to reproduce. Roughly speaking, the `lean --server` and `lean --make` versions generate different `olean` data for the param data of a `user_attribute`, leading to an inconsistency when it is read by `user_attribute.get_param`. Here's a minimal example. It requires two files - `A.olean` is corrupted, and `B` reads the corrupted file causing a segfault.

`A.lean`:
```lean
@[user_attribute] meta def my_attr : user_attribute unit name :=
{ name := `mine, descr := "test", parser := lean.parser.ident }
attribute [mine hello] nat
```
`B.lean`:
```lean
import .A
run_cmd my_attr.get_param `nat >>= tactic.trace
```

### Steps to reproduce:

* Save `A.lean` and `B.lean` in a new folder.
* Execute `lean --make` from there.
* Open `B.lean` in VSCode (take care not to open `A.lean` first, and make sure lean is set to "check visible files")
* Segfault occurs. If `A.lean` is opened first, or if `lean --make` was not run, VSCode is okay, because it doesn't use the `A.olean` file.

Alternatively, without using VSCode, you can trigger a segfault in `lean --make` as follows:

* Save `A.lean` and `B.lean` in a new folder.
* Execute `lean --make A.lean`, then `lean B.lean`. Segfault occurs.

PS: This bug is occurring currently in `mathlib`, and it's not fun to be constantly clearing the bad olean files.

**Comment by Kha** [comment]
Well, this is embarassing. It looks like we never actually serialize or deserialize user attribute data.

@leodemoura I left the following comment in the original implementation, which currently calls into a no-op: https://github.com/leanprover/lean/blob/4f66673fc20d4c663f0d3397efe73226d541c22b/src/library/attribute_manager.cpp#L146. I'm pretty sure we do need access to the environment in the deserializer to implement this. The cleanest way I can think of right now is to attach it as a deserializer extension.

**Comment by Kha** [comment]
> The cleanest way I can think of right now is to attach it as a deserializer extension.

~~I see now that extensions are stateless not context aware. Hm.~~
edit: ignore

**Comment by Kha** [comment]
On second thought, this was indeed trivial to fix. Sorry for the delay.
