### ISSUE TITLE
type-incorrect simp rewrites with recent change

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1888]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The commit f0f2fc42b6163c3b6d4366dfc0663a396582880a has broken many proofs in mathlib, and not in an easily fixable way - if I am reading this correctly it is a newly introduced bug. Here's an example:

```lean
variables {α : Sort*} {p : α → Prop} {P : ∀ x, p x → Prop} {a b c : Prop}

@[simp] theorem exists_prop : (∃ h : a, b) ↔ a ∧ b := sorry
@[simp] theorem exists_and_distrib_right : (∃x, p x ∧ b) ↔ (∃x, p x) ∧ b := sorry
@[simp] theorem and_imp : (a ∧ b → c) ↔ (a → b → c) := sorry
@[simp] theorem exists_imp_distrib : ((∃ x, p x) → b) ↔ ∀ x, p x → b := sorry

set_option trace.simplify.rewrite true
@[simp] theorem bex_imp_distrib : ((∃ x h, P x h) → b) ↔ (∀ x h, P x h → b) :=
by simp
-- 0. [simplify.rewrite] [exists_prop]: Exists (P x) ==> p x ∧ P x h
-- 0. [simplify.rewrite] [exists_and_distrib_right]: ∃ (x : α), p x ∧ P x h ==> (∃ (x : α), p x) ∧ P x h
-- 0. [simplify.rewrite] [and_imp]: Exists p ∧ P x h → b ==> Exists p → P x h → b
-- 0. [simplify.rewrite] [exists_imp_distrib]: Exists p → P x h → b ==> ∀ (x_1 : α), p x_1 → P x h → b
```

The first two rewrite steps are type-incorrect, because the variables `x` and `h` have escaped their context on the right hand side. Despite the apparently successful rewrites, the `simp` call fails due to no progress - I guess the type incorrect terms were recognized at a later stage. For comparison, the same file using 6eae78da01758b8c59db91e633369cc42b8c3dd2 yields the following trace (with selected info from rewrite failure trace):
```
0. [simplify.rewrite_failure] fail to match 'exists_prop':
Exists (P x)
=?=
∃ (h : ?x_0), ?x_1
0. [simplify.rewrite] [exists_imp_distrib]: (∃ (x : α), Exists (P x)) → b ==> ∀ (x : α), Exists (P x) → b
0. [simplify.rewrite] [exists_imp_distrib]: Exists (P x) → b ==> ∀ (x_1 : p x), P x x_1 → b
0. [simplify.rewrite] [iff_self]: (∀ (x : α) (x_1 : p x), P x x_1 → b) ↔ ∀ (x : α) (h : p x), P x h → b ==> true
```
### Versions

f0f2fc42b6163c3b6d4366dfc0663a396582880a thru a395c261652f48a0c7f8b7d1f2efe69a140022a9

**Comment by leodemoura** [comment]
Yes, the problem is due to two approximations tried at https://github.com/leanprover/lean/commit/f0f2fc42b6163c3b6d4366dfc0663a396582880a
They would simplify the bookkeeping in the new unification procedure.
Thanks for posting a small example demonstrating these approximations are not acceptable in practice.
