### ISSUE TITLE
malformed congr lemmas when input has a beta redex

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#1893]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Minimized from Sean Leather's lean-user post. I haven't thought too deeply about the factors that might be in play here; `unit'` is used because I think the `subsingleton` instance for `unit` changes the way `simp` approaches it.

```
inductive unit' | star
def T (x : unit') (e : x = unit'.star) (F : nat → unit') :
  @unit'.rec (λ (u : unit'), nat → unit') F x = F :=
by simp only [e]
```

```
kernel failed to type check declaration 'T' this is usually due to a buggy tactic or a bug in the builtin elaborator
elaborated type:
  ∀ (x : unit'), x = unit'.star → ∀ (F : ℕ → unit'), unit'.rec F x = F
elaborated value:
  λ (x : unit') (e : x = unit'.star) (F : ℕ → unit'),
    eq.mpr
      (id
         ((λ (a a_1 : (λ (u : unit'), ℕ → unit') x) (e_1 : a = a_1) (a_2 a_3 : (λ (u : unit'), ℕ → unit') x)
           (e_2 : a_2 = a_3), congr (congr_arg eq e_1) e_2)
            (unit'.rec F x)
            F
            ((λ (e_1 e_1_1 : (λ (u : unit'), ℕ → unit') unit'.star) (e_1_2 : e_1 = e_1_1) (n n_1 : unit')
              (e_2 : n = n_1), congr (congr_arg unit'.rec e_1_2) e_2)
               F
               F
               (eq.refl F)
               x
               unit'.star
               e)
            F
            F
            (eq.refl F)))
      (eq.refl F)
nested exception message:
type mismatch at application
  (λ (u : unit'), ℕ → unit') (unit'.rec e_1)
term
  unit'.rec e_1
has type
  Π (n : unit'), (λ (u : unit'), ℕ → unit') n
but is expected to have type
  unit'
```

**Comment by digama0** [comment]
I've narrowed it down even further to a specific `congr` lemma:
```
example (F : nat → Π (n : nat), (λ (u : nat), nat → nat) n) : true :=
by do
  ⟨_, p, _⟩ ← i_to_expr ```(F 0 0) >>= mk_specialized_congr_lemma,
  trace p,
  type_check p -- fail
```
Note the beta redex in the type of `F`. The `trace p` shows:
```
λ (a a_1 : ℕ) (e_1 : a = a_1) (n n_1 : ℕ) (e_2 : n = n_1),
  @congr ℕ ((λ (u : ℕ), ℕ → ℕ) (F a)) (F a) (F a_1) n n_1
    (@congr_arg ℕ (Π (n : ℕ), (λ (u : ℕ), ℕ → ℕ) n) a a_1 F e_1)
    e_2
```
Here `(λ (u : ℕ), ℕ → ℕ) (F a)` is malformed. Compare this with the case where the lambda is replaced with `T : ℕ → Type`:
```
λ (a a_1 : ℕ) (e_1 : a = a_1) (n : ℕ),
  @congr_fun ℕ (λ (n : ℕ), T n) (F a) (F a_1) (@congr_arg ℕ (Π (n : ℕ), T n) a a_1 F e_1) n
```
or when the beta redex is contracted:
```
λ (a a_1 : ℕ) (e_1 : a = a_1) (n n_1 : ℕ) (e_2 : n = n_1),
  @congr ℕ (ℕ → ℕ) (F a) (F a_1) n n_1 (@congr_arg ℕ (ℕ → ℕ → ℕ) a a_1 F e_1) e_2
```

**Comment by spl** [comment]
Thanks. I've confirmed this fixes the problem I reported.
