### ISSUE TITLE
Pretty substitution of backslashed keywords doesn't occur unless a space terminates the keyword

### ISSUE THREAD

**Issue by quaeler** [leanprover/lean3#1910]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

In the in-browser version of Lean, if one types `(f : \a \-> \b )` they end up with `(f : α → \b)`. The error highlighting parse recognizes the `\b)` to be illegal, but no substitution is made.

If one types `(f : \a \-> \b )` they end up with `(f : α → β )`

### Steps to Reproduce

1. Visit https://leanprover.github.io/live/ in the latest version of Chrome
2. Type `def foo (\a \b : Type) (f : \a \-> \b) (x : \a) : \b := f x`
3. Note that after substitutions, you see: `def foo (α β : Type) (f : α → \b) (x : \a) : β := f x`
4. On a new line, type `def bar (\a \b : Type) (f : \a \-> \b ) (x : \a ) : \b := f x`
5. Note that after substitutions, you see: `def bar (α β : Type) (f : α → β ) (x : α ) : β := f x`

**Expected behavior:** Substitution should occur once any non-letter is entered (i write in naïveté of the breadth of Lean - so perhaps that should be "... once any non-alphanumeric character is entered ..."

**Actual behavior:** It does not occur as such.

**Reproduces how often:** 100%

### Versions

Served by the server today.

**Comment by leodemoura** [comment]
Moved to `lean-web-editor` repository: https://github.com/leanprover/lean-web-editor/issues/5
