### ISSUE TITLE
Build shouldn't copy files into the source directory

### ISSUE THREAD

**Issue by nunoplopes** [leanprover/lean3#1918]
Right now the build system copies files into the lean source directory. This basically voids the possibility of compiling Lean with multiple compilers at the same time. For example, I can't compile Lean with both MSVC and Cygwin from the same folder.
For example, in `src/shell/CMakeLists.txt` we have the following:
```
    ADD_CUSTOM_COMMAND(TARGET lean
        POST_BUILD
        COMMAND "${CMAKE_COMMAND}" -E make_directory "${LEAN_SOURCE_DIR}/../bin"
        COMMAND "${CMAKE_COMMAND}" -E copy "${CMAKE_CURRENT_BINARY_DIR}/lean_with_path" "${LEAN_SOURCE_DIR}/../bin/lean"
        )
```

Here it copies the lean binary into `${LEAN_SOURCE_DIR}/../bin`.  This should happen.
It would be better to copy stuff to, e.g., `${CMAKE_BINARY_DIR}/bin`. All commands in `src/CMakeLists.txt` would need tweaking as well.

Would you consider changing this behavior?

**Comment by leodemoura** [comment]
Yes, the build copies the binary to `${LEAN_SOURCE_DIR}/../bin`. As far as I remember, there are two motivations for this decision:
- Make sure the relative position of the lean library and the binary is similar in the build directory and the installation directory. So, the lean binary can easily find the lean library when the `LEAN_PATH` environment variable is not set.
- Make sure we have a fixed place where the latest binary is located. This is useful when using the different IDEs. Keep in mind, a few users do not install lean to use it, they just build and use it from the build directory. 

> Would you consider changing this behavior?

I think your suggestion would solve a problem that very few people care (the possibility of compiling Lean with multiple compilers at the same time), and it would create a new problem (inconvenience). 

Here is a compromise:
- We add a cmake option that disables the post build command. As I said above, this command is only necessary if one wants to use lean from the build directory.
- By default, the option is enabled, and the build keeps working as it is now.
- Then, the few users, that care about building different versions at the same time, can disable the post command.

Remark: even if we do not execute the post command, we can create the installation package for Lean.

**Comment by nunoplopes** [comment]
I totally understand that my use case is not common :)
I'm fine with that solution.  I don't know that `lean --make` does, but it seems to be the only thing in the build that runs lean from the bin directory. If that's the case, it's easy to patch that one. And then we can disable the copying.

**Comment by leodemoura** [comment]
> I'm fine with that solution. I don't know that lean --make does,

It builds the lean standard library. 
Actually, this is another obstacle to have two simultaneous builds :(
`lean --make` compiles `.lean` files into `.olean`. It will be a mess if we have two of them running at the same time.
The solution I have described above would have to disable this step too.
Moreover, to have a working version in the end, the user would have to enable the option (that enables `lean --make`, and the binary copy) in one and only one of the builds.

**Comment by leodemoura** [comment]
I'm closing this issue. It is too much extra complication for a feature that will be rarely used.
