### ISSUE TITLE
ematch fails when there are two instance arguments which are different types of a type family

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean3#1940]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

`ematch` gets confused by multiple instance arguments on related types, as in this example:

```lean
class X (α : Type).
structure Y (α β) [X α] [X β] := (f : α → α)
@[ematch] theorem T (α β) [X α] [X β] (F : Y α β) (x : α) : F.f x = x := sorry
example (α β) [X α] [X β] (F : Y α β) (x : α) : F.f x = x :=
begin [smt] 
  ematch, -- doesn't work
end
```

which fails. The corresponding example with only one `[X ?]` argument works fine:

```lean
structure Y' (α) [X α] := (f : α → α)
@[ematch] theorem T' (α) [X α] (F : Y' α) (x : α) : F.f x = x := sorry
example (α) [X α] (F : Y' α) (x : α) : F.f x = x :=
begin [smt] ematch end -- works!
```

@gebner pointed out to me that:
> It seems like the computed pattern for the hinst_lemma is wrong (it requires that both typeclass instances are defeq):
```lean
set_option pp.all true
#eval hinst_lemma.mk_from_decl ``T >>= tactic.trace
```
which shows `[T, patterns: {{@Y.f ?x_0 ?x_1 ?x_2 ?x_2 ?x_4 ?x_5}}]`.

The relevant code is in [hinst_lemmas.cpp](https://github.com/leanprover/lean/blob/master/src/library/tactic/smt/hinst_lemmas.cpp), but well above my pay grade.

Obviously this is a contrived example, but the problem is pervasive in developing algebra (e.g. as soon as we want to talk about homomorphisms of any sort, we need to be able to talk about two groups/rings/modules, etc). I had successfully been using `ematch` to close many goals in my category theory library, but after following @digama0's advice to make `category` a typeclass, `ematch` stopped working.

### Versions

`Lean (version 3.3.1, commit 39270fd46f49, DEBUG)`

### Additional Information

I understand that no one may be interested in fixing this; I heard second hand that all the `ematch` code may be due for an overhaul someday. I thought I'd note this here in case anyone else runs into the issue, or anyone feels like helping me out on this one.

**Comment by leodemoura** [comment]
The `smt_tactic` framework will have to be redone in the future. It has serious technical and performance problems. I'm not even sure whether we will want to keep it in the future or not. It should be treated as experimental code. I strongly suggest users do not use it in long term projects. If they do, they should keep in mind that their projects will break in spectacular ways when we re-implement and/or delete the SMT framework.

**Comment by kim-em** [comment]
Thanks for the summary!

I've written my own solution to the problems I was using `ematch` for (essentially, searching the graph of possible rewrites, prioritizing based on edit distance between lhs and rhs). It's slow, but seems quite robust, and can output a sequence of `rw` invocations, so can be ripped out as necessary.
