### ISSUE TITLE
Typo in Tutorial

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover/lean3#1959]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Tutorial (3.3) says, "Indeed, in dependent type theory (and in Lean), the Pi construction is fundamental, and α → β is just notation for Π x : α, β when β does not depend on α."

I believe it should say, "Indeed, in dependent type theory (and in Lean), the Pi construction is fundamental, and α → β is just notation for Π x : α, β when β does not depend on x."

### Steps to Reproduce

See tutorial.

**Expected behavior:** [What you expect to happen]

See above.

**Actual behavior:** [What actually happens]

See above.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by digama0** [comment]
I think this issue is for https://github.com/leanprover/theorem_proving_in_lean/issues .

**Comment by kevinsullivan** [comment]
Oops, thanks. Moving. --Kevin
