### ISSUE TITLE
Import Isabelle theorems

### ISSUE THREAD

**Issue by mrmartin** [leanprover/lean3#1979]
This is not an issue, but a question regarding LEAN's versatility.

Is it possible to import [Isabelle/HOL](https://isabelle.in.tum.de) proofs into LEAN? How could this be achieved?

The benefit would be the availability of the [archive of formal proofs](https://www.isa-afp.org) within LEAN, which contains over 118'600 lemmas, many of which are very handy.

**Comment by Kha** [comment]
Hi,

Please use the [mailing list](https://groups.google.com/forum/#!forum/lean-user) or [chat room](https://leanprover.zulipchat.com) (which is much more active these days) for discussions around Lean.
