### ISSUE TITLE
I cannot find native_compiler.h and some other header files in src folder while building

### ISSUE THREAD

**Issue by NeverLandFly** [leanprover/lean3#1985]
https://github.com/leanprover/lean/blob/ceacfa7445953cbc8860ddabc55407430a9ca5c3/src/library/native_compiler/native_compiler.cpp#L30

**Comment by Kha** [comment]
Something is wrong with your build setup, this file is not actually included by CMake anywhere.

**Comment by NeverLandFly** [comment]
I have found the right CMake file. Thanks.
