### ISSUE TITLE
Autocomplete is incomplete

### ISSUE THREAD

**Issue by mrakgr** [leanprover/lean3#2001]
```
import data.rat
import data.vector

def E {n} (l : vector rat n) : rat := list.foldl (+) 0 l.val / n
```

I can't get `foldl` to show up in autocomplete. That same goes for `val`. `data.vector` and `data.rat` are from the `mathlib`. I am using VS Code with Windows 10. Lean version 3.42.

**Comment by kim-em** [comment]
@mrakgr, this is the repository for the Lean 3, which
* is frozen while development on Lean 4 takes place
* does not include any of the VS Code front end.

Can you close this and raise the issue either at https://github.com/leanprover/vscode-lean/issues, or in a thread at https://leanprover.zulipchat.com/?
