### ISSUE TITLE
[Linux]: setup PPA for lean

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#223]
- https://github.com/ruediger/VobSub2SRT/blob/master/CMakeModules/UploadPPA.cmake

**Comment by soonhokong** [comment]
@leodemoura, here are the [instructions](http://developer.ubuntu.com/publish/apps/other-forms-of-submitting-apps/ppa) for creating a [launchpad](https://launchpad.net) account. Please let me know your account name when you finished "Creating your PPA" section (step 1 ~ step 10). I'll add you to the [leanprover team PPA](https://launchpad.net/~leanprover) (no rush, of course).

**Comment by leodemoura** [comment]
@soonhokong I did it. My launchpad id is: leonardo-b

**Comment by soonhokong** [comment]
@leodemoura, thanks. I just added you to the team member as an admin.

**Comment by soonhokong** [comment]
FYI, I fixed the problem that I mentioned on 14.04. Now, we support both of 12.04 and 14.04:

https://launchpad.net/~leanprover/+archive/ubuntu/lean

**Comment by leodemoura** [comment]
Great!

**Comment by leodemoura** [comment]
@soonhokong I installed lean using `sudo apt-get install lean`. It seems I only got the binary (i.e., no library, nor emacs mode).

**Comment by soonhokong** [comment]
@leodemoura, yes, that is the case for now. I'm looking at how coq package is handling the similar issues: https://launchpad.net/ubuntu/+source/coq

**Comment by soonhokong** [comment]
Following coq's convention, I'd like to suggest the following:
- /usr/share/emacs/site-lisp/lean: `*.el` files at `src/emacs`
- /usr/lib/lean: All `*.lean` and `*.olean` files under `library/` + `library/.project` + `library/TAGS`
- /usr/share/doc/lean: files at `doc`.

We do need to relocate the contents of `library/TAGS` file since it contains build-specific absolute paths.

@leodemoura, do we need the same relocation process for `*.olean` files? Do you think it's good idea to add `*.clean` files?

FYI, here is a complete list of locations of installed coq files:

``` bash
/usr/
/usr/share/
/usr/share/coq/
/usr/share/coq/coqvars.mk
/usr/share/man/
/usr/share/man/man1/
/usr/share/man/man1/coqdoc.1.gz
/usr/share/man/man1/coq_makefile.1.gz
/usr/share/man/man1/coqtop.opt.1.gz
/usr/share/man/man1/coqchk.1.gz
/usr/share/man/man1/coqtop.1.gz
/usr/share/man/man1/coqtop.byte.1.gz
/usr/share/man/man1/coqwc.1.gz
/usr/share/man/man1/coqdep.1.gz
/usr/share/man/man1/coqc.1.gz
/usr/share/man/man1/gallina.1.gz
/usr/share/man/man1/coq-tex.1.gz
/usr/share/texmf/
/usr/share/texmf/tex/
/usr/share/texmf/tex/latex/
/usr/share/texmf/tex/latex/misc/
/usr/share/texmf/tex/latex/misc/coqdoc.sty
/usr/share/doc/
/usr/share/doc/coq/
/usr/share/doc/coq/CREDITS.gz
/usr/share/doc/coq/README.Debian
/usr/share/doc/coq/README
/usr/share/doc/coq/NEWS.Debian.gz
/usr/share/doc/coq/changelog.Debian.gz
/usr/share/doc/coq/copyright
/usr/share/pixmaps/
/usr/share/pixmaps/coq.xpm
/usr/share/menu/
/usr/share/menu/coq
/usr/share/emacs/
/usr/share/emacs/site-lisp/
/usr/share/emacs/site-lisp/coq/
/usr/share/emacs/site-lisp/coq/coq-font-lock.el
/usr/share/emacs/site-lisp/coq/coq-inferior.el
/usr/share/emacs/site-lisp/coq/coq-syntax.el
/usr/share/emacs/site-lisp/coq/coq-db.el
/usr/share/emacs/site-lisp/coq/coq.el
/usr/bin/
/usr/bin/gallina
/usr/bin/coqdep
/usr/bin/coq-tex
/usr/bin/coqtop.opt
/usr/bin/coqdoc
/usr/bin/coqc
/usr/bin/coq_makefile
/usr/bin/coqchk.opt
/usr/bin/coqtop.byte
/usr/bin/coqwc
/usr/lib/
/usr/lib/coq/
/usr/lib/coq/states/
/usr/lib/coq/states/initial.coq
/usr/lib/coq/tools/
/usr/lib/coq/tools/coqdoc/
/usr/lib/coq/tools/coqdoc/coqdoc.sty
/usr/lib/coq/tools/coqdoc/coqdoc.css
/usr/lib/coq/plugins/
/usr/lib/coq/plugins/micromega/
/usr/lib/coq/plugins/micromega/csdpcert
/usr/lib/emacsen-common/
/usr/lib/emacsen-common/packages/
/usr/lib/emacsen-common/packages/install/
/usr/lib/emacsen-common/packages/install/coq
/usr/lib/emacsen-common/packages/remove/
/usr/lib/emacsen-common/packages/remove/coq
/etc/
/etc/emacs/
/etc/emacs/site-start.d/
/etc/emacs/site-start.d/50coq.el
/usr/share/man/man1/coqchk.opt.1.gz
/usr/bin/coqchk
/usr/bin/coqtop
```

**Comment by soonhokong** [comment]
Let me add a few things:
- `usr/` is a default installation prefix here. If a user specifies other location such as `usr/local`, cmake will handle them accordingly (i.e. emacs stuff goes into `usr/local/share/emacs/site-lisp/lean`). It means that we can use the same setting with homebrew.
- We can add a script to start `lean-mode` at `/etc/emacs/site-start.d`

**Comment by leodemoura** [comment]
I like your suggestion.

> do we need the same relocation process for *.olean files?

No, all links in .olean files are relative to `LEAN_PATH`.

BTW, if `LEAN_PATH` is not set, then `lean` assumes it is `.:[exe-location]/../library`
We have to change it to support the new directory structure.
I see the following options.
1- `lean` becomes a shell script which sets `LEAN_PATH` (if not set), and then invokes the real executable
2- We modify `lean` executable to use `.:[exe-location]/../library:[exe-location]/../lib/lean' as the default`LEAN_PATH`.

**Comment by soonhokong** [comment]
> 2- We modify lean executable to use .:[exe-location]/../library:[exe-location]/../lib/lean' as the defaultLEAN_PATH`.

I think this one is better since it can cover common cases on Linux and OSX. I'll make this change.

**Comment by soonhokong** [comment]
- 4a119a04243551bd9cd85ac0b771191f87b4cd35 : build TAGS file which uses relative paths.
- e40ef9f6c583b77df97f0d94db5c03defc7d0cd9 : add `[exe-location]/../lib/lean` to `LEAN_PATH`.

**Comment by soonhokong** [comment]
@leodemoura, do you think it's good idea to add *.clean files?

**Comment by leodemoura** [comment]
> @leodemoura, do you think it's good idea to add *.clean files?

We should ignore the .clean files. They are only needed if someone wants to change the library. If they decide to do it, then `.clean` files will be automatically generated.

**Comment by soonhokong** [comment]
I see. Thank you!

**Comment by soonhokong** [comment]
Hi @leodemoura,

I created a repository [leanprover/ppa-updater](https://github.com/leanprover/ppa-updater). Could you run it on a virtual machine running Ubuntu 14.04 LTS? Please wrap it with the git-change detection code since it always creates new packages and upload them.

As you can see at https://launchpad.net/~leanprover/+archive/ubuntu/lean, the script creates six builds:
- Ubuntu Releases: precise (12.04 LTS), trusty (14.04 LTS), and utopic (14.10)
- Arch: i386 and amd64

Of course, just let me know if you want me to run it periodically at CMU.

**Comment by leodemoura** [comment]
Awesome! I will setup the VM on Monday.

Thanks,
Leo

**Comment by soonhokong** [comment]
Dear @leodemoura, it seems this one can be closed now, right?

**Comment by leodemoura** [comment]
Yes, I agree.

Best,
Leo
