### ISSUE TITLE
lean-mode: increase robustness

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#263]
1- We should invoke `SYNC` whenever the content of `lean-server-show` and the current buffer are not equal.

2- We should invoke `SYNC` whenever we keep getting `[stale]` info messages for more than `n seconds` AND
      - we haven't SYNC since the user modified the buffer
      - `lean --server` is not busy (we should have a query to test whether it is busy or not)

**Comment by soonhokong** [comment]
@avigad and @fpvandoorn, Leo and I are investigating this issue. I just made a small patch to force lean-server to be restarted when some constraints are met. 

Could you try the new one? I'd like to know how often you get into a situation where you have to restart lean-server manually.

**Comment by avigad** [comment]
I have not hard to restart lean-server manually in a long time. But I haven't been paying attention to whether type information has always been reported. I will now pay attention, and let you know if/when i have to restart lean-server.

**Comment by soonhokong** [comment]
@avigad, thank you!

**Comment by avigad** [comment]
P.S. That task is open-ended -- you may never get a report from me or Floris -- so I think it makes sense to close the issue until the problem recurs. We can reopen it then.

**Comment by soonhokong** [comment]
@avigad, I see.

We do have some more things to implement for this issue. After implementing and testing them on our side, we will close this one. However, as you said, please feel free to open a new issue regarding robustness issues.

**Comment by fpvandoorn** [comment]
Very nice. I had to restart Lean-mode yesterday, so I'll check whether it still happens to me after this commit.

**Comment by fpvandoorn** [comment]
I still have to restart lean mode occasionally after the change. 
But only a couple times a day, once every 1-2 hours. 
Usually I notice it when auto-completion says `no completion found` even though there should be some.

**Comment by soonhokong** [comment]
@fpvandoorn, thank you. @rlewis1988 also sent me some information. I'll implement a fix tonight.

**Comment by leodemoura** [comment]
I'm closing this issue, we are not going to use the emacs <-> lean protocol in `lean3`.
