### ISSUE TITLE
universe polymorphic inductive structures

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#297]
When we write 

```
inductive nat : Type := zero, succ : nat -> nat
```

we get a `nat` which lives in `Type₁`. However, when we write

```
inductive nat2 : Type₊ := zero, succ : nat2 -> nat2
```

We get `nat2.{l_1} : Type.{succ l_1}`. This second definition looks more desirable: we don't have to lift our nat in Type₁ to higher types. In the file [trunc.lean](https://github.com/fpvandoorn/lean/blob/master/library/hott/trunc.lean#L42) the definition of homotopy-n-types only accepts `A : Type₁` which sounds like a restriction which could lead to problems later on. I _think_ this is caused by the fact that `path` lives in `Type₁`.

So my question: is it possible that whenever we write `inductive foo : Type := ...` Lean will try to create a universe polymorphic `foo` for all positive universe levels (which - I think - is always the desired behavior). If this is impossible / hard / low priority, is it an idea to replace all `inductive foo : Type := ...` by `inductive foo : Type₊ := ...` in the library, so that we still get the universe polymorphic inductive types?

**Comment by leodemoura** [comment]
> So my question: is it possible that whenever we write inductive foo : Type := ... Lean will 
> try to create a  universe polymorphic foo for all positive universe levels (which - I think - 
> is always the desired behavior). 

It is possible. However, I think it would overwhelm the system with universe level parameters.
For example, suppose we define a record with 3 nats. If the user doesn't say anything, he would get three universe level parameters. I see the following workarounds:

1) Define a simpler version based on the polymorphic one: `nat1 := nat.{1}`.
Perhaps, we should call them `nat := poly_nat.{1}`. 

2) The user provides explicit universes when declaring the record.

```
record point3.{l} : Type.{l} :=
(x y z : nat.{l})
```

This one is really bad for novice users that probably don't even want to know that universes exist.

3) Have two `nat` types: polymorphic and non-polymorphic. I didn't check carefully, but the file `trunc.lean` doesn't seem to need a lot of constructions from the nat library.

**Comment by fpvandoorn** [comment]
Ah, the extra universe variables could indeed be problematic. Now I'm not sure anymore whether we want polymorphic universes: usually `nat : Type.{1}` will do, so always having to do extra work just for the few times where you need "higher nats" might be excessive. On the other hand, if you need `nat` in `Type.{7}` then you don't want to copy-paste the nat-library for this new universe level, and inserting lifts might also be problematic (does lift commute with succ, add, leq, etc. and do you have to do an extra step every time?)

About your workarounds, (1) and (3) are the same idea, right? This might be useful, but still: we probably want to develop the library for `poly_nat` because that's more general, so when do we want to transition our library to `nat`/`nat1`? About (2): I agree it's not pretty when you have to declare universe levels that way. However, novice users are less likely to push the capabilities of Lean to its limits (if you use coercions, type classes and lots of implicit arguments you're not a novice user anymore :-) ), so it's probably not that bad if a novice forgets them.

(indeed, so far `trunc.lean` only uses the definition of `nat`)

**Comment by leodemoura** [comment]
> On the other hand, if you need nat in Type.{7} then you don't want
> to copy-paste the nat-library for this new universe level, and inserting lifts might also be problematic 

We don't have to create multiple copies: one would be enough (the polymorphic one).
For most applications, the current nat (in Type.{1}) is good enough. 
I think there are very few cases where we need nat in another universe. For these cases, we can use the polymorphic one.

> About your workarounds, (1) and (3) are the same idea, right? 

In (1), we define `poly_nat`, and then just define

```
   definition nat := poly_nat.{1}
```

There is no copying going on.

In (3), we do really have two copies of the `nat` library. 
(3) is hackish but it is more efficient. The kernel does not have to keep moving the universe `1` around when computing with `nat`.

> we probably want to develop the library for poly_nat because that's more general,
> so when do we want to transition our library to nat/nat1

Yes, we can develop `poly_nat`. Let's wait for the algebra library. After it is done, we can reuse many results from there.

> I agree it's not pretty when you have to declare universe levels that way. 
> However, novice users are less likely to push the capabilities of Lean to its limits

I was not clear. When I said "novice", I was referring to users that only use concrete structures such as `int`, `rational` and `real`. These users may be currently using systems such as Isabelle and Z3.
We can say these users "live" in `Type.{1}`, they never go beyond that.
These users may create records of `real`s (example: a point in 3 dimensional space).
Then, they can use it to model engineering problems with hundreds of these points. 
If we make `real`/`nat`/`int` universe polymorphic (by default), then they would have to pay the price of having a lot of universe parameters floating around for nothing.

**Comment by fpvandoorn** [comment]
Yes, let's wait for the algebra library, and when we reuse results from there decide how we exactly want to do it. 

It's frustrating that even though (1) and (3) are basically the same thing from a mathematical point of view, in one of the cases you get code duplication, and in the other case you get inefficiencies. But I can imagine this happens all the time in computer science: making the trade-off between code duplication or inefficiencies.

**Comment by leodemoura** [comment]
> But I can imagine this happens all the time in computer science: making the trade-off between code
> duplication or inefficiencies.

Yes, it happens all the time, and it generates a lot of "anxiety".

**Comment by leodemoura** [comment]
Let's close this issue. I think the current approach is working well, and working with lifts is not that bad.
Feel free to reopen the issue.

**Comment by fpvandoorn** [comment]
I agree. Every inductive type which doesn't have any parameters can live in the lowest universe, and this doesn't seem to cause any problems. (I don't think I can re-open issues in this repository, though :-) )
