### ISSUE TITLE
coercion to universe polymorphic type

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#298]
Currently, when I define the following inductive type in a polymorphic way

```
inductive trunc_index : Type₊ :=
minus_two : trunc_index,
trunc_S : trunc_index → trunc_index

-- trunc_index.{l_1} : Type.{succ l_1}
```

the map with the following type

```
nat_to_trunc_index.{l_1} : ℕ → trunc_index.{l_1}
```

is not allowed to be a coercion. Is it expensive to allow this?

It does work if I make `nat` also universe polymorphic, and restrict the function from `nat.{l}` to `trunc_index.{l}`. Is that the way to go?

**Comment by leodemoura** [comment]
So far, our coercions do not generate metavariables. All the information needed to apply it is "stored" in the source type. Here are the acceptable forms (including universe levels):

```
   coe.{ls} : Pi (x_1 : A_1) ... (x_n : A_n) (y: C.{ls} x_1 ... x_n), D.{us} t_1 ... t_m
   coe.{ls} : Pi (x_1 : A_1) ... (x_n : A_n) (y: C.{ls} x_1 ... x_n), Type.{u}
   coe.{ls} : Pi (x_1 : A_1) ... (x_n : A_n) (y: C.{ls} x_1 ... x_n), (Pi x : A, B x)
```

Here, `ls` is a sequence of universe level parameters; `us` a sequence of universe level expressions; and `u` a universe expression. Given a type `C.{vs} t_1 ... t_n` we can "fill" all the coercion `coe` arguments (including universe parameters) using just the information in the type.

To support this example, we need to create a universe metavariable for `l_1`.  In the general case, we may also have to generate unification constraints. I have to go over the code base and investigate what would be affected.

**Comment by fpvandoorn** [comment]
Since we postponed #297, this can probably also be postponed. It is not clear whether we ever need it.
