### ISSUE TITLE
[lean-mode] minibuffer shows wrong type after abstraction

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#302]
When hovering over a character just after an abstraction (lambda, forall, sigma, ..), Flycheck shows "nonsense".

```
have K : ∀ (r : x ≈ y), path_contr x y ≈ r, from (λ r, path.rec_on r !concat_Vp),
                       ^^
-- output: [have] r : A


---


is_trunc.mk (λ x y,   is_trunc.to_internal)
                   ^  ^
-- output: [(] truncation.is_trunc.mk : is_trunc_internal n .+1 A → is_trunc n .+1 A
```

In the above examples, when your point is on the character above `^` (so the first space after the comma, or the first letter of the next object), you get the wrong output.

(examples are from [trunc.lean](https://github.com/fpvandoorn/lean/blob/master/library/hott/trunc.lean) in my library but it happens in every file)

**Comment by leodemoura** [comment]
@soonhokong `lean --server` is producing the correct information. 
I believe the bug is in the Emacs code. Perhaps, it is related to the new feature you added for displaying the current proof state when using tactics.

**Comment by soonhokong** [comment]
@fpvandoorn, I believe the bug is still there. Could you give me new instructions to reproduce the bug? Because of the restructuring of the library, I think it's not the same anymore. I'll fix it this time.

**Comment by fpvandoorn** [comment]
Yes, the bug is still here. Steps to reproduce the bug is to move your point just behind the comma after a binder, more specifically either the space directly after the comma, or the first letter after the comma.

Examples (in an empty file; move the point to the character above `^`):

```
check (ΣABC:Type, ABC)
                 ^^
check sigma (fun a, a)
                   ^^^
```

**Comment by soonhokong** [comment]
@fpvandoorn, thanks! I'll fix it.

**Comment by fpvandoorn** [comment]
Currently the minibuffer shows nothing at all where it would previously show something strange. Is this intended? It might be annoying if you want to see the type of the term in something like

```
check sigma (fun a, a)
```

**Comment by soonhokong** [comment]
@fpvandoorn, it should be fixed now.
