### ISSUE TITLE
polish `FINDG`

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#336]
Emacs interfaces allows us to auto-complete a placeholder by pressing TAB over a `_`.
This feature is implemented by using the `FINDG` command in `lean --server`.
Some issues:
1- sorting results
2- taking the local context into account

@soonhokong I don't remember how to provide filters (e.g., "+lt -int") in the Emacs user interface.

**Comment by soonhokong** [comment]
I didn't implement it yet. I created an issue for this #339
