### ISSUE TITLE
add tactic "diagnostic" mode

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#348]
When it is on, a tactic will output messages describing why it failed.

**Comment by leodemoura** [comment]
@fpvandoorn Is this feature useful for you?
Right now, we don't get any feedback when a tactic fails. Basically, we just see the goal that could not be solved. Is this a big deal for you?

**Comment by fpvandoorn** [comment]
Yes, this would be super helpful. Especially with `apply` and `exact`, it is useful to see exactly where the type and the expected type differ.
