### ISSUE TITLE
tactics + class inference

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#360]
There are some problems with class inference when doing tactic proofs. In the following example, `apply foo` should automatically synthesize the subgoal `H` (but there should also be an apply which adds `H` as a subgoal, maybe `rapply` and `fapply` should do that).

```
structure is_trunc [class] (A : Type) : Type

theorem foo (A : Type) [H : is_trunc A] (B : Type) : B := sorry

theorem bar [H : is_trunc false] : false :=
by apply foo
```

A similar error happens in the following (not quite minimal) example:

```
import hott.trunc open truncation
--structure is_contr [class] (A : Type) : Type

context
parameters {P : Π(A : Type), A → Prop}

definition my_contr {A : Type} [H : is_contr A] (a : A) : P A a := sorry

definition foo2
(A : Type)
(B : A → Type)
(a : A)
(x : B a)
(H : Π (a : A), is_contr (B a))  --(H : is_contr (B a))
  : P (B a) x :=
by apply my_contr
--by apply (my_contr x)
--!my_contr
end
```

The given tactic fails, but the other two commented out proofs work. Also, replacing `H` by the commented out `H` works. 
Finally, if you define `is_contr` here as class instead of importing `hott_trunc` there is still an error message, but it shows explicitly that it cannot figure out a term of type `is_contr ?M_1`. 

It looks like the arguments of `my_contr` are elaborated in the wrong order: it tries to synthesize `H` before knowing `A`

**Comment by leodemoura** [comment]
This issue is related to #361. 
The `apply t` is executed in two steps.
First we elaborate `t` independently of the goal. `t` is elaborated by the elaborator.
Then, the tactic tries to unify `t`'s type with the goal. 
The class-instance constraints are solved by the elaborator.
It was giving up on the class-instance constraint instead of postponing them.
I fixed this part.
Now, we can use a workaround in the second example

```
apply (@my_contr _ _)
```

To solve the first example in your message I had to write.

```
apply (@foo false _)
```

If we find a good way to decide how many `_` must be inserted, then we can add the `_`'s before invoking the elaborator, and we will be able to write `apply my_contr`.

**Comment by fpvandoorn** [comment]
My first example was maybe a bit too convoluted. Something closer to actual practice would be the following, and that works with the workaround (but not without giving the underscore).

```
structure is_trunc [class] (A : Type) : Type
theorem foo (A : Type) [H : is_trunc A] : A := sorry
theorem bar [H : is_trunc false] : false := by apply (foo _)
```

I do not yet see why the underscores matter for the term synthesis.

Also, in some tactic proofs you want to actually give an explicit proof for the argument `H` is which is between square brackets. In some proofs where I wanted to give `H` explicitly, the elaborator gave that "magically" as extra subgoal. Does the elaborator first try to figure the term out by itself, and if that fails add it as goal? Why doesn't it do that in these examples?

**Comment by leodemoura** [comment]
> I do not yet see why the underscores matter for the term synthesis.

The tactic module is not "aware" that type-classes exist.
So, when the apply tactic creates a metavariable, it does not associate a constraint to synthesize it using class-instance resolution.
When we write `apply (@my_contr _ _)`, the elaborator first elaborates the term `@my_contr _ _`, and then sends it to the `apply` tactic. The elaborator is in the frontend, and it performs the class instance resolution.

> Also, in some tactic proofs you want to actually give an explicit proof for the argument H is which is between square brackets. In some proofs where I wanted to give H explicitly, the elaborator gave that "magically" as extra subgoal. Does the elaborator first try to figure the term out by itself, and if that fails add it as goal? Why doesn't it do that in these examples?

Could you post one of these cases? It will help to describe what is going on.

Thanks.

**Comment by fpvandoorn** [comment]
> Could you post one of these cases? It will help to describe what is going on.

For example the proofs that [sigma-types](https://github.com/fpvandoorn/lean/blob/master/library/hott/types/sigma.lean#L353-L373) or [W-types](https://github.com/fpvandoorn/lean/blob/master/library/hott/types/W.lean#L138-L151) preserve n-truncation. I used the style to use `apply` when I wanted to let the elaborator synthesize the term and `fapply` when I wanted to provide the term myself. 
Maybe we can make a functional difference between `apply` and `fapply` in this way. This is in line with the current use of `fapply`: add a new goal for every hypothesis you cannot solve.

> The tactic module is not "aware" that type-classes exist.

Ah, I see. So `apply` is not aware of the distinction between the different parentheses? It will just solve all arguments it can, and add sufficiently many goals so that it can solve the rest?

Would it be hard to add an extra procedure to solve all unsolved goals using type classes which were marked as such? Because determining the amount of underscores needed is hard (as we see in #361).

**Comment by leodemoura** [comment]
> Ah, I see. So apply is not aware of the distinction between the different parentheses? It will just solve all arguments it can, and add sufficiently many goals so that it can solve the rest?

Yes.

I will try to change that. I will reorganize the code that performs class instance resolution. 
The goal is to make it accessible by the tactic module (and `apply` tactic).

> Would it be hard to add an extra procedure to solve all unsolved goals using type classes which were marked as such?

After I reorganize the code it will. Right now, the class-instance resolution is part of the elaborator.
