### ISSUE TITLE
apply fails if conclusion is a function space

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#361]
```
variables {P Q R : Prop}
theorem foo (H : P → Q → R) (x : P) : Q → R :=
begin
  apply H, -- error
  exact x
end
```

the goal `Q → R` should not only be unified with the "final codomain" `R` of `H`, but also with "intermediate codomains" `Q → R` and `P → Q → R`, if possible.

**Comment by leodemoura** [comment]
I think we need yet another `apply` :-(
See: https://github.com/leanprover/lean/blob/master/src/library/tactic/apply_tactic.cpp#L73-L82
The problem is `apply` commands that are used with eliminators.

```
apply (path.rec_on q)
apply (sigma.destruct p)
```

Suppose the goal is `A -> B`.
Then, we can interpret the tactics above as

```
fun x : A, path.rec_on q x   -- i.e, (path.rec_on q)
```

OR

```
path.rec_on q ?M
```

In other systems, there are special commands for applying recursors/eliminators.
The second interpretation is what we usually want for recursors. 
The first interpretation is what we want in your example.

**Comment by fpvandoorn** [comment]
I see the problem. I dislike a new flavor of `apply` just to address this issue; it's not that important (in the proof where this came up, I could actually replace `apply H` by `exact H`). 

Would it work if we first try to unify the conclusion `Q → R` with the "final codomain" of `H` (i.e. `R`), and only if that fails, backtrack and try to add some hypotheses of `H` in the unification? Then all the induction proofs will work on the first try and choose the correct interpretation, but we can still get my example to work. 
It might lead to some unexpected behavior is some cases, though.

**Comment by leodemoura** [comment]
> It might lead to some unexpected behavior is some cases, though.

Yes, I'm also concerned about that.

BTW, I also want to minimize the number of different `apply` tactics.
I think we can safely get rid of `rapply`. Nobody uses it. 

What about the `elim` tactic suggested by McBride. 
It is like the new `cases` tactic + inductive hypothesis. 
It seems useful because it automates a lot of boilerplate code (e.g., reverts+generalize+subst). 
Have you tried the new `cases` tactic? It helps a lot when we are working with indexed families.

**Comment by avigad** [comment]
Coq has a suite of these -- elim, case, induct, destruct:

  https://coq.inria.fr/refman/Reference-Manual011.html#toc58

**Comment by fpvandoorn** [comment]
> BTW, I also want to minimize the number of different `apply` tactics.
> I think we can safely get rid of `rapply`. Nobody uses it.

I agree. I think that in all cases you want to use `rapply` either `apply` or `fapply` is more useful. I also agree that minimizing the number of tactics is useful. 

What we could do is add options to tactics. Coq has a wealth of them, [for example](https://coq.inria.fr/refman/Reference-Manual011.html#@tactic109): `rewrite foo` `rewrite <- foo` `rewrite foo in H` `rewrite foo at 1` `rewrite foo by *tactic*` `rewrite foo1, foo2, foo3` `rewrite !foo` `rewrite foo!` `rewrite ?foo` `rewrite foo?` `erewrite foo`. 

I think such options are useful to have eventually. Then maybe we could use something have something like `apply H at n` where `n` specifies what part of `H` should be unified with the conclusion.

> Have you tried the new cases tactic? It helps a lot when we are working with indexed families.

No, I haven't worked with indexed families lately, but the examples you sent look really impressive!

**Comment by leodemoura** [comment]
Closed by https://github.com/leanprover/lean/commit/9ba8b284a1e3bb5ccd77c5c38e50bcbb637eb2eb

@fpvandoorn @avigad @javra The fix affects some files.
Now, `apply` is used the "first interpretation" described above.
I added the tactic `eapply` (it implements the old interpretation).
We will be able to delete `eapply` as soon as we have an `induction` tactic.
Note that in the commit above, the affected files were all using `apply` + `rec_on` to simulate the induction tactic.

**Comment by fpvandoorn** [comment]
This is a good change. The new apply is a better default.

> We will be able to delete `eapply` as soon as we have an induction tactic.

It might be useful to keep it a little longer, because of user-defined recursors, like [`homotopy.rec_on`](https://github.com/leanprover/lean/blob/9ba8b284a1e3bb5ccd77c5c38e50bcbb637eb2eb/hott/init/funext.hlean#L258-259) (which occurs once in your commit). This will probably come up more often in the future with all the user-defined recursors of HITs. So `eapply` is probably useful until we can extend both `cases` and `induction` with our own definitions.

**Comment by fpvandoorn** [comment]
>  We will be able to delete `eapply` as soon as we have an `induction` tactic.

This comment is old, but now that we have an `induction` tactic, I wanted to make a small remark on it.

I don't think we can (ever) remove `eapply`. I currently still use it in two cases:
- If I want to induct on something which is not a variable. Example:
  `eapply nat.rec_on (n + m),`
- If I want to use something which looks like a recursor, but which is not supported as one (such as `rec_on_ua2`). However, this is a rare case, since almost all recursor-like theorems _are_ supported as recursors.

**Comment by leodemoura** [comment]
> This comment is old, but now that we have an induction tactic, I wanted to make a small remark on it.

I agree. 
I also realized this problem when you mentioned `rec_on_ua2` at #492
