### ISSUE TITLE
compiler core-dumping (when defining structures?)

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#385]
The following give me a core dump with message `src/tcmalloc.cc:277] Attempt to free invalid pointer 0x7fffd7100118`. I run lean without memory restrictions... Can anyone reproduce this?

```
import types.sigma types.prod
import algebra.binary algebra.group
open eq eq.ops

namespace path_algebra

variable {A : Type}

structure distrib [class] (A : Type) extends has_mul A, has_add A :=
(left_distrib : ∀a b c, mul a (add b c) = add (mul a b) (mul a c))
(right_distrib : ∀a b c, mul (add a b) c = add (mul a c) (mul b c))

structure mul_zero_class [class] (A : Type) extends has_mul A, has_zero A :=
(zero_mul : Πa, mul zero a = zero)
(mul_zero : Πa, mul a zero = zero)

structure zero_ne_one_class [class] (A : Type) extends has_zero A, has_one A :=
(zero_ne_one : zero ≠ one)

structure semiring [class] (A : Type) extends add_comm_monoid A, monoid A,
  distrib A, mul_zero_class A, zero_ne_one_class A

end path_algebra
```

**Comment by avigad** [comment]
I get this same behavior:

-_\- mode: compilation; default-directory: "~/Dropbox/Projects/Lean/" -_-
Compilation started at Tue Jan 6 13:47:14 ~/projects/lean/bin/lean
-Dpp.width=80 /home/avigad/Dropbox/Projects/Lean/test.hlean **\* Error in
`/home/avigad/projects/lean/bin/lean': free(): invalid next size (fast):
0xbfe52e18 **\* Compilation aborted (core dumped) at Tue Jan 6 13:47:14
