### ISSUE TITLE
renaming

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#387]
I'd like to request/suggest the following name changes in init.nat, in namespace nat:

is_inhabited -> inhabited
has_decidable_eq -> decidable_eq
lt.succ_of_lt -> succ_lt_succ
lt.of_succ_lt -> lt_of_succ_lt
lt.of_succ_lt_succ -> lt_of_succ_lt_succ
lt.is_decidable_rel -> lt.decidable_rel
le.of_lt -> le_of_lt
le.of_eq_or_lt -> le_of_eq_or_lt
le.is_decidable_rel -> le.decidable_rel
le.step -> le_succ_of_le (this can be an alternative name)
lt.of_le_of_lt -> lt_of_le_of_lt
lt.of_lt_of_le -> lt_of_lt_of_le
lt.of_lt_of_eq -> lt_of_lt_of_eq
le.of_le_of_eq -> le_of_le_of_eq
lt.of_eq_of_lt -> lt_of_eq_of_lt
le_of_eq_of_leq -> le_of_eq_of_le
sub.lt -> sub_lt

I don't feel strongly about is_inhabited and is_decidable, but I think in most places we write inhabited and decidable, and we should be consistent.

Regarding the dots: I have only been using them for axiomatic names, like mul.assoc and succ.inj. I think it is easier if the user doesn't have to guess whether a theorem name is le.of_lt or le_of_lt. I have found it is really pleasant to just write down the conclusion with underscores.

I will probably have some opinions about "max" later on, but I will wait until we implement algebraic versions.

**Comment by leodemoura** [comment]
> is_inhabited -> inhabited

I'm fine with `nat_inhabited` and `nat.is_inhabited`.
I think `nat.inhabited` may generate confusion. For example `inhabited` in the namespace `nat` would be overloaded: it may be the type `inhabited` or the constant `inhabited`.

BTW, I'm also wondering whether `nat_inhabited` instance should be in the top-level or not.
I think it should. The instance should be available even if we do not open the namespace `nat`.
What do you think?

> Regarding the dots: I have only been using them for axiomatic names, like mul.assoc and succ.inj. I think it is easier if the user doesn't have to guess whether a theorem name is le.of_lt or le_of_lt. I have found it is really pleasant to just write down the conclusion with underscores.

I agree.

**Comment by avigad** [comment]
On Tue, Jan 6, 2015 at 9:21 PM, Leonardo de Moura notifications@github.com
wrote:

> is_inhabited -> inhabited
> 
> I'm fine with nat_inhabited and nat.is_inhabited.
> I think nat.inhabited may generate confusion. For example inhabited in
> the namespace nat would be overloaded: it may be the type inhabited or
> the constant inhabited.
> 
> Couldn't we make it protected, so the name remains nat.inhabited even if
> the namespace is open? If not, either is fine with me.
> 
> BTW, I'm also wondering whether nat_inhabited instance should be in the
> top-level or not.
> I think it should. The instance should be available even if we do not open
> the namespace nat.

I am not sure, but I think so. We might want to infer that some compound
type that depends on nat is inhabited, even if we are not working with the
natural numbers directly.

A similar issue comes up with "decidable", doesn't it?

By the way, I really like the new naming scheme. It was a great idea. I
find it is very easy to remember names now.

**Comment by leodemoura** [comment]
> Couldn't we make it protected, so the name remains nat.inhabited even if
> the namespace is open? If not, either is fine with me.

This would be bad. For example, we would have to write `nat.induction_on` and `nat.rec_on` even when we are in the `nat` namespace. We would have to revise many files.

> A similar issue comes up with "decidable", doesn't it?

Yes, I have already moved many of them to the top-level. 

Best,
Leo
