### ISSUE TITLE
strange effects with "import"

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#389]
I noticed two strange things when importing files in directories outside the hott directory:
- I have two files decl.hlean and basic.hlean in one directory. decl.hlean compiles without error, but when I write `import .decl` in basic.hlean it gives me an `invalid import, unknown module` error. (I tried deleting the olean-Files, clearing the cache, rebuilding Lean and whatnot)
- Auto-complete on imports shows me the theories from library/, not /hott, even if I'm in a .hlean file

**Comment by javra** [comment]
@avigad helped my with that first point, I didn't know that the project files were necessary

**Comment by avigad** [comment]
There are still two issues: there should be an option for creating a
default "hlean" project instead of "lean". And when editing an hlean file,
tab completion on import should use the hlean library.

**Comment by soonhokong** [comment]
> Auto-complete on imports shows me the theories from library/, not /hott, even if I'm in a .hlean file

This is a known issue. I need to work to support .hlean files.

**Comment by soonhokong** [comment]
I think this one is resolved. If not, please re-open this one.
