### ISSUE TITLE
Compatibility with Python 2/3

### ISSUE THREAD

**Issue by favonia** [leanprover/lean3#393]
Lean does not compile if `python` is `python3`. I can think of two ways to increase the compatibility: (1) replace every `python` by `python2`, or (2) convert the code so that it can run under `python3` and also later versions of `python2`. (I can also submit a pull request once a consensus is reached.)

**Comment by leodemoura** [comment]
Thanks for reporting the issue. I think (2) is the ideal solution.

**Comment by leodemoura** [comment]
It would be great if you could submit a pull request :-)

**Comment by favonia** [comment]
Support of Python <= 2.5 is likely to be lost. Is that okay?

**Comment by leodemoura** [comment]
Yes, this is fine.

**Comment by soonhokong** [comment]
Hi @favonia, good to see you here :-)

I used to put `python2` instead of `python` to specify its version. Then I found that some system didn't have `python2` but only have `python`. So, I changed it back to `python`. Note that we want to support major platforms - Windows, Linux, and OS X.

> I can also submit a pull request once a consensus is reached.

It will be great if you can submit a pull-request for this one.

**Comment by favonia** [comment]
@soonhokong I found the usage of `sys.setdefaultencoding()` in `bin/linja`, which is not portable at all.  Could you explain the trouble without that function call?

**Comment by soonhokong** [comment]
It's for the unicode support: http://stackoverflow.com/questions/3828723/why-we-need-sys-setdefaultencodingutf-8-in-a-py-script

**Comment by favonia** [comment]
Question: How to install the python six package in the travis script?

**Comment by soonhokong** [comment]
@favonia, I found the following script installing `six` via `pip` in the travis script:

https://github.com/amitu/importd/blob/0000e3f131c70b153bee94ceef0d51f667fd227a/.travis.yml#L9

**Comment by favonia** [comment]
@soonhokong I already put `pip install six` in `.travis.yml` in the current pull request, but the Travis service failed to install that library. I feel the current travis script is highly engineered and that I didn't modify the script correctly.

@leodemoura @soonhokong In general, I think the current travis script is "broken" in the sense that some builds actually failed but Travis thought they were okay. You can check the logs of the "successful" builds and find "Fail" in them.

**Comment by leodemoura** [comment]
> In general, I think the current travis script is "broken" in the sense that some builds actually failed but Travis thought they were okay. You can check the logs of the "successful" builds and find "Fail" in them.

Do you what is the problem?
The travis script is a little bit mysterious to me.  

Thanks

**Comment by favonia** [comment]
Sorry but I have no ideas.

**Comment by soonhokong** [comment]
> @leodemoura @soonhokong In general, I think the current travis script is "broken" in the sense that some builds actually failed but Travis thought they were okay. You can check the logs of the "successful" builds and find "Fail" in them.

There are two reasons that this happens:
- Anything error in 'after_script' script is ignored when it comes to determine the 'success' of a build
- When we use "A; B" in a script, the error code of 'A" is ignored and it can cause problem.

Let me think about more and refactor the travis script.

**Comment by soonhokong** [comment]
@leodemoura and @favonia,

I merged Favonia's commit and added `six.py` under `/bin` directory. I pushed them to the new branch [python3-compat](https://github.com/leanprover/lean/tree/python3-compat). @leodemoura, could you test this on a Windows machine? I've tested it on OSX and Ubuntu machines with Python2.7. @favonia, it would be great if you can test it on a machine with python3 (I guess you've already done this though)

**Comment by favonia** [comment]
1. If I were you I'll put `six.py` into `python-lib/` or `lib/` or something like that. Just suggesting.
2. Changes in `.travis.yml` should be dropped since there's no need to install the six library.
3. I only compiled it without testing it.

**Comment by soonhokong** [comment]
>  if I were you I'll put six.py into python-lib/ or lib/ or something like that.

@leodemoura, which of the follows would be the best?
- lib
- python-lib
- bin/lib
- bin/python-lib

To me, `bin/python-lib` seems a nice place to put.

> changes in .travis.yml should be dropped since there's no need to install the six library.

Done.

**Comment by leodemoura** [comment]
>  @leodemoura, could you test this on a Windows machine?

I will test it.

**Comment by leodemoura** [comment]
> @leodemoura, which of the follows would be the best?

For me, `bin/lib` and `bin/python-lib` are both fine.

**Comment by favonia** [comment]
To clarify, the organization suggestion is just a suggestion. I figured that you simply meant `six` is used in the files in `bin/`.

**Comment by leodemoura** [comment]
@soonhokong `python3-compat` branch works smoothly on Windows (with MSYS2) 
:-)
