### ISSUE TITLE
ltags - name clash

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#394]
From @UlrikBuchholtz:

When I installed Lean, I ran into the problem that I have an existing binary called ltags (for LaTeX). I think it's pretty common, so you may want to rename your ltags to leantags or something like that.

I solved it on my end by putting your ltags ahead in my $PATH, but that only works because I don't really use the LaTeX ltags.

**Comment by soonhokong** [comment]
It seems that we should rename `ltags` to another name to avoid the conflict. What would be a good name for this? What about `leantags`?

**Comment by soonhokong** [comment]
@leodemoura, please let us know if you have a good idea for this.

**Comment by leodemoura** [comment]
I think `leantags` is a good name.

**Comment by avigad** [comment]
I agree.

On Sat, Jan 17, 2015 at 9:55 PM, Leonardo de Moura <notifications@github.com
