### ISSUE TITLE
System-wide tools are preferred over local ones

### ISSUE THREAD

**Issue by favonia** [leanprover/lean3#396]
I noticed that in `bin/linja` system-wide tools like `ninja`, `lean`, and `ltags`  are preferred over local ones that come with the package. Unfortunately I have a system-wide `ltags` installed by other programs that has nothing to do with Lean, so I have to disable the search of system-wide tools. My question is, why do we prefer system-wide tools over local ones?

**Comment by leodemoura** [comment]
BTW, `ltags` has been renamed to `leantags` (see #394).

> My question is, why do we prefer system-wide tools over local ones?

@soonhokong Is there any reason for preferring system-wide tools?

**Comment by soonhokong** [comment]
> @soonhokong Is there any reason for preferring system-wide tools?

I just haven't thought about it. I think we can assume that `lean` and `leantags` are in the same directory where `linja` is located and try to use those files as a first attempt.

**Comment by favonia** [comment]
@leodemoura Thanks for the information (and I updated the python3 pull request accordingly). Personally I think this issue is the real problem of #394. Renaming is just a workaround.

**Comment by leodemoura** [comment]
> Personally I think this issue is the real problem of #394. Renaming is just a workaround.

I agree.

**Comment by soonhokong** [comment]
I'll fix this.
