### ISSUE TITLE
How to trigger recompiling imports?

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#398]
Often when I make changes to one theory they don't get propagated to another open file which imports the changed files. Or I create a new file, but the import does not recognize it, resulting in `invalid import, unknown module ...`. How can I initiate recompiling the imports so that all that works?

**Comment by leodemoura** [comment]
Do you think this problem is specific to the HoTT version? 
That is, have you ever observed this problem when using standard Lean (.lean files)?
Could you post a sequence of actions that produces the problem?
I'm having trouble reproducing it.

That being said, we can use `linja` to force rebuilds from scratch.
- open shell
- go to directory where your `.project` is located
- execute

```
linja clean
linja
```

The `linja` tool is located in the same directory the `lean` executable is located: `path-to-lean/bin`.

**Comment by avigad** [comment]
Jakob and I noticed before that the "create project" menu option in emacs
created a makefile for .lean files, even if the file being edited was
.hlean. I mentioned it by e-mail I think but I don't remember if I opened
an issue. Has this been fixed?

On Tue, Jan 20, 2015 at 8:03 PM, Leonardo de Moura <notifications@github.com

**Comment by javra** [comment]
The series of actions was just to change one file, compile it successfully, but the other file had the old version in cache, even after clicking "delete all cache". I couldn't reproduce it with dummy files though.

The problem with running linja is generally that one has many construction sites lying around the build process aborts. Couldn't we change linja to try to compile all files but return 1 when at least one of them fails?

@avigad At leat that's not what causes the problem in this case.

**Comment by leodemoura** [comment]
I will investigate.

BTW, `linja` has an option called `--keep-going` (`-k`)
If you call it using
`linja -k 100000`
It will not stop after the first error.
The parameter is the number of failures.

**Comment by leodemoura** [comment]
> The series of actions was just to change one file, compile it successfully, but the other file had the old version in cache, even after clicking "delete all cache". I couldn't reproduce it with dummy files though.

I'm also having problems reproducing the issue with dummy files.

Which files in your development produce this problem?
I will try to use them.

Thanks

**Comment by javra** [comment]
Thanks for the hint at the -k option!
The problem causing file is /code/thin_structure/decl.hlean.

**Comment by leodemoura** [comment]
> The problem causing file is /code/thin_structure/decl.hlean.

I tried the following: 
- open `/code/thin_structure/decl.hlean`
- open `/code/dbl_cat/decl.hlean`
- comment `dbl_precat` structure, and save the file
- go back to `/code/thin_structure/decl.hlean`, and make a change: flycheck reports error
- go to `/code/dbl_cat/decl.hlean`, and uncomment `dbl_precat`, and save
- go back to `/code/thin_structure/decl.hlean`, and make a change: flycheck reports no error

Remarks:
- Information is only propagate to other files when we save the .lean file (in the steps above, I had to save `/code/dbl_cat/decl.hlean)`
- If there is an error processing a foo.lean file, the previous foo.olean file is not deleted.
- When I move to a file, flycheck is not automatically triggered if one of the imports have been modified. I had to make a change.

Are you experiencing a different kind of problem?

**Comment by leodemoura** [comment]
@javra any news?

Thanks,
Leo

**Comment by soonhokong** [comment]
@javra, do you still have this problem?

**Comment by javra** [comment]
Haven't encountered it in the last days. I guess the .hlean support for Flycheck solves it.

**Comment by soonhokong** [comment]
@javra, thanks!
