### ISSUE TITLE
Hovering for type information in .hlean files

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#400]
I'm sure I've seen this issue before but I cannot find it among the open issues. Should this be solved? Because for me it's not working until now.

**Comment by soonhokong** [comment]
> Should this be solved? 

Yes, I'm on this.

**Comment by avigad** [comment]
Egbert Rijke pointed out the following to me: now Lean mode provides type information on hovering, but it is incorrect. For example, open a .hlean file with the following:

section
  variable A : Type
  variables x y : A
  check x = y
end

The output of the "check" is Type, but hovering over = produces A -> A -> Prop.

**Comment by javra** [comment]
Strange... I never get _any_ out output on hovering. I get wrong information on autocompletion for imports though.

**Comment by soonhokong** [comment]
Well.. Lean-mode shouldn't work with .hlean files yet.

## 

Soonho Kong
soonhok@cs.cmu.edu

**Comment by avigad** [comment]
It _is_ strange. I really do get the behavior I reported, as does Egbert.

**Comment by soonhokong** [comment]
I'll double-check. While I have been delaying the issue, @leodemoura patched many things and that might explain the behavior. I'll finish .hlean support soon.

**Comment by leodemoura** [comment]
I think Egbert Rijke may have accidentally named the file with a `.lean` extension.
This is the only way I found to reproduce the behavior @avigad  described.

**Comment by avigad** [comment]
No, I can confirm it happens in an .hlean file. My file is called
graphs.hlean, and it is outside the library directories. The file contains
this:

---

check eq -- ?A → ?A → Type

section
  variable A : Type
  variables x y : A
  check x = y -- Type
end

-- check Prop -- error

exit

---

Putting the cursor on the "=" symbol shows

  = : A → A → Prop

in the messages line.

I would be glad to do more testing...

**Comment by javra** [comment]
@soonhokong Are you working on this? I could also try if I can fix this myself. I only work with .hlean files so this is slowing me down quite a bit...

**Comment by soonhokong** [comment]
I was in the process of fixing this but couldn't finish it yet. Please feel free to try.

**Comment by soonhokong** [comment]
@javra, I just pushed `.hlean` support commits to the `blessed/master`. I think this feature is working now. If you see a problem, please re-open this issue.
