### ISSUE TITLE
cpplint.py is failing

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#404]
@soonhokong `cpplint.py` does not work after today changes.
It is failing on my machine, and at http://build.leanprover.net/
Any ideas?

**Comment by soonhokong** [comment]
I had issues on my mac, but not on my linux machines, so I ignored it. @favonia, I think it comes from your changes in `cpplint.py` file in https://github.com/leanprover/lean/commit/073c1d1c31f8262c8f1ae04006796215d2fdab1a#diff-295600dcc0bae237e888018d819ef0d6. Could you take a look at this one?

**Comment by soonhokong** [comment]
If it's difficult to make `cpplint.py` compatible with both of python 2 and 3, let keep the python2 version. It's only for the C++ developers who know things better. What do you think @leodemoura?

Of course, if it's not so difficult, we're happy to have more compatible programs in general.

**Comment by leodemoura** [comment]
> What do you think @leodemoura?

I agree.

**Comment by soonhokong** [comment]
For the moment, let me rollback `cpplint.py` to the previous version. @favonia, please feel free to take your time if you want to work on this issue.

**Comment by leodemoura** [comment]
fixed by https://github.com/leanprover/lean/commit/65cc4d3c086187d37874526ae3d76373fa44d6d4
