### ISSUE TITLE
Flychecker error

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#406]
I tried recompiling everything and rebuilding lean and restarting emacs but I keep on getting the following error on one of my files:

```
Checker lean-checker returned non-zero exit code 1, but no errors from output: [5/9] generating dep... /home/javra/Dokumente/uni/msc-thesis/code/dbl_gpd/flycheck_fundamental.d        

Traceback (most recent call last):
  File "/home/javra/Programme/lean/lean/bin/linja", line 719, in <module>
    sys.exit(main())
  File "/home/javra/Programme/lean/lean/bin/linja", line 704, in main
    return call_ninja(args)
  File "/home/javra/Programme/lean/lean/bin/linja", line 499, in call_ninja
    process_lean_output(targets[0], out, args, args.targets[0].endswith(".hlean"))
  File "/home/javra/Programme/lean/lean/bin/linja", line 467, in process_lean_output
    flycheckItemList = FlycheckItemList.fromString(out)
AttributeError: 'NoneType' object has no attribute 'fromString'
```

What does that mean?

**Comment by leodemoura** [comment]
@soonhokong I managed to reproduce the bug. I believe this problem was introduced by recent changes in `linja`. Any ideas?

**Comment by soonhokong** [comment]
The problem disappears when I comment line 141 of [bin/linja](https://github.com/leanprover/lean/blob/master/bin/linja#L141) file.

@favonia, it seems that `@python_2_unicode_compatible` has side effects at the type of classes? For instance, with line 141, we have

```
print(type(FlycheckItemList))
<type 'NoneType'>
```

while without line 141, we have

```
print(type(FlycheckItemList))
<type 'classobj'>
```

FYI, I'm using Python 2.7.9.

**Comment by leodemoura** [comment]
@soonhokong Thanks for finding the problem. It would take me "forever" to find it.
This is a really important problem. Any student that installs Lean today using, for example, the .zip file on our website will get the buggy version :-(

**Comment by soonhokong** [comment]
> This is a really important problem. Any student that installs Lean today using, for example, the .zip file on our website will get the buggy version :-(

I agree. It seems that we need to roll back to the version where we only supported python2. We keep the current one with a branch `python3-compat` and keep digging the issues until we find it stable. Then we can merge it back to the master. What do you think?

I can meet @favonia today in the class and ask him about the issue.

**Comment by soonhokong** [comment]
@leodemoura, if you agree, could you do the roll-back operation? I need to prepare and go to the campus :-)

**Comment by leodemoura** [comment]
I will roll-back. Should I perform a destructive update?

**Comment by leodemoura** [comment]
@favonia Thanks for fixing the problem!

**Comment by favonia** [comment]
Sorry for the mistake.  An unrelated suggestion: I think we should remove the outdated `python3-compat` branch from the main repository.

**Comment by leodemoura** [comment]
I removed the branch `python3-compat`

**Comment by favonia** [comment]
Oops I didn't see @soonhokong's suggestion. I'm happy with a separate (but updated) Python3 branch.

**Comment by leodemoura** [comment]
@soonhokong and I were discussing a workaround: rollback. The branch was just a way to "save the state". The problem was fixed, we don't need the branch anymore.

**Comment by soonhokong** [comment]
@favonia, thanks a lot!!
