### ISSUE TITLE
self-contained version of lean-mode

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#410]
https://github.com/leanprover/lean/issues/407#issuecomment-71245413

**Comment by leodemoura** [comment]
@soonhokong 
Tom Ball tried to install lean-mode, but flycheck doesn't work on his machine.
I believe the problem is the latest flycheck. It depends on a new package `let-alist-1.0.1`.
I tried to reproduce the problem on my machine by uninstalling everything, and using the script from your slides. 
However, on my machine, the problem is even worse. 
The installation script breaks trying to install flycheck :-(
I tried many things, nothing works. On my machine, the package `let-alist` is not even in the list of available packages. 

I think this is another motivation for having the self-contained version.

**Comment by leodemoura** [comment]
Small update. As reported above, the lean-mode was not working on my Windows machine.
To fix, I had to delete the directory `.emacs.d`, and use `Emacs 24.3.1 (i386-mingw-nt6.2.9200)`.
If I use `GNU Emacs 24.4.50.1 (x86_64-w64-mingw32)`, I get the same error.
The crazy part is that if I use `Emacs 24.3.1` to install the required packages, and switch to `Emacs 24.4.50.1`, then everything works.

**Comment by leodemoura** [comment]
Update: the .zip file for windows does not contain `ninja`
I think this is why `flycheck` does not work on Tom's machine.

**Comment by soonhokong** [comment]
Dear Leo,

I see the two issues:
- flycheck added a new dependencies `let-alist` starting from its recent version. The problem is that this package is not in `MELPA` but `GNU`. The failure of installing it is a bit mysterious for me because some people claim that `GNU` is the default repo for emacs package management system' and installing `let-alist` shouldn't be a problem. Anyway, we've already have cases (Tom and Steve) and we need to work on it.
- When `linja` fails to find `ninja` in a system, it's supposed to download the source and build in the system. I think that part is broken now and causes a problem.

For the flycheck problem, I hope that updating `package-archives` variable to include `GNU` repo is a solution. I've added it in https://github.com/leanprover/lean/blob/emacs-fix/src/emacs/README.md. I'll test this.

``` elisp
(add-to-list 'package-archives
             '("gnu" . "http://elpa.gnu.org/packages/")
             '("melpa" . "http://melpa.milkbox.net/packages/") t)
```

For the ninja problem, I will take a closer look.

> I think this is another motivation for having the self-contained version.

Now I'm totally convinced that the self-contained version is the way to go.

**Comment by soonhokong** [comment]
It seems that adding 'gnu' repo to 'package-archives' variable solves the first problem:
https://github.com/ap4y/swift-mode/commit/94d687d187868f8ff465c7f80e6553fbaf0cfa8a

I'll check.

**Comment by leodemoura** [comment]
> For the flycheck problem, I hope that updating package-archives variable to include GNU repo is a solution. I've added it in https://github.com/leanprover/lean/blob/emacs-fix/src/emacs/README.md. I'll test this.

I tried that, and it didn't work for me. Actually, I have tried many package-archieves, but I keep getting the same error. I managed to fix the problem on Windows (as I described before), but I still have the problem on my main Linux VM: the VM I used for developing Lean in the office.

It is a big mess, Lean mode does not work anymore on this VM. 
I tried many things, and nothing works.
The only solution I see is to stop using the package management system on this machine, and install the required packages manually using the snapshots from https://github.com/leanprover/emacs-dependencies

I know this is not a nice solution but something is really broken on the package management system used on Emacs or on Flycheck.

**Comment by soonhokong** [comment]
> The only solution I see is to stop using the package management system on this machine

This is tricky.... should we tell people to stop using `package` to use lean?

I know there are some people who don't like `package` and use [cask](https://github.com/cask/cask). Actually, this is what we're using in `leanprover/tutorial` repository to install `org-mode` and other dependencies in the local to compile `.org` file into `.html` and `.pdf`. Last time I checked, it didn't support Windows. Now, it seems they do support Windows. Maybe it's worth trying this time.

**Comment by leodemoura** [comment]
> This is tricky.... should we tell people to stop using package to use lean?

For novice users, I think the best solution is to tell them to avoid `package` and use the self-contained Lean mode. That is, tell them to use the `leanemacs` script.

I think `package` is a big source of problems. I doubt `cask` will solve our problems.
I don't think they are mature enough. flycheck is also not mature. I think it is better for us to control the dependencies ourselves. The goal is to avoid that changes in flycheck will break lean-mode in the future. From time to time, we can test new versions of the packages we use, and decide whether we should upgrade or not. Our distribution should be a self-contained as possible, and as easy to install as possible. 

Of course, we may provide information to advanced users on how to install packages and configure the Lean Emacs mode.

> Last time I checked, it didn't support Windows. Now, it seems they do support Windows. Maybe it's worth trying this time.

I think the Windows version is fine now. It is mostly self-contained. The user still needs to install Python and Emacs, and put both on them in the Path, but everything else is smooth.

**Comment by jroesch** [comment]
I have now factored out the Emacs mode into https://github.com/leanprover/lean-mode, and have opened a PR on the MELPA repository: https://github.com/melpa/melpa/pull/4813.

**Comment by leodemoura** [comment]
@jroesch I wish we had badges on github ;) 
This refactoring would be the "closing a 2 year old issue" badge :)
