### ISSUE TITLE
lean-set-option is buggy

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#416]
reported by @avigad and @leodemoura

**Comment by gebner** [comment]
The current emacs interface no longer has `lean-set-option`.  Should we reintroduce it, or just use `set_option` commands?

**Comment by leodemoura** [comment]
@gebner I never used this command on Emacs. I'm happy having only with the `set_option` command. The only thing I miss is the auto-completion for options :) 
Should we close this issue?

**Comment by gebner** [comment]
I don't think anybody wants to implement it.  So let's close it.
