### ISSUE TITLE
ninja is missing after installing lean using PPA

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#417]
I installed lean using `sudo apt-get install lean` on a clean VM.
`linja` produces the following error message

```
/usr/bin/linja --keep-going 999 --flycheck --flycheck-max-messages 100 --cache /home/leonardo/tmp/a.lean -Dpp.width\=83 -- /home/leonardo/tmp/a.lean
Downloading ninja: https://leanprover.github.io/bin/ninja-1.5.1-linux-x86_64 ===> /usr/bin/ninja

Traceback (most recent call last):
  File "/usr/bin/linja", line 724, in <module>
    sys.exit(main())
  File "/usr/bin/linja", line 700, in main
    args = parse_arg(argv)
  File "/usr/bin/linja", line 421, in parse_arg
    check_requirements()
  File "/usr/bin/linja", line 361, in check_requirements
    g_ninja_path = download_ninja_and_save_at(g_ninja_path)
  File "/usr/bin/linja", line 280, in download_ninja_and_save_at
    urlretrieve(url, ninja_path, show_download_progress)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 244, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 13] Permission denied: '/usr/bin/ninja'
```

It seems there is a missing dependency between `lean` and `ninja`.
BTW, the package is called `ninja-build` in PPA.

**Comment by leodemoura** [comment]
Tried to fix by adding
https://github.com/leanprover/ppa-updater/commit/7c2f63c04f1d445d16ddedcb3d66d33c10102d54

**Comment by soonhokong** [comment]
This is the second problem that I mentioned in #410

**Comment by soonhokong** [comment]
When a system doesn't have `ninja`, `linja` downloads, builds, and installs `ninja` at the same directory where `linja` is located. In this case, it's `/usr/bin`, which requires `sudo` in general.

```
Downloading ninja: https://leanprover.github.io/bin/ninja-1.5.1-linux-x86_64 ===> /usr/bin/ninja
```

I think https://github.com/leanprover/ppa-updater/commit/7c2f63c04f1d445d16ddedcb3d66d33c10102d54 should fix the problem on Ubuntu. @leodemoura, could you confirm?

For OS X, I change `ninja` dependency from 'build dep' to a regular dep in https://github.com/leanprover/homebrew-lean/commit/1e48faf7f0c01b01a1ef0098047120c1cc52d6ca. I'm testing it.

**Comment by soonhokong** [comment]
@leodemoura, FYI, I've tested the new PPA on Ubuntu-12.04 and Ubuntu-14.04. It works on both of them. Thank you!

> For OS X, I change ninja dependency from 'build dep' to a regular dep in leanprover/homebrew-lean@1e48faf. I'm testing it.

I wanted to build a new bottle and test it, but we have a test failure and homebrew doesn't allow us to update the formula with it. Please refer to another issue https://github.com/leanprover/homebrew-lean/issues/4.
