### ISSUE TITLE
emacs-24.3 + flycheck problem

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#418]
While assisting @awodey, I had this problem.

Aquamacs-24.3 has a problem in installing flycheck. It still gives "Package let-alist-1.0.1' is unavailable`" error. I was puzzled because I added [GNU ELPA](http://elpa.gnu.org/) in the`package-archives` list. For now, I resolved his issue by upgrading Aquamacs to 24.4. However, it is a problem.

**Comment by leodemoura** [comment]
This is similar to the problem I had yesterday on my Windows machine. I got the same error, and including `http://elpa.gnu.org` did not help.
For me, the solution was: delete `.emacs.d` directory, and install Emacs 24.3.

**Comment by soonhokong** [comment]
I see. I'll dig it deeper.

**Comment by soonhokong** [comment]
I found some lessons:
- Due to the recent changes in [flycheck](https://github.com/flycheck/flycheck/), it explicitly requires that ["All packages depending on Flycheck must be recompiled!"](https://github.com/flycheck/flycheck/blob/master/CHANGES.rst#022-dec-23-2014). However, it seems that `package.el` does not do this for users. As @leodemoura mentioned, we need to delete `.emacs.d/elpa` and re-install the packages manually. This is very painful, of course.
- Moreover, there is [a problem in GNU ELPA repository and Emacs](http://stackoverflow.com/questions/26108655/error-updating-emacs-packages-failed-to-download-gnu-archive#comment45103304_26449253). The newly introduced flycheck dependency `let-alist` is located in GNU ELPA repository. However, due to the mentioned bug, emacs cannot find this package and complains about it. That's why we had the problem.

I don't think this is a problem limited to emacs-24.3. I _did_ have the same problem in _emacs-24.4_. Actually, the homebrew version of emacs (24.4.1) does have the same problem (as of Feb 2015). So I had to install emacs from http://emacsformacosx.com on my machine.

**Comment by leodemoura** [comment]
Should we close this issue?
The command `(setq package-check-signature nil)`, that you suggested in a different thread, solved the problem. I used in two different machines. Here the recipe that should be used
- Execute `(setq package-check-signature nil)`. I executed it on the scratch buffer.
- `M-x package-list-packages`
- Select the latest `flycheck` and press `x`

**Comment by soonhokong** [comment]
I agree.
