### ISSUE TITLE
add syntax "premise" for "variable"

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#429]
That way, we have the following pleasing list of equivalent pairs:

  constant / axiom
  variable / premise
  parameter / hypothesis
  take / assume

**Comment by leodemoura** [comment]
BTW, we can also use "lemma"/"corollary" instead of "theorem" and "conjecture" instead of hypothesis.

**Comment by avigad** [comment]
Very good -- I will make sure those go in the tutorial as well.
