### ISSUE TITLE
import auto-completion for hlean files

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#434]
If we open a .hlean file, and type

```
import 
```

and then press TAB. The auto-completion will show the directories and files of the standard library.

**Comment by soonhokong** [comment]
![screen shot 2015-02-13 at 12 20 45 pm](https://cloud.githubusercontent.com/assets/403281/6191856/c16f72ca-b37a-11e4-8ab8-6f13af1b4379.png)

@leodemoura, does it look good?

**Comment by leodemoura** [comment]
Yes, it does! :+1: 

Thanks,
Leo
