### ISSUE TITLE
show descriptions in auto-complete + set_option

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#435]

**Comment by leodemoura** [comment]
This is a cool feature :-)

**Comment by soonhokong** [comment]
@avigad is showing many features to the students. I'll add things that I want to improve :-)

**Comment by soonhokong** [comment]
- description goes to the bottom (mini-bar)
- shows type and current value

![screen shot 2015-02-13 at 7 37 48 pm](https://cloud.githubusercontent.com/assets/403281/6197685/d7f09c6c-b3b7-11e4-8b1b-c7c36f163927.png)

**Comment by avigad** [comment]
Nice!
