### ISSUE TITLE
simplify emacs-setup instructions

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#436]
https://github.com/leanprover/lean/pull/423#issuecomment-72707904

@leodemoura, could you run the following elisp code in windows environments (Native Emacs and msys2 Emacs)?

``` elisp
(message "%S" system-type)
```

**Comment by leodemoura** [comment]
On native Emacs for Windows:  "windows-nt"
On msys2 terminal Emacs for Windows: I will have to give you a "rain check".
I only have msys2 in my office at MSR. I will try it next Monday.

**Comment by leodemoura** [comment]
I didn't go to the office today.

**Comment by soonhokong** [comment]
Thank you. No rush please :-)

**Comment by leodemoura** [comment]
`msys2` does seem to provide a precompiled emacs. I tried to find instructions on the web, and all-of-them were about how to compile emacs from sources.

On `cygwin`, the result of `(message "%S" system-type)` is `cygwin`.
