### ISSUE TITLE
Is it possible to provide macports support for OSX?

### ISSUE THREAD

**Issue by lkloh** [leanprover/lean3#437]
I use macports for most installations and I'll prefer not a use Homebrew as well to avoid potential conflicts.

**Comment by soonhokong** [comment]
I will try.

By the way, do you know whether it is possible to have a third-party repository in MacPorts? In homebrew, we're using our [own package repository](https://github.com/leanprover/homebrew-lean) (`tap` in homebrew terminology) where we have full control. Lean is in its early stage and we want to update the package as fast as possible to patch urgent issues.

It seems that MacPorts is a centralized system where we need to submit a [new ticket (via trac)](https://trac.macports.org/auth/login/?next=/newticket) to update a package. I've found things so far from [this reference](https://guide.macports.org/#project.tickets). Of course, my knowledge on MacPorts is very limited. If you have more experiences, please let me know.

**Comment by lkloh** [comment]
I don't know much about development in macports, only usage. I'll just have to install from the source then. Thanks!

**Comment by soonhokong** [comment]
> By the way, do you know whether it is possible to have a third-party repository in MacPorts?

I've found a good example of doing exactly what I wanted:

http://cvc4.cs.nyu.edu/macports/

**Comment by soonhokong** [comment]
@lkloh, I need your help. Could you follow [the instructions](https://github.com/leanprover/macports/blob/master/README.md) and let me know how it works on your machine?

**Comment by soonhokong** [comment]
@leodemoura, macports complains about [examples/ex.lean](https://github.com/leanprover/lean/blob/master/examples/ex.lean) file that we copy during installation. Can we have a quick solution?

``` text
Warning: violation by /opt/local/examples
Warning: lean violates the layout of the ports-filesystems!
Warning: Please fix or indicate this misbehavior (if it is intended), it will be an error in future releases!
```

**Comment by soonhokong** [comment]
- [x] I still need to check whether it picks up changes in upstream and does updates accordingly.
- [x] Once I check things up, I'll update [OSX Installation page](http://leanprover.github.io/download/OSX10inst).

**Comment by lkloh** [comment]
I tested it and got this:

`Warning: violation by /opt/local/examples
Warning: lean violates the layout of the ports-filesystems!
Warning: Please fix or indicate this misbehavior (if it is intended), it will be an error in future releases!`

**Comment by soonhokong** [comment]
@lkloh, thanks for testing it. 
- Those warnings are sort-of harmless, and I think we can easily get rid of them. 
- Could you test the installed lean via macport by running `/opt/local/bin/lean` with some lean file?

**Comment by lkloh** [comment]
It works! Thanks

**Comment by soonhokong** [comment]
Great!

A bad news is that the 'update' part is not working yet. I'll fix it and write a comment here. It will send you a notification as well. Until then, please keep using "build from source" method as you've done.

**Comment by soonhokong** [comment]
Now, the upgrade should work. Please try the following:

``` bash
sudo port -v sync
sudo port upgrade lean
```

I also updated the instructions at http://leanprover.github.io/download/OSX10inst.
