### ISSUE TITLE
limited import imports too much

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#440]
When we open a namespace with an explicit list of declarations, it also imports metaobjects.

For example,

```
import data.nat

open nat (succ)   -- we get all the metaobjects in nat

check ℕ
check λa b, a + b
print coercions
```

Is this the intended behavior?

I expected the command to mean:

```
open [declarations] nat (succ)
```

**Comment by leodemoura** [comment]
Yes, this is the indented behavior. 
We can change it. 
However, if we change another user may complain it is counter-intuitive to implicitly include the `[declarations]`.
Moreover, if we change, I think we need to the same when `hiding` and `renaming` are used.

**Comment by avigad** [comment]
O.k., I will use [declarations], and explain it better in the tutorial.
