### ISSUE TITLE
"open" not limited to section

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#441]
Metaobjects from "open" are still in the context when the section is closed.

```
import data.nat

section
  open nat
end

check ℕ
check λa b, a + b
print coercions
```

**Comment by leodemoura** [comment]
This is the intended behavior. `Section` does not block.
Reason: sometimes we use section to define variables for a small group of theorems.
The idiom we use is 

```
    namespace foo
        section
           variables A B : Prop
           -- declare theorems and their attributes
        end

       section
          variables A B : Type
          -- declare theorems and their attributes
       end
    end foo
```

In this idiom, we want the attributes in the namespace `foo`.
If we want to block we should use `context` instead of `section`.

**Comment by avigad** [comment]
Got it. That makes sense.
