### ISSUE TITLE
emacs tab completion popup does not display absolute value

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#446]
I don't know if there is an easy way to fix this. It would be o.k. to use "abs t" instead of "|t|".

![abs_bug](https://cloud.githubusercontent.com/assets/2783534/6376880/a1c121c6-bcee-11e4-843b-6868e9be4031.png)

**Comment by soonhokong** [comment]
@avigad, I'm on it.

**Comment by soonhokong** [comment]
@leodemoura, we need to escape the symbol `|` which we use as a delimiter in a packet between lean-server and an emacs client. Here is the text we get for the above example:

```
int.abs.by_cases|?P ?a → ?P (- ?a) → ?P | ?a |
                                        ^    ^
```

For this particular case (type information in auto-complete), I can avoid the problem by only splitting a line at the first occurrence of `|` and accept the rest of the line as a type.

Maybe an easier solution to implement is to use a multi-char delimiter to reduce the possibility of having such a conflict?

**Comment by leodemoura** [comment]
@avigad and @soonhokong 
This would be great. If we stop using `|a|` for `abs a`, then `|` can be a separator (like `,`).
Separators are tokens with binding power `0`.
We can improve the syntax in many places. Right now, we rely too much on `,`.
Here are some examples:

1- Nice subtypes `{ x : A | P x }`. We have this notation, but since `|` does not have binding power 0, we sometimes have to use parenthesis around the type.

2- ML-like notation for recursive equations and inductive datatypes

```
inductive nat :=
| zero : nat
| succ : nat -> nat
```

```
definition add : nat -> nat -> nat 
| add 0        b := b
| add (succ a) b := succ (add a b)
```

**Comment by leodemoura** [comment]
@soonhokong 
Thanks for finding the problem.
I think we should escape the character `|` as you suggested.
I can do that in the Lean server. 

That being said, I still think it would be nice to stop using `|a|` for absolute value.

**Comment by leodemoura** [comment]
Here is another example.

Current syntax:

```
definition nth [h : inhabited T] : list T → nat → T,
nth nil      n     := arbitrary T,
nth (a :: l) 0     := a,
nth (a :: l) (n+1) := nth l n
```

New syntax:

```
definition nth [h : inhabited T] : list T → nat → T
| nth nil      n     := arbitrary T
| nth (a :: l) 0     := a
| nth (a :: l) (n+1) := nth l n
```

**Comment by soonhokong** [comment]
> I think we should escape the character | as you suggested. I can do that in the Lean server.

Thank you. I'll also work on emacs-side for that change.

Regarding the notation for absolute value, for your information, we have some unicode characters such as
- ‖ (U+2016, double vertical line)
- | (U+007C, vertical line)

and people can still define their own notations for `abs` and `norm` using those unicode characters. Note that we already have the entries for them in lean mode's input-method -- `\|` for `|` and `\Vert` for `‖`.

Of course, those notations should be only used among a group of people who know what they're doing otherwise it certainly makes other readers confused.

**Comment by avigad** [comment]
We used to use "|" for inductive definitions, etc. We changed it because of
abs.

I think it is a good idea to use | . I will put that on my to-do list.

Please don't make that change now. I am about to commit a lot of changes to
the int library.

**Comment by leodemoura** [comment]
@avigad I have integrated your latest commits.
I have replaced '|a|' with 'abs a', and used '(a | b)' for divides (btw, this is the same notation used in Coq).
Here the commit in my private repo:
https://github.com/leodemoura/lean/commit/3c24461e514f1bf262846066604f8ab9bdc064ba

I will add the new notation for recursive functions and inductive datatypes.
I will keep the old and new notations for a couple of months.

**Comment by avigad** [comment]
Thanks! Did you use some regexp search and replace to make the process less
painful?

Are you against the use of a different symbol, |, for either divides or
absolute value or both? Isabelle uses that solution for abs (as well as
"abs x"). I can live with (a | b), but all the parentheses look funny.

**Comment by leodemoura** [comment]
> Did you use some regexp search and replace to make the process less
> painful?

Yes, but I had to manually fix some cases.

> Are you against the use of a different symbol, |, for either divides or
> absolute value or both?

No, I'm not.  I'm fine with it. 
I can change to unicode later.

> I can live with (a | b), but all the parentheses look funny.

I think you referring to the `(H : (a | b))` case, right?
I agree it looks weird.

I think the instances of the form `(a | b) -> (c | d) -> ...` look fine.

**Comment by avigad** [comment]
I will create a branch to experiment later.

It looks like the | binding is now to

  U+2223 ∣ DIVIDES

which looks bad in my emacs. It is really skimpy.

The symbol

  U+007C | VERTICAL LINE

looks much better.

  http://en.wikipedia.org/wiki/Vertical_bar
  http://www.fileformat.info/info/unicode/char/2223/index.htm

The fact that we were otherwise not having problems suggests that it can be
used for both abs and div, with

  precedence `|`:55
  reserve notation  | a:55 |

By the way, when I write

  infix `***` := foo

or

  notation a `***` b := foo a b

what are the default rbp's?

On Wed, Feb 25, 2015 at 6:44 PM, Leonardo de Moura <notifications@github.com

**Comment by leodemoura** [comment]
> The symbol
> U+007C | VERTICAL LINE
> looks much better.

Great! 
It seems it is the standard symbol for abs. This is an extra plus.

> what are the default rbp's?

It is 1. It can be easily changed in the code.
We have

```
#define LEAN_DEFAULT_PRECEDENCE 1
```

**Comment by soonhokong** [comment]
> The symbol
>  U+007C | VERTICAL LINE
> looks much better.

You're right. I'll make the change in lean-mode.

**Comment by soonhokong** [comment]
> > The symbol
> > U+007C | VERTICAL LINE
> > looks much better.
> > Great! 
> 
> It seems it is the standard symbol for abs. This is an extra plus.

I think it's actually the ascii character '|' which we wanted to avoid.

**Comment by soonhokong** [comment]
> It looks like the | binding is now to
>  U+2223 ∣ DIVIDES
> which looks bad in my emacs. It is really skimpy.

@avigad, could you try the following trick? It helped @leodemoura and me before.
1. Install `unicode-fonts` package via `M-x package-install` command.
2. Add the following lines in your emacs setup:
   
   ``` lisp
   (require 'unicode-fonts)
   (unicode-fonts-setup)
   ```

**Comment by leodemoura** [comment]
> I think it's actually the ascii character '|' which we wanted to avoid.

You are right :-)

**Comment by avigad** [comment]
When I try to install unicode-fonts I get "Error during download request:
Not Found". I will try again later.

**Comment by soonhokong** [comment]
Executing `package-refresh-contents` before installing `unicode-fonts` should help. If not, please let me know.

**Comment by avigad** [comment]
Yes, that solved it, and now the divides symbol | looks fine. Thanks!

**Comment by soonhokong** [comment]
@avigad, great! I've added those instructions in `doc/emacs/README.md` file via 88e287d.

**Comment by soonhokong** [comment]
> For this particular case (type information in auto-complete), I can avoid the problem by only splitting a line at the first occurrence of | and accept the rest of the line as a type.

It's done by 05cfb21. I'm using an old version to test it:

![screen shot 2015-02-27 at 8 06 18 pm](https://cloud.githubusercontent.com/assets/403281/6423921/1dd4c6cc-bebc-11e4-920c-7b6891b469d1.png)

**Comment by leodemoura** [comment]
Great!!!!

**Comment by soonhokong** [comment]
> @soonhokong Thanks for finding the problem. I think we should escape the character | as you suggested.

@leodemoura, could you ping me when it's done. No rush please, of course :-)

**Comment by leodemoura** [comment]
> @leodemoura, could you ping me when it's done. No rush please, of course :-)

Do we still need it? I believe only `FINDP` produces output mixing types and `|`. It is a sequence of the form

```
[name]|[type]
```

It is not ambiguous, since name never contains `|`. So, the solution you used is perfect.
In all other messages, we use `|` to separate an ID from the column and line numbers.
Am I missing the problem?

**Comment by soonhokong** [comment]
@leodemoura, you're right!
