### ISSUE TITLE
`Alt-.` does not work on HoTT mode (.hlean files)

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#450]
It seems to use the TAG file for the standard library.
Here is a repro.
1- Create a .hlean file (e.g., foo.hlean)
2- Type `check funext`
3- Press `Alt-.` at `funext`. 
Lean will jump to the definition of `funext` in the standard library instead of the HoTT library.

**Comment by soonhokong** [comment]
@leodemoura, we're using the result of `lean --path` to figure out the location of Lean library. Can we have different results for `lean --hlean --path` and `lean --lean --path`? For now, it gives me the same result, and it doesn't include HoTT library.

**Comment by leodemoura** [comment]
@soonhokong This is a good idea. I will fix the result of `lean --hlean --path`.

**Comment by soonhokong** [comment]
@leodemoura, thank you. I'll use the new information.

**Comment by soonhokong** [comment]
@leodemoura, this one is fixed. 

But I've found other things to change in tag generation. It's mainly because of the changes in definitional packages, and we need to update `bin/leantags` and `src/emacs/lean-tags.el` file. I'll do that after class.
