### ISSUE TITLE
unfold definition from same context

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#466]
It's a bit strange that it seemingly impossible to unfold a definition from the same context in tactics mode:

``` lean
open eq

context
  parameter (A : Type)

  definition foo (a : A) : a = a := refl a
end

context
  parameter (A : Type)

  definition bar (a : A) : foo A a = refl a :=
  begin
    unfold foo,
  end

end
```

Can you make that possible somehow?

**Comment by leodemoura** [comment]
Just to make it clear. The example in your post works. They one that doesn't work is

``` lean
context
  parameter (A : Type)

  definition foo (a : A) : a = a := refl a

  definition bar (a : A) : foo A a = refl a :=
  begin
    unfold foo,
  end

end
```

In the context where `foo` is defined, the expression `foo` is an alias for `foo A`. This is why `unfold foo` doesn't work. I will fix this.
In the meantime, you can use `esimp {foo}`. The `esimp` is going to apply `beta` and `iota`, and can optionally unfold definitions.

**Comment by javra** [comment]
Ah, of couse. I copied the wrong example ;) Thanks for the hint with `esimp`!
