### ISSUE TITLE
unsolved metavariables with ap

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#469]
The following example produces an "unsolved metavariables"-error:

``` lean
open eq is_equiv

variables {A : Type} {B : A → Type} {C : Πa, B a → Type}

definition homotopy2 [reducible] (f g : Πa b, C a b) : Type :=
Πa b, f a b = g a b
notation f `∼2`:50 g := homotopy2 f g

definition eq_of_homotopy2 {f g : Πa b, C a b} (H : f ∼2 g) : f = g :=
eq_of_homotopy (λa, eq_of_homotopy (H a))

definition apD100 {f g : Πa b, C a b} (p : f = g) : f ∼2 g :=
λa b, apD10 (apD10 p a) b

definition foo (f g : Πa b, C a b) (H : f ∼2 g) (a : A)
  : apD100 (eq_of_homotopy2 H) a = H a :=
begin
  apply concat, apply (ap (λx, apD10 (x a))), apply (retr apD10),
  apply (retr apD10)
end
```

It occurs in the following subterm: `(λ (x : ?M_1), C a x)`, but this is solvable just with first-order unification, because the type of `C` known. 
(the proof is accepted when the second tactic is replaced by 
`apply (ap (λx, @apD10 _ (λx : B a, _) _ _ (x a))),`)

Another comment: I don't see why `apply (retr apD10)` works here. The printed definition reveals that `foo` finds the instance `funext.is_equiv_apD`, but this instance should be only available in the namespace `funext`. The command `print instances is_equiv` doesn't print this instance.

**Comment by leodemoura** [comment]
> The printed definition reveals that foo finds the instance funext.is_equiv_apD

It is not using type class resolution for solving `foo`.
I believe the `funext.is_equiv_apD` appears when the unification constraints are solved.
The definition of `eq_of_homotopy` is:

``` lean
λ (A : Type) (P : A → Type) (f g : Π (x : A), P x),
  @inv (@eq (Π (x : A), P x) f g) (@homotopy A (λ (x : A), P x) f g) (@apD10 A P f g)
    (@funext.is_equiv_apD A (λ (x : A), P x) f g)
```

and it is unfolded when solving the unification constraints.

**Comment by fpvandoorn** [comment]
Ah, that makes sense. Interesting!

It is a little fragile, though, because writing `apply (retr apD10 (*explicit term*))` fails, because then it is using type class resolution. So it is better to open `funext` in either case.

**Comment by leodemoura** [comment]
Reopening: I closed the wrong issue

**Comment by leodemoura** [comment]
@fpvandoorn I cannot reproduce the bug above anymore due to changes in the HoTT library (wild guess). Could you please double check?

Thanks!

**Comment by fpvandoorn** [comment]
I also cannot reproduce it anymore. I also don't have to give the implicit argument anymore [in the original location](https://github.com/fpvandoorn/lean/commit/f605159e00552161bd703fd187eeb1ca70c454bc).

**Comment by leodemoura** [comment]
Good. We have been fixing some many things... :-)
Eventually a bugfix fixes more than one problem...
