### ISSUE TITLE
make rewrite more robust

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#470]
I'm still using `apply concat, apply ap ..., apply H` often as substitute for `rewrite H`. Rewrite is very nice when it works, but it still fails often. Then it gives a unhelpful error message and there's not always a good way to give extra information. Currently, I (and Jakob as well) find that it is faster to give some more explicit information with `concat`/`ap`/`apply`. But maybe the rewrite tactic can be improved to work for all our cases.

For example, in the definition of issue #469 I don't know how to use rewrite to make progress. In the following example, I give quite some information (more than I usually want to give), but it still fails.

``` lean
open eq is_equiv funext

variables {A : Type} {B : A → Type} {C : Πa, B a → Type}

definition homotopy2 [reducible] (f g : Πa b, C a b) : Type :=
Πa b, f a b = g a b
notation f `∼2`:50 g := homotopy2 f g

definition eq_of_homotopy2 {f g : Πa b, C a b} (H : f ∼2 g) : f = g :=
eq_of_homotopy (λa, eq_of_homotopy (H a))

definition apD100 {f g : Πa b, C a b} (p : f = g) : f ∼2 g :=
λa b, apD10 (apD10 p a) b

definition foo (f g : Πa b, C a b) (H : f ∼2 g) (a : A)
  : apD100 (eq_of_homotopy2 H) a = H a :=
begin
  esimp {apD100, eq_of_homotopy2},
  rewrite {apD10 (eq_of_homotopy (λ(a : A), eq_of_homotopy (H a)))}(retr apD10 (λ(a : A), eq_of_homotopy (H a))),
end
```

In a different situation I tried to rewrite using theorems like the following

``` lean
  definition transport_eq_l (p : a1 = a2) (q : a1 = a3)
    : transport (λx, x = a3) p q = p⁻¹ ⬝ q :=
```

However, this fails because there is a binder in the conclusion. Would it be an idea to match (subterms of) the goal with `transport ?M_1 ?M_2 ?M_3`, i.e. to replace a binder with a metavariable (just as the matcher replaced "`?M_1` applied to `?M_2`" with a fresh metavariable in issue #433).

**Comment by leodemoura** [comment]
I'm confused. The goal is:

``` lean
(λ (b : B a), apD10 (apD10 (eq_of_homotopy2 H) a) b) = H a
```

We can eta reduce it to

``` lean
apD10 (apD10 (eq_of_homotopy2 H) a) = H a
```

The type of `retr apD10 (λ(a : A), eq_of_homotopy (H a))` is

``` lean
apD10 (apD10⁻¹ (λ (a : A), eq_of_homotopy (H a))) =  λ (a : A), eq_of_homotopy (H a)
```

So, its left-hand-side does not match any subterm in the goal.

**Comment by leodemoura** [comment]
> Then it gives a unhelpful error message and there's not always a good way to give extra information.

It is not easy to give a good error message. The tactic is trying to match the left-hand-side of the given equation with all subterms in the goal (and/or hypotheses). There are many failures.
It would be a tsunami of information to report all failures.
What about the following compromise?
1) We display which term the rewriting is using for pattern-matching.
2) We report which sub-terms in the goal matched the pattern.
3) For the ones that matched, we report the unification failure error message: given type vs expected type.

**Comment by leodemoura** [comment]
> In a different situation I tried to rewrite using theorems like the following
> 
> ``` lean
>   definition transport_eq_l (p : a1 = a2) (q : a1 = a3)
>     : transport (λx, x = a3) p q = p⁻¹ ⬝ q :=
> ```

Could you post the complete example?

Thanks

**Comment by fpvandoorn** [comment]
> I'm confused.

I forgot to also unfold `eq_of_homotopy` (maybe we should make that reducible). When unfolding `eq_of_homotopy` (and `eq_of_homotopy2`, which I did do), the goal becomes (up to eta-equivalence)

```
apD10 (apD10 (apD10 ⁻¹ (λ (a : A), apD10 ⁻¹ (H a))) a) = H a
```

so we can (I think) match the left-hand-side of the type of the rewrite term with the `_` in `apD10 (_ a) = H a`. However, also unfolding `eq_of_homotopy` doesn't help (but note from #469 that using 
`apply concat, apply (ap (λx, @apD10 _ (λx : B a, _) _ _ (x a))), apply (retr apD10),` 
does work)

> It is not easy to give a good error message. 

I understand. My comment was not meant as "this should be changed ASAP" but as a comment that unfortunately the current error messages don't help very well with finding the problem when a rewrite tactic doesn't work. I think your suggestion is very good, and can the resulting information can be very helpful. Maybe it will sometimes print too much information, but that's usually better than too little.

> Could you post the complete example?

A simple example would be

```
import types.eq

open eq
  variables {A : Type} {a1 a2 a3 : A}
  definition my_transport_eq_l (p : a1 = a2) (q : a1 = a3)
    : transport (λx, x = a3) p q = p⁻¹ ⬝ q :=
  begin
    rewrite transport_eq_l,
  end
```

A more involved example would be replacing line 44 in [types.fiber](https://github.com/leanprover/lean/blob/master/hott/types/fiber.hlean#L44) with `rewrite transport_eq_Fl,`

**Comment by leodemoura** [comment]
I added the `unfold eq_of_homotopy`. The `rewrite` doesn't succeed because the pattern matcher does **not** perform matching modulo eta-reduction. We can add a tactic for eta reduction, or even do it at `esimp`. If we do eta by hand, the rewrite works if `eq_of_homotopy` is marked reducible.
Here is the working version:

``` lean
local attribute eq_of_homotopy [reducible]

definition foo (f g : Πa b, C a b) (H : f ∼2 g) (a : A)
  : apD100 (eq_of_homotopy2 H) a = H a :=
begin
  esimp {apD100, eq_of_homotopy2, eq_of_homotopy},
  -- goal is
  -- (λ (b : B a), apD10 (apD10 (apD10 ⁻¹ (λ (a : A), apD10 ⁻¹ (H a))) a) b) = H a
  -- Applying eta by hand
  change (apD10 (apD10 (apD10 ⁻¹ (λ (a : A), apD10 ⁻¹ (H a))) a) = H a),
  -- It will only match because eq_of_homotopy is reducible
  rewrite (retr apD10 (λ(a : A), eq_of_homotopy (H a)))
end
```

**Comment by fpvandoorn** [comment]
> The `rewrite` doesn't succeed because the pattern matcher does not perform matching modulo eta-reduction.

That's good to know. I think this won't be a problem if there is some tactic to do eta reduction (using `change` by hand is quite tedious)

> We can add a tactic for eta reduction

That would be nice. Tactics typically become much more readable after eta-reducing, so an `eta` command is useful. I think it would also be nice to automatically do eta-reduction with `esimp`, especially since `esimp` itself sometimes adds extra eta-reducible expressions (like in this example).

**Comment by leodemoura** [comment]
I added support for eta-reduction in the `esimp` tactic.
It is not enough for the problem above because the type of `(retr apD10 (λ(a : A), eq_of_homotopy (H a)))` also contains non-eta reduced terms (in the implicit arguments). 
So, I also added support for matching modulo eta.

Now, we can do it using

``` lean
local attribute eq_of_homotopy [reducible]

definition foo (f g : Πa b, C a b) (H : f ∼2 g) (a : A)
  : apD100 (eq_of_homotopy2 H) a = H a :=
begin
  esimp {apD100, eq_of_homotopy2, eq_of_homotopy},
  rewrite (retr apD10 (λ(a : A), eq_of_homotopy (H a))),
  apply (retr apD10)
end
```

I'll create another issue for improving the rewrite tactic error message.

**Comment by leodemoura** [comment]
issue was fixed by:
https://github.com/leanprover/lean/commit/a9fa0fead9175165dea48a96b88bf10d05e51135
https://github.com/leanprover/lean/commit/7de3d5771df1e80591289f19c782836d052f5c55
