### ISSUE TITLE
parentheses around abbreviations

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#475]
Here's an example where the parentheses around an abbreviation are not printed correctly:

```
import algebra.precategory.basic

open category

example {C : Precategory} : C = Precategory.mk C C := _
```

Hovering over `_` gives

```
don't know how to synthesize placeholder
C : Precategory
⊢ C = Precategory.mk carrier C C
```

while the last term should be `C = Precategory.mk carrier C C`.

**Comment by leodemoura** [comment]
closed by b5acbb222893264a60
