### ISSUE TITLE
Support for degenerate rings

### ISSUE THREAD

**Issue by fgdorais** [leanprover/lean3#478]
The ring and semiring classes extend the `zero_ne_one_class`. While this is usually a good assumption, this excludes degenerate rings and prevents the use of some convenient algebraic facts for possibly degenerate rings. I think it would be desirable to factor out this hypothesis where it is not relevant (though this is clearly not a pressing issue at this time).

**Comment by avigad** [comment]
This is reasonable -- I will make the change soon.
