### ISSUE TITLE
add an "induction" tactic

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#483]

**Comment by fpvandoorn** [comment]
Very nice! I'll extensively test this soon. :-)

**Comment by leodemoura** [comment]
Great!
BTW, I'm testing an extension needed for `finset`: parameters that can be synthesized by type class resolution.
The type of `finset.induction` is:

``` lean
  ∀ {A : Type} [h : decidable_eq A] {P : finset A → Prop},
    P finset.empty →
    (∀ {s : finset A} {a : A}, ¬finset.mem a s → P s → P (finset.insert a s)) → 
    (∀ (s : finset A), P s)
```

Note that the parameter `h` does not occur in the major premise `s : finset A`.

**Comment by avigad** [comment]
BTW, I plan to change the order of arguments in the second hypothesis. I found it confusing to write "take s a, assume H : a in s".

**Comment by leodemoura** [comment]
@avigad  The new `induction` tactic is quite convenient for applying `finset.induction`. See
https://github.com/leanprover/lean/commit/3e87f09d7890d98ebd6cf380d4a87c86130a5e73
The `take ..., assume ..., assume ...` pattern can be avoided. Here is a new proof:

``` lean
theorem inter_Union (s : finset B) (t : finset A) (f : A → finset B) :
      s ∩ (⋃ x ∈ t, f x) = (⋃ x ∈ t, s ∩ f x) :=
  begin
    induction t with s' x H IH,
      rewrite [*Union_empty, inter_empty],
      rewrite [*Union_insert_of_not_mem _ H, inter.distrib_left, IH],
  end
```

**Comment by avigad** [comment]
Excellent. (I still think I should switch the order of arguments, though.)

The proof term and tactic proof are about the same length, and about as easy to read / understand / write. Do you think the tactic idiom should generally be preferred for induction proofs, because it puts less burden on the elaborator?

**Comment by leodemoura** [comment]
> Do you think the tactic idiom should generally be preferred for induction proofs, because it puts less burden on the elaborator?

Good question. I'm thinking about that. The only problem with the tactic version is the syntax. For `nat` and `finset` is not a big deal, but if we have many cases it is quite messy to list all parameters in the `with` argument. I think it would be nice to add special syntax for the `induction` and `cases` tactic.
Something like:

``` lean
 induction t
 |           := rewrite [*Union_empty, inter_empty]
 | s' x H IH := rewrite [*Union_empty, inter_empty]
```

The idea would be to make each case explicit, and separate the identifiers.
We can also make this construction available in term-mode. 

BTW, the `induction` tactic also implements the `revert-apply-intro` idiom when needed.

**Comment by fpvandoorn** [comment]
About the `finset.induction`, is it possible to interchange the arguments `h` and `P`, and treat `h` as a minor premise? If I replace line 197 in `finset.basic` by

``` lean
omit h
protected theorem induction [recursor] {P : finset A → Prop} [h : decidable_eq A]
```

the definition is accepted.

**Comment by leodemoura** [comment]
> About the finset.induction, is it possible to interchange the arguments h and P, and treat h as a minor premise?

Yes, it is possible, but it will generate a goal for `decidable_eq A`. 
BTW, I should probably add a tactic for invoking type class resolution. We talked about that in the past, but I did not implement it.

**Comment by fpvandoorn** [comment]
Ok, that makes sense.

Yes, a tactic for invoking type class resolution is useful. Although `exact _` also works pretty well (which I've used a couple of times).
