### ISSUE TITLE
cases tactic for user-defined recursors

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#492]
(4) make `cases`-tactic extendible, for example:

``` lean
cases F using homotopy.rec_on
```

where 

``` lean
  definition homotopy.rec_on {A : Type} {B : A → Type} {f g : Πa, B a} {P : (f ∼ g) → Type}
    (p : f ∼ g) (H : Π(q : f = g), P (apD10 q)) : P p :=
  retr apD10 p ▹ H (eq_of_homotopy p)
```

@fpvandoorn: it would be much simpler to implement if we do not consider "indices". That is, the "motive" `P` would always have type of the form: `P : t -> Type`. 
For example, the motives for `list` and `category` are:  `C : list T -> Type` and `C : category ob -> Type`.  The motive for `vector` is different since it is an indexed family `C : forall n : nat, vector A n -> Type`. This includes `homotopy.rec_on`.
Do you have examples that would not be covered if we have this restriction?
@avigad: and you? 

A definition can be considered recursor-like when
1- There is an argument of the form `(P : t -> Type)`  (the motive)
2- Arguments before `(P : t -> Type)` are assumed to be parameters
3- The argument immediately after `(P : t -> Type)` is assumed to be the main premise.
4- The remaining arguments are assumed to be minor premises (they will be used to generate the subgoals)
5- The resulting type is of the form `P p` where `p` is the major premise.

What do you think?

**Comment by leodemoura** [comment]
Another restriction: we should be able to infer all parameters (but the motive) from the major premise.
This is the case for `homotopy.rec_on` and all inductive datatypes automatically generated `rec_on`s.

Issue: The inductive datatypes are nice because given an inductive datatype `C`, `C As` is in whnf.
This is not the case for user-provided recursors. Example: `homotopy` is a (reducible) definition.
So, we need a reliable way to check whether things match. One option is to do the matching assuming all definitions are opaque. 

Another improvement: make this feature available for recursive equation and match-with compilation.
I think it would be nice. The user would be able to write

``` lean
theorem foo  ... : f ~ g -> g ~ h -> C
| (apD10 e1) (apD10 e2) := ...   
```

**Comment by fpvandoorn** [comment]
>  it would be much simpler to implement if we do not consider "indices". That is, the "motive" P would always have type of the form: P : t -> Type. 

Currently all my examples are like this, but I haven't worked with indexed families yet.

> Issue: The inductive datatypes are nice because given an inductive datatype C, C As is in whnf.
> This is not the case for user-provided recursors. Example: homotopy is a (reducible) definition.
> So, we need a reliable way to check whether things match. One option is to do the matching assuming all definitions are opaque.

Can you explain why this is a problem? You have to match the variable `p` (of type `f ∼ g`) with subterms of the goal, right? Do you also have to match `f ∼ g` in the goal? But if it is required, I think assuming that all definitions are opaque is reasonable.

**Comment by leodemoura** [comment]
> Can you explain why this is a problem?

In the `cases` tactic, I use `whnf` followed by a syntactic check to decide whether `cases` is applicable or not. It is also used in the middle of the procedure. 
For example, for selecting the `cases_on` function, I put the type of the hypothesis in whnf. Assume it is of the form `C As`, then I know I should use `C.cases_on`.  
This works well because inductive datatypes and constructors are opaque constants.

To implement the feature above, I want to allow the user to associate recursors with constants `C`. 
Example: `homotopy` --> `homotopy.rec_on`. The problem is that `homotopy` is reducible. 
So, the current approach whnf + syntactic check does not work.

**Comment by fpvandoorn** [comment]
Ah, ok. Yes, then it sounds good to not unfold. 
But I also wouldn't mind writing explicitly which theorem I want to use when using this extended `cases`-tactic. It would be nice if that is not required, but that might become ambiguous (if both a regular recursor is possible after unfolding definitions, or a user-defined recursor without unfolding).

**Comment by leodemoura** [comment]
> But I also wouldn't mind writing explicitly which theorem I want to use when using this extended cases-tactic. It would be nice if that is not required, but that might become ambiguous (if both a regular recursor is possible after unfolding definitions, or a user-defined recursor without unfolding).

I will allow users to specify the theorem explicitly as you suggested. 
The automatic mode will be useful for compiling recursive equations and match-with expressions.

**Comment by avigad** [comment]
I am afraid I have no useful comments here -- I agree with everything that has been said.

**Comment by fpvandoorn** [comment]
I have defined some recursors myself now which do have indices. Examples are a custom recursor for [pathovers](https://github.com/leanprover/lean/blob/master/hott/cubical/pathover.hlean#L126-127) and multiple for [squares](https://github.com/leanprover/lean/blob/master/hott/cubical/square.hlean#L79-129). The pathover file also contains some examples where `pathover.idp_rec_on` is used. 

**If** we implement the `cases` tactic for user-defined recursors with indices, the constraints look like this (these constraints hold in all my examples):

A definition can be considered recursor-like _with indices_ when
- There is an argument of the form `(P : Pi {a0 : A0} {a1 : A1 a0} ... {an : An a0 a1 ...}, t a0 a1 ... an -> Type)` (the motive)
- Arguments before `(P : t -> Type)` are parameters
- All indices and all parameters can be inferred from `t a0 a1 ... an`
- The `n` arguments after the motive are indices `{a0 : A0} {a1 : A1 a0} ... {an : An a0 a1 ...}`
- The argument immediately after the indices is the main premise `(p : t a0 a1 ... an)`
- The remaining arguments are assumed to be minor premises (they will be used to generate the subgoals)
- The resulting type is of the form `P p` (i.e. `@P a0 a1 ... an p`)

However, the examples of user-defined recursors _without_ indices are still more numerous (especially now with HITs), so if it is much harder to support recursors with indices it may be worthwhile to just implement the simpler case.

---

_(side note)_
For squares the situation is especially crazy. A square is an inductive type which has 4 paths as indices: the boundaries of the square:

``` lean
  inductive square {A : Type} {a₀₀ : A}
    : Π{a₂₀ a₀₂ a₂₂ : A}, a₀₀ = a₂₀ → a₀₂ = a₂₂ → a₀₀ = a₀₂ → a₂₀ = a₂₂ → Type :=
  ids : square idp idp idp idp
```

Now if you have an arbitrary element of `square t b l r` then you can apply the recursor only if all the paths and all the corners (except perhaps one) are variables. So if you have an element of `square t b l idp`, where one of the paths is the identity path, you cannot apply the recursor. However, you can define a new recursor for this case, which can be applied if the remaining paths and points are all variables. And you need recursors for different situations. For example, "most general" elements of `square t idp l idp` or `square idp b idp idp` both need their own recursor. In total this gives rise to 14 user-defined recursors just for squares. I actually don't know how often they come up in practice. However, Dan Licata's Agda file from which I'm taking the ideas does define some of these, so they are probably sometimes useful.

**Comment by leodemoura** [comment]
Dear Floris,

Here is a list of issues I have been thinking about (and struggling with).

1- It would be nice to have a single module that implements `induction` and `cases` tactics with support for user provided recursors. The current `cases` tactic would be just a special case where the inductive hypothesis is suppressed. Note that, with user provided recursors, there is no way to prevent the user from providing `t.induction_on`. The main motivation is to avoid code duplication.

2- Everything is clear if we don't have indexed families.  With indexed families, (I think) it is a big mess. There are a couple of issues. The main issue is that the types are different in each minor premise. For example, consider the recursor for `vector A n`:

``` lean
@vector.rec :
  Π {A : Type} {C : Π (a : nat), vector A a → Type},
    C 0 nil →
    (Π {n : nat} (a : A) (v : vector A n), C n v → C (succ n) (cons a v)) →
    (Π {a : nat} (n : vector A a), C a n)
```

Given a goal `h, v : vector A n |- c` where `h` represents the other hypotheses and `c` the conclusion, when we apply `cases v`, it creates two goals. 
In the first goal, we can't simply replace `v` with `nil`, since it would produce a type incorrect goal.

The standard trick is to convert the goal into

``` lean
h, v : vector A n, n_1 : nat, v_1 : vector A n_1 |- n = n_1 -> v == v_1 -> c    
```

(if it is the standard library)
and

``` lean
h, v : vector A n, n_1 : nat, v_1 : vector A n_1 
    |-  Pi (e : n = n_1) -> eq.rec v e = v_1 -> c    
```

(if it is the HoTT library)

Then, we apply the recursor on `v_1` instead of `v`. We know it will not produce a type incorrect goal.

First problem: to process the equation on the new goal, we use `no_confusion`. This works great for the standard library, but it is problematic for the HoTT library. Recall the following comment: https://github.com/leanprover/lean/issues/500#issuecomment-98259965

Second problem: inductive hypothesis will be messy. Since we apply the recursor on the auxiliary goal, the inductive hypothesis will contain these messy auxiliary equalities. 
Moreover, in most cases the inductive hypotheses would be useless. 
For example for vector, the minor premise 

``` lean
(Π {n : nat} (a : A) (v : vector A n), C n v → C (succ n) (cons a v))
```

for the goal

``` lean
h, v : vector A n, n_1 : nat, v_1 : vector A n_1 |- n = n_1 -> v == v_1 -> c    
```

would look like

``` lean
        (Π {n' : nat} (a' : A) (v' : vector A n1), (n' = n_1 -> v' == v_1 -> c) → 
              succ n' = n_1 -> cons a' v' == v_1 -> c
```

I say the inductive hypothesis is useless because `n' = n_1` is uninhabited since we have `succ n' = n_1`.

Third problem: to process the auxiliary equations introduced in previous step, we use `no_confusion`. 
That is, we are using the fact constructors are injective and pair-wise distinct. 
Moreover, we are using the fact that in every minor premise, the conclusion contains only constructor applications. For example, in vector, the conclusion of the first minor premise is `C 0 nil` and the second `C (succ n) (cons a v)`. For user provided recursors, there is no guarantee that the conclusion of each minor premise will contain only variables and constructor applications.

My problem is that I don't see a way to generalize the trick that converts a goal

``` lean
h, v : vector A n |- c
```

into

``` lean
h, v : vector A n, n_1 : nat, v_1 : vector A n_1 |- n = n_1 -> v == v_1 -> c    
```

in such a way it will work for `induction` and user provided recursors.

So far, the best I could come up with is the following: try the recursor as given, and check if the result is type correct. If it is not, generate an error. We can try to automate the `revert` + `apply rec` + `intro` idiom, but beyond that, I don't see how to do it.

**Comment by fpvandoorn** [comment]
I see the problems. I tend to forget how complicated the current `cases` tactic is.
Some questions:
- If I write `cases t` (or in future `induction t`) where `t` is an element of an inductive type _without_ indices, does the `cases` tactic do things which `revert` + `apply rec` + `intro` cannot do?
- If "yes", were you planning to have those features as well for `cases` for user-defined "recursors"?

I think that I'm completely fine with a solution where `cases`/`induction` user-defined recursors is just an automated way of doing  `revert` + `apply rec` + `intro` for type families with indices.

Let me elaborate on the last point. I think that so far every time I used `cases`, for me it was a shortcut for `revert` + `apply rec` + `intro` (but maybe I'm missing something here). For vectors, it is super useful that you can case on a vector `v : vector A (succ n)`. But the type families I've been using most is equality, and there you cannot do a trick like that. If you want to recurse on `p : a = b`, then `b` must be a variable, otherwise it fails (I just see that I can also do cases on something like `p : succ a = succ b` or `p : succ a = 0`. I didn't know that. That is neat!)

I _think_ that in general, (using the notation from my previous post), if we have a variable
`(p : t a0 a1 ... an)` and we want to use `cases p` with a custom recursor, then _as long as `a0, a1, ... an` are variables_ just doing `revert` + `apply rec` + `intro` works, and I'm fine with a solution which does just that.

Actually, the custom recursors I define for `pathover`/`square` are exactly for the cases where a parameter is _not_ a variable, but instead it is `idp`.

**Comment by leodemoura** [comment]
> If I write cases t (or in future induction t) where t is an element of an inductive type without indices, does the cases tactic do things which revert + apply rec + intro cannot do?

No, it essentially doing just that. It computes the dependencies, revert them, apply rec, then introduce back everything, and clears the eliminated hypothesis.

> If "yes", were you planning to have those features as well for cases for user-defined "recursors"?

Yes.

For non-indexed families, it is clear to me what must be done.

> I just see that I can also do cases on something like p : succ a = succ b or p : succ a = 0. I didn't know that. That is neat!

In the HoTT library, it only works if it is a constructor of a hset. For the standard library, we can handle any constructor. In principle, we could extend it to any injective function.

>  I'm fine with a solution which does just that.

Great.

**Comment by leodemoura** [comment]
For the record, here is a list of additional limitations:
1- The recursor must have only one motive. Builtin recursors for mutually recursive datatypes have multiple motives. The induction tactic will not support them. We will also not support user-defined recursors with multiple motives.
2- User-defined recursors must perform dependent elimination. That is, the motive depends on the major premise.
3- The `Type` in the motive is really `Type.{0}` or `Type.{l}` where `l` is a universe parameter. The case `Type.{0}` (aka Prop) is only supported in the standard library. That is, we will not support a recursor where the motive is, for example, of the form `(P : Pi {a0 : A0} ... {an : An a0 a1 ...}, t a0 ... an -> Type.{l+1})`

**Comment by leodemoura** [comment]
@fpvandoorn The commit above allow us to annotate declarations as recursors. It also checks whether the recursor is well-formed or not. We can inspect the information stored internally by using `print [recursor] id`.
Here is an example

``` lean
import data.nat
attribute nat.strong_induction_on [recursor]
print [recursor] nat.strong_induction_on
```

**Comment by fpvandoorn** [comment]
Sorry for my late response.

(1) That sounds fine.
(2) That's too bad. So it won't work for the non-dependent eliminators for hits, such as [`circle.elim`](https://github.com/leanprover/lean/blob/master/hott/hit/circle.hlean#L121-123)?
(3) I think that covers all my recursors so far.

Is the `[recursor]` attribute needed for the `match-with` expression?

I tried applying the `[recursor]` attribute to some of the defined recursors. It works for

``` lean
definition rec_on_ua [recursor] {A B : Type} {P : A ≃ B → Type}
  (f : A ≃ B) (H : Π(q : A = B), P (equiv_of_eq q)) : P f
```

However, it doesn't work for some others:

``` lean
protected definition homotopy.rec_on {Q : (f ∼ g) → Type} (p : f ∼ g)
  (H : Π(q : f = g), Q (apd10 q)) : Q p
```

_"invalid user defined recursor, motive 'Q' must have a type of the form (C:Pi (i:B A), I A i -> Type), where A is (possibly empty) sequence of bound variables (aka parameters), (i:B A) is a (possibly empty) telescope (aka indices), and I is a constant"_

``` lean
definition trunc.rec_on [reducible] {n : trunc_index} {A : Type} {P : trunc n A → Type}
  (aa : trunc n A) [Pt : Πaa, is_trunc n (P aa)] (H : Πa, P (tr a)) : P aa
definition type_quotient.rec_on [reducible] {A : Type} {R : A → A → Type} {P : type_quotient R → Type}
  (x : type_quotient R) (Pc : Π(a : A), P (class_of R a))
  (Pp : Π⦃a a' : A⦄ (H : R a a'), eq_of_rel R H ▸ Pc a = Pc a') : P x
```

_"invalid user defined recursor, resultant type of minor premise 'Pt' must be of the form (P ...)"_

Is the problem with the first that `homotopy` is a definition instead of a constant?
For the others, is the restriction on the type for minor premises necessary?

**Comment by leodemoura** [comment]
> (2) That's too bad. So it won't work for the non-dependent eliminators for hits, such as circle.elim?

I added this restriction because it makes it really easy to detect the major premise.
What about the following alternative?
- We have a different attribute to mark recursors that implement non dependent elimination.
- In this case, Lean assumes the major premise is the first argument (from right to left) that does _not_ "produce" the motive.

**Comment by leodemoura** [comment]
Ooops, updated the previous comment: "does **not** produce"

**Comment by leodemoura** [comment]
> However, it doesn't work for some others:

I will investigate and fix.
It would be super useful if you could me send as many problematic examples as possible. Then, I will make sure it will work for all examples you care about.

**Comment by leodemoura** [comment]
> Is the problem with the first that homotopy is a definition instead of a constant?

I will fix that. It must work for definitions too. For example, in the standard library, we want to use this feature for handling `finset` and other types defined using quotients.

**Comment by leodemoura** [comment]
> Is the [recursor] attribute needed for the match-with expression?

My initial goal is to use this attribute to implement the `induction` tactic. 
For example, given `(s : finset A)`, we will be able to write
`induciton s` instead of `induction s using finset.induction_on`.

BTW, even if we are willing to use `induction ... using ...`, it is still useful to mark the definition with `[recursor]` because Lean will pre-calculate all information for us (and validate whether the definition is a valid recursor or not).

The second application is the `blast` tactic that I'm (trying to) develop.
It will automatically try different recursion principles provided by the user.

The `match ... with` is in a distant future.

**Comment by leodemoura** [comment]
BTW, I said the support for user-defined recursors in `match ... with` is in a distant future because it applies multiple recursors. It is not clear to me how to let the user select recursors for subterms, and/or control the search if we try to guess which recursor should be used in the multiple steps.

**Comment by leodemoura** [comment]
> For the others, is the restriction on the type for minor premises necessary?

Not really. The motive in the conclusion of a minor premise helps for detecting when to stop applying `intros` for each new subgoal. For example, suppose we have a minor premise of the form `H : decidable_eq A`. Should the new subgoal be `|- decidable_eq A` or `x y : A |- decidable (x = y)`?

**Comment by fpvandoorn** [comment]
> In this case, Lean assumes the major premise is the first argument (from right to left) that does not "produce" the motive.

I'm fine if this is always assumed. I thought that was currently already the case. So I'd be perfectly happy if this becomes the default, but maybe it's confusing to have this restriction.

~~Another idea would be to infer the type of the major premise from the motive, and then let the major premise be the first (hopefully unique) variable with that type.~~

> It would be super useful if you could me send as many problematic examples as possible

I will look for more.

> My initial goal is to use this attribute to implement the `induction` tactic. 

Okay, great! So the `induction` tactic will not treat the automatically generated `foo.rec_on` specially? That will be just another identifier with the `[recursor]` attribute?
How will `induction` decide which recursor to use if multiple are applicable?

> The `match ... with` is in a distant future.

That's fine.

> The motive in the conclusion of a minor premise helps for detecting when to stop applying intros for each new subgoal.

I think the best behavior is to introduce the same number of variables as Pi's or forall's the user has written down explicitly in the type of the minor premise. 
A good approximation of this behavior is to use `intros` as often as possible while treating all `definitions` and the motive as opaque (is something like this possible?).
(there is a difference between these behaviors for example when `decidable_eq` is an abbreviation and there is a minor premise `H : decidable_eq A`. In this case I think the first behavior is slightly preferable, but the second one is also good)

**Comment by fpvandoorn** [comment]
An example which also currently fails

``` lean
-- cubical.pathover
  definition idp_rec_on [recursor] {P : Π⦃b₂ : B a⦄, b =[idpath a] b₂ → Type}
    {b₂ : B a} (r : b =[idpath a] b₂) (H : P idpo) : P r
```

Error: _invalid user defined recursor, motive 'P' must have a type of the form (...)_. 
It looks like `P` has that form to me. (the same problem probably happens in `rec_on_b` in `cubical.square`).

An example to test non-dependent recursors:

``` lean
-- hit.circle
  protected definition elim_on [reducible] {P : Type} (x : circle) (Pbase : P)
    (Ploop : Pbase = Pbase) : P
```

I think allowing these will allow all recursors which I've currently dfined.

Induction-like principles which will probably require major work to allow, so where I'm fine if they are not implemented:

``` lean
-- init.ua (I think this only exists in my personal repository so far)
  definition rec_on_ua2 {A B : Type} {P : A ≃ B → A = B → Type}
    (f : A ≃ B) (H : Π(q : A = B), P (equiv_of_eq q) q) : P f (ua f)

-- types.W
  definition double_induction_on {P : (W a, B a) → (W a, B a) → Type} (w w' : W a, B a)
    (H : ∀ (a a' : A) (f : B a → W a, B a) (f' : B a' → W a, B a),
      (∀ (b : B a) (b' : B a'), P (f b) (f' b')) → P (sup a f) (sup a' f')) : P w w'
```

**Comment by fpvandoorn** [comment]
> Another idea would be to infer the type of the major premise from the motive, and then let the major premise be the first (hopefully unique) variable with that type. 

I realize now that this is not possible for non-dependent recursors.

**Comment by leodemoura** [comment]
> So the induction tactic will not treat the automatically generated foo.rec_on specially?

It will. I'm planning to use the following heuristic for the `induction` tactic. If it is a builtin inductive datatype, then we use the automatically generated recursor. If it is not, then we use the last definition marked with `[recursor]`. Note that `finset`, `rat` and `int` are not builtin inductive datatypes, but definitions based on quotients. The heuristic is useful for this kind of type.

> That will be just another identifier with the [recursor] attribute?

The module that manages the user-defined recursors is also taking the automatically generated ones into account. 

> How will induction decide which recursor to use if multiple are applicable?

It gives preference to the last one (if the major premise is not a builtin inductive datatype).

The `blast` tactic will try first the builtin and then cycle over the user defined ones.

**Comment by fpvandoorn** [comment]
That sounds good! 
As long as we can override the behavior which one to use via `induction x using ...`, for example if I want to use `equiv.rec_on_ua` instead of `equiv.rec_on`.

**Comment by leodemoura** [comment]
I'm working on this module today.
I have fixed the following cases: `homotopy.rec_on`, `trunc.rec_on` and `type_quotient.rec_on`.
I'm working on `idp_rec_on`. It doesn't go through because I was assuming that a major premise was of the form `h : C A i` where `A` are the parameters and `i` the indices. This is not the case for `idp_rec_on` because the major premise has "extra" information. This complicates the induction tactic but it is still feasible to implement. The idea is to store a mapping that indicates where the parameters and indices are located in the major premise.

For non-dependent elimination, the user will have to say which argument is the major premise. Something like `[recursor pos]`. The left-to-right heuristic doesn't always work.

Regarding `rec_on_ua2` and `double_induction_on`, they will not be supported.
In the first one, we have `ua f` in the conclusion. In the second one, we have two major premises.

**Comment by fpvandoorn** [comment]
I do not see the problem with `idp_rec_on`. Is it required that `C` is an identifier, or can it be something like `fun A a B b b2, @pathover A a B b a (idpath a) b2`. Because if the latter is allowed, then we can take `A a B b` as parameters and `b2` as index, and the major premise contains exactly the information the motive is expecting, right?

I tried to workaround this by using an intermediate definition, but I got a segfault because of the `[recursor]` attribute

``` lean
-- HoTT
import cubical.pathover
open cubical eq
variables {A : Type} {a : A} {B : A → Type} (b : B a)

definition pathover_idp (b₂ : B a) := b =[idpath a] b₂

definition idp_rec_on' [recursor] {P : Π⦃b₂ : B a⦄, pathover_idp b b₂ → Type}
  {b₂ : B a} (r : pathover_idp b b₂) (H : P idpo) : P r :=
idp_rec_on r H
```

`C-c C-x` output: `Compilation bus error (core dumped)`
command-line output: `Segmentation fault (core dumped)`

**Comment by leodemoura** [comment]
> I do not see the problem with `idp_rec_on`.

There is no problem, I just have to work harder, and implement a more general solution. 
The induction tactic is creating a recursor application. In this recursor application, we "fix" the parameters and indices using the information available in the major premise. We only have to create subgoals for the minor premises.
In the approach I was using, the major premise would be `h : I A i`, where `A` is a sequence of parameters and `i` a sequence of indices, and the recursor application would contain these parameters and indices in the exact same order. This is **not** true for `idp_rec_on`. So, I have to store a mapping saying how to "set" the parameters and indices in the recursor application using the information in the major premise. For, `h : @pathover A a B b a (idpath a) b2`, I will store the following information: arguments `1 3 4 5` are the parameters, and argument `7` is the index. 

I also need to know which ones are indices to be able to implement the revert-intro-apply idiom.
I also need this information to decide whether the `induction` tactic is applicable or not.

**Comment by leodemoura** [comment]
> I tried to workaround this by using an intermediate definition, but I got a segfault because of the [recursor] attribute

This was already fixed on my branch.

**Comment by fpvandoorn** [comment]
Ok, thanks for the extra explanation!
