### ISSUE TITLE
Start using the `[unfold-c]` attribute for defined recursors, like eq.rec_on. 

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#496]
The idea is to improve the usability of `esimp`.
For example, `esimp` will not automatically simplify something like

``` lean
eq.rec_on (eq.refl a) H
```

**Comment by fpvandoorn** [comment]
And it will also simplify something like `eq.rec_on idp H`, because it puts the specified argument in whnf (by only unfolding `reducible` definitions), right?

**Comment by leodemoura** [comment]
> And it will also simplify something like eq.rec_on idp H, because it puts the specified argument in whnf (by only unfolding reducible definitions), right?

Yes, with #497 and this one, it will simplify it.

**Comment by fpvandoorn** [comment]
> Yes, with #497 and this one, it will simplify it.

But do we want `idp` to unfold when fully applied (i.e. always) when using `esimp`? Proofs with `eq.refl` are much longer, and don't usually give more useful information than proofs with `idp`.

**Comment by leodemoura** [comment]
I see your point.
It seems we need a way to say `unfold` `esimp` when it is the argument of a recursor.
More generally, we need a mechanism to say `unfold` `f` when a `f` application is the i-th argument of `g`. What do you think?

**Comment by fpvandoorn** [comment]
I'm not sure what you mean. If I write `eq.rec_on p H`, I _don't_ want to unfold `p` no matter what when calling `esimp`. 

I just want to unfold `p` to check whether it reduces to `eq.refl _`. If it does, I want `eq.rec_on p H` to perform a iota-reduction step. If it doesn't, I don't want to change anything in `p` (unless I specifically say that some subterm of `p` must be unfolded).

**Comment by leodemoura** [comment]
> I'm not sure what you mean. If I write eq.rec_on p H, I don't want to unfold p no matter what when calling esimp.

I meant a general mechanism, that would unfold `g` when we have `(f ... (g ...) ...)` and `(g ...)` is the ith-argument.

> I just want to unfold p to check whether it reduces to eq.refl _

This is simpler to implement. However, we should put some restrictions to avoid performance problems. Example: we only unfold `reducible` definitions. Otherwise, for every recursor application, we will have to perform a potentially expensive whnf operation.

**Comment by fpvandoorn** [comment]
> I meant a general mechanism, that would unfold g when we have (f ... (g ...) ...) and (g ...) is the ith-argument.

Why do we want this?

> This is simpler to implement. However, we should put some restrictions to avoid performance problems. Example: we only unfold reducible definitions. Otherwise, for every recursor application, we will have to perform a potentially expensive whnf operation.

That sounds good.

**Comment by leodemoura** [comment]
> Why do we want this?

I assumed it would be useful.

**Comment by fpvandoorn** [comment]
> I assumed it would be useful.

It might be. I was wondering whether you had a specific use for it. I can't think of a situation where I would need it right now.

**Comment by leodemoura** [comment]
I’m frustrated with this one.
Adding the `[unfold-c]` annotations automatically for `rec_on`, `cases_on`, … was fine, and didn’t affect the library.
The second feature was a mess, the library was broken in many places.
It unfolds too much. For example, in field.lean, if execute `esimp` at

``` lean
    a * b = 0
```

which corresponds (without notation) to

``` lean
    has_mul.mul a b = has_zero.zero A
```

After applying `esimp`, we get

``` lean
    division_ring.mul a b = division_ring.zero A
```

The new version is really bad for pattern matching with existing theorems.

I tried different combination (e.g., avoid new features for structures), but there were always something breaking in the library.

**Comment by fpvandoorn** [comment]
That's annoying. 

To check: with "the second feature" you mean putting the specified argument in whnf to check whether to unfold the definition, right?

There is indeed little difference between

```
eq.rec_on idp [foo]
```

and

```
has_zero.zero ([coercions] A)
```

Both reduce to `[type].rec [arguments] [constructor]`, but in the first case we want to unfold it, and in the second case we don't. To make things worse, if I have something like

```
precategory.rec_on precategory_hset [stuff]
```

(where precategory_hset := precategory.mk [something]), I _do_ want this to be unfolded. And there's very little difference between this example and the ring one. I can see why you get frustrated with this issue.

I think that the ring-example is special, because you apply a projection of a "small" structure (`has_mul`) to an extended structure (`division_ring`), and that in most (all?) other cases you **do** want the projection to get unfolded. Would that be a reasonable heuristic to use?

**Comment by leodemoura** [comment]
> I think that the ring-example is special, because you apply a projection of a "small" structure (has_mul) to an extended structure (division_ring), and that in most (all?) other cases you do want the projection to get unfolded. 

I think the ring example is not an isolated issue. The issue I described happens all over the place in the `algebra` folder. 

> Would that be a reasonable heuristic to use?

How small should be a "small" structure?
I'm pretty sure no matter what we decide, people will complain later.

**Comment by fpvandoorn** [comment]
> How small should be a "small" structure?

Small was maybe not the best word for it. I mean that whenever you have a pair of structures like `(has_mul, division_ring)` such that the second structure is an extension of the first ("smaller") one. Then if you apply the projection of the first structure to the second one (+ coercions), don't unfold. Otherwise unfold. It's probably messy, though

> I'm pretty sure no matter what we decide, people will complain later.

That's probably right...

**Comment by leodemoura** [comment]
> That's probably right...

So, I think we should let the user decide. That is, we add yet another attribute :-)

**Comment by leodemoura** [comment]
I added a new attribute `[unfold-m]`, when a declaration is annotated with this hint, it will be unfolded by `esimp` and the (future) simplifier whenever it is the major premise of a recursor like application.
Thus, `eq.rec_on idp H` reduces to `H` in the HoTT library.

We also avoid the the problems with the algebraic hierarchy described above

**Comment by fpvandoorn** [comment]
My point earlier was that I _think_ that we want to add the attribute `[unfold-m]` to every definition, except the ones which are (automatically generated) coercions from an extended structure to a parent structure. 

But maybe there are more examples where we don't want to unfold.

**Comment by leodemoura** [comment]
The implemented approach is a compromise. It doesn't change the behavior of the existing system.
It just adds a new feature. So, nothing breaks.
The more general rule broke many files in the library and the test suite.
The heuristic you suggested fixes one of the breaks I analyzed. 
Even if we implement the heuristic it is not clear we will be able to compile the whole library.
We will probably have to keep polishing the heuristic.

**Comment by fpvandoorn** [comment]
That is possible. 

Let's leave it as-is. I'll start using `[unfold-m]`, and I'll check 
- whether it is annoying to add that attribute to every definition where I want it
- whether there are other kinds of definitions where we don't want the attribute `[unfold-m]`
