### ISSUE TITLE
`esimp`: new attribute for automatically unfolding fully applied definitions

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#497]
Example: `(f o g) x` should simplify to `f (g x)`.

**Comment by avigad** [comment]
@leodemoura I noticed a missing close bracket ] here:
  https://github.com/leanprover/lean/blob/d731a4ab13dbdf1467e4761da5b49d72b1a6999e/src/frontends/lean/tokens.cpp#L230

**Comment by avigad** [comment]
(Also the line above it.)

**Comment by leodemoura** [comment]
This is intended. Both of them have a numeric argument. We write `[unfold-c <num>]` and `[priority <num>]`.
