### ISSUE TITLE
alternative `typeof` notation

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#498]
@avigad We discussed about it last week.
The following works well:

``` lean
notation `(` t `:` T `)` := is_typeof T t
```

I think it is an improvement, we can write `(a : int) + 1` instead of `(typeof a : int) + 1`.

The simpler one does not work

``` lean
notation  t `:` T  := is_typeof T t
```

The problem is that the `calc` expression would become ambiguous. We use `:` to separate the right-hand-side from the proof term.

**Comment by avigad** [comment]
I like this a lot. I will make the changes to both the standard and HoTT libraries tomorrow. I will leave the typeof notation also present temporarily, until we update the tutorial.

**Comment by leodemoura** [comment]
closed by https://github.com/leanprover/lean/commit/74b28f6ad9ca4de5022b4e8a05a49d559fbe512c
