### ISSUE TITLE
more tactics from Coq

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#500]
Today I looked over my Coq files from last year, and Coq has some tactics which are quite convenient, and probably not too hard to implement given what we already have. Here are the ones I consider most important (or which I expect to be easy to implement and which are still convenient).
More explanation can be found [here](https://coq.inria.fr/refman/Reference-Manual010.html).
- [x] `reflexivity`, `symmetry` and `transitivity t`: apply the corresponding theorem. This should at least work for equality, but maybe we can extend it to any relation where we've defined calc_refl/calc_symm/calc_trans. `transitivity t` changes to goal `s = r` to `s = t` and `t = r`.
- [x] `f_equal`: If the goal is `f x y = f' x' y'`, produce new goals `f = f'`; `x = x'` and `y = y'`. Maybe only for nondependent functions, but of arbitrary arity. Perhaps already solve all goals provable by reflexivity.
- [x] `contradiction`: does `intros` and then searches context for element of `false` or `empty` to solve goal
- [x] `exfalso`: replace current goal by `false` (`empty` in HoTT)
- [x] `constructor`: if the goal is an inductive definition, try to apply each constructor in order, until you find one which succeeds. This has the following useful variants:
  - [x] `contructor n`: use the `n`th constructor
  - [x] `split`: apply the unique constructor (for example if the goal is `A ∧ B`) 
  - [x] `exists t`: apply unique constructor with argument `t` (for example if the goal is `∃x, P x`, create new goal `P t` (we define `exists` inductively, right?))
  - [x] `left`/`right`: apply first/second constructor if there are two constructors (for example if the goal is `A ∨ B`)
- [x] `injection t`: if the type of `t` is `f x y = f x' y'` and `f` is the constructor of an (non-Prop) inductive type, replace conclusion `A` by `x = x' -> y = y' -> A`. Maybe it would also be nice (Coq doesn't do this): already introduce those new hypotheses to the context (with optional ability to name them) and if `t` is an hypothesis not occurring anywhere else, remove it.
- [x] `discriminate t`: if the type of `t` is `f x y = g a b c`, where `f` and `g` are different constructors of the same inductive type, solve the goal. Maybe with variant `discriminate` which searches the context for any such equality.
- [x] `subst`: for any hypothesis `H` of the form `x = t` or `t = x`, where `x` is a variable; replace `x` by `t` anywhere in the conclusion and hypotheses, and remove both `H` and `x` from the context. (Coq also has the variant `subst x` where this only happens for the single variable `x`, but I've never used that variant)

**Comment by leodemoura** [comment]
Small remark: both `injection` and `discriminate` can be simulated using `no_confusion`.

**Comment by fpvandoorn** [comment]
Yes, but it would be nice if that simulation can be done behind the scenes, instead of that the user explicitly has to use `no_confusion`.

**Comment by leodemoura** [comment]
For more examples of the `contradiction` tactic, see
https://github.com/leanprover/lean/commit/9760968b458a9f9e46441c9ddf4804a128fa5d8a

**Comment by leodemoura** [comment]
> Maybe with variant discriminate which searches the context for any such equality.

The new `contradiction` tactic does that.

**Comment by leodemoura** [comment]
> we define exists inductively, right?

Yes

**Comment by leodemoura** [comment]
`exists` is a keyword in Lean. So, I called the tactic `existsi` (`i` for introduction).

**Comment by fpvandoorn** [comment]
Great! I updated the opening post. (feel free to update :smile: )

Mathematicians (including me) have to adapt to start counting at 0 for the command `constructor i`. Coq starts with 1. (I am a weird mix between a mathematician and a computer scientist: 0 is definitely a natural number, but I start counting at 1). 

I do get some weird behaviour with the `constructor` tactic:

``` lean
-- standard library
open nat

example (n m : ℕ) (H : n < m) : n < succ m :=
begin
  constructor 1
end 
```

Expected output: new goal `n < m`.
Given output: two goals, `?M_1 : ℕ` and `n < ?M_1` (and the resulting term will fail if something different than `m` is chosen in the first goal)

**Comment by fpvandoorn** [comment]
I want to say that the implemented tactics are really nice! I also love the simpler syntax for tactics like `intro`.

To clarify the `constructor` tactic (without argument): it is very strange to use it for "normal" inductive definitions. But it is super useful for enumerated inductive families like the one below. That is from my formalization of propositional calculus in Coq, and lists all axioms of the propositional Hilbert calculus. If my goal is `AxiomH X`, and I know that `X` has the form of one of the axioms below, then with `constructor` I don't have to remember the order or the names of the axioms.

``` coq
Inductive AxiomH : PropF -> Prop :=
| HOrI1  : forall A B  , AxiomH (A → A∨B)
| HOrI2  : forall A B  , AxiomH (B → A∨B)
| HAndI  : forall A B  , AxiomH (A → B → A∧B)
| HOrE   : forall A B C, AxiomH (A∨B → (A → C) → (B → C) → C)
| HAndE1 : forall A B  , AxiomH (A∧B → A)
| HAndE2 : forall A B  , AxiomH (A∧B → B)
| HS     : forall A B C, AxiomH ((A → B → C) → (A → B) → A → C)
| HK     : forall A B  , AxiomH (A → B → A)
| HClas  : forall A    , AxiomH (¬(¬A) → A)
.
```

**Comment by leodemoura** [comment]
Example for `constructor` tactic:
https://github.com/leanprover/lean/blob/7e9f574ef36324af9d12b61687312596c7919a9f/tests/lean/run/soundness.lean#L90-L101

**Comment by fpvandoorn** [comment]
That is fast! (as always) :-) Very nice! 

I also really appreciate that you ported some of my Coq files to Lean. :smile: 

It's nice to see the Coq formalization and Lean formalization side-by-side (for others: the e-mail where I send my files (as zip) is [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lean-discuss/aZTh41wT6PM/g8oS9vhtuRsJ) or you can download them from [arXiv](http://arxiv.org/abs/1503.08744)).
My Coq-proofs are shorter, but highly unreadable and fragile. We're still missing some features I'm heavily using, such as Ltac and this way of chaining tactics `t1; [t2 | t3.. | t4]` in Coq (this applies tactic `t1`, and then to the new goals generated by `t1`: apply `t2` to the first, `t4` to the last and `t3` to the rest). 
However, overall I'm pretty pleased with how similar the files look. Many simple definitions look exactly the same!

About the example you linked: there's a lot of backtracking going on, right? In all the tactics `by constructor; exact weakening2 H Hs`, the `exact` tactic determines which constructor has to be applied (and e.g. `Nax` is always applicable and tried first), right?

---

``` lean
 inductive Nc : list PropF → PropF → Type :=
  infix ⊢ := Nc
  | Nax   : ∀ Γ A,   A ∈ Γ →             Γ ⊢ A
  | ImpI  : ∀ Γ A B, A::Γ ⊢ B →          Γ ⊢ A ⇒ B
(...)
```

Wait! We can do that? I didn't know we could declare notation when defining a structure inductively! That is super useful!

So is it only the inductive type for which a notation can be declared? Or can we even do something like this?

``` lean
structure semigroup [class] (A : Type) :=
(mul : A → A → A)
infixr * := mul
(mul_assoc : ∀a b c, (a * b) * c = a * (b * c))
```

**Comment by leodemoura** [comment]
> I also really appreciate that you ported some of my Coq files to Lean. :smile:

Here is the ported file (without the `constructor` tactic)
https://github.com/leanprover/lean/blob/master/library/logic/examples/propositional/soundness_type.lean

It is super useful to have it as an example for new users. Recall that Alexandre and Guilherme are trying to formalize description logics using Lean. 

> We're still missing some features I'm heavily using, such as Ltac

You want the pattern matching, right?
For pattern matching (and traversing terms), I'm wondering whether we should support something like mtac (https://www.mpi-sws.org/~neelk/mtac.pdf). After we add the efficient evaluator (#462), we will be able to implement non-trivial automation using Lean itself.

> t1; [t2 | t3.. | t4] in Coq (this applies tactic t1, and then to the new goals generated by t1: apply t2 to the first, t4 to the last and t3 to the rest). 

We can try to add this one. It would be useful to understand all "bells and whistles" this combinator provides. 

> About the example you linked: there's a lot of backtracking going on, right? In all the tactics by constructor; exact weakening2 H Hs, the exact tactic determines which constructor has to be applied (and e.g. Nax is always applicable and tried first), right?

Yes, there is a lot of backtracking. 
This was another motivation for using this example to test the `constructor` tactic.

> Wait! We can do that? I didn't know we could declare notation when defining a structure inductively! That is super useful!

Right now, it just declares a local notation, the scope is the inductive declaration. I added this feature for Alexandre and Guilherme

> Or can we even do something like this?

Not yet, we can add it for structures. It is not hard if the scope is local.
It is trickier to move this kind of local notation to the global scope.
It is not always possible, and may not even make sense. I'm postponing this part.
For structures, we also have the additional complication that users would expect to be able to use the notation when extending the structure.

**Comment by fpvandoorn** [comment]
> You want the pattern matching, right?

Yes, that is indeed what I meant. There are also some other features of Ltac, like naming fresh variable names, but pattern matching is probably the hardest one, and very useful.

> We can try to add this one. It would be useful to understand all "bells and whistles" this combinator provides. 

It is described in [section 9.2](https://coq.inria.fr/distrib/current/refman/Reference-Manual011.html#sec448) of the Reference Manual (General sequence + Variants).

> Not yet, we can add it for structures. It is not hard if the scope is local.
> It is trickier to move this kind of local notation to the global scope.
> It is not always possible, and may not even make sense. I'm postponing this part.
> For structures, we also have the additional complication that users would expect to be able to use the notation when extending the structure.

It never ceases to amaze me to hear which parts are hard and which parts are not :-) Do you mean that it doesn't make sense if notation mentions a parameter of the inductive type? I'm okay with postponing this (or anything else in this comment, for that matter).

**Comment by leodemoura** [comment]
> It never ceases to amaze me to hear which parts are hard and which parts are not :-)

These claims depend on the "pieces" of code we already have. 
We already have support for defining local notation. 
For example, we can write 

``` lean
check λ (A : Type) (f : A → A → A) (infix * := f) (a b : A), a * b
```

This has been supported for a long time.
So, it is not difficult to support the same thing for the `structure` command.
All the pieces are already there.
It just a matter of connecting them together. 

On the other hand, we have no support for "reinterpreting" these local declarations in the global scope.
For example, if the structure is not a class, I think it doesn't make sense to export the declaration.

``` lean
structure g (A : Type) :=
(mul : A -> A -> A) (infix * := mul) (assoc : forall x y z, (x * y) * z = x * (y * z))
```

The projection `g.mul` is not even a binary function. It has type

``` lean
g.mul : Pi {A : Type}, g A -> A -> A -> A
```

Then, we say, we do it only if the structure is a `class`. 
So, we have to write the following pieces of code: 
- Save the local notation declarations somewhere because we have to re-declare them in the global scope after we finish the elaboration step.
- Reinterpret the declarations, we have to replace the local constants (that correspond to projections) with projection applications.
- We can extend structures. So, it is reasonable to expect that the local notation from parents is available when declaring the child structure. So, we have to save all these local notations also in the .olean files. We also have to deal with issues such as: what happens when a structure has multiple parent structures and they have conflicting notation?

**Comment by fpvandoorn** [comment]
Thanks for the explanation. That makes sense. I didn't know about the fact that we could declare local notation in that way, I probably forgot about it.

You're right that exporting notation of projections only makes sense for classes.

**Comment by arademaker** [comment]
> It is super useful to have it as an example for new users. Recall that Alexandre and Guilherme are trying to formalize description logics using Lean.
> 
> Yes, and the translation is very useful.
> 
> Right now, it just declares a local notation, the scope is the inductive declaration. I added this feature for Alexandre and Guilherme
> 
> Thanks. 

Ab.,
Alexandre

**Comment by leodemoura** [comment]
Examples for the new `injection` tactic:
https://github.com/leanprover/lean/blob/de369a0a0a0181a884ee6485a8ae1f487613816d/tests/lean/run/inj_tac.lean
https://github.com/leanprover/lean/blob/de369a0a0a0181a884ee6485a8ae1f487613816d/library/data/list/perm.lean#L284-L310

**Comment by leodemoura** [comment]
The `injection` tactic has all the "bells and whistles" for the standard library. This is not true for the HoTT library when we have dependencies. For example, consider the following example:

``` lean
example (A : Type) (n : nat) (v w : vector A n) (a : A) (b : A) :
        a :: v = b :: w →  b = a :=
begin
  intro H, injection H with aeqb neqn veqw,

end
```

After `injection`, the goal is:

``` lean
A : Type,
n : ℕ,
v w : vector A n,
a b : A,
H : a :: v = b :: w,
aeqb : a = b,
neqn : n = n,
veqw : eq.rec v neqn = w
⊢ b = a
```

I had a similar issue with the definition package. I describe the hack I used there in the end of this comment. In principle, it is possible to get the equality `v = w`. However, we need another `no_confusion` construction that comes with a `no_confusion_inv`. This alternative construction is described in the following paper: http://people.cs.kuleuven.be/~jesper.cockx/Without-K/Pattern-matching-without-K.pdf.
I didn't implement it yet, and it has a very low priority. BTW, Coq injection tactic does not produce `v = w`.

In the definition package, I used the following "hack", `nat` is a `hset`, thus we have (neqn = refl n), and I use it to get `veqw : v = w`. This is hackish for two reasons. It only works for hsets.
The second problem is clear with an example. Consider the following definition:

``` lean
definition map (f : A → B) : Π {n : nat}, vector A n → vector B n
| map []     := []
| map (a::v) := f a :: map v
```

In the HoTT library, the second equation does not hold definitionally.
That is, the following will fail

``` lean
example (f : A → B) : forall {n : nat} (a : A) (v : vector A n), 
              map f (a::v) = f a :: map f v :=
rfl
```

We can prove the equation, but it does not hold definitionally.
It fails because `n` is not a canonical value. To get (neqn = refl n), we are using 
https://github.com/leanprover/lean/blob/master/hott/init/hedberg.hlean,
and to show that `nat` has decidable equality we recurse on `n`.

**Comment by leodemoura** [comment]
`subst` examples:
https://github.com/leanprover/lean/blob/ac8ba6a3cff93f9d64517b3223dea5188a689255/tests/lean/run/subst_tact.lean

**Comment by leodemoura** [comment]
`f_equal` is called `congruence` in lean

**Comment by leodemoura** [comment]
`congruence` examples:
https://github.com/leodemoura/lean/blob/415ca2b93f9ccedd02ff4975089e8e72dc982dd7/tests/lean/run/congr_tac.lean

**Comment by fpvandoorn** [comment]
Great! These tactics will be super useful to make proving with tactics more efficient.

> This alternative construction is described in the following paper: http://people.cs.kuleuven.be/~jesper.cockx/Without-K/Pattern-matching-without-K.pdf. I didn't implement it yet, and it has a very low priority.

I agree.
