### ISSUE TITLE
esimp and unfold in hypotheses

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#502]
It would be nice to be able to apply tactics like `esimp` and `unfold` to an hypothesis. 
Coq has the following notation for this: (see [here](https://coq.inria.fr/refman/Reference-Manual010.html#sec391))
- `in ident1 … identn |-` only in hypotheses `ident1 …identn`
- `in ident1 … identn |- *` in hypotheses `ident1 …identn` and in the conclusion
- `in * |-` in every hypothesis
- `in *` (equivalent to `in * |- *`) everywhere
- `in (type of ident1) (value of ident2) … |-` in type part of `ident1`, in the value part of `ident2`, etc. _note: I don't think this applies to Lean. I believe this is for definitions in the context of the form `s := t : T` where `s` is defined to be `t` (of type `T`)_
- For backward compatibility, the notation `in ident1…identn` performs the conversion in hypotheses `ident1…identn`.

For example in Coq `unfold t in H` (or `unfold t in H |-`) would unfold the term `t` in the type of hypothesis `H`.

**Comment by leodemoura** [comment]
We can do that for `esimp`. We can use `at` modifier. It uses the same notation used in the `rewrite` tactic. The tutorial describes it.

**Comment by fpvandoorn** [comment]
Great! Sorry, I forgot.
