### ISSUE TITLE
uniform notation for lists in tactics

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#504]
Maybe we should try to have a uniform notation for lists of things in tactic mode. Currently it's not hard to remember everything, but if the tactic language gets big enough it might be harder, and it is probably confusing for new users. I'm talking about the following (and there are probably more I forgot or don't know about)

```
intros (a, b, c),
esimp {t, s, r},
rewrite ⟨H1, H2, H3⟩,
rewrite [H1, H2, H3],
rewrite H at {1, 2, 3},
```

I don't know which parentheses are ambiguous in what cases, but maybe we can reduce the number of different parentheses. I think it's good to have one type of parentheses as "main one", and then other parentheses for different purposes (for example using `{ ... }` to always specify occurrences). I guess that `rewrite (H1, H2, H3)` is hard/ambiguous for the parser? In that case we can maybe use `[ ... ]` as main parentheses, so change the syntax to

```
intros [a, b, c],
esimp [t, s, r],
rewrite [H1, H2, H3],
rewrite H at {1, 2, 3},
```

(or it would be even better if we could also replace the parentheses in the last line by `[ ... ]`, if that does not lead to parser issues).

What do you think? Is this feasible?

**Comment by leodemoura** [comment]
I think this is a good idea.
Your proposal is feasible. We should use it.
