### ISSUE TITLE
tokens `{{` and `}}` in binders

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#505]
From the Lean mailing list:

Dear Jeremy,

I will fix this issue. The problem is how the parser handles `{{` and `}}` in binders.
It treats `{{` as two tokens `{`  followed by `{`. This is the problem.
It should treat it as a single token `{{`. 
When you define

``` lean
              notation `{{`:max s:(foldr `,` (a t, insert a t) ∅) `}}`:0 := s
```

The tokens `{{` and `}}` are added to Lean.
After that, the only one to enter the binder 

``` lean
                {{ X : Type }} 
```

is to type

``` lean
                { { X : Type } }
```

Of course, this is unacceptable. I will fix it.

BTW, for lists and vectors, we use the notation [1, 2, 3] for explicit collections.
Perhaps, we should use the same notation for sets.
What do you think?

Best,
Leo

From: lean-discuss@googlegroups.com [mailto:lean-discuss@googlegroups.com] On Behalf Of Jeremy Avigad
Sent: Tuesday, March 24, 2015 11:43 AM
To: lean-discuss@googlegroups.com
Subject: [lean-discuss] notation for sets

Dear all,

There is an MS student here who is formalizing properties of sets (i.e. subset of a type).

We introduced notation `{ x : A | P x }` for forming a subset, and also notation

``` lean
  {{1, 2, 3}} or ⦃1, 2, 3⦄
```

for writing explicitly enumerated sets. 

The first of these, however, conflicts with the `{{ x : X }}` notation for binders. (The second one causes no problems, whether we write `⦃x : X⦄` or `{{ x : X }}` for the binder.)

Is there a workaround? One solution is to use only `⦃1, 2, 3⦄` for enumerated sets, or find some other ascii-equivalent.

An example of the problem is appended below.

Best wishes,

Jeremy

``` lean
import data.set
open set

section
  variable {A : Type}

  definition set_of (P : A → Prop) : set A := P

  notation `{` binders `|` r:(scoped:1 P, set_of P) `}` := r

  definition insert (a : A) (s : set A) : set A := {x : A | x = a ∨ x ∈ s}

  notation `⦃` s:(foldr `,` (a t, insert a t) ∅) `⦄` := s
  notation `{{`:max s:(foldr `,` (a t, insert a t) ∅) `}}`:0 := s

  check ⦃1, 2, 3⦄
  check {{1, 2, 3}}

  definition foo  {X : Type} {{ x : X }} : X := x    -- error here
end
```

**Comment by leodemoura** [comment]
@avigad I recalled why the parser tries to parse `{{` as `{` `{` and `}}` as `}` `}`.
The motivation is declarations such as `{A : Type.{l}}`. If `}}` is a single token, we would be forced to write `{A : Type.{l} }`. This is a pretty common case.
We can use the following workaround for this problem

``` lean
notation `{` `{` s:(foldr `,` (a t, insert a t) ∅) `}` `}` := s
```

**Comment by avigad** [comment]
That's reasonable. Squiggly braces play a special role.

The problem with the workaround is that it breaks the notation {x : A | P}:

``` lean
import data.set
open set

section
  variable {A : Type}

  definition set_of (P : A → Prop) : set A := P

  notation `{` binders `|` r:(scoped:1 P, set_of P) `}` := r

  definition insert (a : A) (s : set A) : set A := {x : A | x = a ∨ x ∈ s}

  check {x : A | x = x}  -- o.k.

  notation `⦃` s:(foldr `,` (a t, insert a t) ∅) `⦄` := s
  notation `{` `{` s:(foldr `,` (a t, insert a t) ∅) `}` `}` := s

  check ⦃1, 2, 3⦄
  check {{1, 2, 3}}

  check {x : A | x = x} -- broken
end
```

I think the best solution is to use the notation {[1, 2, 3]} for an enumerated set:

``` lean
  notation `⦃` s:(foldr `,` (a t, insert a t) ∅) `⦄` := s
  notation `{[`:max s:(foldr `,` (a t, insert a t) ∅) `]}`:0 := s

  check ⦃1, 2, 3⦄
  check {[1, 2, 3]}
```

I kind of like it. What do you think?

**Comment by leodemoura** [comment]
> The problem with the workaround is that it breaks the notation {x : A | P}

Yes, you are right. The workaround introduces an ambiguity. The beginning of a `binders` primitive is an identifier, or any binder annotation: `(`, `{`, `{{`, `[`, ...
I think it is silly to consider binder annotations for `{x : A | P}`. 
We may create a `simplebinder` that expects something of the form `x : A`. 
If we do that, we will be able to disambiguate this instance. 

> I think the best solution is to use the notation `{[1, 2, 3]}` for an enumerated set:
> I kind of like it. What do you think?

It looks good.

**Comment by avigad** [comment]
The `simplebinder` idea sounds good. We'll have lots of uses for such binders, for sums, products, unions, intersections, etc.

**Comment by leodemoura** [comment]
I'm closing this issue. The `simplebinder` is a mess to implement. To be useful, we would have to implement a form of backtracking/lookahead in the parser.

Here is an alternative solution for this kind of problem. We can tell emacs to render some patterns in a slightly different way. For example, `{[` would be rendered as `{`. Similarly, `∀₀` would be rendered as `∀`. This is not different from the Isabelle approach where the user uses "tags" such as `\<noteq>` and `\<lambda>`, but they are rendered in a nice way by JEdit.

**Comment by avigad** [comment]
That's o.k. I don't mind a little ascii art. 

The emacs trick is o.k., though it wouldn't extend e.g. to the github listings.

Other hacks are to use exotic unicode characters, like the full width braces here:

  http://xahlee.info/comp/unicode_matching_brackets.html

Or even to use invisible unicode characters in tokens:

  http://www.fileformat.info/info/unicode/char/2063/index.htm
  http://www.fileformat.info/info/unicode/char/200B/index.htm

But I expect there will be all sorts of problems with that.

**Comment by leodemoura** [comment]
> The emacs trick is o.k., though it wouldn't extend e.g. to the github listings.

Yes. At least, it would still be readable. On github, we would see `{[` instead of `{` and `∀₀` instead of `∀`. 

I don't really want to go into the "backtracking" parser direction.
It would produce even more counter intuitive behavior.

**Comment by leodemoura** [comment]
> But I expect there will be all sorts of problems with that.

Yes. I think this would produce a lot of confusion.

**Comment by soonhokong** [comment]
FYI, since emacs-24.4, we have a minor-mode, [prettify-symbols-mode](http://emacsredux.com/blog/2014/08/25/a-peek-at-emacs-24-dot-4-prettify-symbols-mode/), which easily allows us to do what @leodemoura mentioned. For example, have the following elisp in your emacs:

``` elisp
(add-hook 'lean-mode-hook
          (lambda ()
            (push '("forall" . ?∀) prettify-symbols-alist)))
```

then, turn on `prettify-symbol-mode` in a lean file. You will see that `forall` is rendered as `∀`.
