### ISSUE TITLE
formatting of "unsolved subgoals" output

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#509]
I'd propose to 
- Print `<n> unsolved subgoals` instead of `unsolved subgoals` so that one can quickly see how many subgoals there's left to solve.
- Print an empty line between the goal blocks, so that it's easier to disginguish when you have long outputs.

**Comment by leodemoura** [comment]
@soonhokong Lean includes line breaks between goals. linja or flycheck seem to eliminate them.
Here is a small example. If we execute the file we get two subgoals with a space between them. 
However, when I hover over the red wiggle, they line break is not there:

``` lean
example (a b c : Prop) : a → b → c → a ∧ b ∧ c :=
begin
  intros,
  apply and.intro,
end
```

**Comment by leodemoura** [comment]
see #512
