### ISSUE TITLE
add tactics xrewrite and srewrite

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#511]
They are both variants of the `rewrite` tactic.
- `xrewrite` unfolds terms more aggressively during pattern matching, and
- `srewrite` simulates SSReflect keyed-matching

**Comment by fpvandoorn** [comment]
When implemented, test whether either of these tactics work on the example in #551.

**Comment by leodemoura** [comment]
`srewrite` is called `krewrite`

**Comment by leodemoura** [comment]
Example: 
https://github.com/leanprover/lean/blob/85409a59d36e6f373e57cb7d60aea8d33c6aad45/tests/lean/run/511a.lean
