### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [leanprover/lean3#514]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [finalize_debug](https://github.com/leanprover/lean/blob/9b61b18eaac41b6f2bc5e5eb00dc0021f1202af1/src/util/debug.cpp#L28)
- [finalize_thread_state_ref](https://github.com/leanprover/lean/blob/516c0c73b9d1a713d77bb9fe36d57049c0ffbd36/src/util/thread_script_state.cpp#L126)
- [set_print_fn](https://github.com/leanprover/lean/blob/f5811d6092e887b00889b60a952df1df7c595a97/src/kernel/formatter.cpp#L23)

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/leanprover/lean/commit/88495f9d59f551b1d19f37fe6d5a3f0952348fb9).

**Comment by leodemoura** [comment]
@elfring Thank your for suggesting the improvement
