### ISSUE TITLE
linja + space in filename

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#515]
I was fixing #513, and testing it. Then I found that `linja` has a problem if a filename/directory-name contains spaces. One of the problem is that its dependency file (`.d`) uses a different escaping rule than `build.ninja` file.
- In `build.ninja`, ' ' goes to '$ '
- In `.d` file, ' ' should become '\ '.

**Comment by dmcooke** [comment]
The fix breaks on OS X with Python 3.4. The argument to `escape_dep` is (sometimes!) a `bytes` instance, but the arguments to `s.replace` in that function are strings (`str`), raising the error

```
TypeError: 'str' does not support the buffer interface
```

(Also, the indentation in `escape_dep` should be 4 spaces, not 2.)
