### ISSUE TITLE
round parantheses for [ tactic1 | tactic2 ]

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#516]
since we now have a uniform notation of terms in tactics, wouldn't it be better to also unify lists of tactics? (we discussed this last week, but I'm not completely sure what the result was)

**Comment by leodemoura** [comment]
@javra I think this is a good idea.
The idea is to use `( tactic_1 | ... | tactic_n)` as notation for the `orelse` tactical, right?

What about nested `begin...end` blocks? We use the alternative notation `{tactic_1, ..., tactic_n}`. Should we use `(tactic_1, ..., tactic_n)`? Or do we force users to write `begin` ... `end` for nested blocks?

**Comment by javra** [comment]
Yes, that was the idea.

For the blocks: Opposed to the brackets in `orelse` where `|` is the "actual" operator, the `{... }` themselves "do something", namely restricting to the first goal. That would imo justify having a different type of brackets than `( )` for them. But I've no strong opinion whether to allow `{ }` or force `begin ... end`.

**Comment by leodemoura** [comment]
@javra This is a good point.
I will change only the `orelse` notation.
