### ISSUE TITLE
Dropbox button hits 400 page (malformed request)

### ISSUE THREAD

**Issue by carlpaten** [leanprover/lean3#518]
From https://leanprover.github.io/tutorial/index.html, clicking the Dropbox button sends me to a page with the following text:

> Error (400)
> It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.
> 
> More details for developers
> 
>    Invalid redirect_uri: "https://leanprover.github.io/tutorial/index.html". It must exactly match one of the redirect URIs you've pre-configured for your app (including the path)

**Comment by soonhokong** [comment]
@lilred, could you move this one to leanprover/tutorial as well?

**Comment by carlpaten** [comment]
Moved to leanprover/tutorial#77.
