### ISSUE TITLE
keyboard shortcuts for cases 

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#520]
@UlrikBuchholtz proposed this: Can we implement a keyboard shortcut which automatically inserts the cases you have to do in a `match ... with` expression. This feature exists in Agda, and is very briefly described [here](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.QuickGuideToEditingTypeCheckingAndCompilingAgdaCode) under `C-c C-c`. I do not exactly know how this should work (or how it works in Agda), but it would be nice if you write something like `match n` (for a natural number `n`) and then hitting the keyboard shortcut produces something like

```
match n with
| zero   := _
| succ k := _
end
```

**Comment by soonhokong** [comment]
- I need a help from lean-server to implement this feature.
- One question is how to pick up names for arguments (such as `k` in `succ k`). I think `cases` and `cases ... with [...]` tactics are related to this problem. I wish Leo can reuse some code written for the tactics.
- We can think of two emacs commands `lean-complete-cases` and `lean-complete-cases-interactive` where:
  - `lean-complete-cases` lets Lean to pick names for users (such as `a_1`, `a_2`, ...).
  - `lean-complete-cases-interactive` provides cases with holes, number of names. Then it will ask a user to provide the names for the holes, and complete the cases.
- Emacs part needs some post-processing such as indenting texts.

@fpvandoorn and @UlrikBuchholtz, will you be happy with this implementation?
@leodemoura, do you think it's a feasible plan?

**Comment by UlrikBuchholtz** [comment]
On Fri, Apr 3, 2015 at 4:50 PM, Soonho Kong notifications@github.com
wrote:

> will you be happy with this implementation?

Yes, that seems promising!

**Comment by leodemoura** [comment]
> @leodemoura, do you think it's a feasible plan?

It is feasible, but low priority.

**Comment by leodemoura** [comment]
I'm marking this one as postponed and closing it.
I don't see anybody working on this feature any time soon.
If we have volunteers to implement it, we reopen it.
