### ISSUE TITLE
match without opening namespace

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#528]
The following code gives a funny error. The problem is that I didn't open `bool`. 

```
variables {P : bool → Type} {x : P bool.tt} {y : P bool.ff}

example (b : bool) : P b := 
match b with
| tt := x
| ff := y
end
```

Interestingly, for non-dependent functions I don't need to open `bool`:

```
variables {P : Type} {x y : P}

example (b : bool) : P := 
match b with
| tt := x
| ff := y
end
```

Can you let Lean accept the first example? Otherwise, can you improve the error message?

**Comment by fpvandoorn** [comment]
I just realized that my original example is not solved by just opening the namespace `bool`. My full example is

``` lean
structure diagram [class] :=
  (Iob : Type)
  (Ihom : Type)
  (ob : Iob → Type)
  (dom cod : Ihom → Iob)
  (hom : Π⦃j : Ihom⦄, ob (dom j) → ob (cod j))

inductive pushout_ob :=
| tl : pushout_ob
| tr : pushout_ob
| bl : pushout_ob

open pushout_ob bool

universe variable u
variables {TL TR BL : Type.{u}} {f : TL → TR} {g : TL → BL}

definition pushout_diag : diagram :=
diagram.mk pushout_ob
           bool
           (λi, match i with | tl := TL | tr := TR | bl := BL end)
           (λj, match j with | tt := tl | ff := tl end)
           (λj, match j with | tt := tr | ff := bl end)
           (λj, match j with | tt := f  | ff := g  end) /- error -/

-- the following definition is included purely to show that my above definition should work
definition pushout_diag' : diagram :=
diagram.mk pushout_ob
           bool
           (λi, pushout_ob.rec_on i TL TR BL)
           (λj, bool.rec_on j tl tl)
           (λj, bool.rec_on j bl tr)
           (λj, bool.rec_on j g  f)
```

**Comment by leodemoura** [comment]
@fpvandoorn The whole thing is tricky.

First some remarks.
- The definition package and match expressions are a little bit problematic because they add new variables to the context. We are simultaneously declaring variables and patterns.
- If an identifier is not a constant/parameter/hypothesis/axiom/alias, then lean assume we are adding/declaring a new variable.

The first example fails because Lean is assuming `tt` is a variable.
It is interpreting the example as

``` lean
example (b : bool) : P b := 
match b with
| z := x
| z := y
end
```

It has two overlapping equations. 
The second example (the non dependent one) doesn't really work. It is not defining the term you expect. It is really treating `tt` and `ff` as variables. It works because there is no dependency.

Your real example is quite trick to process without auxiliary annotations. 
It works when you use `bool.rec_on` because all unification constraints are being solved  simultaneously.  Each `match` expression term is compiled independently of each other. 
So, one trick is to provide the expected type for the last match-expression. 

``` lean
definition pushout_diag : diagram :=
diagram.mk pushout_ob
           bool
           (λi, match i with | tl := TL | tr := TR | bl := BL end)
           (λj, match j with | tt := tl | ff := tl end)
           (λj, match j with | tt := tr | ff := bl end)
           (λj, show pushout_ob.cases_on (bool.cases_on j tl tl) TL TR BL → pushout_ob.cases_on (bool.cases_on j bl tr) TL TR BL,
                from match j with | tt := f | ff := g end)
```

Opening namespaces automatically is not that simple. We may have to open several of them. For example, suppose we are pattern matching on `list (nat x bool x nat)`. The patterns may have constructors of four different datatypes.

**Comment by fpvandoorn** [comment]
Hmm... I see, that is indeed tricky. I think the lesson is to only use `match` when the corresponding namespaces are open. 

However, this does sometimes lead to unintuitive behavior, as in the examples of my first post. Is it possible to enhance the error message from my first example and add some information (or is this the generic type-mismatch error message)? Maybe if the free variables written by the user are in the error message this could help. For the first example this would be something like

```
type mismatch at definition 'match', has type
  P bool.ff
but is expected to have type
  P bool.tt
(The following identifiers are treated as free variables 
  in the match expression: tt, ff)
```

For the example in my second post, it seems that a tactic proof is most convenient for this definition, where I can use `cases`. Then the type of the last argument is already elaborated when it is needed.

I can see that the definition in my example is hard to elaborate, because I give very little type information. However, if I replace the last line by `_`, Lean can figure out exactly which type is needed there. It would be nice if there was some notation which we can use which means "initially treat this part of the term as an underscore, only when you have elaborated the rest of the term, start elaborating what's here". This is how I try to use `proof ... qed`, but this often doesn't lead to desired results (I don't know exactly why, but I guess it has to do with moving to the tactic framework). For example: adding `proof...qed` to the last line doesn't help:

``` lean
definition pushout_diag {f : TL → TR} {g : TL → BL} : diagram :=
diagram.mk pushout_ob
           bool
           (λi, match i with | tl := TL | tr := TR | bl := BL end)
           (λj, match j with | tt := tl | ff := tl end)
           (λj, match j with | tt := tr | ff := bl end)
           (λj, proof match j with | tt := f  | ff := g end qed) /- error -/
```

Derailing the issue even more: `begin refine (match j with | tt := _  | ff := _  end) end` gives a `failed to synthesize placeholder`-error. If it's not hard, it would be nice to allow this.

**Comment by leodemoura** [comment]
> Maybe if the free variables written by the user are in the error message this could help.

I agree. 

>  This is how I try to use proof ... qed, but this often doesn't lead to desired results (I don't know exactly why, but I guess it has to do with moving to the tactic framework).

Note that `proof T qed` is an "one way road". That is, information inferred from `T` is not available for elaborating the term surrounding the `proof ... qed`.

> Derailing the issue even more: begin refine (match j with | tt := _ | ff := _ end) end gives a failed to synthesize placeholder-error. If it's not hard, it would be nice to allow this.

I have to think about this one. Recall we do not have match-expressions in the language. They are all compiled into recursors. I know the feature you requested will not work in full generality. Example: recursive calls.
In Lean, we can have nested recursive definitions. 
https://github.com/leanprover/lean/blob/master/library/data/list/perm.lean#L200-L202

**Comment by avigad** [comment]
For the record, I have also made the mistake of writing "succ n" in a function definition without opening nat, and from the error message I was confused about what it does not work. ("succ is not a constructor, ..."). It took me a while to figure out that succ was interpreted as a variable. So the better error message would have helped me.

I just met with Andrew, who is writing proofs in elementary set theory. We tried to clean them up to make them look natural to undergraduate students.  When we tried putting a subproof in a "proof ... qed" block, we had to replace every "have" we used by "assert" to make it visible (or use "using"). I don't remember having to do that in the past -- did it change?

**Comment by leodemoura** [comment]
> I just met with Andrew, who is writing proofs in elementary set theory. We tried to clean them up to make them look natural to undergraduate students. When we tried putting a subproof in a "proof ... qed" block, we had to replace every "have" we used by "assert" to make it visible (or use "using"). I don't remember having to do that in the past -- did it change?

Recall that we changed how `proof ... qed` is compiled. 
I described the change in the mailing list:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lean-discuss/vk291scwbfo/DsQQs1B_ficJ

Now `proof t qed` is compiled using `by exact t`. This is why we need an `assert`. 
The modification was performed to simplify the elaboration procedure and make the control flow simpler to understand.

**Comment by fpvandoorn** [comment]
> Note that proof T qed is an "one way road". That is, information inferred from T is not available for elaborating the term surrounding the proof ... qed.

Yes, but that shouldn't be a problem in my example. If I replace the `proof ... qed` by `_`, everything is elaborated correctly (except the value of `_` of course). Is the term inside `proof ... qed` elaborated after its type is fully known? Because then I don't understand why your example (with `show ... from ...`) does work, but `proof ... qed` doesn't.

> did it change?

Yes, see [this mail](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lean-discuss/vk291scwbfo/DsQQs1B_ficJ).

**Comment by avigad** [comment]
Oh, good. I remember the e-mail now. I'll make sure the tutorial explains this.

**Comment by leodemoura** [comment]
> Yes, but that shouldn't be a problem in my example. If I replace the proof ... qed by _, everything is elaborated correctly (except the value of _ of course).

The type inferred for `_` is not the type I entered in the `show`. I did not invest time trying to understand the inferred type, but it looks different:

``` lean
pushout_ob.cases_on 
  (bool.cases_on j (λ (e_1 : j = ff), tl) (λ (e_1 : j = tt), tl) (eq.refl j))
  (λ (e_1 : bool.cases_on j (λ (e_1 : j = ff), tl) (λ (e_1 : j = tt), tl) (eq.refl j) = tl), TL)
  (λ (e_1 : bool.cases_on j (λ (e_1 : j = ff), tl) (λ (e_1 : j = tt), tl) (eq.refl j) = tr), TR)
  (λ (e_1 : bool.cases_on j (λ (e_1 : j = ff), tl) (λ (e_1 : j = tt), tl) (eq.refl j) = bl), BL)
  (eq.refl (bool.cases_on j (λ (e_1 : j = ff), tl) (λ (e_1 : j = tt), tl) (eq.refl j))) →
pushout_ob.cases_on (bool.cases_on j (λ (e_1 : j = ff), bl) (λ (e_1 : j = tt), tr) (eq.refl j))
  (λ (e_1 : bool.cases_on j (λ (e_1 : j = ff), bl) (λ (e_1 : j = tt), tr) (eq.refl j) = tl), TL)
  (λ (e_1 : bool.cases_on j (λ (e_1 : j = ff), bl) (λ (e_1 : j = tt), tr) (eq.refl j) = tr), TR)
  (λ (e_1 : bool.cases_on j (λ (e_1 : j = ff), bl) (λ (e_1 : j = tt), tr) (eq.refl j) = bl), BL)
  (eq.refl (bool.cases_on j (λ (e_1 : j = ff), bl) (λ (e_1 : j = tt), tr) (eq.refl j)))
```

> Is the term inside proof ... qed elaborated after its type is fully known?

The tactics are invoked after the unification constraints have been solved.
The type may not yet be fully known. In this case, it is, but it doesn't mean it is the one we want.
Moreover, we will not backtrack and try another solution if the type is not the one we want.
That is, a tactic failure does not trigger backtracking in the unification constraint solver.
Could we try to backtrack? Yes, we could, but it would be too expensive and produce counter-intuitive behavior when we have several different tactic blocks.

**Comment by fpvandoorn** [comment]
Sorry, I still don't exactly understand what is going on. 
First of all: I agree that it would be terrible to backtrack in the unification constraint solver when a tactic fails.

Where did you put the underscore to get the inferred type you posted? I can't reproduce something which looks like that.

If I write the following (this is the same code as before, except the last term replaced by `_`)

``` lean
structure diagram [class] :=
  (Iob : Type)
  (Ihom : Type)
  (ob : Iob → Type)
  (dom cod : Ihom → Iob)
  (hom : Π⦃j : Ihom⦄, ob (dom j) → ob (cod j))

inductive pushout_ob :=
| tl : pushout_ob
| tr : pushout_ob
| bl : pushout_ob

open pushout_ob bool

universe variable u
variables {TL TR BL : Type.{u}} {f : TL → TR} {g : TL → BL}

definition pushout_diag : diagram :=
diagram.mk pushout_ob
           bool
           (λi, match i with | tl := TL | tr := TR | bl := BL end)
           (λj, match j with | tt := tl | ff := tl end)
           (λj, match j with | tt := tr | ff := bl end)
           (λj, _)
```

The inferred type of `_` is 

``` lean
pushout_ob.cases_on (bool.cases_on j tl tl) TL TR BL →
  pushout_ob.cases_on (bool.cases_on j bl tr) TL TR BL
```

Let's call this type `T`. If I now replace the underscore by 

``` lean
show T, from 
  match j with | tt := f  | ff := g end
```

the resulting term gets accepted:

``` lean
definition pushout_diag : diagram :=
diagram.mk pushout_ob
           bool
           (λi, match i with | tl := TL | tr := TR | bl := BL end)
           (λj, match j with | tt := tl | ff := tl end)
           (λj, match j with | tt := tr | ff := bl end)
           (λj, show pushout_ob.cases_on (bool.cases_on j tl tl) TL TR BL →
                     pushout_ob.cases_on (bool.cases_on j bl tr) TL TR BL, from 
                       match j with | tt := f  | ff := g end )
```

This is how I think about the elaboration when I write `proof match j with | tt := f  | ff := g end qed`. But apparently this intuition is wrong, since the latter is not accepted. To be more precise, the following is not accepted:

``` lean
definition pushout_diag {f : TL → TR} {g : TL → BL} : diagram :=
diagram.mk pushout_ob
           bool
           (λi, match i with | tl := TL | tr := TR | bl := BL end)
           (λj, match j with | tt := tl | ff := tl end)
           (λj, match j with | tt := tr | ff := bl end)
           (λj, proof (match j with | tt := f  | ff := g end) qed)
```

Disturbingly: if I replace `proof t qed` by `by exact t`, the definition _is_ accepted. 

``` lean
definition pushout_diag {f : TL → TR} {g : TL → BL} : diagram :=
diagram.mk pushout_ob
           bool
           (λi, match i with | tl := TL | tr := TR | bl := BL end)
           (λj, match j with | tt := tl | ff := tl end)
           (λj, match j with | tt := tr | ff := bl end)
           (λj, by exact (match j with | tt := f  | ff := g end))
```

But `proof t qed` is supposed to be syntax sugar for `by exact t`, right? Is that a bug?

**Comment by leodemoura** [comment]
> Where did you put the underscore to get the inferred type you posted? I can't reproduce something which looks like that.

I put in the same place you inserted it.

**Comment by leodemoura** [comment]
> the resulting term gets accepted:
> 
> ``` lean
> definition pushout_diag : diagram :=
> diagram.mk pushout_ob
>            bool
>            (λi, match i with | tl := TL | tr := TR | bl := BL end)
>            (λj, match j with | tt := tl | ff := tl end)
>            (λj, match j with | tt := tr | ff := bl end)
>            (λj, show pushout_ob.cases_on (bool.cases_on j tl tl) TL TR BL →
>                      pushout_ob.cases_on (bool.cases_on j bl tr) TL TR BL, from 
>                        match j with | tt := f  | ff := g end )
> ```

Same for me.

**Comment by leodemoura** [comment]
> But proof t qed is supposed to be syntax sugar for by exact t, right? Is that a bug?

I fixed a problem today with `proof ... qed`. https://github.com/leanprover/lean/commit/107763a506772d9fcc294fb536d24d5fce02dbab

It was being mapped to `by rexact t`.

**Comment by leodemoura** [comment]
I'm still exploring alternatives for this one.
- It is not trivial to add the extra information to the error messages. The errors are produced when constraints cannot be solved. The constraints are created in many different places (e.g., in the type checker). Most of these places are not even aware of the existence of match-expressions.
- The extra information is not a complete solution. We would still get counter intuitive behavior for examples such as:

``` lean
   open nat
  definition to_nat : bool -> nat :=
  | tt := 1
  | ff := 0

  open bool
  eval to_nat tt  -- produces 1 (correct)
  eval to_nat ff  -- produces 1 (error)
```

The problem is that `tt` and `ff` were treated as variables instead of constructors when we compiled `to_nat`.
- It is not feasible to open namespaces for the reasons I described above. It would generate  confusion. Recall that the order we open namespaces matter.

So, I'm thinking about the following solution: on the left-hand-side of equations we reject variables names that are suffixes of unary constructors. For example, we will reject `tt`, `ff`, and `zero` because we have the constructors `bool.tt`, `bool.ff` and `nat.zero`.
Non-unary constructors are not problematic because the compiler would reject a term such as `(succ n)`. It generates an error such as

``` lean
 invalid argument, it is not a constructor, variable, nor it is marked as an inaccessible pattern
  succ n
in the following equation left-hand-side
  add (succ n) m
```

**Comment by leodemoura** [comment]
Update: after commit https://github.com/leanprover/lean/commit/107763a506772d9fcc294fb536d24d5fce02dbab

The following also works:

``` lean
definition pushout_diag {f : TL → TR} {g : TL → BL} : diagram :=
diagram.mk pushout_ob
           bool
           (λi, match i with | tl := TL | tr := TR | bl := BL end)
           (λj, match j with | tt := tl | ff := tl end)
           (λj, match j with | tt := tr | ff := bl end)
           (λj, proof (match j with | tt := f  | ff := g end) qed)
```

**Comment by fpvandoorn** [comment]
> The following also works:

Great. That solves that part of this issue.

> So, I'm thinking about the following solution: on the left-hand-side of equations we reject variables names that are suffixes of unary constructors.

It might be problematic if we have something like the following, though

``` lean
structure this_is_almost_never_used (A : Type) := (n : A)
```

or more realistically:

``` lean
structure pair (A : Type) := (x : A) (y : A)
```

This can be especially problematic, since we don't even have to open the corresponding namespace of the these structure, we only have to import the file where they are declared... So just defining such a structure can break definitions at completely different places.

**Comment by fpvandoorn** [comment]
Maybe this idea works.

If I write something like this

``` lean
definition foo : bool × nat × list num → Type :=
| /- big list match cases here -/
```

is it easy to extract the datatypes which we could potentially match over (so `prod, bool, nat, list, num` in the above example)? If so, the `match` expression could generate a warning when (declarations from) one of these namespaces is not opened. Would that work?

**Comment by leodemoura** [comment]
> or more realistically:
> 
> ``` lean
> structure pair (A : Type) := (x : A) (y : A)
> ```

Yes, this would be a mess.

**Comment by leodemoura** [comment]
> is it easy to extract the datatypes which we could potentially match over (so prod, bool, nat, list, num in the above example)?

For the example you posted is easy. However, this is not true in general.
Suppose we have `match t with ... end`, the type of `t` is only known after we perform type inference and solve unification constraints. Even after we find the type, the exact datatypes used are only known after we normalize. Moreover, we are not necessarily matching against all of them.
Only in the pattern matching compiler, we obtain this information. To make things messier, the pattern matching compiler is unaware of the existence of the `open` command, `aliases`, etc.

**Comment by fpvandoorn** [comment]
Hmm... I see how this can be hard in general.

I give up, I'm out of ideas. Maybe we should just add **make sure that you open all relevant namespaces when writing match expressions** bolded and in huge font in the tutorial. :-)

**Comment by avigad** [comment]
I'll add an explanation next time I settle down to work on the tutorial.

**Comment by leodemoura** [comment]
After the two commits above, Lean produces the following error message for:

```
528.lean:6:5: error: type mismatch at definition 'match', has type
  P bool.ff
but is expected to have type
  P bool.tt
The following identifier(s) are introduced as free variables by the left-hand-side of the equation:
  ff 
```

**Comment by avigad** [comment]
Lovely!
