### ISSUE TITLE
rewrite fails after giving complete pattern

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#531]
In [this gist](https://gist.github.com/fpvandoorn/a645917ca52129319fd8) the rewrite tactic fails on line 132, even though I give the complete pattern. 

What is even stranger: if I copy-paste the whole goal to a new example (lines 136-147) and apply the same tactic, it does succeed. It somehow seems as if an earlier tactic did something strange to the proof state, which makes the current tactic fail. 

This also happened in #488. I've had this a couple of times earlier, with either `esimp`, `rewrite` or `clear`. However, it makes it hard to create a minimal example, because I need earlier steps of the tactic proof as well.

I hope you forgive me for not making a minimal example because of this.

**Comment by fpvandoorn** [comment]
EDIT: I added a second file to the gist (almost the same file), with another example, where the `change` tactic [fails](https://gist.github.com/fpvandoorn/a645917ca52129319fd8#file-colimit2-hlean-L128), but [succeeds](https://gist.github.com/fpvandoorn/a645917ca52129319fd8#file-colimit2-hlean-L158) if I copy the goal to an example.

**Comment by leodemoura** [comment]
closed by
https://github.com/leanprover/lean/commit/d0559472438026950fc8d32799fa878eec09ff7e
https://github.com/leanprover/lean/commit/dce71773824654ebeed12b59e0971c5f8a8f89bd
