### ISSUE TITLE
ability to make parameters implicit / explicit

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#532]
If you have a parameter `A` in a context, you typically want it to be implicit in some definitions and explicit in others. There should be a way to do this. Maybe using the following syntax?

``` lean
context
  parameters {A : Type₁} (B : Type₁)

  definition foo1         (a : A) := a -- A implicit, B explicit
  definition foo2 (A)     (a : A) := a -- A and B both explicit
  definition foo3 {B}     (a : A) := a -- A and B both implicit
  definition foo4 (A) {B} (a : A) := a -- A explicit, B implicit
end
```

I know that currently the `(A)` and `{B}` are parsed as fresh variables, so maybe this is not the best notation, but I couldn't think of something better.

(this should also be implemented for `variables`, but with `variables` there is an easy workaround (just give a fresh variable as argument))

**Comment by leodemoura** [comment]
This is a useful feature, but we have to come up with a clean and uniform semantics.
As you pointed out, it must work uniformly for parameters and variables.
What about lambdas? Suppose we write `foo2` as

``` lean
definition foo2 := fun (A) (a : A), a
```

What about variables introduced by `match-expressions`?
Another issue: suppose `A` is used in a nested lambda, and it contains references to other parameters that are not available in the context. We would have to sign an error.

Potential problem: a uniform treatment may generate more confusion.

**Comment by fpvandoorn** [comment]
_(first a note: The examples in my first post are wrong; since the definition doesn't mention `B` there is no reason to include it. Assume that the definition also depends on `B` in some way.)_

I don't know whether (or how) this feature generalizes to other binders, such as lambdas or match expressions. 

Are you proposing something for an arbitrary lambda? Because I think this notation only makes sense for the lambda directly after the `:=`, right? The following doesn't make sense (if `(A)` is treated as the new notation):

``` lean
definition foo' := bar (fun (A) (a : A), a)
```

 I don't think we have to support this notation for lambdas. Instead of your example, the user can just write 

``` lean
definition foo2 (A) := fun (a : A), a
```

I also don't understand your "another issue".

About the notation: it is super inconvenient it replaces existing notation. Now I don't use `(A)` or `{A}` in binders very often. For `(A)` you can just leave out the parentheses, but currently 

``` lean
definition foo {A} := bar
```

is the shortest way to write 

``` lean
definition foo {A : _} := bar
```

so we should probably allow that notation.

Another option would be to remove the variables, and just give parentheses in the same order as the variables/parameters. For example:

``` lean
parameters {A : Type₁} (B : Type₁)
definition foo4 () {} (f : A → B) := f -- A explicit, B implicit
```

That doesn't clash with any existing notation right? However, it is much less readable.

**Comment by leodemoura** [comment]
> Are you proposing something for an arbitrary lambda? 

I think it is important to have uniform behavior. Lean is getting more and more complicated. 
For example, right now,

``` lean
definition id (A : Type) (a : A) : A := a
```

is syntax sugar for

``` lean
definition id : Pi (A : Type) (a : A), A := fun (A : Type) (a : A), A
```

if we add the feature above, this will not be the case anymore. By switching between these two styles, the user may get different behavior.

We also have the "explicit variables" suggested by Georgers, that are tightly related to this issue.
I attached his proposal in the end.

> Because I think this notation only makes sense for the lambda directly after the :=, right? 

Yes, and this is the problem I was trying to point out. 
It feels like the rules for shadowing declarations are not uniform.
If the lambda is inside we shadow, otherwise we don't.

> I also don't understand your "another issue".

The other issue is that we automatically include dependencies. If the variable is in the beginning, then it is easy, we just include them too. If the variable is deeply nested, then it is not clear where to add them. In the "explicit variable" proposal, Georges suggested we should sign an error in this situation.

> That doesn't clash with any existing notation right? However, it is much less readable.

I agree

---

Explicit variables proposal:

We should probably add “explicit variables”. They are called implicit types in Coq.
     The idea is the following. 
     The user specify the default type for variables using a command such as
                explicit variable x : A
     After that, a lambda (or Pi) term of the form (fun x, t) is interpreted as (fun x : A, t)
     This will help the system with coercions, since the type of x would be known at preprocessing time.
     It would also minimize the number of metavariables we have to create.
     It also helps to enforce a consistent notation. For example, we could say that “a,b,c,d” are ob’s, “f,g,h” are hom’s on the top of a category file.
     Here is an example that would benefit from that:
                https://github.com/leanprover/lean/blob/master/hott/algebra/precategory/functor.hlean#L31-L45

**Comment by fpvandoorn** [comment]
Yes, the explicit variables proposal is indeed very similar to this. 

I think we can even merge the concepts of `variables` (which we currently have) and the `explicit variables` proposed by Georges. Then I think we _can_ implement my suggestion uniformly, and also accept "deeply nested" variables. The disadvantage is that we cannot use the (explicit) variables in the again for other uses. So if we write `variable [H : inhabited A]` we cannot use `H` for anything else. I think we can easily work around this issue, by not using `H` as variable, but something like `inhA`.

So I propose something like this:
- We can write `variables {A : Type} [inhA : inhabited A] (a : A)`
- If we have any binder where either variable `A`, `inhA` or `a` is used, the default type is the indicated type. So `fun A a, t` is interpreted as `fun {A : Type} (a : A), t`
- We can override the type of binders by writing something like `fun (A) {a}, t`, which is now interpreted as `fun (A : Type) {a : A}, t`
- Possibly we might also want to be able to "overwrite" the type and write `fun (a : A'), t`. This is only accepted if `A` and `A'` are definitionally equal. (but this can still be useful, if `A` is a reducible definition, and it's easier for the unifier to give an `A'` definitionally equal to `A`.
- If a variable `a` is mentioned without an explicit binder before it, say in `definition foo := a`, then `a` (and all variables in the type of `a`) are inserted as arguments to `foo`.
- In particular, if we can allow a declaration like `definition foo := bar (fun a, t)`, and interpret this as `definition foo {A : Type} := bar (fun a, t)`. This would also be the result if we would have written `definition foo := bar (fun (a : A), t)` under the current behavior in Lean. (this is an example of a "deeply nested" variable, right?)

For parameters we can do something similar. It is less nice though: deeply nested parameters don't make sense. But if we use the restriction that if `(p : P)` is a parameter in the context, we cannot use the letter `p` for anything but that parameter (which is similar to the restriction that if `x : X` is a variable in the context, all letters `x` must have type `X`), then the term `bar (fun p, t)` would also be rejected. So then we can still use the notation `fun {p}, t` to overwrite the type of binder used for `p`, as long as `fun p, t` would make sense in that position (which is only when `p` is not deeply nested).

Does this make sense? Does it sound reasonable?

**Comment by leodemoura** [comment]
> this is an example of a "deeply nested" variable, right?

Yes

> Does this make sense? Does it sound reasonable?

Everything makes sense and sounds reasonable. 
We should invest time thinking about all the consequences of this change.
This is not a small modification. It is a lot of work to change again how the variable/parameter mechanism works.
I think there are many details. Example: is the following a valid declaration or not?

``` lean
variable {A : Type}
variable (a : A)

definition foo (b : bool) := 
    if b = tt then (fun (A1 : Type) a, a) 
    else (fun A a, a)
```

I think it is invalid, if we add `A` for the "then branch", we get the following type incorrect term

``` lean
definition foo (A : Type) (b : bool) := 
    if b = tt then (fun (A1 : Type) (a : A), a) 
   else (fun (A : Type) (a : A), a)
```

It seems messy the procedure that decides whether it is ok to add a dependency or not.
This is just a random example, I think we may find many more issues like the one above.

In principle, I think it is nice to merge the concepts of "variable" and "explicit variable", but we have to work out all the details, and think about nasty corner cases.

**Comment by fpvandoorn** [comment]
> We should invest time thinking about all the consequences of this change.

I agree. Especially we should consider carefully whether we want to give up the power to use the same name for variables inside a section and (different) local variables inside a definition. So if I write

``` lean
variable (a : T)
```

all variables `a` _anywhere_ in the scope of that declaration must have type `T`.
@avigad, @javra, what do you think?

>  Example: is the following a valid declaration or not?

That should indeed be invalid: you cannot use `a` in a term which has a different type (`A1`) than the one declared in the section (`A`).

> It seems messy the procedure that decides whether it is ok to add a dependency or not.

What do you mean with this?

Another thing we have to think about is tactic proofs. If I write `intros [x, y, a]` with `a` an (explicit) variable; do we also enforce its type? I think we have to: we might change to declarative style later, and still use `a`. Is that a problem?

**Comment by leodemoura** [comment]
> What do you mean with this?

The procedure that says that `definition foo := bar (fun a, t)` is ok, but 
`definition foo (b : bool) := if b = tt then (fun (A1 : Type) a, a)  else (fun A a, a)` is not.
What about this one?

``` lean
definition foo (A) (b : bool) := if b = tt then a  else bla (fun A a, a)
```

What about this one?

``` lean
definition foo (b : bool) := if b = tt then a else bla (fun A a, a)
```

I think it is sensible to reject both of them, but one can make an argument that it is ok to accept them.

> Another thing we have to think about is tactic proofs. If I write intros [x, y, a] with a an (explicit) variable; do we also enforce its type?

The tactics are implemented on top of the kernel. They are completely unaware of the syntactic representation used for Lean terms. In principle, we can completely change the concrete syntax, and the tactic module is unaffected. From the tactic module perspective, there are no parameters, variables, sections, etc. All these features exist only in the Lean front-end.
So, the only way to enforce the type is to have a new `intro` tactic that allows the front-end to communicate to the tactic framework what is the expected type.

**Comment by javra** [comment]
I never felt like I needed this feature. I'm not sure if it's not cleaner to leave it as it is, I think it's better style to give the types explicit in most cases. I see that it's nice to have for parameters and variables but I don't know if it's worth the effort and how much confusion it will cause for beginners.

**Comment by fpvandoorn** [comment]
> The procedure that says that `definition foo := bar (fun a, t)` is ok, but
> `definition foo (b : bool) := if b = tt then (fun (A1 : Type) a, a) else (fun A a, a)` is not.

But that is because the second example can only be well-typed if the `a` in the then-clause has type `A1`. 

I'm not sure whether we are on the same line. My suggestion is that if we declare an _explicit variable_ `variable (a : A)`, then this is the same as declaring `(a : A)` as a variable in our current system, except that in all definitions we need to
- replace `*binder* a` with `*binder* (a : A)` everywhere;
- replace `a` (not in a binder) with `(a : A)` (i.e. `is_typeof A a`) everywhere.

This doesn't look messy to me. Maybe this can even be done mostly by the preprocessor on top of our current mechanism of variables. There are some special cases if you write `*binder* {a}` or `*binder* (a : A')` if you want to overwrite the default binder or type, but the basic idea is simple.

So your examples. Your first one becomes (assuming `variables {A : Type}(a : A)`)

``` lean
definition foo (A : Type) (a : A) (b : bool) := 
  if b = tt then (a : A) else bla (fun {A : Type} (a : A), a)
```

which is type-correct if and only if the type of `bla (fun {A : Type} (a : A), a)` is definitionally `A`.

(this example is a little weird since we have two different `a`'s: but I don't think that is something we have to disallow).

The second becomes

``` lean
definition foo {A : Type} (a : A) (b : bool) := 
  if b = tt then (a : A) else bla (fun {A : Type} (a : A), a)
```

(i.e. the same, except that `A` is now an implicit argument of `foo`, which is how we declared `A`)

**Comment by leodemoura** [comment]
@fpvandoorn We are on the same page.
I was trying to build examples that generate weird behavior.
For example, the definitions with two `a`'s look like a bug. 
When I said "messy", I was thinking about a preprocessor that would reject the weird examples.
It is not clear to me where we draw the line: "what is messy and what is not".

**Comment by fpvandoorn** [comment]
I don't see a reason to reject them. We also accept messy things like

``` lean
example {A B C : Type} (x : A) : B -> C -> nat := fun x x, 0
```

**Comment by leodemoura** [comment]
> I don't see a reason to reject them. We also accept messy things like
> 
> ``` lean
> example {A B C : Type} (x : A) : B -> C -> nat := fun x x, 0
> ```

There is a difference. In your example, the user decided to write the messy thing. The mess is clear to him. In the examples I wrote, the mess is not explicit. It will only become apparent when we type `check foo`, or we try to prove things about `foo`.

**Comment by fpvandoorn** [comment]
That is true, and a valid point.

**Comment by avigad** [comment]
I am just now catching up on this thread. I don't have strong opinions; the system is already quite usable in this respect.

It is a small annoyance that often we begin a section with  `variables (a b c d e : foo)` because we want to prove a bunch of theorems about elements of foo, except sometimes we want them to be implicit and sometimes we want them to be explicit. Whichever one we choose, we have to state the parameters explicitly for the exceptions. In those cases, though, writing {a b c d e : foo} is not a big deal. In fact, most of the time we can write {a b c d e} and let Lean infer the type. So the proposed changes will not change my life much.

It seems that there are two variations of these proposals: one where we take the variables or explicit variables commands to apply only to parameters to theorems appearing before the :=, the other where we actually take the conventions to apply to bound variables within proofs as well.

We can already write (a b c) or {a b c} in many situations without type annotations. Is there any evidence that the extra information will have a significant positive effect on the elaborator? If not, I don't see any pressing need to modify the current behavior. 

@fpvandoorn, is it often the case that Lean has trouble if you do not annotate binders inside your proofs? And, in cases like that, is it really annoying to annotate the binders?

**Comment by fpvandoorn** [comment]
> It seems that there are two variations of these proposals: one where we take the variables or explicit variables commands to apply only to parameters to theorems appearing before the :=, the other where we actually take the conventions to apply to bound variables within proofs as well.

The problem with this is that currently

``` lean
definition foo (A : Type) : B := t
```

is syntax sugar for

``` lean
definition foo : Pi (A : Type), B := fun (A : Type), t
```

So the variables before the `:=` are just a special case of bound variables within the proof. I agree with Leo that whatever we change, this is a good property to keep.

> @fpvandoorn, is it often the case that Lean has trouble if you do not annotate binders inside your proofs? And, in cases like that, is it really annoying to annotate the binders?

In long proofs, the elaborator has definitely a lot of trouble if I give a minimal amount of information, even if that information is "technically sufficient" to infer everything. This especially happens if I use induction (or other higher-order unification) in a couple of places. Usually at that point I switch to tactic mode. Annotating the binders is possible, especially the binders which we would declare as "explicit variable", because those will typically have short types. Still, it's nice not to have to annotate most binders.

---

Summarizing, there are three feature requests in this issue:
1. Ability to change the binder type of a parameter/variable (for parameters there is currently no workaround)
2. Explicit variables which have the same type in the whole document (we can workaround this)
3. Combining variables and explicit variables.

I actually don't feel strongly about 3, since it has some annoying consequences mentioned earlier (and it doesn't really solve the issue for parameters). 1 is annoying because there is no workaround, but it's not _that_ important. 2 can also wait, IMO (in my opinion). I never had the strong feeling that I needed it, but I would definitely use them if it was available.

**Comment by leodemoura** [comment]
I agree with Floris' summary.

I agree 1 is annoying but there is one possible workaround. 
It is based on the following observation: the binder type of a parameter "only" matters outside of the section/context. Thus, if we want to define `foo` with a different binder type, we can first define a private `foo` inside the section using the current binder types. Then after the end of the section,  we define the non-private `foo` with the right binder types. Here is an "extreme" example:

``` lean
section
  parameters (A : Type₁) (B : Type₁)
  include A B

  private definition foo1  (a : A) := a 
  private definition foo2  (a : A) := a 
  private definition foo3  (a : A) := a 
  private definition foo4  (a : A) := a 
end

definition foo1 {A} (B) (a) := foo1 A B a
definition foo2 (A) (B) (a) := foo2 A B a
definition foo3 {A} {B} (a) := foo3 A B a
definition foo4 (A) {B} (a) := foo4 A B a
```

This is not a perfect solution, but it seems to be good enough.

**Comment by fpvandoorn** [comment]
That is indeed a possible workaround for the moment. I think that the `definitions` outside the section should be `abbreviations`, though.

Another (I think better) way to implement 1: have a command `parameter {a}` which just changes the binding type of an _existing_ parameter `a`. 

```
section
  parameters (A : Type₁) {B : Type₁} (b : B)
    -- A explicit, B implicit, b explicit
  parameters {A} (B)
    -- A implicit, B explicit, b explicit
end
```

**Comment by leodemoura** [comment]
> Another (I think better) way to implement 1: have a command parameter {a} which just changes the binding type of an existing parameter a.

This one is easy to implement. Let's try it.

**Comment by leodemoura** [comment]
> Another (I think better) way to implement 1: have a command parameter {a} which just changes the binding type of an existing parameter a.

I added this feature. It is simple and seems to work well. See example in the commit above.
I will close this issue. 
We can add "explicit variables" in the future.

**Comment by fpvandoorn** [comment]
Great!
