### ISSUE TITLE
strange behavior of function definition package

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#541]
@rlewis1988 and I noticed some strange behavior in the function definition package. The proof below works, but the line the starts "have Hor: ..." is redundant. It is not used anywhere in the proof.If you comment out the line, there is an error in the next line, a very complicated "type mismatch at application." This feels like a bug; at least, we do not understand what is going on.

``` lean
import data.list data.nat
open nat list eq.ops

theorem nat.le_of_eq {x y : ℕ} (H : x = y) : x ≤ y := H ▸ !le.refl
calc_trans nat.ge.trans

section

variable {Q : Type}

definition f : list Q → ℕ  -- default if l is empty, else max l
  | []        := 0
  | (h :: t)  := f t + 1

theorem f_foo : ∀{l : list Q}, ∀{q : Q}, q ∈ l → f l ≥ 1
  | []                := take q, assume Hq, absurd Hq !not_mem_nil
  | [h]               := take q, assume Hq, nat.le_of_eq !rfl
  | (h :: (h' :: t))  := take q, assume Hq,
    have Hor : q = h ∨ q ∈ (h' :: t), from iff.mp !mem_cons_iff Hq,
    have H : f (h' :: t) ≥ 1, from f_foo (mem_cons h' t),
    have H1 : 1 + 1 ≤ f (h' :: t) + 1, from nat.add_le_add_right H 1,
    calc
      f (h :: h' :: t) = f (h' :: t) + 1 : rfl
                   ... ≥ 1 + 1           : H1
                   ... ≥ 1               : !le_succ_of_le !le.refl

end
```

To more small comments: it seems that the theorem nat.le_of_eq has been deleted from the library. Why? Also, for some reason, nat.ge.trans is not declared as a calc_trans rule; shouldn't we declare it? (If you import and open "algebra", the rule is present.)

**Comment by leodemoura** [comment]
I will investigate this issue later. In the meantime, we can workaround the problem by avoiding the unnecessary `takes` and `assumes`. Here is the simpler `f_foo`:

``` lean
theorem f_foo : ∀ {l : list Q} {q : Q}, q ∈ l → f l ≥ 1
  | []              q Hq := absurd Hq !not_mem_nil
  | [h]             q Hq := nat.le_of_eq !rfl
  | (h :: h' :: t)  q Hq := 
    have H : f (h' :: t) ≥ 1, from f_foo (mem_cons h' t),
    have H1 : 1 + 1 ≤ f (h' :: t) + 1, from nat.add_le_add_right H 1,
    calc
      f (h :: h' :: t) = f (h' :: t) + 1 : rfl
                   ... ≥ 1 + 1           : H1
                   ... ≥ 1               : !le_succ_of_le !le.refl
```

> To more small comments: it seems that the theorem nat.le_of_eq has been deleted from the library. Why?

I don't know. Do you know which commit deleted it?

> Also, for some reason, nat.ge.trans is not declared as a calc_trans rule; shouldn't we declare it?

We should.

**Comment by robertylewis** [comment]
I'm not sure that nat.le_of_eq ever existed. At least, I don't see algebra.le_of_eq anywhere in the history of order.lean. (The theorem I noticed disappear was one of the redundant trans rules -- lt_of_lt_of_eq, I think -- and I see why that was removed.) They may have just been overlooked.

**Comment by avigad** [comment]
O.k., I'll add le_of_eq, and make nat.ge.trans a calc_trans rule. Thanks, Leo, for showing us how to simplify the proof.

**Comment by leodemoura** [comment]
The source of the bug is the following:
On the left hand side, `f_foo` is described as a unary function (it returns a function of type `∀{q : Q}, q ∈ l → f l ≥ 1`). On the right hand side, there is a recursive application that treats `f_foo` as a ternary function. The application `f_foo (mem_cons h' t)` is notation for `f_foo _ _ (mem_cons h' t)`.
The current compiler incorrectly assumes that the number of arguments provided to `f_foo` is equal to the number of arguments on the left-hand-side. So, it incorrectly eliminates the recursive call.
The strange error message is generated by the kernel during the type checking step. It is weird because it is due to a compilation bug. 
When we add extra terms, we change the order the constraints are solved. This is why the superfluous `have` is also a workaround.   Note that the superfluous `have` is also giving hints to the elaborator. It is constraining the type of `Hq` and `q`.

**Comment by avigad** [comment]
Interesting. So sending the "right" number of arguments fixes the problem in this case, but the problem would likely come up again in situations where the more general recursion is needed (because the function or theorem has to be applied to different arguments).

**Comment by robertylewis** [comment]
Aha! That's tricky. Thanks for looking, Leo.

**Comment by leodemoura** [comment]
> Interesting. So sending the "right" number of arguments fixes the problem in this case, but the problem would likely come up again in situations where the more general recursion is needed (because the function or theorem has to be applied to different arguments).

I think this issue only occurs in really rare cases. I don't see any realistic example where the workaround would not work. For me, this is a very low priority issue. It will be fixed, but not in the near future.
