### ISSUE TITLE
Emacs mode C-c C-x doesn't handle spaces in paths

### ISSUE THREAD

**Issue by criemen** [leanprover/lean3#544]
Steps to reproduce
Create a folder with a space in the name
Create a file test.lean inside that folder
Open Emacs, try out C-c C-x, you'll get a "cannot open file" error, because the space is not quoted.

**Comment by fpvandoorn** [comment]
Is it possible that this fix broke it for me? Any time I try to compile with `C-c C-x` now, I get an error like this:

```
-*- mode: compilation; default-directory: "~/projects/lean/hott/types/" -*-
Compilation started at Thu Apr 16 19:10:34

\~/projects/lean/bin/lean -Dpp.width=120  /home/floris/projects/lean/hott/types/square.hlean
/bin/bash: ~/projects/lean/bin/lean: No such file or directory

Compilation exited abnormally with code 127 at Thu Apr 16 19:10:34
```

**Comment by soonhokong** [comment]
@fpvandoorn, possibly. I'll double check it on a Linux machine. Can you confirm that you do have a file at `~/projects/lean/bin/lean`?

**Comment by leodemoura** [comment]
@fpvandoorn I also had this problem. I'm not sure exactly what fixed it, but the problem was gone after I: deleted the build directory and rebuilt from scratch, and restarted emacs. 
@soonhokong I had `~/projects/lean/bin/lean` when I experienced the problem.

**Comment by soonhokong** [comment]
Hmm... the only change was to use the function `shell-quote-argument` to escape any special characters in a pathname (i.e. space).

@fpvandoorn, can you exit emacs and reopen it and check whether you can reproduce the problem?

**Comment by soonhokong** [comment]
OK. I can reproduce it on my linux machine... I'll investigate it.

**Comment by soonhokong** [comment]
@fpvandoorn, please try the latest version.

**Comment by fpvandoorn** [comment]
Wow, that was fixed quickly. Thanks! 
I can't check right now whether it works, but I'll try it tomorrow.
