### ISSUE TITLE
robust coercions

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#547]
To address issue raised in the following thread at the Lean group:

---

That sounds like a very sensible and robust solution. So, for now, I will leave the implementation of quotients as it is, and work around the lack of coercions for numerals. 

Best wishes,

Jeremy

On Sat, Apr 18, 2015 at 11:28 AM, Leonardo de Moura leonardo@microsoft.com wrote:
Dear Jeremy,

I had a similar problem with finset (also defined using quotients).
I have been thinking about the following solution.
In the current Lean, we use the default normalizer (+ reducible hints) to decide whether a coercion can be applied or not.
We can “fix” the problem by using a different normalizer.
Here is the summary:

1) We have a new (internal) attribute: coercion-head.
This attribute is set automatically by Lean, and the user is not even aware it exists.

2) A constant C is marked as a coercion-head whenever we declare a coercion from (C …) or to (C …)

3) When deciding whether a coercion can be applied or not, we use a normalizer that treats coercion-head constants as opaque (independently of the reducible hints associated with them).

I think this will solve this kind of problem. 

Best,
Leo

From: lean-discuss@googlegroups.com [mailto:lean-discuss@googlegroups.com] On Behalf Of Jeremy Avigad
Sent: Saturday, April 18, 2015 5:36 AM
To: lean-discuss@googlegroups.com
Subject: [lean-discuss] coercing to rationals

Dear all,

I defined the rationals and showed that they are a field. With quotients, it was easy and pleasant. The "migrate" command worked nicely, and now we have all of Rob's theorems about fields specialized to the rationals. I will issue a pull request soon.

I still have to define the order and make it an instance of an ordered field, but I think that will also be straightforward.

There is one small glitch: right now, we cannot coerce to rationals. In other words, this doesn't work:

---

definition rat : Type.{1} := quot prerat.setoid
notation `ℚ` := rat

definition rat.of_int [coercion](i : ℤ) : ℚ := ⟦prerat.of_int i⟧
definition rat.of_num [coercion] [reducible](n : num) : ℚ := of_int (int.of_num n)

check (0 : ℚ)  -- error
check (rat.of_int 0 : ℚ) -- ok

---

I assume the problem is they are not an inductive type. I was initially confused by this, even though I have come across the same problem many times before, and even though I wrote the tutorial section explaining coercions. Leo, is it possible to issue an error or warning when the user tries to coerce to something that is not an inductive family or sort class or function class?

A more serious question is how to work around this. It would be annoying to wrap rat as an inductive family and destruct it repeatedly when transferring properties from prerat, but that could be done. At least, the annoyance would be limited to the construction of the rationals.

But would it be hard to allow coercions to / from quotients as well, at least when the argument to quot is explicit? It will be a common use case, I think.

Best wishes,

Jeremy

**Comment by leodemoura** [comment]
This issue conflicts with #540. 
If we implement the solution I described above. Then, when we write

``` lean
constant add (s t : sequence) : sequence

definition sequence [reducible] := ℕ → ℕ

record s_sequence : Type :=
(seq : sequence)

definition s.to_seq [reducible] [coercion] (s : s_sequence) : sequence :=
...
```

`sequence` would be marked as `coercion-head`, and `s.to_seq` would be a coercion from `s_sequence` to `sequence` and not to `ℕ → ℕ`.
Then, 

``` lean
check λ s t : s_sequence, add s t
```

would be accepted, but 

``` lean
check λ s : s_sequence, s 0
```

would not.

**Comment by leodemoura** [comment]
@avigad @rlewis1988 
What do you think?

**Comment by robertylewis** [comment]
One way around the issue in #540 is to declare `sequence` as notation for ℕ → ℕ instead of as a reducible definition. Would that still work with the fix you described here?

import init.nat 
open nat

notation `sequence` := ℕ → ℕ
constant add (s t : sequence) : sequence

record s_sequence : Type :=
(seq : sequence)

definition s.to_seq [reducible] [coercion](s : s_sequence) : sequence
:=
s_sequence.seq s

check λ s t : s_sequence, add s t
check λ s : s_sequence, s 0

**Comment by leodemoura** [comment]
> Would that still work with the fix you described here?

Yes, it would work.

**Comment by avigad** [comment]
As I recall, it also worked with "abbreviation" (though maybe that would change with the robust coercions mechanism).

Anyhow, I think the "robust coercions" are important, and having to use a notation for sequences is not a problem. In fact, even having to write the function space explicitly just to define the coercion is not bad. There is a clear instruction to the user: declare the coercions in the form in which you want them detected by the system. If you want to coerce to a function space, the coercion should be explicitly to a function space.

**Comment by leodemoura** [comment]
Great. I will close #540 and keep this one.

**Comment by fpvandoorn** [comment]
I might completely misunderstand this issue, but does this mean we can create coercions from any type to any other type (if we make them `coercion-heads`)? That sounds kind of dangerous, as Rob's example shows.

However, do we need this full generality? Both examples mentioned in this issue have a codomain which is (after reducing) of the form `C x_1 ... x_n` where `C` is a _constant_. Is there a reason why we do allow coercion to a inductive family, but do not allow coercing to a constant? Both should be fine, because they cannot be reduced to anything else, right?

**Comment by leodemoura** [comment]
> However, do we need this full generality? Both examples mentioned in this issue have a codomain which is (after reducing) of the form C x_1 ... x_n where C is a constant.

Consider the original example in the thread: rationals.
If we expand the rationals, we get `quot prerat.setoid`. 
So, we are actually defining a coercion from `num` to `quot`.
We will probably have many quotient types in the standard library.
Then, we will have many coercions going to `quot`. 
They are completely unrelated to each other, but Lean doesn't know that: more backtracking.
Another issue: `real` will probably also be a `quot`. So, we will also have coercions from `quot` to `quot`.

> Is there a reason why we do allow coercion to a inductive family, but do not allow coercing to a constant?

We need a reliable way to detect whether we need a coercion or not. The current one is: put the types in whnf and use the head symbol.
If the head symbol is a constant, then it is an opaque one: inductive datatype, axiom or opaque definition. The opaque definition is also problematic, because opaque definitions are considered transparent in the module where they were defined.

**Comment by fpvandoorn** [comment]
Ok, that does make sense. We indeed don't want to consider all coercions from/to any `quot` whenever we work on a particular quotient.
