### ISSUE TITLE
rewrite fails because of differing implicit arguments

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#551]
In the following example, the rewrite tactic fails

``` lean
import algebra.precategory.nat_trans

open category functor nat_trans eq

variables {C : Precategory} (F G : C ⇒ C)
(η : functor.id ⟹ functor.compose G F)
(ε : functor.compose F G ⟹ functor.id)
(d : C)

-- set_option pp.notation false
-- set_option pp.implicit true
-- set_option pp.abbreviations false
-- set_option pp.coercions true

example : (G (ε d) ∘ η (G d) ∘ G (ε d)) ∘ η (G d) = sorry :=
begin
  rewrite [assoc (G (ε d)) (η (G d)) (G (ε d))]
  -- the following does work:
  -- apply concat, apply (ap (λx, x ∘ η _)), exact (assoc (G (ε d)) (η (G d)) (G (ε d)))
end
```

The problem is that the implicit arguments differ in the rewrite pattern and the goal.
For example a subterm in the pattern is

``` lean
(...)
    (@to_fun_ob C C G (@to_fun_ob C C (@functor.compose C C C F G) d))
(...)
```

while the corresponding subterm in the goal is

``` lean
(...)
          (@to_fun_ob C C (@functor.compose C C C G F) (@to_fun_ob C C G d))
(...)
```

Both of these terms are definitionally equal to
`(@to_fun_ob C C G (@to_fun_ob C C F (@to_fun_ob C C G d)))`
(using coercions, `G (F (G d))`)

And there are undoubtedly dozens more places where the implicit arguments differ.

So my question is: is there a way to still unify the pattern with the goal? Or have we reached the limits of the rewrite tactic here? The latter would be a bit sad, because the example looks not so hard. However, there is quite a lot going on: especially the fact that quite some `functor.compose` and `functor.id` have to be unfolded even to type check the composition. 

Maybe we can add an attribute to `functor.compose` and `functor.id` so that they act like abbreviations for the rewrite tactic? (but it does require another attribute...)

PS: I do not actually know whether unfolding `functor.compose` and `functor.id` everywhere will make the pattern unify with the goal, but I think it does. The only way I found so far to unify the pattern with the goal was to give the full 15-line long pattern including all implicit arguments and coercions)

**Comment by leodemoura** [comment]
I think the features in issue #511 will solve this one.

**Comment by leodemoura** [comment]
In keyed-matching (ssreflect) we use only the head symbol to locate potential places that can be rewritten. After we detect a potential place, we do full unification.

**Comment by fpvandoorn** [comment]
Ah, those features sound indeed as if they will work. Then this issue can be closed as duplicate (as long as we try the new commands on this example).
