### ISSUE TITLE
compiler warning for "exit" use?

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#553]
Shouldn't the lean compiler output a warning for each use of `exit`? I guess the use of giving warnings for `sorry` is to indicate unfinished theories. Putting an `exit` somewhere has a similar is meaning in my opinion.

**Comment by leodemoura** [comment]
At one point, Lean generated an error when `exit` was used, and people complained about it. Then, I removed the error. It seems the warning is the ideal solution. Note that warnings do not prevent .olean files from being generated.
Let's include the others in the discussion: @avigad, @fpvandoorn @soonhokong

**Comment by fpvandoorn** [comment]
I would also like to have a warning issued for an exit. Once I had a problem which was caused by an `exit` which I added to a file, and then I forgot about.

**Comment by avigad** [comment]
No strong opinion here. A warning sounds good to me.

**Comment by soonhokong** [comment]
+1 for warning
