### ISSUE TITLE
"let" tactic

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#555]
When @leodemoura was visiting CMU, we collected tactics that are still lacking. One idea was a `let` tactic that lets the user introduce a new variable to the context without having to give its type explicitly like it's necessary for `assert`.

**Comment by leodemoura** [comment]
@javra I'm assuming the tactic `let f := t` should fail if `t` still contains metavariables after elaboration.

**Comment by javra** [comment]
Yes, that's how I thought it would be.
