### ISSUE TITLE
pp.metavar_args

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#558]
`help option` says that the default value of the option `pp.metavar_args` is `false`. However, if I write

``` lean
open nat
variables (P : ℕ → Type) (p : Πn, P n)
check !p
set_option pp.metavar_args false
check !p
```

The first `check` outputs explicit arguments for the metavariables.

**Comment by leodemoura** [comment]
Some commands and error messages override the default value for an option.
See:
https://github.com/leanprover/lean/blob/master/src/frontends/lean/builtin_cmds.cpp#L322

These overrides are usually motivated by user feedback.
For example, the one on `check` was motivated by this example

``` lean
check eq.rec
-- eq.rec : ?C → (Π {a : ?A}, ?a = a → ?C)
```

The `?a` at `?C ?a` is being suppressed, and the type looks incorrect.

**Comment by leodemoura** [comment]
Note that, the override is performed only if the user did not specify any value for the option.

**Comment by fpvandoorn** [comment]
Ok. I guess that is fine. The reason I asked is because I wanted to put the following example in the tutorial, but with the default option the output of the `check` is a bit overwhelming. But I'll just set that option to false there.

```
import data.vector
open vector nat

variables (P : Π(n m : ℕ) (v : vector bool n) (w : vector bool m), Type)
          (p : Π(n m : ℕ) (v : vector bool n) (w : vector bool m), P n m v w)
          (n m : ℕ) (v : vector bool n) (w : vector bool m)
eval (!p : P n m v w)
check !p
```

(personally when I want to know the type of `foo` with `check`, I _always_ write `check @foo`)
