### ISSUE TITLE
Crash when including a parameter

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#559]
The following bit of code produces the error "Compilation segmentation fault (core dumped)".

``` lean
import algebra.ordered_field
open algebra
section sequence_c

  parameter Q : Type
  parameter lof_Q : linear_ordered_field Q
  definition to_lof [instance] : linear_ordered_field Q := lof_Q
  include to_lof

  theorem foo (a b : Q) : a + b = b + a := !add.comm

end sequence_c
```

I see this isn't the appropriate way to do what I want to. But, I'm guessing the crash isn't intentional!

**Comment by leodemoura** [comment]
Dear Rob,

I fixed the crash. However, with the fix, Lean rejects `foo`.
Your file makes sense, but Lean does not support this kind of instance yet.
This limitation is discussed at issue #554. 
For convenience, I'm copying a relevant part here:

---

> Eventually (this can be implemented much later than the other points) it would be nice that for every attribute we have a local attribute which acts as an attribute for the alias (and hence would act the same way as if all parameters were replaced by constants). Then local coercions and local instances are special cases of this. This is probably an enormous amount of work to implement, because it is different for every attribute. It's probably not useful for every attribute (local attribute foo [c-unfold n] doesn't look very useful). Is there a full list of attributes somewhere?

Floris is right. This one is an enormous amount of work.
Right now, all attributes local or not are for the abstracted version. 
I think it too much work for a relatively modest improvement in usability. 
As I told with Jeremy yesterday, I want to focus all resources on better automation.

**Comment by robertylewis** [comment]
Thanks, Leo! That's more than fair. This is easy enough to work around for now, and more automation will be a huge help.
