### ISSUE TITLE
trunc.rec reduces wrong

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#564]
In [this file](https://github.com/fpvandoorn/lean/blob/issue564/hott/test.hlean) I get a type-incorrect goal when applying an unfold tactic, and I think this is caused by a bug in the new computation rule for `is_trunc.rec`. 

The goal before `rewrite ↑trunc.rec_on` is

``` lean
eq.rec (trunc.rec_on (tr a) (λ (a : A), tr idp))
    (trunc.rec_on (tr a')
       (trunc.rec_on (tr a)
          (λ (a a' : A) (x : trunctype.carrier (trunc_eq_type n (tr a) (tr a'))),
             trunc.rec_on x (ap tr)))
       x) = id x
```

If I reduce this on paper, by reducing `trunc.rec_on (tr x) H` to `H x` I get

``` lean
eq.rec (tr idp) (trunc.rec (ap tr) x) = id x
```

However, after the unfold tactic, the goal becomes

``` lean
eq.rec (tr idp) (λ (a' : A), trunc.rec (ap tr)) = id x
```

which is a type incorrect term (the resulting term is rejected when I write `apply sorry`)

**Comment by leodemoura** [comment]
Yes, this is a bug in the new computation rule.

BTW, I cannot try the example, I get the following errors when I try to compile the `issue564` branch:

```
/home/leo/projects/lean/hott/types/equiv.hlean:12:28: error: invalid import, unknown module 'hprop_trunc'
/home/leo/projects/lean/hott/types/equiv.hlean:87:78: error: don't know how to synthesize placeholder
A : Type,
B : Type,
f : A → B
⊢ is_hprop (is_contr_fun f)
/home/leo/projects/lean/hott/types/equiv.hlean:87:78: error: failed to add declaration 'is_equiv.is_hprop_is_contr_fun' to environment, value has metavariables
remark: set 'formatter.hide_full_terms' to false to see the complete term
  λ (A : Type) (B : Type) (f : …),
    ?M_1
/home/leo/projects/lean/hott/types/equiv.hlean:102:2: error: failed to synthesize placeholder
A : Type,
B : Type,
f : A → B
⊢ is_hprop (is_contr_fun f)
```

**Comment by fpvandoorn** [comment]
oops. I forgot to add that file. I pushed a new commit. It should compile now (until `test.hlean` is reached)
