### ISSUE TITLE
rewrite produced type incorrect term

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#567]
Minimal example of error in issue leanprover/tutorial#98

```
import data.set

example {A : Type} (H : set A) (a x : A) (p : a = x) (l : H x) : H a :=
begin
 rewrite p, exact l
end
```

Note: the example works if `(H : set A)` is replaced by `(H : A → Prop)`.

**Comment by leodemoura** [comment]
The problem is that the `rewriter` treats most constants as opaque.
The example works if we add

``` lean
   local attribute set [reducible]
```

I will fix the problem by using a more relaxed type checker in the parts that triggered the error.
