### ISSUE TITLE
assumption fails

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#570]
``` lean
open nat
variables (P : ℕ → Prop)

example (H1 : ∃n, P n) : ∃n, P n :=
begin
  cases H1 with n p,
  apply (exists.intro n),
  assumption
end
```

`assumption` fails with the following output:

```
tactic failed
P : ℕ → Prop,
n : ℕ,
p : P n
⊢ P n
```

**Comment by leodemoura** [comment]
The current `assumption` tactic is syntactic.
The hypothesis `p` is not really `p : P n`.  Try to set `set_option pp.beta false`.
I will improve it. I will use the unifier but in conservative mode.

**Comment by fpvandoorn** [comment]
That makes sense. We indeed want `assumption` to be fast, and it doesn't have to solve all cases where `exact p` works (where `p` is a variable in context). But a little bit more than syntactic would indeed be nice.
