### ISSUE TITLE
calc/subst sometimes works sometimes doesn't

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#572]
In the following two symmetric cases the first one (glcoset) doesn't work but the second one (grcoset) works fine.

```
import algebra.group
open algebra
variable {A : Type}
variable [s : group A]
include s
definition glcoset a (H : set A) : set A := λ x, H (a⁻¹ * x)
definition grcoset H (a : A) : set A := λ x, H (x * a⁻¹)
infixr `∘>`:55 := glcoset -- stronger than = (50), weaker than * (70)
infixl `<∘`:55 := grcoset
local attribute set [reducible]
lemma glcoset_inv a (H : set A) : a⁻¹ ∘> a ∘> H = H :=
      funext (assume x,
        calc glcoset a⁻¹ (glcoset a H) x = H x : {inv_mul_cancel_left a⁻¹ x})
lemma grcoset_inv H (a : A) : (H <∘ a) <∘ a⁻¹ = H :=
      funext (assume x,
        calc grcoset (grcoset H a) a⁻¹ x = H x : {inv_mul_cancel_right x a⁻¹})
```

Also `local attribute set [reducible]` still affects the following (on application of `inv_one`). Without it both lemmas failed to type check.

```
lemma glcoset_id (H : set A) : 1 ∘> H = H :=
      funext (assume x,
        calc (1 ∘> H) x = H (1⁻¹*x) : rfl
        ... = H (1*x) : inv_one
        ... = H x : one_mul)
lemma grcoset_id (H : set A) : H <∘ 1 = H :=
      funext (assume x,
        calc H (x*1⁻¹) = H (x*1) : inv_one
        ... = H x : mul_one)
```

Is this expected after the patch in #567?

**Comment by fpvandoorn** [comment]
The first example fails because you need to use the theorem `mul_inv_cancel_left`.

The error in the second example isn't related to #567, since you don't use the rewrite tactic (`{ ... }` in calc are different than rewrite). I'm not sure why making `set` reducible solves the error you're getting. But it does indicate that we should just make `set` always reducible. I'll do that in my next pull request (unless someone else does it earlier).

**Comment by htzh** [comment]
@fpvandoorn, thanks for spotting the mistake in the first part. I should have checked that one more carefully before submitting it. (I proved it another way so thought the lemma was fine but missed that the proof was not). 
I also tried with {...} for the second part and that seems to work. I reread the relevant section in the tutorial and it seemed that {...} is more limited, that is it gets tried anyway:

```
If the justification for a line of a calculations proof is foo, Lean will try adding implicit arguments if foo alone fails to do the job. If that doesn't work, Lean will try the symmetric version, foo⁻¹, again adding arguments if necessary. If that doesn't work, Lean proceeds to try {foo} and {foo⁻¹}, again, adding arguments if necessary. 
```

I will read more on the reducible attribute to see if I understand why.

**Comment by htzh** [comment]
BTW for the second part, if I remove the reducible attribute on set, in addition to {inv_one} I have to also explicitly specify {one_mul x}, which proves H (1*x) = H (x), which on the face of it does not have anything to do with set. But then again if it has trouble unfolding the definition of set it might not see that H x has the expected type.

```
--local attribute set [reducible]
lemma glcoset_id (H : set A) : 1 ∘> H = H :=
      funext (assume x,
        calc (1 ∘> H) x = H (1⁻¹*x) : rfl
        ... = H (1*x) : {inv_one}
        ... = H x : {one_mul x})
lemma grcoset_id (H : set A) : H <∘ 1 = H :=
      funext (assume x,
        calc H (x*1⁻¹) = H (x*1) : {inv_one}
        ... = H x : {mul_one x})
```

**Comment by avigad** [comment]
I think you are right, set should be marked reducible globally. The problem is that subst and calc use higher-order unification to infer the context for the substitution, and for performance reason higher-order unification has to be conservative about unfolding definitions. I will experiment and make the change.
