### ISSUE TITLE
lean mode flycheck problem in a project directory

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#573]
I set up a directory following the instruction using menu -> create new project. However in the project directory the flycheck messages are no longer shown at the relevant places, instead the error indicator (red wavy underline) only appears at the very top of the file and the messages only show if I click there. This only happens in a project directory. Emacs works fine on files not in a project directory. I have Emacs 24.4 and I just updated my flycheck package and the problem persists. The project file is unmodified from the auto-generated version:

```
# Lean project file

# Include all .lean files under this directory
+ *.lean

# Exclude flycheck generated temp files
- flycheck*.lean

# Exclude emacs temp files
- .#*.lean
```

Anything else I should be checking?

**Comment by soonhokong** [comment]
@htzh, which OS are you using? which version of Python are you using?

**Comment by soonhokong** [comment]
I can reproduce the problem on Windows(msys2) + python3.

**Comment by htzh** [comment]
I am on Windows/MSYS2 + Python2.7.

**Comment by leodemoura** [comment]
@soonhokong Have you tried with or without this commit: https://github.com/leanprover/lean/commit/24b00c3a73241d856f134a30a76517d8c984933e ?

I can try it today since I don't have a windows (with msys2) machine at home.

**Comment by leodemoura** [comment]
BTW, I asked the question above, because I added the 

``` python
 # I had to add the following line to avoid a crash on Python 3.4 for Windows       
line = line.decode("utf-8")
```

to fix problems with Emacs + flycheck + Lean on windows.

**Comment by soonhokong** [comment]
I was working on it on the campus, but I'm home now. I'll go back to lab soon.

> @soonhokong Have you tried with or without this commit: 24b00c3?

I had some problem without it. It's related to output Unicode text to stdout in Windows environment. I'm investigating it..

**Comment by leodemoura** [comment]
Thanks!

**Comment by soonhokong** [comment]
@htzh, please try the latest version and let me know if you still have the problem.

**Comment by htzh** [comment]
@soonhokong, it looks like the problem is fixed. Thanks for your hard work!

**Comment by soonhokong** [comment]
@htzh, great!
