### ISSUE TITLE
local notation replaces previous notation, rather than overloads

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#574]
Is this the intended behavior?

``` lean
import data.nat data.set
open set

variables a b : set nat

check a ∩ b  -- ok

infix `∩` := nat.add

check a ∩ b  -- ok

local infix `∩` := nat.add

check a ∩ b  -- error
```

**Comment by fpvandoorn** [comment]
Yes, that is indeed the intended behavior: https://github.com/leanprover/lean/issues/554#issuecomment-95010837 (item 4)

I think that is also what I usually want.

**Comment by avigad** [comment]
Thanks! But it might not always be what we want. For example, I can imagine that sometimes it would be useful to use \* for some binary operation locally, but also still use \* for multiplication on the natural numbers. This is minor, though, since for local notation, we can always choose a different symbol if necessary.

The current behavior gives a way of turning off overloads, which is nice. For example, suppose in a file we are overloading \* for nat and int, and it is causing problems. Then we can open a section and specify that \* is the multiplication on nat.

The current behavior and workaround are fine, so I'll close this issue.

**Comment by leodemoura** [comment]
> For example, I can imagine that sometimes it would be useful to use \* for some binary operation locally, but also still use \* for multiplication on the natural numbers. This is minor, though, since for local notation, we can always choose a different symbol if necessary.

We can still use `#nat` for temporarily retrieving the `nat` notation
