### ISSUE TITLE
eliminate `opaque` definitions

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#576]
In the current Lean kernel, we have support for opaque definitions. 
By default, opaque definitions are treated as transparent in other opaque definitions in the same file (the idea is to allow us to prove things about the opaque definition). 
Theorems are always opaque (even in the file where they were defined).
We also have reducibility annotations: `[reducible]` `[semi-reducible]` and `[irreducible]`.
The annotations are implemented outside of the kernel and are used by the elaboration procedure.

The `opaque` definitions were implemented first, and here are the original motivations:
1- Help the type checker (the normalizer would never unfold opaque definitions)
2- Encapsulation (hide the definition from other modules)
3- With opaque theorems we don't need any kind of synchronization mechanism to be able to compile theorems in parallel.

Motivation 1 is just wrong. The opaque definitions do not really help. When a declaration in sent to the kernel after elaboration, they are usually type correct (unless there is a bug in the elaborator). The current type checker unfolds definitions "lazily" (on demand). So, any potential saving would only happen for type incorrect declarations (which only happens modulo bugs in the elaborator). 
Note that, the reducible hints are essential for the elaboration process. Without them, the elaboration process is intractable.

We gave up 2 a long time ago. It just doesn't work. It is really hard to predict ahead of time whether a definition should be opaque or not. Actually, we barely use opaque definitions in the standard and HoTT libraries. On the other hand, we use reducible hints all the time. 

Motivation 3 does not apply to HoTT. In HoTT, proofs are relevant. So, we don't even use the keywords `theorem` and `lemma` in the HoTT library. Consequently, we can't really compile theorems in parallel in HoTT mode. This is bad.

So, my plan is to eliminate opaque definitions from the kernel, and keep only the reducible hints.
This would simplify the kernel and the rest of the system. For example, whenever Lean creates a constraint, or tries to apply a tactic, it has to keep track whether opaque definitions should be treated as opaque or not. This is a really tedious bookkeeping for a feature we barely use (yes, we barely use opaque definitions). Here is an example of bookkeeping:
https://github.com/leanprover/lean/blob/master/src/library/tactic/constructor_tactic.cpp#L34

The proof state carries a flag indicating whether the opaque definitions should be treated as opaque or not. The operation `relax_main_opaque` retrieves this flag. 

This change would also make sure that any definition based on well-founded recursion would compute when the hints are ignored. Right now, the computation may get stuck whenever we use theorems to justify that a particular recursive application is decreasing. It is really boring to go over the library and replace `theorem` with `definition` just because we use it to justify a recursive application.

The change would also reduce confusion and duplication.

Here is the plan:
1- Remove opaque definitions from the kernel and keep only reducible hints.
2- The keywords `theorem` and `lemma` are syntax sugar for `definition ... [irreducible]`
3- Lean would compile [irreducible] definitions in parallel. Commands such as `(local)? attribute id [reducible]` are treated as synchronization points if `id` was defined in the current file. That is, Lean would wait until the proof of `id` is finished.

**Comment by fpvandoorn** [comment]
I agree that we can remove `opaque definition`, we hardly use it and `definition ... [irreducible]` is also fine.

So it is possible to compile `[irreducible]` definitions in parallel? Or do we elaborate them in parallel (where we don't have to unfold them) and synchronize for type checking in the kernel?

How about unfolding irreducible definitions (in tactic mode). Will we lose that ability? Example:

``` lean
definition foo [irreducible] (A : Type₁) : Type₁ := A → A

example (A : Type₁) : foo A :=
begin
    unfold foo, intro a, exact a
end
```

Other than these (possible) issues: I think this is a good change.

**Comment by leodemoura** [comment]
> So it is possible to compile [irreducible] definitions in parallel? Or do we elaborate them in parallel (where we don't have to unfold them) and synchronize for type checking in the kernel?

My current plan is the following. Whenever `foo` is declared as irreducible, we try to compile it in parallel. It goes into a `TODO` queue that is being processed in parallel by other execution threads. 
If the user uses the command `attribute foo [reducible]` or any other command that makes `foo` not irreducible. The parser views it as a synchronization point, and waits for `foo` to be compiled.

> How about unfolding irreducible definitions (in tactic mode). Will we lose that ability?

In the current plan, the user would have to write

``` lean
attribute foo [reducible]
attribute foo [irreducible]
```

It looks hackish. I think a better solution is to add a `wait` command that creates an explicit synchronization point.

``` lean
wait foo
```

Now that you asked these questions. It seems bad design to define synchronization points based on the reducible hints. Here is a simpler approach:
1- Only declarations marked as `theorem`, `lemma` and `xyzw definition` are compiled in parallel (I don't have a name for `xyzw definition` yet).
2- The type of these declarations is elaborated independently of their values. 
3- If the user wants to unfold them in the current file, then they must use the `wait` command.

What do you think?

**Comment by fpvandoorn** [comment]
This sounds good. Do I understand the following correctly?
- `definition foo [irreducible]`: `foo` is irreducible, but still a synchronization point.
- `xyzw definition foo`: `foo` is irreducible, but can be elaborated in parallel, so can only be unfolded later if we write `wait foo`.

Or do you mean that `xyzw definition foo` is just syntactic sugar for `definition foo [irreducible]`?

Will there be a difference between `xyzw definition` and `theorem`?

The `wait` command might be a little complicated, and we need to make sure it isn't required most of the time. It's fine if you cannot unfold theorems without it, because that is practically never done anyway.

**Comment by leodemoura** [comment]
> definition foo [irreducible]: foo is irreducible, but still a synchronization point.
> xyzw definition foo: foo is irreducible, but can be elaborated in parallel, so can only be unfolded later if we write wait foo.

This is correct.

> Will there be a difference between xyzw definition and theorem?

No difference. It would be just an alternative name for cases where it is too weird to say the definition is a theorem.

> The wait command might be a little complicated, and we need to make sure it isn't required most of the time. It's fine if you cannot unfold theorems without it, because that is practically never done anyway.

Yes. 

Users just have to keep in mind that they should minimize the use of `wait` if they want to maximize parallelism.

**Comment by leodemoura** [comment]
> 3- With opaque theorems we don't need any kind of synchronization mechanism to be able to compile theorems in parallel.

For the record, we also rely on `opaque` theorems when we generate `lean.js` (web version). To save space, we discard the proof of all theorems in the web version. If we execute

``` lean
print axioms
```

on the web version, we get a huge list of "axioms".

The (native) lean binary also provides an option that discards the proof of imported theorems. We claimed this feature is useful for saving memory. For example, in a distant future, we would be able to load a huge number of theorems, and discard their proofs after check them. If theorems are not opaque anymore, this feature may break other definitions. 

That being said, I still think theorems should not be opaque. First, this does not work for the HoTT mode. Second, for the web version, we may still delete them. Some examples will not work on the web. I don't think this is a big deal. The web version is for demo purposes only. Finally, regarding memory consumption, I don't think this is a real problem. If we load the whole standard library in memory, Lean consumes only 35Mb. So, even if the library gets 100x bigger, it would consume  approx 3.5Gb. Even if someone needs the whole library simultaneously , it would still fit in memory.  
Now, if it is 1000x bigger, we would probably need to implement a new kernel that loads definitions on demand.

**Comment by leodemoura** [comment]
I'm going to rename `wait` to `reveal`. Sometimes, we have to "wait" to reveal a theorem, but this is not always the case. 
To guarantee deterministic behavior, a theorem is only revealed in the end of the file or if the user requests it using `wait` (and `reveal` in the next commit). That is, even if a thread finished compiling the theorem, the result is not immediately available. So, there is no risk of race conditions.
