### ISSUE TITLE
Unexpected level error

### ISSUE THREAD

**Issue by UnkindPartition** [leanprover/lean3#581]
The following code

```
variables {a r : Type}

definition f a := Πr, (a -> r) -> r

lemma blah2 (sa : f a) (k : (a -> r)) : 
  sa r k = sa r k :=
  sorry
```

gives a level error (I can't figure out how to copy paste the exact message from the web editor). Yet if I inline the definition of `f` into the type of `blah2`, it compiles.

**Comment by leodemoura** [comment]
Thanks for reporting the problem. I'm investigating. In the meantime, we can workaround this issue by providing the universe levels explicitly. Example:

``` lean
definition f (a : Type) := Π r : Type, (a → r) → r

lemma blah2.{l₁ l₂} {a  : Type.{l₁}} {r  : Type.{l₂}}  (sa : f.{l₁ l₂} a)  (k  : a → r) : 
    sa r k = sa r k :=
    sorry
```

Or

``` lean
definition f (a : Type) := Π r : Type, (a → r) → r

universe variables l₁ l₂
variables {a  : Type.{l₁}} {r  : Type.{l₂}}

lemma blah2 (sa : f.{l₁ l₂} a) (k  : a → r) : sa r k = sa r k :=
sorry
```

**Comment by UnkindPartition** [comment]
Thanks for the quick fix. Is there a way for me to take advantage of it in the browser? My actual program is a bit more complicated than this minimal example, and I'm struggling to provide the right annotation.

**Comment by leodemoura** [comment]
> Is there a way for me to take advantage of it in the browser?

I've just updated the web version.
