### ISSUE TITLE
Rewrite tactic fails with "rewrite step produced type incorrect term"

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#583]
The following fails at the last rewrite:

```
import algebra.group data.set
namespace group_hom
open algebra
-- ⁻¹ in eq.ops conflicts with group ⁻¹
-- open eq.ops
notation H1 ▸ H2 := eq.subst H1 H2
open set
open function
local attribute set [reducible]

section
variables {A B : Type}
variable [s1 : group A]
variable [s2 : group B]
include s1
include s2
variable f : A → B
definition is_hom := ∀ a b, f (a*b) = (f a)*(f b)
definition ker (Hom : is_hom f) : (set A) := {a : A | f a = 1}
theorem hom_map_id (f : A → B) (Hom : is_hom f) : f 1 = 1 :=
        have P : f 1 = (f 1) * (f 1), from
        calc f 1 = f (1*1) : mul_one
        ... = (f 1) * (f 1) : Hom,
        eq.symm (mul.right_inv (f 1) ▸ (mul_inv_eq_of_eq_mul P))
check (is_hom f)
theorem hom_map_inv (Hom : is_hom f) (a : A) : f a⁻¹ = (f a)⁻¹ :=
        assert P : f 1 = 1, from hom_map_id f Hom,
        begin
          rewrite (eq.symm (mul.left_inv a)) at P,
          rewrite (Hom a⁻¹ a) at P,
        end
end
end group_hom
```

But this succeeds:

```
theorem hom_map_inv (Hom : is_hom f) (a : A) : f a⁻¹ = (f a)⁻¹ :=
        assert P : f 1 = 1, from hom_map_id f Hom,
        assert P1 : f (a⁻¹ * a) = 1, from (eq.symm (mul.left_inv a)) ▸ P,
        assert P2 : (f a⁻¹) * (f a) = 1, from (Hom a⁻¹ a) ▸ P1, sorry
```

If I only move P1 out and leave P2 in the rewrite I get

```
theorem hom_map_inv (Hom : is_hom f) (a : A) : f a⁻¹ = (f a)⁻¹ :=
        assert P : f 1 = 1, from hom_map_id f Hom,
        assert P1 : f (a⁻¹ * a) = 1, from (eq.symm (mul.left_inv a)) ▸ P,
        begin
          rewrite (Hom a⁻¹ a) at P1,
          rewrite (mul.left_inv (f a)) at P,
        end

invalid 'rewrite' tactic, rewrite step produced type incorrect termfunction expected at
  Hom a⁻¹ a
proof state:
A : Type,
B : Type,
s1 : group A,
s2 : group B,
f : A → B,
Hom : is_hom f,
a : A,
P : f 1 = 1,
P1 : f (a⁻¹ * a) = 1
⊢ f a⁻¹ = (f a)⁻¹
```

**Comment by fpvandoorn** [comment]
The `rewrite` tactic is very conservative in unfolding definitions. This is to ensure that it has a good performance.

In both examples with an error, here are two solutions
- Explicitly unfold `is_hom`. In the first example, you could do this by replacing the offending line by

``` lean
rewrite [↑is_hom at Hom, (Hom a⁻¹ a) at P],
```
- Mark `is_hom` as reducible: (this tells the elaborator that it should be always unfolded)

``` lean
definition is_hom [reducible] := ∀ a b, f (a*b) = (f a)*(f b)
```

@leodemoura: can we improve these error messages? The first one just says `tactic failed` and the second one (in the third example) is strange: `Hom a⁻¹ a` is not applied to anything (and the error message is missing `:` between `termfunction`)

**Comment by avigad** [comment]
Thanks, Floris. I was baffled by this too. The funny thing is that replacing `rewrite (Hom a⁻¹ a) at P` by

``` lean
          let H := Hom a⁻¹ a,
          rewrite H at P
```

works fine. Why does the "let" unfold `is_hom` while just writing `Hom a⁻¹ a` doesn't?

**Comment by htzh** [comment]
Good to know, thanks! I have also encountered a case where a term style proof failed with "iteration limit exceeded" but I was able to work around using "by exact" with the same conclusion. So that is another case of the term style being more aggressive?

**Comment by fpvandoorn** [comment]
> Why does the "let" unfold `is_hom` while just writing `Hom a⁻¹ a` doesn't?

If you just write terms normally, definitions which are not marked as `[reducible]` are unfolded most of the time. So in the `let` example, I think the following happens:
- First the elaborated figures out what the type of `H` is. It is `f (a*a⁻¹) = (f a)*(f a⁻¹)`
- Now `rewrite` doesn't have to unfold `is_hom` anymore to rewrite with `H`.

> So that is another case of the term style being more aggressive?

The term style is indeed more prone to get a `unifier max steps reached` error (is that the error you're talking about, or do you mean a different one?). This happens especially if you're doing nested induction proofs, substitutions (such as rewriting a subterm in a `calc`-proof), or other theorems which require higher-order unification. Then the corresponding tactic proof is usually easier to elaborate, since it breaks the proof in smaller steps

**Comment by htzh** [comment]
> The term style is indeed more prone to get a unifier max steps reached error (is that the error you're talking about, or do you mean a different one?).

Yes, that is what I meant. What you said makes great sense. Thanks!

**Comment by leodemoura** [comment]
> @leodemoura: can we improve these error messages? 
> The first one just says tactic failed and the second one (in the third example) is strange: Hom a⁻¹ a is not applied to anything (and the error message is missing : between termfunction)

I'm working on this issue. Now, the error message for

``` lean
theorem hom_map_inv (Hom : is_hom f) (a : A) : f a⁻¹ = (f a)⁻¹ :=
        assert P : f 1 = 1, from hom_map_id f Hom,
        begin
          rewrite (eq.symm (mul.left_inv a)) at P,
          rewrite (Hom a⁻¹ a) at P,
        end
end
```

is

``` lean
/home/leo/projects/lean/build/release/msg.lean:30:18: error:invalid 'rewrite' tactic, rewrite step produced type incorrect term
function expected at
  Hom a⁻¹ a

proof state:
A : Type,
B : Type,
s1 : group A,
s2 : group B,
f : A → B,
Hom : is_hom f,
a : A,
P : f (a⁻¹ * a) = 1
⊢ f a⁻¹ = (f a)⁻¹
```

Note that Haitao probably did not see the `tactic failed` message since the uninformative message  was recently introduced by #579

**Comment by leodemoura** [comment]
BTW, I'm working on this issue. The step  `rewrite (Hom a⁻¹ a) at P` fails because the `rewrite` tactic uses a conservative type checker that assumes most symbols are opaque. This is intended when performing rewriting (to avoid performance problems).
However, we should use a more relaxed type checker to elaborate the proof step `Hom a⁻¹ a`.

**Comment by leodemoura** [comment]
The commit above fixes this issue. The step `rewrite (Hom a⁻¹ a) at P` is now accepted.
