### ISSUE TITLE
request: combine have/assert with calc

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#586]
Right now we need to say:

```
have P : A = C, from
calc A = B : eq1
... = C : eq2
```

It would be nice if we can simply say:

```
have P calc A = B : eq1
... = C : eq2
```

and the prover should register P: A = C as an intermediate result. This should promote short forward chain reasoning which I think is clearer than if I simply write out the same in function application style using subst. Also it would be nice to be able to forward chain implications, just like chaining equations in calc, maybe with a different command name such as "imp".

**Comment by leodemoura** [comment]
It doesn't look as nice, but we can write

``` lean
have P : _, from calc 
     A = B : eq1
   ... = C : eq2,
```

**Comment by htzh** [comment]
Okay. I can work with that.

**Comment by leodemoura** [comment]
Regarding implication, we can use the following workaround:

``` lean
definition implies [reducible] (p q : Prop) := p → q
infixr `⇒`:25 := implies

lemma implies.trans [trans] {p q r : Prop} (h₁ : p ⇒ q) (h₂ : q ⇒ r) : p ⇒ r :=
assume hp, h₂ (h₁ hp)

example (A B C D : Prop) (h1 : A → B) (h2 : B → C) (h3 : C → D) : A ⇒ D :=
calc A ⇒ B : h1
   ... ⇒ C : h2
   ... ⇒ D : h3
```

We cannot use `attribute → [trans]` because `→` is not a definition, but a builtin symbol.
I will change the `calc` command, and let the user write `calc A → B : ...`.

**Comment by htzh** [comment]
cool! Thanks for the tip.

**Comment by leodemoura** [comment]
I implemented custom support for `→` in the `calc` expression. 
Example: https://github.com/leodemoura/lean/blob/aff9257c7233381abe7aa58352a88535118f5cc3/tests/lean/run/calc_imp.lean

**Comment by fspeech** [comment]
Great! I was just going to say that I will wait for the feature instead of using the workaround but it already happened. Wow!

The other thing is: it seems to me I don't get consistent type feedback in calc. Since the intention is clear for each step (unlike say the function application style) it would be nice to have good feedback regardless  of failures that happen after the point during calc.

**Comment by leodemoura** [comment]
> The other thing is: it seems to me I don't get consistent type feedback in calc. Since the intention is clear for each step (unlike say the function application style) it would be nice to have good feedback regardless of failures that happen after the point during calc.

Could you post some examples? 

Thanks!

**Comment by fspeech** [comment]
> Could you post some examples?

Sure I will document it more carefully next time it happens.
