### ISSUE TITLE
treat hit-constructors as constructors

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#587]
Is it possible to treat the constants `trunc.tr` and `type_quotient.class_of` as constructors for the purposes of `[unfold-c _]` (and similarly for `quot.mk` in the standard library)?

This would be a bit hackish, but also very helpful. For example, if I want to reduce `circle.rec_on base Pbase Ploop` to `Pbase`, currently I have to write

```
esimp [circle.rec_on, circle.rec, base, rec2_on, rec2, base1, 
  suspension.rec_on, suspension.rec, north, pushout.rec_on, 
  pushout.rec, pushout.inl, type_quotient.rec_on]
```

**Comment by leodemoura** [comment]
Here is an example:
https://github.com/leanprover/lean/blob/b03266be70cadd6f4cb5366845407a2147c4b215/library/init/quot.lean#L121-L128

**Comment by leodemoura** [comment]
BTW, I renamed the hint `[unfold-m]` to `[constructor]`.
The hint instructs lean that a constant/definition is "like" or "unfolds to" a constructor.

**Comment by leodemoura** [comment]
Example of the hint in "action"
https://github.com/leanprover/lean/blob/b03266be70cadd6f4cb5366845407a2147c4b215/tests/lean/587.lean

**Comment by fpvandoorn** [comment]
Very nice!

The name `[constructor]` might be misleading, because we might also want to add it to functions which are not constructors:

``` lean
open nat
example (n : ℕ) (H : n = 7) : nat.rec_on (succ zero + 7) 0 (λk q, k) = n :=
begin
  esimp,
  state,
  rewrite H
end

attribute nat.add nat.of_num [constructor]
example (n : ℕ) (H : n = 7) : nat.rec_on (succ zero + 7) 0 (λk q, k) = n :=
begin
  esimp,
  state,
  rewrite H
end
```

However, this also unfolds `nat.add` if there is no reduction step possible:

``` lean
import types.nat -- data.nat
open nat
attribute nat.add nat.of_num [constructor]
example (n : ℕ) : nat.rec_on (1 + n) 0 (λk q, k) = n :=
begin
  -- uncomment only one line
  esimp, state, rewrite add.comm -- fails
  -- rewrite add.comm -- succeeds
end
```

Is it feasible to do what I suggested in https://github.com/leanprover/lean/issues/496#issuecomment-85546386? What I want is the following:
- If unfolding the definitions with attributes `[unfold-c _]` and `[unfold-m]` leads to a iota reduction (including the hit/quot reduction), unfold them (as is currently the case)
- If after unfolding, no iota reduction can be performed, fold them back to the original state.

---

~~Lastly, for `circle` the unfolding doesn't yet work. I'm not sure why, maybe because multiple definitions have to be unfolded to show that `circle` is definitionally equal to `suspension (suspension empty)`. However, if I change the definition of `circle` to ``suspension (suspension empty)`, it still doesn't work. It is also possible that I messed up one of the `[unfold-c _]` arguments or something, but I did double (and triple) check them.~~

~~On 98948754765fb295744e10b92bb39b0897522d36 (my current master) I have the following lines in `hit.circle` (in root namespace):~~

``` lean
attribute circle.base1 [constructor]
attribute circle.rec2 [unfold-c 6]
```

~~The following example shows the problem (works only on my branch):~~

``` lean
import hit.circle
open circle eq

example {P : circle → Type} (x : circle) (Pb1 Pb1' : P base1) (Pb2 : P base2)
    (Ps1 : seg1 ▸ Pb1 = Pb2) (Ps2 : seg2 ▸ Pb1 = Pb2)
  (H : Pb1 = Pb1') : circle.rec2 Pb1 Pb2 Ps1 Ps2 base1 = Pb1' :=
begin
  -- uncomment only one of the following three lines
  esimp, state, -- doesn't unfold
  -- esimp [base1], state, -- unfolds
  -- esimp, esimp [base1], state, -- doesn't unfold
  rewrite -H
end
```

~~gives the following output, which means that `base1` is not unfolded correctly:~~

```
proof state
[stuff]
⊢ type_quotient.rec
    [stuff]
    base1 = Pb1'
```

~~For other recursors it works great. Example:~~

``` lean
import hit.suspension
open eq suspension

example {A : Type} {P : suspension A → Type} (PN PN' : P !north) (PS : P !south)
    (Pm : Π(a : A), merid a ▸ PN = PS) (H : PN = PN') : suspension.rec_on !north PN PS Pm = PN' :=
begin
  esimp, state, -- unfolds
  rewrite -H
end
```

**Comment by leodemoura** [comment]
> Is it feasible to do what I suggested in #496 (comment)?

Maybe... I don't have any energy to try it right now... I spent the last 8hs fixing and addressing issues all over the place ... I'm really tired... :-(

**Comment by fpvandoorn** [comment]
> Maybe... I don't have any energy to try it right now... I spent the last 8hs fixing and addressing issues all over the place ... I'm really tired... :-( 

That's fine. Don't overwork yourself! Both issues mentioned here can wait.
