### ISSUE TITLE
most recent build failed

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#591]
At the last stage with the following error

```
python  "C:\Users\haitao\proj\pkgs\lean\bin\leantags" --relative -- ...

Traceback (most recent call last):
  File "C:\Users\haitao\proj\pkgs\lean\bin\leantags", line 232, in <module>
    sys.exit(main())
  File "C:\Users\haitao\proj\pkgs\lean\bin\leantags", line 228, in main
    resolve_abbr(info, decl_dict)
  File "C:\Users\haitao\proj\pkgs\lean\bin\leantags", line 195, in resolve_abbr
    item = decl_dict[declname]
KeyError: u'bool.tt\r'
ninja: build stopped: subcommand failed.
```

**Comment by leodemoura** [comment]
@soonhokong Any ideas? 
Do you think this might be related to line-break + carriage return issues?

**Comment by soonhokong** [comment]
It's strange he gets this error now, not previously if anything is wrong. Anyway, I'll investigate it this evening in the lab.

**Comment by htzh** [comment]
Last commit that works for me is e2c1dc92a8f85afd2470e9032d50b1b5b54b5776 before @fpvandoorn 's recent merge. I tried a couple commits after that and they all failed. Something to do with the merge?

**Comment by soonhokong** [comment]
I can reproduce the problem. I'm working on a patch.

**Comment by soonhokong** [comment]
f8f2127 seems to fix the problem but I still don't understand why we have `\r` in .ilean file. Let me figure it out and commit it to the blessed repo. @htzh, please cherry-pick f8f2127 if you need to use the latest changes immediately. Otherwise, please wait.
