### ISSUE TITLE
better unifier failure message

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#592]
I wish when unifier fails (exceeding limit) Lean would tell me at which step it fails. When I have a long calc and the unifier fails without telling me where can make things rather hard to debug. I basically use an `example` outside of the lemma to test each step but that is tedious. You experts can probably tell by inspection about what is going on but I am not there yet :-(

```
example (a b : A) : same_lcoset N a⁻¹ b⁻¹ = (a⁻¹ ∘> N = b⁻¹ ∘> N) := rfl
lemma nsubg_same_lcoset_inv : ∀ a b, same_lcoset N a b → same_lcoset N a⁻¹ b⁻¹ :=
  take a b, assume Psame, calc
  a⁻¹ ∘> N = a⁻¹*b*b⁻¹ ∘> N : {eq.symm (mul_inv_cancel_right a⁻¹ b)}
  ... = a⁻¹*b ∘> b⁻¹ ∘> N : glcoset_compose
  ... = a⁻¹*b ∘> (N <∘ b⁻¹) : {nsubg_normal b⁻¹}
  ... = (a⁻¹*b ∘> N) <∘ b⁻¹ : lcoset_rcoset_assoc
  ... = (a⁻¹ ∘> b ∘> N) <∘ b⁻¹ : glcoset_compose
  ... = (a⁻¹ ∘> a ∘> N) <∘ b⁻¹ : {Psame}
  ... = N <∘ b⁻¹ : glcoset_inv
  ... = b⁻¹ ∘> N : {eq.symm (nsubg_normal b⁻¹)}
```

I will push the full thing to https://github.com/htzh/leanproved/blob/master/group_theory/subgroup.lean in case anyone wants to run it. I know I will figure it out eventually but it is my turn to make dinner tonight so this will have to wait. The main purpose of this issue is to ask for better messages. Debug tips welcome too.

**Comment by leodemoura** [comment]
I usually use the `rewrite` tactic. It is much faster.
The notation `lhs = rhs : { p }` in calc mode expands into `lhs = rhs : eq.rec_on p (eq.refl lhs)`.
`eq.rec_on` is the eliminator for the equality. Eliminators usually generate non-trivial higher-order unification problems, and higher-order unification is a undecidable problem.
The notation `lhs = rhs : { p }` was introduced when we did not have the `rewrite` tactic. 
Now, I usually use `by rewrite ...`. It is faster and more predictable. As we improve the `rewrite` tactic, we will have fewer and fewer cases where full higher-order unification is needed. 
Here is your lemma using `rewrite`.

``` lean
lemma nsubg_same_lcoset_inv : ∀ a b, same_lcoset N a b → same_lcoset N a⁻¹ b⁻¹ :=
  take a b, assume Psame, calc
  a⁻¹ ∘> N = a⁻¹*b*b⁻¹ ∘> N    : by rewrite mul_inv_cancel_right
  ... = a⁻¹*b ∘> b⁻¹ ∘> N      : by rewrite glcoset_compose
  ... = a⁻¹*b ∘> (N <∘ b⁻¹)    : by rewrite nsubg_normal
  ... = (a⁻¹*b ∘> N) <∘ b⁻¹    : by rewrite lcoset_rcoset_assoc
  ... = (a⁻¹ ∘> b ∘> N) <∘ b⁻¹ : by rewrite glcoset_compose
  ... = (a⁻¹ ∘> a ∘> N) <∘ b⁻¹ : by rewrite Psame
  ... = N <∘ b⁻¹               : by rewrite glcoset_inv
  ... = b⁻¹ ∘> N               : by rewrite nsubg_normal
```

Eventually, we will have even better automation, and we will not even need to write the name of the theorem(s) being used.

**Comment by htzh** [comment]
Thanks for the `by rewrite` tip. Definitely looking forward to more automation!

**Comment by htzh** [comment]
Funny that the very next lemma I added failed the `by rewrite` but worked with `{}`:

```
lemma coset_product_left_inv (a : A) : ⟦a⁻¹⟧ cx ⟦a⟧ = ⟦1⟧ := calc
      ⟦a⁻¹*a⟧ = ⟦1⟧ : {mul.left_inv a}
```

**Comment by htzh** [comment]
I have come to appreciate that the unifier/unfolder are quite robust. For example the following is impressive:

```
-- under the wrap the tower of concepts collapse to a simple condition
example (a x : A) : (x ∈ a ∘> ker f) = (f (a⁻¹*x) = 1) := rfl
example [Pker : is_normal_subgroup (ker f)] (a : A) : ker_natural_map Hom ⟦a⟧ = f a := rfl
```

However what I got tripped up was that the error messages make it appear that there may be unification/unfolding problem at the "big" steps like above because the error messages tend to be displayed near the goals/premises, and I would waste time making the steps more explicit (and sometimes inadvertently introducing further mistakes). My errors actually tend to happen at "small" steps with missing explicit arguments or inability to infer implicit arguments. As errors propagate through the constraint solver they eventually show up as errors unrelated to where the actual mistakes are. I don't have a solution for this. This is just an observation. It would be useful to develop techniques to localize the errors, perhaps interactively with the user.

By "big" I mean when I rely on the unifier/unfolder to unify terms of drastically different looking forms (so identity is not obvious to the human user not familiar with the definitions/notations). By "small" I mean applying an explicit theorem or eq.subst to transform two forms that are obvious to the human user (and therefore failure is not normally suspected).

**Comment by leodemoura** [comment]
Sorry for not being more responsive, but I have been fixing many problems. 

Let me try to explain what is going on in the following example

``` lean
lemma coset_product_left_inv (a : A) : ⟦a⁻¹⟧ cx ⟦a⟧ = ⟦1⟧ := calc
      ⟦a⁻¹*a⟧ = ⟦1⟧ : {mul.left_inv a}
```

Internally, this `calc` is being processed as `eq.subst (mul.left_inv a) rfl`.
This is a "big-step" because the elaborator has to "evaluate" the term `⟦a⁻¹⟧ cx ⟦a⟧` a little bit and then apply the substitution `mul.left_inv`. When a `calc` has only one step, the terms provided in the `calc` expression do not affect the elaboration process that much. This can be improved. However, this is the way it is in the current version. 

The `rewrite` tactic fails in this example because it tries to find the pattern `x⁻¹ * x` in the goal `⟦a⁻¹⟧ cx ⟦a⟧`. Here are some tricks to help the `rewrite` tactic:

``` lean
lemma coset_product_left_inv (a : A) : ⟦a⁻¹⟧ cx ⟦a⟧ = ⟦1⟧ := 
show ⟦a⁻¹*a⟧ = ⟦1⟧, by rewrite mul.left_inv
```

or

``` lean
lemma coset_product_left_inv (a : A) : ⟦a⁻¹⟧ cx ⟦a⟧ = ⟦1⟧ := 
begin 
    change ⟦a⁻¹*a⟧ = ⟦1⟧,
    rewrite mul.left_inv
end
```

In the first, I'm using `show` to change the goal. The `lean` type checker will check whether the goals 
`⟦a⁻¹⟧ cx ⟦a⟧ = ⟦1⟧` are indeed definitionally equal. In the second case, I'm using the `change` tactic to do the same thing.

You have many theorems that really on the fact that `⟦a⟧ cx ⟦b⟧` and `⟦a*b⟧` are definitionally equal.
In this kind of situation, it might be useful to define an auxiliary lemma

``` lean
private lemma to_mul (a b : A) : ⟦a⟧ cx ⟦b⟧ = ⟦a*b⟧ := rfl
```

and use it as a rewrite rule.

``` lean
lemma coset_product_left_inv (a : A) : ⟦a⁻¹⟧ cx ⟦a⟧ = ⟦1⟧ :=
by rewrite [to_mul, mul.left_inv]
```

**Comment by leodemoura** [comment]
> It would be useful to develop techniques to localize the errors, perhaps interactively with the user.

Yes, this is really important.

**Comment by leodemoura** [comment]
> By "small" I mean applying an explicit theorem or eq.subst to transform two forms that are obvious to the human user (and therefore failure is not normally suspected).

Sometimes a term may look small, but it is much bigger when we take the implicit arguments into account. For example, the term `a⁻¹*x` in

``` lean
example (a x : A) : (x ∈ a ∘> ker f) = (f (a⁻¹*x) = 1) := rfl
```

is really

``` lean
(@has_mul.mul A (@semigroup.to_has_mul A (@monoid.to_semigroup A (@group.to_monoid A s1)))
               (@has_inv.inv A (@group.to_has_inv A s1) a)
               x)
```

All these operations for converting structures (e.g., `group.to_monoid`) get in the way of the unifier.
In the future, I want to modify the unifier in such a way it "ignores" these "convertions". 
One trick is to avoid full higher-order unification when processing these parts.

**Comment by leodemoura** [comment]
@htzh With the commit above, the following will also work:

``` lean
lemma coset_product_left_inv (a : A) : ⟦a⁻¹⟧ cx ⟦a⟧ = ⟦1⟧ := 
calc ⟦a⁻¹*a⟧ = ⟦1⟧ : by rewrite mul.left_inv
```

**Comment by htzh** [comment]
@leodemoura thanks for the detailed responses. I hope I didn't distract you from more urgent matters. My intention was to document some pitfalls that I encountered as a new user while they are fresh on my mind. I totally understand that they may not have immediate solutions and I appreciate your explaining the nuances. Feel free to keep this on the back burner and only respond when you have time.

> One trick is to avoid full higher-order unification when processing these parts.

I hope this does not remove the strength of the unifier. I definitely consider the following a really big step:

```
example (a x : A) : (x ∈ a ∘> ker f) = (f (a⁻¹*x) = 1) := rfl
```

which is why I consider it impressive. This is a great feature as it allows one to document human level intuition by allowing notations that are automatically taken care of. If one has to peel off the conceptual layers manually one would be discouraged from introducing them.
For the sake of documentation I will cite the example from the email thread to detail what I was referring to w.r.t. error messages:

```
-- this does not work
lemma nsubg_same_lcoset_product : ∀ a1 a2 b1 b2, (a1 ~ b1) → (a2 ~ b2) →  ((a1*a2) ~ (b1*b2)) :=
  take a1, take a2, take b1, take b2,
  assume Psame1 : same_lcoset N a1 b1, --a1 ∘> N = b1 ∘> N,
  assume Psame2 : same_lcoset N a2 b2, --a2 ∘> N = b2 ∘> N,
  assert Psame3 : same_lcoset N (a1*b1) (a2*b2), from calc
  a1*a2 ∘> N = a1 ∘> a2 ∘> N : glcoset_compose
  ... = a1 ∘> b2 ∘> N : by rewrite Psame2
  ... = a1 ∘> (N <∘ b2) : by rewrite (nsubg_normal N)
  ... = (a1 ∘> N) <∘ b2 : lcoset_rcoset_assoc
  ... = (b1 ∘> N) <∘ b2 : {Psame1}
  ... = N <∘ b1 <∘ b2 : {nsubg_normal N b1}
  ... = N <∘ (b1*b2) : grcoset_compose
  ... = (b1*b2) ∘> N : nsubg_normal N,
  Psame3
```

This was a working lemma. Then I added the section variable N from implicit to explicit so I need  to add it to many lemmas used here. I missed one or two. But the error indicator was under `take a1` and the message made me think that the unifier was failing at the "big steps", so I changed Psame1,2 and added 3 to try to help the unifier. I also changed everything to `by rewrite`. I realized I was missing the N argument and fixed that. The error message stayed about the same throughout all the changes:

```
error: type mismatch at definition 'nsubg_same_lcoset_product', has type
  ∀ (A : Type) (s : group A) (N : set A),
    is_normal_subgroup N →
    (∀ (a1 a2 b1 b2 : A), same_lcoset N a1 b1 → same_lcoset N a2 b2 → same_lcoset N (a1 * b1) (a2 * b2))
but is expected to have type
  ∀ {A : Type} [s : group A] (N : set A) [is_nsubg : is_normal_subgroup N] (a1 a2 b1 b2 : A),
    same_lcoset N a1 b1 → same_lcoset N a2 b2 → same_lcoset N (a1 * a2) (b1 * b2)
```

There were variations in details in the message but overall it is almost the same giving me little clue about I just did. Eventually Jeremy noticed with a fresh pair of eyes (and maybe using debug options that I should learn) that my Psame3 was constructed wrongly. I actually introduced Psame3 to help the unifier! In the end it seems that the unifier actually handled the "big steps" very well and did not need any help:

```
-- this works
lemma nsubg_same_lcoset_product : ∀ a1 a2 b1 b2, (a1 ~ b1) → (a2 ~ b2) →  ((a1*a2) ~ (b1*b2)) :=
  take a1, take a2, take b1, take b2,
  assume Psame1 : a1 ∘> N = b1 ∘> N,
  assume Psame2 : a2 ∘> N = b2 ∘> N,
  calc
  a1*a2 ∘> N = a1 ∘> a2 ∘> N : glcoset_compose
  ... = a1 ∘> b2 ∘> N :    by rewrite Psame2
  ... = a1 ∘> (N <∘ b2) :  by rewrite (nsubg_normal N)
  ... = (a1 ∘> N) <∘ b2 :  by rewrite lcoset_rcoset_assoc
  ... = (b1 ∘> N) <∘ b2 :  by rewrite Psame1
  ... = N <∘ b1 <∘ b2 :    by rewrite (nsubg_normal N)
  ... = N <∘ (b1*b2) :     by rewrite grcoset_compose
  ... = (b1*b2) ∘> N :     by rewrite (nsubg_normal N)
```

So my take away is to trust the big steps of the unifier more. But the "small steps" (you are right they are not small once all the implicit inferences are taken into account) can introduce errors that are hard to find because they look the same to the human eye and unless a location is provided by the error message it is hard to know where to start.
I don't expect solutions. As I said I would like to document this case while it is fresh on my mind. Once I get more experienced hopefully it will happen less frequently but then I won't be able to give the feedback from a new user's perspective.

**Comment by htzh** [comment]
> You have many theorems that really on the fact that ⟦a⟧ cx ⟦b⟧ and ⟦a*b⟧ are definitionally equal.
> In this kind of situation, it might be useful to define an auxiliary lemma

I find inference by definitional equality easier to follow mentally. The nice thing about it is I can keep many equalities in my head as they are intuitive to me. If I had to search for an auxiliary lemma to use them that is certainly less attractive. I understand it would be a good thing to try if a difficulty is encountered but I would appreciate Lean handling most of these.

**Comment by avigad** [comment]
Just for the record: I didn't use any special tricks to debug the lemma. I just commented most of it out, put a "sorry" at the end, and then added pieces back one bit at a time. Then it was just a matter of reading the error message carefully.

The elaborator is a really incredible piece of code, but we have to be careful not to overuse it. It is really designed to support the parser and let us write expressions in a way that is compact and natural. If we overdo it, things become brittle and sluggish. In the long run, we will do better using special purpose automation (like a term simplifier) to fill in reasoning steps.

**Comment by htzh** [comment]
@avigad Thanks for going through the trouble debugging that issue. I would have copy-and-pasted each step to an `example` to see if it works but I was tired and the end goal was near so I was in a bit of a hurry.

> but we have to be careful not to overuse it. It is really designed to support the parser and let us write expressions in a way that is compact and natural.

Yes I very much appreciate the ability to write compact and natural expressions. But what constitutes overuse? Are we not supposed to let the unifier undo the expressions? If I have to manually undo the compact representation in each proof that would discourage me from introducing them in the first place.

**Comment by avigad** [comment]
I don't have a precise criterion. One heuristic is that the elaborator is supposed to be an extension of the parser; it is supposed to do things like disambiguate notation and fill in information that is straightforwardly implicit in an expression. Because it has to manage so many things, including higher-order unification and unfolding computation, we should not expect too much from it.

That said, there is no fine line between "proving that something is a homomorphism" and "noticing that something is a homomorphism," i.e. the boundary between parsing an expression and proving a theorem is not sharp.

So really the problem is empirical. In your given domain, if the things you want to leave implicit are inferred smoothly and everything works fine, there is no problem. If not, you have to either tinker with the encodings or supply more information. There are usually multiple ways to set up definitions and notation, and figuring out which ones will work best is often the most important part of the project.
