### ISSUE TITLE
python3 unicode error

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#598]
In my hom.lean when I cut L26-27 https://github.com/htzh/leanproved/blob/master/group_theory/hom.lean#L26 I get the following error message when using Python3 (3.4.3):

```
Traceback (most recent call last):
  File "c:/alt/msys64/usr/local/bin/linja", line 751, in <module>
    sys.exit(main())
  File "c:/alt/msys64/usr/local/bin/linja", line 736, in main
    return call_ninja(args)
  File "c:/alt/msys64/usr/local/bin/linja", line 523, in call_ninja
    process_lean_output(targets[0], out, args, args.targets[0].endswith(".hlean"))
  File "c:/alt/msys64/usr/local/bin/linja", line 497, in process_lean_output
    print(flycheckItemList)
  File "c:\alt\Python34\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 1187: character maps to <undefined>
```

Sometimes the error was triggered immediately, sometimes I had to force a save to trigger it. (Probably other actions may trigger it too I haven't extensively checked.)

Python 2.7.8 does not appear to have this problem. I am switching back to Python 2 but thought you may be interested in the error from using Py3.

**Comment by soonhokong** [comment]
@htzh, I was able to reproduce the problem by using Python3. 4a03570 fixes the problem on my machine. Could you confirm it?

**Comment by htzh** [comment]
Yes it worked. Thanks.
