### ISSUE TITLE
esimp doesn't unfold everything

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#603]
In [this file](https://github.com/fpvandoorn/lean/blob/issue603/hott/algebra/category/constructions/comma.hlean#L44-45) I write `esimp [ap011,ap] at r`, but not every occurrence of `ap` in `r` gets replaced (and actually `esimp` should already unfold both occurrences of `ap`, since it has the `unfold-c` attribute and it is applied to `refl`).

I tried to make a minimal example, but in more minimal examples `ap` does get unfolded.

**Comment by leodemoura** [comment]
`ap` is overloaded. There is `eq.ap` and `core.ap`. The goal is using `core.ap`, but the `rewrite` tactic is unfolding `eq.ap`. If we use `eimp[ap011, core.ap]`, then all `ap`s disappear from the goal.

**Comment by fpvandoorn** [comment]
That makes sense. Thanks for investigating. 

In this case `core.ap` is just the export of `eq.ap`, so I actually didn't know that `ap` was overloaded, and I thought I was using `eq.ap` everywhere.
But this means that my current approach of having a [`core` namespace](https://github.com/leanprover/lean/blob/master/hott/init/default.hlean#L17-26) which contains the most important declarations of all namespaces in the `init` folder is bad. I don't want to overload definitions just because I open both `core` and the other namespace(s).

The reason I wanted this namespace is to reduce the number of namespaces which have to be opened at the top of every file. Many files use definitions from various namespaces, but for some of those namespaces it will use only the most rudimentary facts (for example, some files use only the notation `≃` from the namespace `equiv` and nothing else).

**Comment by leodemoura** [comment]
We can selectively `export`. Example, we may export only the notation and the rudimentary facts you need.

Another option is to add an option to `export` that makes all exported definitions `protected`?

**Comment by fpvandoorn** [comment]
I'm already exporting pretty selectively: https://github.com/leanprover/lean/blob/master/hott/init/default.hlean#L17-26. And I think that making exported definitions `protected` defeats the purpose a bit. If you then write `core.ap`, you could just as well have written `eq.ap`.

I think the main issue is that I had a misconception about the `export` command. I thought that if I write

``` lean
namespace core
  export bool empty unit sum
end core

open core
```

this would be similar to

``` lean
open bool empty unit sum
```

but it's not. Instead, all declarations are copied to the `core` namespace. 

I think it would be nice (but this is low priority and I don't know how feasible it is) if export doesn't actually copy declarations, but instead when I write `open core`, I open all the namspaces as specified by `export`. So I cannot write `core.tt` instead of `bool.tt`, but if I open `core`, there is an alias `tt` created for `bool.tt`.

Are there reasons why the current behavior is more useful than what I'm suggesting?

I'm closing this issue now. The original issue is resolved, and the rest is low priority, in my opinion.

**Comment by leodemoura** [comment]
> I think it would be nice (but this is low priority and I don't know how feasible it is) if export doesn't actually copy declarations, but instead when I write open core, I open all the namspaces as specified by export. So I cannot write core.tt instead of bool.tt, but if I open core, there is an alias tt created for bool.tt.
> Are there reasons why the current behavior is more useful than what I'm suggesting?

The new behavior you suggest is nice.
I will think about it. We would have to add a notion of persistent "aliases". We don't have this feature in the current version. We create transient "aliases" when we open namespaces.

There is also a conflict with the `migrate` command. Jeremy and I have been talking about "merging" `export` and `migrate` since they are quite similar. The main difference is that `migrate` can "fix" parameters or exported declarations, and it simplifies the types. So, `migrate` really has to create new declarations.

**Comment by avigad** [comment]
Hmmm.... That is a little disconcerting, and casts a shadow on the utility of "export". It seems strange to overload "ap" to "core.ap" and "eq.ap" when these are both the same thing. Would it help at all if the export command marked all the newly created theorems as abbrevations?

I am not against fancier export commands, but maybe there is a more ligh-weight approach. It seems to me that Floris wants a mechanism like this: we define a string

my_default :=
"open foo
open bar [notation]
open baz (mydecl1, mydecl2)"

and then say "execute my_default", and have the parser treat is as though the user just entered the string.

For example, if these lines were in "core.slean" ("s" for script), he could use a command like

  execute "core.slean"

Maybe something like that would be useful to setting up configurations later on. It's a bit of a hack though. And he'd probably have to do the include separately, so it would like look like

```
  import core
  execute "core.slean"
```

Is this something best done with Lua? It would be nice if we could use a little scripting language to do things like this.

I am just thinking out loud here.

**Comment by avigad** [comment]
Another option: whenever Lean creates an alias, it first checks to see whether there is already an alias with the same name, and if the two things are definitionally equal, it doesn't bother.

**Comment by leodemoura** [comment]
@avigad I'm thinking about these issues. Your second suggestion is the easiest to implement because we have to change very little in the code base.

> Another option: whenever Lean creates an alias, it first checks to see whether there is already an alias with the same name, and if the two things are definitionally equal, it doesn't bother.

@fpvandoorn's suggestion has some nice properties since `export` would only create aliases. For instance, we don't pollute the environment with a lot of redundant definitions.

**Comment by avigad** [comment]
It sounds like a natural way to implement @fpvandoorn's suggestion is to associate with each namespace a script that gets executed when the namespace is opened. So "export" means "add open commands to the script".

We could then use namespaces to set up all sorts of configurations. For example, opening a namespace could set configuration variables.

The difference is that aliases go away when the namespace is closed, whereas setting configuration variables are not scoped like that. So maybe the extra generality is a bad idea.
