### ISSUE TITLE
type class inference for minor premises

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#611]
Is it possible to automatically try to solve minor premises which are in square brackets by type class resolution?

Example: `Pt` in `trunc.rec`

``` lean
  protected constant rec {n : trunc_index} {A : Type} {P : trunc n A → Type}
    [Pt : Πaa, is_trunc n (P aa)] (H : Πa, P (tr a)) : Πaa, P aa
```

Example usage currently:

``` lean
-- HoTT
open is_trunc
attribute trunc.rec [recursor]

definition my_elim {n : trunc_index} {A : Type} {P : Type}
  [Pt : is_trunc n P] (H : A → P) : trunc n A → P :=
begin
  intro x, induction x,
  exact _,
  apply H, assumption
end
```

**Comment by leodemoura** [comment]
It is possible :-)

**Comment by leodemoura** [comment]
BTW, I'm assuming that if users do not want to solve a minor premise using type class resolution, then they should create another recursor where the minor premise does not have `[ ]`.

**Comment by fpvandoorn** [comment]
That sounds fine. Thanks!
