### ISSUE TITLE
blank error message

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#618]
There is an error in this proof:

``` lean
import data.nat data.nat.bquant
open nat

theorem mul_mod_eq_mod_mul_mod (m n k : nat) : (m * n) mod k = ((m mod k) * n) mod k :=
by_cases_zero_pos k
  (by rewrite [*mod_zero])
  (assume H : k > 0,
    (calc
      (m * n) mod k = (((m div k) * k + m mod k) * n) mod k : eq_div_mul_add_mod
            ... = ((m mod k) * n) mod k                     : by rewrite [foo]))
```

In the last line, `foo` is not an identifier. But Flycheck does not show any errors. Compilation shows the following:

```
/home/avigad/Dropbox/Projects/Lean/lean_work/temp2.lean:2:0: warning: imported file uses 'sorry'
/home/avigad/Dropbox/Projects/Lean/lean_work/temp2.lean:5:0: error: 
```

In other words, the error message is blank. I could not figure out how to produce a smaller example of the problem.

**Comment by avigad** [comment]
Update: the problem seems to have been introduced with the changes to the error messages. If I revert to the commit just before d5da659 the problem goes away.

**Comment by avigad** [comment]
P.S. The problem occurred in other places as well. You can probably make it recur by opening any library file and typing random characters. If you introduce an obvious error like a nonsense identifier, and Flyspeck doesn't report it, you have found the problem.

**Comment by leodemoura** [comment]
I'm not managing to reproduce this problem. 
I'm getting the following error message:

```
type mismatch at application
  by_cases_zero_pos k ?M_2 (λ (H : k > 0), eq.trans ?M_3 ?M_4)
term
  λ (H : k > 0),
    eq.trans ?M_3 ?M_4
has type
  k > 0 → m * n mod k = m mod k * n mod k
but is expected to have type
  ∀ {y : ℕ},
    y > 0 → ?M_1
```

Could you close and reopen emacs? Recompile all libraries?

BTW, It is plausible the problem is related to the commit you mention.

**Comment by leodemoura** [comment]
I think the issue may be related to the argument evaluation order produced by different compilers.
I submitted a commit that should produce the correct error message independently of the argument evaluation order used by a given compiler.
Could you try again?

Thanks

**Comment by avigad** [comment]
I checked out the same commit I used yesterday, rebuilt everything from scratch, and the problem did _not_ recur in my example. So the problem is likely the result of something I did wrong or something wrong with my local files.

I also checked out the most recent commit, and the example looks fine with that.

I am sorry to have caused you more trouble...
