### ISSUE TITLE
emacs initialization

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#627]
Todays commits cause an error when executing my `.emacs` file whenever I open emacs.

```
Warning (initialization): An error occurred while loading `/home/floris/.emacs':

Symbol's function definition is void: flycheck-define-command-checker

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

The Lean part my `.emacs` file:

``` elisp
(require 'package)
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)

;; Install required/optional packages for lean-mode
(defvar lean-mode-required-packages
  '(company dash dash-functional flycheck f
            fill-column-indicator s lua-mode mmm-mode))
(let ((need-to-refresh t))
  (dolist (p lean-mode-required-packages)
    (when (not (package-installed-p p))
      (when need-to-refresh
        (package-refresh-contents)
        (setq need-to-refresh nil))
      (package-install p))))

;; Set up lean-root path
(setq lean-rootdir "~/projects/lean")  ;; <=== YOU NEED TO MODIFY THIS
(setq-local lean-emacs-path
            (concat (file-name-as-directory lean-rootdir)
                    (file-name-as-directory "src")
                    "emacs"))
(add-to-list 'load-path (expand-file-name lean-emacs-path))
(require 'lean-mode)

;; Customization for lean-mode
(customize-set-variable 'lean-delete-trailing-whitespace t)
(customize-set-variable 'lean-flycheck-use t)
(customize-set-variable 'lean-eldoc-use t)
```

backtrace:

```
Debugger entered--Lisp error: (void-function flycheck-define-command-checker)
  (flycheck-define-command-checker (quote lean-checker) "A Lean syntax checker." :command (lean-flycheck-command) :error-patterns (quote ((error line-start "FLYCHECK_BEGIN ERROR" (32 "
") "\n" (file-name) ":" line ":" (32 column ":") " error: " (minimal-match (message (one-or-more (zero-or-more not-newline) (32 "
") "\n"))) "FLYCHECK_END" (32 "
") line-end) (warning line-start "FLYCHECK_BEGIN INFORMATION" (32 "
") "\n" (file-name) ":" line ":" (32 column ":") " information: " (minimal-match (message (one-or-more (zero-or-more not-newline) (32 "
") "\n"))) "FLYCHECK_END" (32 "
") line-end))) :error-filter (quote (lambda (errors) (flycheck-sanitize-errors (flycheck-increment-error-columns errors)))) :modes (quote (lean-mode)))
  lean-flycheck-init()
  (lambda nil (lean-flycheck-init))()
  funcall((lambda nil (lean-flycheck-init)))
  eval((funcall (quote (lambda nil (lean-flycheck-init)))))
  eval-after-load(flycheck (lean-flycheck-init))
  (progn (require (quote flycheck)) (eval-after-load (quote flycheck) (quote (lean-flycheck-init))))
  (if lean-flycheck-use (progn (require (quote flycheck)) (eval-after-load (quote flycheck) (quote (lean-flycheck-init)))))
  eval-buffer(#<buffer  *load*-960808> nil "/home/floris/projects/lean/src/emacs/lean-mode.el" nil t)  ; Reading at buffer position 11589
  load-with-code-conversion("/home/floris/projects/lean/src/emacs/lean-mode.el" "/home/floris/projects/lean/src/emacs/lean-mode.el" nil t)
  require(lean-mode)
  eval-buffer(#<buffer  *load*> nil "/home/floris/.emacs" nil t)  ; Reading at buffer position 2651
  load-with-code-conversion("/home/floris/.emacs" "/home/floris/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "\205\262
```

**Comment by soonhokong** [comment]
@fpvandoorn, could you check your flycheck version by calling `flycheck-version`?

**Comment by fpvandoorn** [comment]
`Flycheck version: 0.21alpha (package: 20140819.1136)`

**Comment by fpvandoorn** [comment]
I just updated all my packages (and learned how to do that).
That solved the problem!

**Comment by soonhokong** [comment]
Could you try the following steps to upgrade Flycheck?
- <kbd>M-x</kbd>`list-package`
- Press `U`, `x`, and `y`

**Comment by soonhokong** [comment]
Great!

Just to make sure, what's your version number now?

**Comment by fpvandoorn** [comment]
`Flycheck version: 0.24alpha (package: 20150524.144)`

**Comment by soonhokong** [comment]
Great!

**Comment by leodemoura** [comment]
I have the same problem. My version is: `0.21snapshot1`.
For me, the first commit that produces the problem is ac04b996ab2da26d0

**Comment by leodemoura** [comment]
BTW, this issue also affects the PPA and Windows installation packages.
We have a snapshot of flycheck at
https://github.com/leanprover/emacs-dependencies

**Comment by soonhokong** [comment]
@leodemoura, you're right. This is due to https://github.com/leanprover/lean/commit/ac04b996ab2da26d0e55de77472ace5096dcba23. I was working on #617 and the author of flycheck strongly recommended me to use `flycheck-define-command-checker` over `flycheck-define-checker`. I followed his advice then. I think `flycheck-define-command-checker` was introduced in a newer version. I just checked MELPA stable (flycheck-0.23) and MELPA (flycheck-0.24). Both of them support `flycheck-define-command-checker`.

**Comment by soonhokong** [comment]
> BTW, this issue also affects the PPA and Windows installation packages. We have a snapshot of flycheck at https://github.com/leanprover/emacs-dependencies

You're right. This snapshot contains version 0.21-cvs1. I can upgrade it to [MELPA stable version (0.23)](http://stable.melpa.org/packages/flycheck-0.23.tar).

**Comment by leodemoura** [comment]
> I can upgrade it to MELPA stable version (0.23).

That would be great. 

I'm concerned because I had problems in the past installing more recent versions of flycheck. I will try to find the thread were we discussed this issue.

We should also send an email to the lean discussion list. 

Thanks,
Leo

**Comment by leodemoura** [comment]
I just tried to upgrade. It didn't work. I got the following error:

```
Package `let-alist-1.0.1' is unavailable
```

I have the following in my .emacs. 

```
(require 'package)
(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/") t)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)
(when (not package-archive-contents)
  (package-refresh-contents))
```

**Comment by soonhokong** [comment]
@leodemoura, I just created a new branch [leanprover/emacs-dependencies/tree/flycheck-0.23](https://github.com/leanprover/emacs-dependencies/tree/flycheck-0.23). Once we confirm that this version is working, we can make it as a master branch.

> I'm concerned because I had problems in the past installing more recent versions of flycheck. 

I remember that. That was related with [let-alist](http://elpa.gnu.org/packages/let-alist.html).

**Comment by leodemoura** [comment]
I also tried to install version: `20150524.144` from melpa. It produced the same error :-(

**Comment by soonhokong** [comment]
:-( It's a nightmare again... Could you try the following hack and try to install flycheck again?

``` elisp
(setq package-check-signature nil)
```

**Comment by leodemoura** [comment]
I tried the command you suggested. Emacs "installed" flycheck. However, when I tried to restart it, I got the following error message. 

```
Warning (initialization): An error occurred while loading `/home/leo/.emacs':

error: Autoloading failed to define function flycheck-define-command-checker

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
Warning (:warning): for magit-1.4.0

You have just updated to version 1.4.0 of Magit, and have to
make a choice.

Before running Git, Magit by default reverts all unmodified
buffers that visit files tracked in the current repository.
This can potentially lead to data loss, so you might want to
disable this by adding the following line to your init file:

  (setq magit-auto-revert-mode nil)

The risk is not as high as it might seem.  Snapshots on MELPA
and MELPA-Stable have had this enabled for a long time, so if
you have not experienced any data loss in the past, you should
probably keep this enabled.

Keeping this mode enabled is only problematic if you, for
example, use `git reset --hard REV' or `magit-reset-head-hard'
and expect Emacs to preserve the old state of some file in a
buffer.  If you turn off this mode then file-visiting buffers and
the Magit buffer will no longer be in sync, which can be confusing
and would complicate many operations.  Note that it is possible
to undo an automatic buffer reversion using `C-x u' (`undo').

To prevent this message from being shown each time you start
Emacs, you must add the following line to your init file:

  (setq magit-last-seen-setup-instructions "1.4.0")

You might also want to read the release notes:
https://raw.githubusercontent.com/magit/magit/next/Documentation/RelNotes/1.4.0.txt
```

**Comment by soonhokong** [comment]
- Which version of flycheck did you install? 0.24 or 0.23?
- I think the 2nd half of the message is regarding the newer version of `magit` and not related with this issue.

**Comment by leodemoura** [comment]
I tried `20150524.144`.

**Comment by leodemoura** [comment]
I uninstalled it, and installed 0.23. It is working now.

**Comment by leodemoura** [comment]
BTW, why did I have to use?

``` emacs
(setq package-check-signature nil)
```

**Comment by soonhokong** [comment]
I guess it was not installed completely:

> The autoloaded file usually contains other definitions and may require or provide one or more features. If the file is not completely loaded (due to an error in the evaluation of its contents), any function definitions or provide calls that occurred during the load are undone. 
> ...
> If the autoloaded file fails to define the desired Lisp function or macro, then an error is signaled with data "Autoloading failed to define function function-name".

http://webcache.googleusercontent.com/search?q=cache:wLrIk8mldB0J:www.gnu.org/s/emacs/manual/html_node/elisp/Autoload.html+&cd=1&hl=en&ct=clnk&gl=us

**Comment by soonhokong** [comment]
> BTW, why did I have to use?
> (setq package-check-signature nil)
- `let-alist` package is hosted in GNU ELPA repository.
- Some versions of emacs have bug in checking signature of package repositories. Setting `package-check-signature` to `nil` is a workaround.

http://stackoverflow.com/a/26110978/2654527

**Comment by leodemoura** [comment]
Thanks!

> @leodemoura, I just created a new branch leanprover/emacs-dependencies/tree/flycheck-0.23. Once we confirm that this version is working, we can make it as a master branch.

Could you please include the `let-alist` at leanprover/emacs-dependencies?

Thanks,
Leo

**Comment by soonhokong** [comment]
> Could you please include the let-alist at leanprover/emacs-dependencies?

Just updated flycheck-0.23 branch of https://github.com/leanprover/emacs-dependencies. Do you think we can mark it as a master branch?

**Comment by leodemoura** [comment]
> Just updated flycheck-0.23 branch of https://github.com/leanprover/emacs-dependencies. Do you think we can mark it as a master branch?

Yes. 
Thanks a bunch!!!

**Comment by soonhokong** [comment]
Updated: https://github.com/leanprover/emacs-dependencies
