### ISSUE TITLE
or.elim to universal in tactic mode

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean3#631]
In the following, the apply tactic in test fails, but of course test2 succeeds:

``` lean
import logic data.nat
open nat

constant P : ℕ → Prop
constant Q : ℕ → Prop
constant N : ℕ

axiom pqn : P N ∨ Q N

axiom pn_all : P N → ∀ n : ℕ, P n
axiom qn_all : Q N → ∀ n : ℕ, P n

theorem test : ∀ n : ℕ, P n :=
  begin
    apply or.elim,
  end

theorem test2 : ∀ n : ℕ, P n :=
  or.elim pqn (take Hp, pn_all Hp) (take Hq, qn_all Hq)
```

This seems to happen whenever I try to use or.elim to prove a universal. Any ideas?

Edit -- the following works:

``` lean
theorem test : ∀ n : ℕ, P n :=
  begin
    apply or.elim pqn (take Hp, pn_all Hp)
  end
```

**Comment by fpvandoorn** [comment]
If you write `apply H`, Lean assumes that if the goal is of the form `A → B` or `∀ a : A, B a`, that `B` (resp `B a`) matches the conclusion of `H`, and `A` is the last hypothesis. 

This is behavior is necessary for an example like this:

```
  example {A B C : Prop} (H1 : A → B → C) (H2 : A) : B → C :=
  begin
    apply H1, exact H2
  end
```

For theorems which are "like an induction principle", this heuristic is not always correct. The conclusion of `H` could match with `A → B` or `∀ a : A, B a`. For these theorems you want to use `eapply`, this will match the _whole_ goal with the conclusion of `H`. In your case, if you write

```
eapply or.elim,
```

you get three unsolved subgoals, as you would expect.

EDIT: See also #361

**Comment by robertylewis** [comment]
I see, thanks for clarifying. I was familiar with apply and fapply, but not eapply!
