### ISSUE TITLE
printing definitions using parameters with @

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#634]
As we discussed before, making sure that the pretty printer output can be parsed + elaborated correctly is a very hard problem. However, I do think we should make sure that this is possible if the pretty printer print enough information, specifically with the following options: (+ maybe a few?)

``` lean
set_option pp.notation false
set_option pp.implicit true
set_option pp.coercions true
set_option pp.full_names true
set_option pp.universes true
set_option pp.numerals false
```

This is already almost always the case. However, here is a tricky example where it is currently not the case

``` lean
open nat
namespace foo
section
  parameter (X : Type₀)
  definition A {n : ℕ} : Type₀ := X
  variable {n : ℕ}
  set_option pp.implicit true
  check @A n
  set_option pp.full_names true
  check @foo.A X n
end
end foo
```

Output:

``` lean
A n : Type₀
foo.A n : Type₀
```

Expected output:

``` lean
@A n : Type₀
@foo.A X n : Type₀
```

Unfortunately the rules whether to print the parameter of `A` is quite tricky. If I'm correct the rule should be
- never if `A` is declared in the root namespace
- only if the full name of `A` is printed when `A` is _not_ declared in the root namespace

**Comment by fpvandoorn** [comment]
I'm reopening this issue for two reasons:
- The printer should always print the `@` in front of the `A` with the option `set_option pp.implicit true`. So `634.lean.expected.out` should be 

``` lean
@A n : Type₁
@foo.A X n : Type₁
@foo.A X n : Type₁
@A n : Type₁
@A n : Type₁
```
- When the option `set_option pp.full_names true` is enabled, the pretty printer incorrectly prints parameters which are declared in the root namespace:

``` lean
section
  parameter (X : Type₀)
  definition A : Type₀ := X
  set_option pp.full_names true
  check A
end
```

Output: `A X : Type₀`
Expected output: `A : Type₀` or `_root_.A X : Type₀`

**Comment by leodemoura** [comment]
Trying again... there are too many cases, I'm not sure we are all covering all possible cases.
I included tests for some nasty cases.

**Comment by fpvandoorn** [comment]
Oh wow, I see what you mean. That required much more code than I thought.

I also didn't know/realize the pretty printer doesn't print `@` for definitions which don't need them, even with `set_option pp.implicit true`.

Sometimes I feel bad for making you spend an afternoon on something like this. Feel free to mark such issues as low priority or postponed.

(and sorry for opening a "sequel" to this issue immediately after you solved this one. The timing was a coincidence)
