### ISSUE TITLE
remove branch

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#637]
Oops, I accidentally created a branch `master1year}`, can someone remove it. (I tried using the notation `master@{1year}` on the commits page. This notation is allowed on Github for comparing branches. But on the commits page apparently it creates a new branch).

**Comment by soonhokong** [comment]
I just removed it.

**Comment by fpvandoorn** [comment]
Thanks!

**Comment by soonhokong** [comment]
FYI, http://stackoverflow.com/a/2003515.
