### ISSUE TITLE
order in init

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#643]
Is there a reason that `init.nat` in both libraries contain so many theorems about the orders, but not - for example - commutativity of addition? If not, then I'll move almost all these theorems to `[data|types].nat.order`. I'll leave `lt.wf` and `decidable_[le|ge|lt|gt]` in `init`.

**Comment by leodemoura** [comment]
> Is there a reason that init.nat in both libraries contain so many theorems about the orders, but not - for example - commutativity of addition?

The idea is to use these theorems when implementing automation for well-founded recursion.
Each recursive application contains a proof term showing that it is decreasing.
In most cases, this proof term is obvious, and can be easily synthesized.
Several well-founded relations will also be synthesized using tricks such as:
- https://github.com/leanprover/lean/blob/master/library/init/measurable.lean

The idea is to build a (simple) well-founded relation for an arbitrary type on type of `<` for nat.

**Comment by leodemoura** [comment]
Should we close this issue?

**Comment by fpvandoorn** [comment]
Yes. I'll leave these theorems in init.
