### ISSUE TITLE
"generalize - intro - induction" idiom

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#645]
Right now, the tactic `induction H` assumes `H` is a hypothesis. This is annoying in some cases, and forces us to use `eapply` or use the idiom `generalize t, intro H, induction H`. The `cases` tactic has the same problem. Here is an annoying example:

``` lean
definition to_pred {A : Type} (p : A → bool) : A → Prop :=
λ a, p a = tt

definition to_pred_dec [instance] {A : Type} (p : A → bool) 
                : decidable_pred (to_pred p) :=
begin
  intro a, unfold to_pred,
  generalize p a, intro H, induction H,
    right, contradiction,
    left, reflexivity
end
```

It would be nicer to be able to write `induction p a`, and let Lean apply the `generalize, intro, induction` idiom automatically for us. 
@fpvandoorn Have you had similar problems with the `induction` tactic?

**Comment by fpvandoorn** [comment]
Yes, I've used `eapply` a couple of times in cases where I wanted to induct over something which was not an identifier. For example, three times in this file (search for `eapply`): 
https://github.com/fpvandoorn/leansnippets/blob/master/propositional_truncation.hlean
(this file can be compiled in my master branch).

It would indeed be nice if the `induction` tactic does this automatically for us.

**Comment by leodemoura** [comment]
@fpvandoorn To compile `propositional_truncation.hlean`, we need the new `nat.le` (issue #638). 
Could you push this change to the master branch?

Thanks

**Comment by fpvandoorn** [comment]
I'll make a pull request later. For the moment you can compile it on `fpvandoorn/master`.

**Comment by fpvandoorn** [comment]
Great! I could change all the `eapply` in that file by `induction`.
