### ISSUE TITLE
double private definition

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#648]
``` lean
import hit.colimit hit.pushout
```

Error: `invalid object declaration, environment already has an object named 'private.144776243.R'`
I use `R` as `local abbreviation` (inside a section) in `hit.colimit` (twice) and in `hit.pushout`.

**Comment by leodemoura** [comment]
I will fix it. BTW, this is a big coincidence: the hashcode `144776243` is computed using current line&column numbers, user given name (R in this case), and number of commands executed so far in the file. Unfortunately, all these values are the same for the `R` in `hot.colimit` and `hit.pushout` :-(

**Comment by fpvandoorn** [comment]
Ah, that is indeed quite the coincidence. Although not entirely, since both files do have exactly the same structure.
