### ISSUE TITLE
decidable.rec stuck on simple example

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#651]
Hi,

I cannot seem to figure out why the following evaluation gets stuck.

``` lean
    import data.set
    open bool set

    lemma decidable_univ [instance] {T : Type} [T_dec : decidable_eq T] (x : T) : 
      decidable (x ∈ univ) := decidable.inl trivial

    eval if tt ∈ univ then tt else ff
```

yields

``` lean
decidable.rec (λ (Hc : true), tt) (λ (Hnc : true → false), ff) (decidable_univ tt)
```

Evaluation works fine if the definition of `univ` is made reducible and the lemma is removed. Any clarification would be appreciated.

Thanks,

Daniel

**Comment by fpvandoorn** [comment]
This is because the proof of `theorems` (and hence `lemmas`) are elaborated in parallel. Therefore, the value of `decidable_univ` is not available for the remainder of the file, by default (only the type is available). If you want to have the value available, you can either make it a definition, or use the `reveal` command:

``` lean
import data.set
open bool set

lemma decidable_univ [instance] {T : Type} [T_dec : decidable_eq T] (x : T) : 
  decidable (x ∈ univ) := decidable.inl trivial

reveal decidable_univ
eval if tt ∈ univ then tt else ff
```

For discussion about this, see this issue: #576.

**Comment by avigad** [comment]
I believe all the instances of `decidable` in the standard library are declared as definitions. This seems to me to be natural; the instance is a decision procedure which returns a piece of data. Even though thoerems and the like are no longer opaque, I think we should still reserve "theorem", "lemma", etc. in the standard library for things that return elements of `Prop`.

**Comment by dselsam** [comment]
Thanks. I usually make instances of `decidable` definitions instead of lemmas, and this was just a careless mistake on my part. I agree that "theorem" and "lemma" should be reserved for things that return elements of `Prop`, especially since one could accomplish the same thing by using "xyzw definition". Perhaps Lean could even give an error/warning when this is not the case.
