### ISSUE TITLE
changing explicitness of multiple parameters

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#652]
``` lean
section
  parameters {b c : bool}

  definition R : Type₀ := (b = c)

  parameters (b c)
  definition R2 := R
  parameter (c)
  parameter (b)
  definition R3 := R
end

check @R
check @R2
check @R3
```

Output:

``` lean
R : Π {b c : bool}, Type₀
R2 : Π {b : bool}, bool → Type₀
R3 : bool → (Π {c : bool}, Type₀)
```

Expected output:

``` lean
R : Π {b c : bool}, Type₀
R2 : bool → bool → Type₀
R3 : bool → bool → Type₀
```

**Comment by avigad** [comment]
Actually, I would expect R2 and R3 to inherit the implicit arguments from R, I think.

**Comment by fpvandoorn** [comment]
I don't think that expectancy can be generalized. What if I change the definitions of `R2` and `R3` to some compound term where `R` occurs? What if in that term also another identifier `R'` occurs where the parameters `b` and `c` are actually explicit?

**Comment by avigad** [comment]
Good point.
