### ISSUE TITLE
Strange error involving universe variables

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#657]
Hi,

I am confused by an error I get when using universe variables. When I run the following code:

``` Lean
import logic.cast

set_option pp.universes true
set_option pp.implicit true

constants (A : Type) (B : A → Type)
constants (a1 a2 : A)
constants (a1_eq_a2 : a1 = a2)

constants (b1 : B a1)
constants (f : ∀ (a : A), B a → Type)

definition pf := @dcongr_arg2 _ _ _ _ _ b1 _ f a1_eq_a2 rfl
example : f a1 b1 = f a2 (@eq.rec_on A a1 (λ (a : A), B a) a2 a1_eq_a2 b1) := pf
```

I get the error:

```
error: type mismatch at definition 'example', has type
  f.{l_3 l_4 l_5} a1.{l_4} b1.{l_4 l_5} = f.{l_3 l_4 l_5} a2.{l_4}
    (@eq.rec_on.{l_5 l_4} A.{l_4} a1.{l_4} (λ (a : A.{l_4}), B.{l_5 l_4} a) a2.{l_4} a1_eq_a2.{l_4} b1.{l_4 l_5})
but is expected to have type
  f.{l_3 l_4 l_5} a1.{l_4} b1.{l_4 l_5} = f.{l_3 l_1 l_2} a2.{l_1}
    (@eq.rec_on.{l_2 l_1} A.{l_1} a1.{l_1} (λ (a : A.{l_1}), B.{l_2 l_1} a) a2.{l_1} a1_eq_a2.{l_1} b1.{l_1 l_2})
```

I am not sure where the two extra universe variables come from, or why they cannot be unified by equating `l_1 = l_4` and `l_2 = l_5`. When I change the implicit universe variables for `A` and `B` to both be constants, it works as expected. Any clarification would be appreciated.

Thanks,

Daniel

[Note: the definition of `pf` and the additional implicit arguments seem to be required to make the error message this detailed.]

**Comment by leodemoura** [comment]
Lean elaborates the types of `theorem`, `lemma` and `example` independently of their values.
The idea is that the proof should not influence the statement of the theorem. 
For `example`, It is debatable whether we should do this or not, but this is what lean is currently doing.

Note that `f` has three universe parameters: one for `A`, one for `B` and another for the resulting `Type`. In the example, the equation `f ... = f ...` is only forcing the third universe to be the same. 
That is, if we only take into the account the type of the example, there are 5 universes. We have 3 for the first `f`, 3 for the second `f`, but the third universe of each `f` should be the same.

That being said, the example works if we use a definition

``` lean
definition my_example : f a1 b1 = f a2 (@eq.rec_on A a1 (λ (a : A), B a) a2 a1_eq_a2 b1) := pf
```

Now, the value `pf` and the type of `my_example` are elaborated simultaneously. So, the universe constraints you pointed are solved, and everything works.

**Comment by leodemoura** [comment]
BTW, the `subst` tactic is quite useful for handling examples that need casts/transports.
Given a hypothesis of the form `h : t = a` (or `h : a = t`), where `a` is a variable, it will automatically revert any other hypothesis that depends on `a` or `h`; eliminate `a`, reintroduce all reverted hypothesis, and delete `h` and `a`. It also automatically uses dependent elimination if needed. `substvars` tries to eliminate as many variables as possible using `subst`. Here is an example:

``` lean
import data.list

section

parameters (A : Type) (B : A → Type)
parameters (a1 a2 : A)
parameters (b1 : B a1)
parameters (b2 : B a2)
parameters (f : ∀ (a : A), B a → Type)

definition foo₁ : ∀ h : a1 = a2, eq.rec_on h b1 = b2 → list (f a1 b1) = list (f a2 b2) :=
begin
  intro e1 e2, subst e1, subst e2
end

definition foo₂ : ∀ h : a1 = a2, eq.rec_on h b1 = b2 → list (f a1 b1) = list (f a2 b2) :=
by intros; substvars

end
```

**Comment by dselsam** [comment]
Thank you. I realize now that I misunderstood how universe variables work in constants. The tutorial says:

```
When we declare a constant A : Type, Lean implicitly creates a variable
l, and declares A : Type.{l}. In other words, A is a type in some unspecified universe.
```

which makes it sound as if `A` is in a single (though unknown) universe. But it seems that `A` is actually universe polymorphic, i.e. a function that takes a universe level `l` and returns an element that has type `Type.{l}`. The reason there are five universe variables and not three is because `a1` and `a2` are also functions, that each take a universe level `l` and return an element of type `A l` (my notation to stress the function perspective). I understood that defined functions that take elements of type `Type` as arguments were universe polymorphic, but I didn't realize that constants were too. The behavior I was expecting for constants can be obtained by declaring a universe constant explicitly using `universe l`.

**Comment by leodemoura** [comment]
By default, constants and axioms are universe polymorphic. I will fix the tutorial.
The behavior described in the tutorial is for parameters and variables (which cannot be universe polymorphic).

To define a constant that is not universe polymorphic, we should write

``` lean
universe u
constant A : Type.{u}
constant B : Type.{u} -- we can use the same universe for different constants.
```
