### ISSUE TITLE
emacs message: Not enabling jit-lock

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#664]
When I open a file in Lean, the message line reads "Not enabling jit-lock: it does not work in indirect buffer".

I first noticed this yesterday or today. @rlewis1988 tells me he gets the same message. It does not seem to cause any problems, and we can just ignore it. But it happens every time I open a file.

I am using emacs 24.4.1.

**Comment by soonhokong** [comment]
I also get this message as well. As far as I know, it's not harmful and It comes from using `mmm-mode` (to syntax-highlight Lua code in Lean). Let me ask the mmm-mode maintainer how to fix this (or not showing the message).

**Comment by robertylewis** [comment]
While we're on the topic of emacs problems: I've noticed that the behavior of the lean-info buffer can be inconsistent. Usually, hovering over a comma in a tactic proof prints the current context and goal. But sometimes this will stop working, either temporarily or until I restart emacs. It doesn't seem to have anything to do with errors in the proof or elsewhere in the file. 

I tried briefly to reproduce the problem, but couldn't figure out what triggered it. Is this a known issue? If not, I'll try again to reproduce it. The buffer is really helpful for long tactic proofs!

**Comment by soonhokong** [comment]
There is a similar issue #633. I'll try to fix #499 this week which is also related one.

**Comment by soonhokong** [comment]
@avigad, a mmm-mode collaborator confirms that the warning is harmless. Please see https://github.com/purcell/mmm-mode/issues/51.

**Comment by soonhokong** [comment]
`mmm-mode` is updated. Please upgrade it to the latest version. I'm using emacs-24.5.1 and I don't see the message anymore.

**Comment by soonhokong** [comment]
https://github.com/leanprover/emacs-dependencies/commit/efe944f812b96c9e1b7f35009c10e797eae060e0 added the latest version of mmm-mode.
