### ISSUE TITLE
transitive closure of the coercion graph

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#668]
The discussion at issue #666 suggests we should change how we maintain the transitive closure of the coercion graph. The current approach is too dynamic and generates confusion. 
For example, consider the following code snippet

``` lean
set_option pp.coercions true

namespace Nat
  constant Nat : Type₁
  constant num2Nat : num → Nat
  attribute num2Nat [coercion]
  check (0 : Nat)  -- num2Nat 0
end Nat

namespace Int
  open Nat
  constant Int : Type₁
  constant Nat2Int : Nat → Int
  attribute Nat2Int [coercion]
  check (0 : Int) -- Nat2Int (num2Nat 0)
end Int

open Int
check (0 : Int) -- Error
```

The last check produces an error because the coercion `num2Nat` is not available. 
To make it work, we also have to open `Nat`

``` lean
open Nat Int
check (0 : Int)
```

The problem is that the transitive closure is being computed over and over again whenever we open namespaces. I think this approach has some problems: 
1- We compute the transitive closure over and over again.
2- It is easy to make mistakes like the one above. For example, to workaround  this problem, Jeremy defined 3 coercions (`rat.of_int`, `rat.of_nat` and `rat.of_num`) at `rat/basic.lean`. 
3- It is bad if we want to create auxiliary definitions to represent derived coercions. In principle, we would have to generate auxiliary definitions whenever we open a namespace.

To address these issues, I think we should change how we manage coercions.
When we declare a new coercion, we would compute the transitive closure (at the time of the declaration), add a new auxiliary definition for each derived coercion (and also mark it as a coercion). Then, when we open a namespace, we don't perform any transitive closure computation. 
The new approach is more efficient, and would solve the problem above.
However, it would fail in the following example that works in the current implementation

``` lean
set_option pp.coercions true
set_option pp.full_names true

namespace Nat
  constant Nat : Type₁
  constant num2Nat : num → Nat
  attribute num2Nat [coercion]
end Nat

namespace Int
  constant Int : Type₁
  constant Nat2Int : Nat.Nat → Int
  attribute Nat2Int [coercion]
  -- the derived coercion num2Int is not created here since we did not open Nat
end Int

open Nat Int
check (0 : Int) -- Error
```

@avigad @fpvandoorn What do you think?

**Comment by leodemoura** [comment]
BTW, another benefit is that we could use the same approach for implementing the transitive closure of the child/parent structure graph. I think it would be nice to use the same approach for both of them.

**Comment by fpvandoorn** [comment]
I like the change. Usually if you already have a coercion `A -> B` and you define a new coercion `B -> C`, then the existing coercion is in the current environment, so you get the full transitive closure.

**Comment by avigad** [comment]
It sounds good to me too. I think it is o.k. to place more of a burden on library developers (to know that they have to open the relevant namespaces when they define the coercions), to make the system better for users. We can explain everything in the documentation.
