### ISSUE TITLE
rewrite with equivalences

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#670]
I'm generally hesitant to open issues for enhancements, but in this case it's about an issue which happens all over the HoTT library.

The problem is that the `rewrite` tactic doesn't work nicely with equivalences. Suppose I have an equivalence `e : A ≃ B`, and suppose that `to_fun e` reduces to `f : A → B` and `to_inv e` reduces to `g : B → A`. We also have the other two components of `e`:

```
to_left_inv  e a : g (f a) = a
to_right_inv e b : f (g b) = b
```

However, we cannot rewrite with these equalities, because _syntactically_ the type of `to_right_inv e b` is `function.compose (to_fun e) (inv (to_fun e)) b = b`. This means that if you have a subterm `f (g b)` in your goal, `rewrite [to_right_inv e b]` doesn't match with this subterm. Also `xrewrite` and `krewrite` don't work in this case

In an example:

``` lean
-- HoTT
open equiv

constants (A B : Type₀) (f : A → B) (g : B → A) (p : Πb, f (g b) = b) (q : Πa, g (f a) = a)

definition e [constructor] : A ≃ B :=
equiv.MK f g p q

-- this works, but in a typical proof with equiv.MK, 
--  the fields p and q are too long to write down explicitly over and over again
example (b : B) : g (f (g b)) = g b :=
by rewrite p

-- this fails
example (b : B) : g (f (g b)) = g b :=
by rewrite [to_right_inv e b]

-- this workaround works
example (b : B) : g (f (g b)) = g b :=
begin
  let H := to_right_inv e b,
  esimp at H,
  rewrite H
end
```

The workaround works most of the time for rewriting with equivalences, as long as `e` is marked with the `constructor` attribute.

The workaround gives an idea: could we apply `esimp` to the type of the rewrite rule before applying it? 

However, I doubt that this behavior is always desirable, and it will probably break many current uses of rewrite. But I think this would be a generally useful feature, also for all kinds of other cases, so I think it would be worth it to create a new rewrite-tactic-variant for this.

**Comment by leodemoura** [comment]
> The workaround gives an idea: could we apply esimp to the type of the rewrite rule before applying it?

Yes, we can. As you say, it should not be the default.

> I think it would be worth it to create a new rewrite-tactic-variant for this.

We can also use a modifier to the rewrite step. We have a couple of modifiers already `-`,`+`,`*`
We can add another one.

**Comment by fpvandoorn** [comment]
> We can also use a modifier to the rewrite step. 

That would be even better

**Comment by leodemoura** [comment]
I used a trick: when a rewrite step fails, I reduce the type and try again.
It solves your example :-)
