### ISSUE TITLE
constructor using fapply

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#676]
Could the `constructor` tactic be based on `fapply` instead of `apply`? Often a structure consists of some data and then some properties about that data, and you want to give both of them explicitly when using the constructor. Examples: categories, functors, groups (bundled or unbundled).

**Comment by leodemoura** [comment]
BTW, note that the commit contains an example/test that was negatively affected by the change.
It is the kind of example where `apply` is the right choice.

**Comment by fpvandoorn** [comment]
In that case we could also have two tactics: `constructor` and `fconstructor`.
