### ISSUE TITLE
type classes and inductive families

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#679]
In Chapter 9 of the tutorial we say this:

> Type Classes and Instances
> 
> The basic idea is simple. In Section ..., we saw that
> any family of inductive types can serve as the source or target of a
> coercion. In much the same way, any family of inductive types can be
> marked as a /type class/.

I have already changed the description of coercions, and I will fix it here. But I wonder whether similar issues will arise, i.e. people will wonder why we can't declare any defined type to be a class. Should type classes be handled in a manner similar to coercions?

I don't feel strongly about this, but I thought I would ask.

**Comment by leodemoura** [comment]
> Should type classes be handled in a manner similar to coercions?

Yes, we should. It is not implemented yet, but we should do it.

**Comment by avigad** [comment]
In the meanwhile, I will make the correction in the tutorial to reflect the current state.
