### ISSUE TITLE
[unfold-c ] with multiple arguments

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#693]
Sometimes you only want to unfold a definition if multiple arguments are a constructor, for example a binary function which is defined by induction on both arguments. It would be nice to have an `[unfold-c n_1 n_2 ... n_k]` attribute which unfolds the definition if all the specified arguments are constructors.

**Comment by leodemoura** [comment]
This is feasible. 
BTW, do you have a better name for `[unfold-c]`?
In the past, you also pointed out that the `[constructor]` annotation is misleading.
It would be nice to have good names for all of them.

**Comment by fpvandoorn** [comment]
I've started to like `[constructor]`. Quite a lot of definitions with that attribute are a kind of "alternative constructors" to a type. 
The name of `[unfold-c]` is indeed not great. Maybe just `[unfold]` (I like to have a relatively short name, because I'm using it often)? And `[unfold-f]` can be `[unfold-full]`.

**Comment by leodemoura** [comment]
@fpvandoorn I will change the names.

**Comment by leodemoura** [comment]
Example: https://github.com/leanprover/lean/blob/26574e29a9ba456b8b445441e23a43cb902098db/tests/lean/693.lean
