### ISSUE TITLE
heuristic for insterting [unfold-c] and [constructor]

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#694]
It is annoying to tag everything with the `[unfold-c _]` and `[constructor]` attributes. I'm adding them mostly when I'm actually using them, but still they occur already a lot in the HoTT-library.

We should have good heuristics for adding them automatically. This also requires a method to remove either of these attributes from a definition, because no heuristic is perfect.

For `[unfold-c]`: If we define a definition and only a single `[recursor]` occurs in the definition and the major premise of that recursor is an argument of the definition, then add the attribute `[unfold-c n]`, where `n` marks the place of the major premise. 

The idea is that the unfolded version is "simpler" because we can reduce the recursor. However, the actual unfolded term might still be much longer than the folded definition. 

Here is a conservative variant:
Same as above, but also require that all minor premises are either variables (terms of the form `(fun a_1 a_2 ... a_n, x` where `x` is a variable in the local context (can be `a_i` or another variable)) or have a `[constructor]` as head. 

Example: in `hott/init/path`, `concat` would fall in the first category, and `inverse` in the second. Even though this is a very restrictive condition, loads of definitions fall into this conservative variant (e.g. most definitions in `hott/init/path`)

---

For `[constructor]`: if the head of the definition is a `[constructor]` then this definition is also a `[constructor]`. The idea is that the new definition is a "special case" of the old definition, so if you would want to unfold terms with the previous definition, then you also want to do it with the new one.

The only counterexamples I've found so far is in the algebraic hierarchy, where we don't want to add this attribute from definitions defining an parent `structure` from an extended `structure`. We could add the exception that automatically generated definitions like this do not have this attribute.

**Comment by leodemoura** [comment]
I'm planning to mark this feature as `postponed` and close it. Unless someone volunteers to implement it.
I will not work on this kind of feature in the near future.

**Comment by Kha** [comment]
I applied `[unfold]` to quite a few definitions defined by pattern matching today. In general, if a definition starts by applying a function with an `unfold` attribute (or a primitive recursor), I think it would be a safe heuristics to just copy that attribute. If this sounds reasonable, I can give it a try.

**Comment by Kha** [comment]
Ah, I should have read the the opening post more closely. Floris's heuristic makes much more sense and shows that the implementation is probably not that trivial. I'd start with definitions created by the definitional package then, that way I shouldn't have to worry about major and minor premises.
