### ISSUE TITLE
small issues with the tactic framework

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#695]
I don't want to create an issue for each of these individually.
- [x] `intro` without argument should introduce a single variable (that's what Coq does)
- [ ] `intro` upto variant. 
- [x] Some notation to say that some names are irrelevant in the `intro` tactic. Example: `intro _ _ _ a b` introduces 5 variables, but the first three get the default name.
- [x] accept a trailing comma when rewriting multiple expressions, such as in `rewrite [foo,^bar,]` (I will still remove them when I finish the proof, but when adding a new rewrite rule one-by-one, it's useful not to have to worry each time about that additional comma).
- [x] According to the tutorial `<D foo` is an ASCII variant of `↓foo` in a rewrite tactic. However, it doesn't seem to work

``` lean
open nat
example (n : ℕ) : n + 1 = succ n :=
by rewrite [<D n+1]
```
- ~~`check_expr` fails when there are no goals. If easily possible it would be nice to still display the type in the context of the goal which has just been closed (though this is in no way important).~~

**Comment by leodemoura** [comment]
Everything is feasible, but item 4. `check_expr` is implemented using a tactic. It only has access to the current proof state.

**Comment by fpvandoorn** [comment]
When I posted it here I realized that it was more tricky than I initially thought, because there's no proof state. The issue is minor, so let's not worry about it.

**Comment by leodemoura** [comment]
I added two extra improvements to the list.

**Comment by leodemoura** [comment]
I'll not implement the `intro` upto variant.
