### ISSUE TITLE
Missing check in `check_level`

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#696]
Hi,

In the following code:

https://github.com/leanprover/lean/blob/master/src/kernel/type_checker.cpp#L144-L152

~~the level is only checked for undefined params if `m_params` happens to be not empty. I think it would make sense to add an else clause that confirms `l` has no params in the case that `m_params` is empty.~~ 

(This issue doesn't even make sense)

Daniel

**Comment by leodemoura** [comment]
The type checker provides the method `check_ignore_undefined_universes`.
https://github.com/leanprover/lean/blob/master/src/kernel/type_checker.cpp#L357
It sets `m_params` to `nullptr` to indicate the universe level parameters do not need to be checked

We use the `check_ignore_undefined_universes` to implement the sanity check procedure `check_term`
https://github.com/leanprover/lean/blob/d8620ef4c90afb6bc44a404b0467ff25535d9b4d/src/library/util.cpp#L772

The `check_term` is used in several tactics to make sure they are not producing type incorrect terms
https://github.com/leanprover/lean/search?utf8=✓&q=check_term

**Comment by dselsam** [comment]
Retracted. It seems this is intensional, since it provides a way to check terms while ignoring undefined universe errors. Sorry for the mixup.
