### ISSUE TITLE
unit should not be universe polymophic

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#698]
`unit` is currently the only inductive type without parameters which is universe polymorphic. I think we should have only a `unit` in `Type₁` (standard) / `Type₀` (HoTT). 
I tried to do this: https://github.com/fpvandoorn/lean/commit/ada33f1662d03ff162d13b4a1386dd79c3f6c2c0, but I failed, because `brec_on` in the definitional package uses the fact that `unit` is universe polymorphic. This can probably be fixed easily using some lifts.

Leo, if you can fix the C++-code, then I'm willing to go over both libraries to fix type errors.

**Comment by leodemoura** [comment]
We can use a different universe polymorphic `unit` just for `brec_on`.
I would prefer to avoid changing the following piece of code
https://github.com/leanprover/lean/blob/e5a82ef516d47319e4b743cc50d4ac7ffa59aa01/src/library/definitional/brec_on.cpp

It takes time to remember how it works.
Moreover, the change may have unforeseen consequences: `brec_on` is used in the definitional package. For example, `no_confusion` uses lifts in the HoTT version, and it affected automation in a couple of places.

**Comment by fpvandoorn** [comment]
That is a better solution. I think I can do that.
I'll create a universe polymorphic `poly_unit` and let `brec_on` use that.
