### ISSUE TITLE
apply ... at ...

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#700]
Similar to `rewrite foo at H` it would be nice to have an `apply foo at H` tactic for forward reasoning. Here would be an example:

``` lean
constants (A B : Type) (foo : A → B)
example (H : A) : B :=
begin            -- proof state: H : A ⊢ B
  apply foo at H -- proof state: H : B ⊢ B
  assumption
end
```

How it works in Coq is explained in the [Coq manual](https://coq.inria.fr/refman/Reference-Manual010.html#hevea_tactic13)

> 8.2.5  `apply term in ident`
> 
> This tactic applies to any goal. The argument `term` is a term well-formed in the local context and the argument `ident` is an hypothesis of the context. The tactic `apply term in ident` tries to match the conclusion of the type of `ident` against a non-dependent premise of the type of `term`, trying them from right to left. If it succeeds, the statement of hypothesis `ident` is replaced by the conclusion of the type of `term`. The tactic also returns as many subgoals as the number of other non-dependent premises in the type of `term` and of the non-dependent premises of the type of `ident`. 
> 
> If the conclusion of the type of `term` does not match the goal and the conclusion is an inductive type isomorphic to a tuple type, then the tuple is (recursively) decomposed and the first component of the tuple of which a non-dependent premise matches the conclusion of the type of `ident`. Tuples are decomposed in a width-first left-to-right order (for instance if the type of `H1` is a `A <-> B` statement, and the type of `H2` is `A` then `apply H1 in H2` transforms the type of `H2` into `B`). The tactic apply relies on first-order pattern-matching with dependent types.

The last paragraph is also a useful enhancement for the regular `apply` function.

**Comment by leodemoura** [comment]
I'm planning to mark this issue as `postponed` and close it. 
Unless someone volunteers to implement it.
I will not work on this kind of feature.
My reasons:
- It produces cryptic proofs. 
- We can workaround this command.
- My focus is on high-level automation and support what @avigad refers as Johannes-style proof scripts.

**Comment by fpvandoorn** [comment]
That's too bad, but I understand.
