### ISSUE TITLE
fold fails

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#702]
I have two questions about the following example:

``` lean
definition bar := bool
example (b : bar) : bool :=
begin
  rewrite [↓bar]
end
```

1: Why does it fail?
2: Is it possible to improve the error message? Maybe just 

```
invalid 'rewrite' tactic, rewrite step failed using pattern
bool
no subterm in the goal matched the pattern
```

**Comment by leodemoura** [comment]
> 1: Why does it fail?

The tactic is expecting to fold **applications**
