### ISSUE TITLE
Classical decidable instances shadow regular ones

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#704]
Hi,

In the following Lean code, only the second `eval` evaluates to `1`:

``` Lean
import classical
eval if true then 1 else 0
attribute prop_decidable [priority 0]
eval if true then 1 else 0
```

Does it make sense to lower the priority of `prop_decidable` in the standard (classical) library?

Daniel

**Comment by leodemoura** [comment]
Yes, it makes sense. 
If we can build an instance without using axioms, we should use it.

Advanced used users may manually raise the priority whenever they want to compute these instances quickly and they do not care about evaluating terms.
