### ISSUE TITLE
Lean hangs

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#705]
Lean hangs both in Emacs and at command line linja on the following file:

https://github.com/htzh/leanproved/blob/835bbc72ff37e11fb4d3fc6ac859e9e188691f63/group_theory/cyclic.lean

My suspicion is that the trouble is around:

https://github.com/htzh/leanproved/blob/835bbc72ff37e11fb4d3fc6ac859e9e188691f63/group_theory/cyclic.lean#L386-L395

**Comment by leodemoura** [comment]
The option `--profile` helps to identify where Lean is getting stuck.
I will investigate this issue later, I'm currently in a "black hole" that I entered when I started to investigate issue #666 :-( 
In the meantime, it would be great if you could rewrite the proof to avoid the problem.

**Comment by htzh** [comment]
> I'm currently in a "black hole"

No problem.  I have a proof that I think is correct but Lean still loops after type elaboration:

```
cyclic.lean:393:6: type elaboration time for rotl_seq_ne 0.03300 secs
```

After which I had to `ctrl-C`. I will see if breaking up the proof helps.

https://github.com/htzh/leanproved/blob/df6587801d0b116d661addd9b446a8e3de5bebfb/group_theory/cyclic.lean#L393-L402

**Comment by htzh** [comment]
The theorem cited above had an error in it. After correcting it Lean is now working on the correct version. So it is good to know that Lean only has problem with an intermediate incorrect form of the theorem.

```
-lemma rotl_seq_ne : ∀ {n : nat}, (∃ a b : A, a ≠ b) → ∀ i, i < n → rotl_fun i ≠ (@id (seq A (succ n)))
+lemma rotl_seq_ne : ∀ {n : nat}, (∃ a b : A, a ≠ b) → ∀ i, i < n → rotl_fun (succ i) ≠ (@id (seq A (succ n)))
```

https://github.com/htzh/leanproved/commit/270fed480cdb7c6f8ff5ed28b4ff79f4683704fb#diff-8c4fb2975f772162cdea51fd4cd3f963L393

The difference between i and succ i caused Lean to loop. I have memory of slowdowns dealing with different forms of nat.succ. Not sure if these are related.
