### ISSUE TITLE
make it easier to turn section base type variables implicit or explicit

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#715]
Often we have a base type, say `A`, that has a lot of inferred or other implicitly derived types dependent on it. When used as a section variable, it would be nice to be able to easily turn `A` implicit or explicit. Right now every time I want to change the implicitness of `A` I have to start a new section and redeclare all the other dependent variables. It creates a lot of boiler plate code and breaks the code flow, making code less readable. For an example see:

https://github.com/htzh/leanproved/blob/master/group_theory/pgroup.lean#L39

I had to create many spurious sections to manage the implicitness of the base type.

**Comment by leodemoura** [comment]
We can change it in the section. Here is an example

``` lean
section
  variable {A : Type}
  variable [decA : decidable_eq A]
  include decA

  definition ex1 (a b : A) := if a = b then 1 else 0 -- A is implicit

  variable (A)  

  definition ex2 (a b : A) := if a = b then 1 else 0  -- A is explicit

  check @ex1
  check @ex2

end
```

**Comment by htzh** [comment]
It does not work if there are dependencies between definitions.
For example the following definitions don't work:

```
variables {A : Type} [ambA : group A] [finA : fintype A]
include ambA finA

open fin

definition prodseq {n : nat} (s : seq A n) : A := Prodl (upto n) s

variable [deceqA : decidable_eq A]
include deceqA

definition peo [reducible] {n : nat} (s : seq A n) := prodseq s = 1
definition peo_seq (A : Type) (n : nat) := {s : seq A (succ n) | peo s}

failed to synthesize placeholder
A : Type,
ambA : group A,
finA : fintype A,
deceqA : decidable_eq A,
A_1 : Type,
n : ℕ,
s : seq A_1 ?M_1
⊢ group A_1
```

It works fine if they are in separate sections:

```
section defs

variables (A : Type) [ambA : group A] [finA : fintype A] [deceqA : decidable_eq A]
include ambA finA deceqA

open fin

definition peo_seq (n : nat) := {s : seq A (succ n) | peo s}

definition all_peo_seqs (n : nat) : list (peo_seq A n) :=
dmap peo tag (all_prodseq_eq_one A n)

end defs
```

https://github.com/htzh/leanproved/blob/904c4ab2562e2f6aeea23cbd0342276a3d2f776a/group_theory/pgroup.lean#L57-L85

**Comment by avigad** [comment]
I am writing from my phone. I think the problem is that the include forces
the insertion of the first A, and then the second A in peo-seq shadows it,
so there are two A's.

Don't declare A again in peo-seq, redeclare A beforehand, as in Leo's
example.

**Comment by leodemoura** [comment]
I used the feature I described in your file. Here is the list of changes
https://github.com/leodemoura/leanproved/commit/c8031630635446691d435cb78fc921323e148424

BTW, I had to modify two extra lines to make sure your file compiles with the latest lean.
The issue is similar to the one I described in the pull request I made yesterday.

**Comment by htzh** [comment]
That is cool. Thanks! I missed that the syntax is to just redeclare explicitness, not the full type. I think I got it now.
