### ISSUE TITLE
"keyed matching" for type class resolution

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#717]
Right now, if we want to synthesize a term of type (C A) using type class resolution, lean will try to unify the resulting type of each instance for class C with (C A). The first problem is that if the list of instances may be big, and the instance we want may be in the end of the list.

The second problem is that Lean may manage to solve the unification problem for the wrong instance. In the past, we had the “opposite” category instance for the class category. This created problems because lean would enter in a loop trying to create the opposite of the opposite of the opposite … One workaround is to move the opposite instance to the end of the list, but this is still problematic for type class resolution problems that cannot be solved.

So, I want to change to “keyed matching”. In keyed matching, the procedure works in the following way.
We collect the head symbol of every instance. For example, for the instance that produces

```
inhabited (prod A B)
```

the head symbol is prod. For the instance that produces

```
inhabited (sum A B)
```

the head symbol is sum. The next step is to create a mapping M from head symbol S to list of instances (where the head symbol is S).
In many cases, the list will contain a single element.
Then, when lean wants to synthesize C t, first it puts t in weak-head-normal-form assuming any head symbol in the mapping M is opaque. That is, the normalization will stop as soon as the head symbol of t is a key in the mapping M.
Then, we extract from M the list of candidate instances and try only them. 
This will reduce the number of instances that need to be tried for each sub-problem.
Second, the opposite category loop will not happen anymore. In this new approach, the opposite instance would only be considered when we are trying to synthesize the opposite category. That is, the “opposite” operator occurs in t.
Remark: the actual implementation is more complicated because a type-class may have multiple parameters.

**Comment by leodemoura** [comment]
Remark: to take full advantage of keyed matching, we need to refactor the standard library. 
For example, we have many decidable equality instances. The head symbol of all of them is `=`.
So, keyed matching will not help much in this case. 
However, we can define a new type class: `decidable_eq`, and add the following instance for the `decidable` type class.

``` lean
definition has_decidable_eq [instance] {A : Type} [h : decidable_eq A] 
           : forall x y, decidable (x = y) :=
...
```

Now, the `decidable` class has a single instance with head symbol `=`. And the `decidable_eq` class has instances with head symbols such as: `nat`, `int`, `prod`, `sum`, `list`, ...

**Comment by fpvandoorn** [comment]
This sounds very useful, and I think this heuristic is good. This sounds as if it will significantly speed up the type class inference. The `decidable_eq` class sounds very natural to me.

I hope the transition is not too painful, maybe we're using the fact that we can currently unfold elements of the mapping M.

I'm not sure how this would solve the looping for the opposite category. The definition of opposite category is

``` lean
definition opposite [reducible] {ob : Type} (C : precategory ob) : precategory ob
```

Currently it's not an instance (it's not yet needed), but if it was, I don't think that looking at the head would help, since the head (`ob`) is just a variable.

**Comment by leodemoura** [comment]
> I hope the transition is not too painful, maybe we're using the fact that we can currently unfold elements of the mapping M.

Me too :-)

> I'm not sure how this would solve the looping for the opposite category.

Perhaps I'm imagining things, but I thought we had an instance that given `C : Category` would produce `Cᵒᵖ`.

**Comment by leodemoura** [comment]
We have added a new type class resolution procedure in the module type_context
