### ISSUE TITLE
lemmas not working if put into fin namespace

### ISSUE THREAD

**Issue by htzh** [leanprover/lean3#735]
For some reason the following lemmas only work if I keep them outside the fin namespace. I would like to migrate them to fin but they have problems compiling in the fin namespace.

https://github.com/leanprover/lean/blob/a04c6b0c7dbdd8253c833bba581ccede6e3b82d5/library/theories/group_theory/cyclic.lean#L275-L293

**Comment by leodemoura** [comment]
Recall that in the namespace `fin`, `succ` is always a reference to `fin.succ`.
This is why the proof breaks. We can fix the issue by using `nat.succ` or defining a local notation.
In the commit above, I used a local notation.
