### ISSUE TITLE
repeat alternatives crashes lean.exe

### ISSUE THREAD

**Issue by digama0** [leanprover/lean3#737]
When I open data/real/basic.lean in lean-emacs on windows, I get a message from windows saying "lean.exe has stopped working" every few seconds, presumably because emacs restarts the process. Some judicious commenting of the file traces the problem down to the line

repeat (apply rat.mul_pos | apply rat.add_pos | apply inv_pos | apply rat_of_pnat_is_pos),

in a tactic script. Tested on a99c44b, here is the output if you comment out everything after line 603 of data/real/basic.lean:

-_\- mode: compilation; default-directory: "c:/lean/library/data/real/" -_-
Compilation started at Fri Jul 24 01:18:56

"c:/lean/bin/lean.exe" -Dpp.width=120  "c:/lean/library/data/real/basic.lean"
c:/lean/library/data/real/basic.lean:30:32: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:36:76: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:55:73: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:80:2: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:83:45: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:85:93: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:87:79: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:90:63: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:94:65: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:97:2: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:99:80: warning: using 'sorry'
c:/lean/library/data/real/basic.lean:168:13: warning: using 'sorry'

Compilation exited abnormally with code 5 at Fri Jul 24 01:19:00

Commenting out line 603 as well causes lean to successfully parse the file (with errors due to the unfinished proofs).

**Comment by digama0** [comment]
After more testing, I found that although
        repeat (apply rat.mul_pos | apply rat.add_pos | apply inv_pos | apply rat_of_pnat_is_pos),
causes the bug, the (apparently equivalent) version
        repeat (apply rat.mul_pos | apply rat.add_pos | apply rat_of_pnat_is_pos | apply inv_pos),
does not. Furthermore, the same bug is triggered a few lines later, with the command
        repeat apply inv_pos,
Oddly enough, the same command works correctly just before, from a similar proof state. On line 611:

s t : ℕ+ → ℚ,
Hs : regular s,
Ht : regular t,
a b c j n : ℕ+,
Hn : pceil ((rat_of_pnat (K s) \* (b⁻¹ + c⁻¹) + (a⁻¹ + c⁻¹) \* rat_of_pnat (K t)) \* rat_of_pnat j) ≤ n
⊢ 0 < b⁻¹

⊢ 0 < c⁻¹

⊢ 0 < (a⁻¹ + c⁻¹) \* rat_of_pnat (K t)

⊢ 1 / ((rat_of_pnat (K s) \* (b⁻¹ + c⁻¹) + (a⁻¹ + c⁻¹) \* rat_of_pnat (K t)) \* rat_of_pnat j) \* (rat_of_pnat
     (K s) \* (b⁻¹ + c⁻¹) + (a⁻¹ + c⁻¹) \* rat_of_pnat (K t)) ≤ j⁻¹

Applying "repeat apply inv_pos" at this point discharges the first two subgoals as expected. On line 614, an almost identical proof state:

s t : ℕ+ → ℚ,
Hs : regular s,
Ht : regular t,
a b c j n : ℕ+,
Hn : pceil ((rat_of_pnat (K s) \* (b⁻¹ + c⁻¹) + (a⁻¹ + c⁻¹) \* rat_of_pnat (K t)) \* rat_of_pnat j) ≤ n
⊢ 0 < a⁻¹

⊢ 0 < c⁻¹

⊢ rat_of_pnat (K t) > 0

⊢ 1 / ((rat_of_pnat (K s) \* (b⁻¹ + c⁻¹) + (a⁻¹ + c⁻¹) \* rat_of_pnat (K t)) \* rat_of_pnat j) \* (rat_of_pnat
     (K s) \* (b⁻¹ + c⁻¹) + (a⁻¹ + c⁻¹) \* rat_of_pnat (K t)) ≤ j⁻¹

but "repeat apply inv_pos" triggers a crash here.

**Comment by leodemoura** [comment]
Dear Mario,

Thanks for reporting the issue.
I believe this is a bug in the background lean process that dynamically generates type and auto-completion information. I believe we didn't notice the problem before because the process is silently restarted on Linux and OS X and Rob uses OS X. 

This kind of problem is hard to reproduce because it depends on the sequence of actions performed by the user. We have a "debug mode" in emacs. It traces the communication between Lean and Emacs.
We can activate it using `M-x lean-turn-on-debug-mode`. 
The trace will be stored in the buffer `*lean-server-standard-trace*`. 

If you also know a small sequence of actions (in Emacs) that deterministically triggers the bug, please post it here. I'm currently trying to produce a small sequence that triggers the problem.

Thanks,
Leo

**Comment by digama0** [comment]
The test I describe (comment everything after line 602/603 of data/real/basic.lean except for "end" lines so it compiles) deterministically reproduces the bug, although I have not tried to make a MWE since GitHub doesn't seem to accept attachments (I can email you my test files if you want). Furthermore, I think emacs is not involved, since I can also see the problem if I run "Lean > execute Lean": if I am not triggering the bug it gives several errors for the incomplete proof and returns error code 1, but with the bug it quits halfway through processing with error code 5 (or sometimes 255 if it takes too long).

**Comment by leodemoura** [comment]
I didn't manage to reproduce the problem yet.
I'm using the following file: https://gist.github.com/leodemoura/9bf7ac7808232bbee878
I tried on Windows/MSYS2 and Linux.
I'm using https://github.com/leanprover/lean/commit/a99c44b644f0afb1650ef647d41e9ae1f2327686

> I can email you my test files if you want

This would be very useful!

> Furthermore, I think emacs is not involved, since I can also see the problem if I run "Lean > execute Lean"

This is good news.
It is usually much easier to fix the problem when emacs is not involved.

Thanks,
Leo

**Comment by leodemoura** [comment]
I just fixed a bug that was preventing you from using `repeat apply inv_pos` in a couple of places at `data/real/basic.lean`.

**Comment by digama0** [comment]
Looks like your bug fix solved the problem (both in the alternatives and in `repeat apply inv_pos` ). BTW your test file correctly reproduces the bug; if I pass the file to lean.exe in the console it segfaults. Perhaps it should be added to your test base.

**Comment by leodemoura** [comment]
> Perhaps it should be added to your test base.

Good point. I added it.
