### ISSUE TITLE
compile quick reference separately

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#746]
- [x] compile the reference manual separately, 
- [x] link to it from the main Lean documentation page

**Comment by soonhokong** [comment]
@avigad, I sent you an email regarding this.

**Comment by avigad** [comment]
It is perfect. I will add a link to the leanprover.github.io page today (Helsinki time -- it is early morning here). I will also expand the reference today to add some new proof syntax that Leo has added.

Will the quick reference also appear in the online tutorial, as one of the chapters? I think it will look o.k. there.

**Comment by soonhokong** [comment]
Dear @avigad,

> It is perfect. I will add a link to the leanprover.github.io page today (Helsinki time -- it is early morning here). I will also expand the reference today to add some new proof syntax that Leo has added.

Great. https://travis-ci.org is pretty slow nowadays and I guess it might take 10 ~ 15 hours to process my updates. Anyway, the link - http://leanprover.github.io/tutorial/quickref.pdf - will be available sooner or later.

> Will the quick reference also appear in the online tutorial, as one of the chapters? I think it will look o.k. there.

Yes, I've fixed it as well. Because of the same reason, it's not available now. But you will see something like the screenshot soon.

![screen shot 2015-07-28 at 7 24 53 pm](https://cloud.githubusercontent.com/assets/403281/8948668/60529092-355e-11e5-9597-78b569f0bea8.png)

**Comment by avigad** [comment]
Excellent. It would be nicer if the sections were numbered "A1, A1.1, A1.2,
..." but maybe that is hard? It is not a big deal.

**Comment by soonhokong** [comment]
> Excellent. It would be nicer if the sections were numbered "A1, A1.1, A1.2, ..." but maybe that is hard? It is not a big deal.

Fixed.

![screen shot 2015-07-28 at 7 57 02 pm](https://cloud.githubusercontent.com/assets/403281/8949010/d6c9e294-3562-11e5-80d3-f2176b0b8d5f.png)

**Comment by avigad** [comment]
Great!

**Comment by soonhokong** [comment]
Dear @avigad,

The quickref pdf file is available at https://leanprover.github.io/tutorial/quickref.pdf. Could you edit https://github.com/leanprover/leanprover.github.io/blob/master/documentation/index.md file to link the quickref.pdf file from there?

**Comment by avigad** [comment]
@soonhokong Once again, I already did this in the pull request I issued yesterday:

https://github.com/leanprover/leanprover.github.io/pull/36

Aren't the pull requests sent to you automatically? (Maybe you have been too busy fixing bugs to notice it?)

**Comment by soonhokong** [comment]
@avigad, somehow I missed it. I just merged your pull-request. Thank you!

**Comment by avigad** [comment]
No problem. I just wanted to make sure I was doing it right. Thanks!
