### ISSUE TITLE
metavariables in displayed goal

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#755]
In [this gist](https://gist.github.com/fpvandoorn/75f20b0fee0682a7f8e6), when hovering over the comma after `exact f (tr a)` on line 57 and then pressing `C-c C-g` I get

``` lean
position 57:52
A : Type,
B : Type,
f : one_step_tr A → B
⊢ Π (x y : A),
    ?M_1 = ?M_1
```

However, `*lean-info*` shows the goal without metavariables (as expected):

``` lean
A : Type,
B : Type,
f : one_step_tr A → B
⊢ Π (x y : A),
    f (tr x) = f (tr y)
```

**Comment by soonhokong** [comment]
Leo will handle this.. BTW, we're thinking about getting rid of `*lean-info*` since `*Lean-Goal*` is doing exactly the same thing.

**Comment by fpvandoorn** [comment]
Yes, eventually we can get rid of it. But let's keep it for a couple more weeks until we're quite sure `*Lean-Goal*` works correctly.

**Comment by soonhokong** [comment]
> Yes, eventually we can get rid of it. But let's keep it for a couple more weeks until we're quite sure _Lean-Goal_ works correctly.

:+1:

**Comment by robertylewis** [comment]
They don't do exactly the same thing, do they? _Lean-Goal_ displays only the first goal, while _lean-info_ displays all remaining goals. I've had a lot of trouble with _lean-info_ being unreliable (this has come up in a few issue threads). But when it's working, being able to see all remaining goals is nice.

Maybe _Lean-Goal_ could do the same thing- print the context for the current goal, and list the remaining goals without contexts below? Then I'd be happy to forget about _lean-info_.

**Comment by leodemoura** [comment]
> They don't do exactly the same thing, do they? Lean-Goal displays only the first goal, while lean-info displays all remaining goals. 

I will make the change and display all goals in the buffer "_Lean Goal_"

**Comment by fpvandoorn** [comment]
That is indeed nicer :+1:
