### ISSUE TITLE
print definitions by keyboard shortcut

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#756]
It would be nice to have a keyboard shortcut which prints the information of the identifier/notation you're hovering over (exactly the same as the `print` command). So in the following example

``` lean
import data.int
open nat int
example (n : nat) : n + n = n + n :=
rfl
```

if I hover over the type `nat` and press the keyboard shortcut, I get

``` lean
inductive nat : Type₁
constructors:
nat.zero : ℕ
nat.succ : ℕ → ℕ
```

if I hover over `+` I get

``` lean
_ `+`:65 _:65 :=
  | nat.add #1 #0
  | [priority 999] int.add #1 #0
```

and if I hover over `rfl` I get

``` lean
definition rfl : ∀ {A : Type} {a : A}, a = a :=
eq.refl
```

This feature does not need to know the elaborated term, I want the output just as if I typed `print <identifier>` or `print <token>` (because I want to see all possible overloads, not just the one which was applicable here). It would be great if this keyboard shortcut also works in a definition which is _not_ accepted yet (for example because it contains a mismatched application).

I don't care too much about whether the information is displayed in the minibuffer and is lost after I move the point, or whether there is a persisting buffer which keeps this information visible for a while. 

Examples of uses:
- Quickly look-up the number of explicit (or implicit) arguments of a definition or the order of these arguments
- Look whether some notation/definition is overloaded in your term (the minibuffer doesn't always show information in tactic proofs, e.g. the terms inside the following `unfold`)

``` lean
import data.int
open nat int
example (n : nat) : n + n = 2 * n :=
begin
  unfold [nat.add,mul]
end
```

**Comment by soonhokong** [comment]
@fpvandoorn, the feature is pushed to the repo. For now, the keybinding for the feature is <kbd>C-c</kbd><kbd>C-p</kbd>.

**Comment by fpvandoorn** [comment]
:+1: I just wanted to say that this feature is very nice. I'm using this a lot already!

**Comment by soonhokong** [comment]
:+1:
