### ISSUE TITLE
autocompletion for `import`

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#766]
I think autocompletion for `import` doesn't work anymore.
Example: open empty `.lean` file and type

``` lean
import data
```

and press `<TAB>`. Emacs freezes for me. I have to press `Ctrl-g`.

@avigad does it work for you?

**Comment by fpvandoorn** [comment]
It works for me. 

Does it still fail after running `M-x lean-server-restart-all-processes`?

**Comment by leodemoura** [comment]
@fpvandoorn Yes, it does. I think there is something wrong with my Emacs.
The syntax-highlight is also failing when the last character in the buffer is a unicode one (e.g., λ).

**Comment by avigad** [comment]
Yes, it seems to work fine for me. I had forgotten that we even had tab completion for imports. I will add something to the tutorial and the quick reference. We have tab completion for:

o identifiers (when writing a theorem or definition, or after check, etc.)
o imports (after import)
o options (after set_option)

Am I missing any others?

Yesterday, after I returned from Helsinki, my Emacs mode would not start. It seems that my Emacs was not using an up-to-date version of Flycheck. @soonhokong diagnosed the problem, gave me a line to add to my .emacs file, and updated the documentation. It is the third line here, the one that starts with "when".

  https://github.com/leanprover/lean/blob/master/src/emacs/README.md#installation

Maybe that will help?

I also had an issue with unicode fonts, which was easy to fix, but I have a suggestion that might make it easier for users. I will open an issue on the leanprover.github.io page for discussion.

**Comment by leodemoura** [comment]
I explored it a little bit more. 
The auto-completion works when I press `<TAB>` in a file located at `library` or `hott` folders.
The problem only happens when I'm editing a file in other directories (example: the `examples` folder used in the CADE tutorial).

**Comment by avigad** [comment]
It works for me even in my work directory, outside the library folders.

**Comment by soonhokong** [comment]
I'll try to reproduce this tonight.

**Comment by soonhokong** [comment]
@leodemoura, could you check whether you can reproduce this problem even after restarting the lean-server in emacs?

**Comment by leodemoura** [comment]
> @leodemoura, could you check whether you can reproduce this problem even after restarting the lean-server in emacs?

Yes, I can reproduce it consistently. I restarted emacs, the server, etc.
If I open a file outside of the library and hott directories, then Emacs always freeze when I try to autocomplete an import.

**Comment by soonhokong** [comment]
@leodemoura, thanks for checking it up. I've tried to reproduce but failed to succeed. Could you give me your environment? I guess you're using OSX (if not, please let me know). What's your emacs version?

**Comment by leodemoura** [comment]
Yes, I'm using OS X. The emacs version is 
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

It is super weird, I'm having all sorts of problems with the lean-mode. I described the syntax highlight problem above. The regular autocompletion is also failing all the time. 
Even flycheck is working unreliably on my machine. Sometimes flycheck takes a long time to update the red marks. The problem is not on the lean since since Lean can process the file in less than 1 sec.

**Comment by leodemoura** [comment]
Extra information: it seems the 'import' autocompletion problem only happens when the `.lean` file is located in the build directory. 
I use the following build dir: `~/projects/lean/build/release`.

**Comment by soonhokong** [comment]
That should help. I will check.

**Comment by avigad** [comment]
Yimu, who I e-mailed you about few days ago, is using OS/X on a not-very-new Macbook Air. I think I noticed that Emacs mode was slow to provide type information. His office is up the hall from mine; Soonho, I am sure he would be happy to let you experiment with his laptop when you come by tomorrow.

**Comment by soonhokong** [comment]
> Yimu, who I e-mailed you about few days ago, is using OS/X on a not-very-new Macbook Air. I think I noticed that Emacs mode was slow to provide type information. His office is up the hall from mine; Soonho, I am sure he would be happy to let you experiment with his laptop when you come by tomorrow.

I see. I'll test [byte compilation](http://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html) tonight. Let's see how this improve the performance on his machine.

**Comment by soonhokong** [comment]
> The syntax-highlight is also failing when the last character in the buffer is a unicode one (e.g., λ)

I can reproduce this problem. I opened #773.

**Comment by soonhokong** [comment]
> Extra information: it seems the 'import' autocompletion problem only happens when the .lean file is located in the build directory. 
> I use the following build dir: ~/projects/lean/build/release.

@leodemoura, I can't reproduce this problem yet:
- I'm using OSX 10.10.4
- I'm using the same version of emacs that you're using, `GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org`. This is downloaded from http://emacsformacosx.com site.

I want to see the communication between emacs and lean. Could you do the following for me?
- Start emacs. Open a `.lean` file to reproduce
- <kbd>M-x</kbd>`lean-debug-mode` to enable `lean-debug-mode`
- Try auto-completion in the buffer (which should fail)
- Visit `*lean-debug*` buffer, please send me the contents of the buffer.

It might be the case that you have more than one version of Lean in the system, and not the right one is being used in emacs. Could you give me the following information to check?
- Press <kbd>C-h</kbd><kbd>v</kbd>`lean-root`, it will show the value of `lean-root` variable.
- Press <kbd>C-c</kbd><kbd>C-l</kbd>, it will show the full path of lean binary that emacs is using. For example, I have `/Users/soonhok/work/lean/bin/lean`
- Press <kbd>M-x</kbd>`list-processes`, it will show the list of processes in emacs. There should be an entry for `lean-server`, could you let me know the `Command` part of the line? For me, I have `/Users/soonhok/work/lean/bin/lean --lean --server`.

Also please make sure that you don't have lean installed by homebrew. You can remove it by running `brew remove lean` (if it was installed). If you run `brew info lean`, it should either give you an error or lines including "not installed".

**Comment by leodemoura** [comment]
Here is the output from _lean-debug_

```
06:43:57.794 -- after-change-function
06:43:57.794 -- before-text: 
06:43:57.794 -- after-text: i
06:43:58.114 -- after-change-function
06:43:58.114 -- before-text: 
06:43:58.114 -- after-text: m
06:43:58.423 -- after-change-function
06:43:58.423 -- before-text: 
06:43:58.423 -- after-text: p
06:43:58.663 -- after-change-function
06:43:58.663 -- before-text: 
06:43:58.663 -- after-text: o
06:43:58.747 -- after-change-function
06:43:58.747 -- before-text: 
06:43:58.747 -- after-text: r
06:43:58.974 -- after-change-function
06:43:58.974 -- before-text: 
06:43:58.974 -- after-text: t
06:43:59.090 -- after-change-function
06:43:59.090 -- before-text: 
06:43:59.090 -- after-text:  
06:43:59.939 -- after-change-function
06:43:59.939 -- before-text: 
06:43:59.939 -- after-text: t
06:44:00.448 -- get-info-record-at-point: (INFO 1 nil)
06:44:00.449 -- send-cmd-async: INFO 1
06:44:00.449 -- send-cmd-async: queue len = 1
06:44:00.449 -- send-cmd-async: REPLACE 1
06:44:00.449 -- send-cmd-async: queue len = 1
06:44:00.449 -- Sent Message:
REPLACE 1
import t

06:44:00.449 -- Sent Message:
INFO 1

06:44:00.450 -- send-cmd-async: added to INFO the queue, queue size = 2
06:44:00.450 -- send-cmd-async: call handler
06:44:00.450 -- set-timer-for-event-handler
06:44:00.454 -- Received Message:
-- BEGININFO STALE NAY
-- ENDINFO


06:44:00.502 -- after-change-function
06:44:00.502 -- before-text: t
06:44:00.502 -- after-text: 
06:44:00.579 -- after-change-function
06:44:00.579 -- before-text: 
06:44:00.579 -- after-text: d
06:44:01.092 -- get-info-record-at-point: (INFO 1 nil)
06:44:01.092 -- send-cmd-async: INFO 1
06:44:01.092 -- send-cmd-async: queue len = 2
06:44:01.092 -- send-cmd-async: REPLACE 1
06:44:01.092 -- send-cmd-async: queue len = 2
06:44:01.092 -- Sent Message:
REPLACE 1
import d

06:44:01.093 -- Sent Message:
INFO 1

06:44:01.093 -- send-cmd-async: added to INFO the queue, queue size = 3
06:44:01.093 -- send-cmd-async: call handler
06:44:01.093 -- set-timer-for-event-handler
06:44:01.097 -- after-change-function
06:44:01.097 -- before-text: 
06:44:01.097 -- after-text: a
06:44:01.118 -- Received Message:
-- BEGININFO STALE NAY
-- ENDINFO


06:44:01.352 -- after-change-function
06:44:01.352 -- before-text: 
06:44:01.352 -- after-text: t
06:44:01.627 -- after-change-function
06:44:01.627 -- before-text: 
06:44:01.627 -- after-text: a
06:44:01.827 -- after-change-function
06:44:01.827 -- before-text: 
06:44:01.827 -- after-text: .
06:44:19.200 -- get-info-record-at-point: (INFO 1 nil)
06:44:19.201 -- send-cmd-async: INFO 1
06:44:19.201 -- send-cmd-async: queue len = 3
06:44:19.201 -- send-cmd-async: REPLACE 1
06:44:19.201 -- send-cmd-async: queue len = 3
06:44:19.201 -- Sent Message:
REPLACE 1
import data.

06:44:19.201 -- Sent Message:
INFO 1

06:44:19.202 -- send-cmd-async: added to INFO the queue, queue size = 4
06:44:19.202 -- send-cmd-async: call handler
06:44:19.202 -- set-timer-for-event-handler
06:44:19.204 -- Received Message:
-- BEGININFO STALE NAY
-- ENDINFO


06:44:19.308 -- The following pre-message will be thrown away:
06:44:19.308 -- 
06:44:19.308 -- process-message-with-cont: type = INFO, cmd-type = INFO
06:44:19.308 -- process-message-with-cont: body
-----
-- BEGININFO STALE NAY
-- ENDINFO
-----

06:44:19.308 -- Process: INFO
06:44:19.308 -- executing continucation for get-info-record-at-point 0: NAY DETECTED
06:44:19.308 -- event-handler: processed. now the queue size = 3

06:44:19.308 -- set-timer-for-event-handler
06:44:19.413 -- The following pre-message will be thrown away:
06:44:19.413 -- 

06:44:19.413 -- process-message-with-cont: type = INFO, cmd-type = INFO
06:44:19.413 -- process-message-with-cont: body
-----
-- BEGININFO STALE NAY
-- ENDINFO
-----

06:44:19.414 -- Process: INFO
06:44:19.414 -- executing continucation for get-info-record-at-point 0: NAY DETECTED
06:44:19.414 -- event-handler: processed. now the queue size = 2

06:44:19.414 -- set-timer-for-event-handler
06:44:19.515 -- The following pre-message will be thrown away:
06:44:19.515 -- 

06:44:19.515 -- process-message-with-cont: type = INFO, cmd-type = INFO
06:44:19.515 -- process-message-with-cont: body
-----
-- BEGININFO STALE NAY
-- ENDINFO
-----

06:44:19.515 -- Process: INFO
06:44:19.515 -- executing continucation for get-info-record-at-point 0: NAY DETECTED
06:44:19.515 -- event-handler: processed. now the queue size = 1

06:44:19.515 -- set-timer-for-event-handler
06:44:20.018 -- get-info-record-at-point: (INFO 1 nil)
06:44:20.018 -- send-cmd-async: INFO 1
06:44:20.018 -- send-cmd-async: queue len = 1
06:44:20.018 -- Sent Message:
INFO 1

06:44:20.018 -- send-cmd-async: added to INFO the queue, queue size = 2
06:44:20.019 -- send-cmd-async: call handler
06:44:20.019 -- set-timer-for-event-handler
06:44:20.020 -- Received Message:
-- BEGININFO
-- ENDINFO


06:45:53.814 -- get-info-record-at-point: (INFO 1 nil)
06:45:53.854 -- send-cmd-async: INFO 1
06:45:53.854 -- send-cmd-async: queue len = 2
06:45:53.855 -- Sent Message:
INFO 1

06:45:53.855 -- send-cmd-async: added to INFO the queue, queue size = 3
06:45:53.855 -- send-cmd-async: call handler
06:45:53.855 -- set-timer-for-event-handler
06:45:53.856 -- Received Message:
-- BEGININFO
-- ENDINFO


06:45:53.961 -- The following pre-message will be thrown away:
06:45:53.961 -- 

06:45:53.961 -- process-message-with-cont: type = INFO, cmd-type = INFO
06:45:53.961 -- process-message-with-cont: body
-----
-- BEGININFO STALE NAY
-- ENDINFO
-----

06:45:53.961 -- Process: INFO
06:45:53.962 -- executing continucation for get-info-record-at-point 0: NAY DETECTED
06:45:53.962 -- event-handler: processed. now the queue size = 2

06:45:53.962 -- set-timer-for-event-handler
06:45:54.068 -- The following pre-message will be thrown away:
06:45:54.068 -- 

06:45:54.068 -- process-message-with-cont: type = INFO, cmd-type = INFO
06:45:54.068 -- process-message-with-cont: body
-----
-- BEGININFO
-- ENDINFO
-----

06:45:54.068 -- Process: INFO
06:45:54.069 -- executing continucation for get-info-record-at-point: OK
06:45:54.069 -- event-handler: processed. now the queue size = 1

06:45:54.069 -- set-timer-for-event-handler
```

**Comment by leodemoura** [comment]
Here is the output I get for a `.lean` file that is not located in the build directory (and emacs does not hang).

```
06:50:34.104 -- lean-server process [standard] #<process lean-server-standard> is created
06:50:34.104 -- send-cmd-async: VISIT "/Users/leodemoura/tmp/tst3.lean"
06:50:34.104 -- send-cmd-async: queue len = 0
06:50:34.105 -- Sent Message:
VISIT /Users/leodemoura/tmp/tst3.lean

06:50:34.105 -- Delete cache file /Users/leodemoura/tmp/tst3.clean
06:50:34.105 -- after-change-function
06:50:34.106 -- before-text: 
06:50:34.106 -- after-text: i
06:50:34.361 -- after-change-function
06:50:34.361 -- before-text: 
06:50:34.361 -- after-text: m
06:50:34.590 -- after-change-function
06:50:34.590 -- before-text: 
06:50:34.590 -- after-text: p
06:50:34.793 -- after-change-function
06:50:34.793 -- before-text: 
06:50:34.793 -- after-text: o
06:50:34.837 -- after-change-function
06:50:34.837 -- before-text: 
06:50:34.837 -- after-text: r
06:50:35.048 -- after-change-function
06:50:35.048 -- before-text: 
06:50:35.048 -- after-text: t
06:50:35.124 -- after-change-function
06:50:35.124 -- before-text: 
06:50:35.124 -- after-text:  
06:50:35.308 -- after-change-function
06:50:35.308 -- before-text: 
06:50:35.308 -- after-text: d
06:50:35.533 -- after-change-function
06:50:35.533 -- before-text: 
06:50:35.533 -- after-text: a
06:50:35.796 -- after-change-function
06:50:35.796 -- before-text: 
06:50:35.796 -- after-text: t
06:50:36.038 -- after-change-function
06:50:36.038 -- before-text: 
06:50:36.038 -- after-text: a
06:50:36.122 -- after-change-function
06:50:36.122 -- before-text: 
06:50:36.122 -- after-text: .
06:50:38.074 -- after-change-function
06:50:38.074 -- before-text: data.
06:50:38.074 -- after-text: 
06:50:38.075 -- after-change-function
06:50:38.075 -- before-text: 
06:50:38.075 -- after-text: data.vector
```

**Comment by leodemoura** [comment]
I have only one version on my system, and I did not install lean using brew.
 C-hv `lean-root` produces

```
lean-rootdir is a variable defined in `lean-settings.el'.
Its value is "~/projects/lean"
```

**Comment by leodemoura** [comment]
When I press C-cC-l for a .lean file, I get

```
/Users/leodemoura/projects/lean/bin/lean -Dpp.width=120  /Users/leodemoura/projects/lean/build/release/t.lean
```

**Comment by leodemoura** [comment]
> Press M-xlist-processes, it will show the list of processes in emacs. 

I get

``` lean
lean-server-... run     *lean-server... --           /Users/leodemoura/projects/lean/bin/lean --lean --server
```

**Comment by leodemoura** [comment]
`brew info lean` produces

```
Error: No available formula for lean
```

**Comment by soonhokong** [comment]
@leodemoura, thanks for all the information. I found a way to reproduce the problem.

**Comment by soonhokong** [comment]
@leodemoura, I'm pretty sure that it's because of [f-files](https://github.com/rejeep/f.el#f-files-path-optional-fn-recursive) function that we're using at https://github.com/leanprover/lean/blob/master/src/emacs/lean-company.el#L60-L62 .

To make sure, could you do the following on your emacs?
- Visit `*scratch*` buffer
- eval the following elisp code:
  
  ``` lisp
  (require 'f)
  (f--files "~/projects/lean/build/release" (equal (f-ext it) "lean") t)
  ```

It's supposed to return all `.lean` files under `~/projects/lean/build/release` directory. I guess it will hang on your machine.

**Comment by leodemoura** [comment]
> It's supposed to return all .lean files under ~/projects/lean/build/release directory. I guess it will hang on your machine.

Yes, you are correct. It hangs.

**Comment by soonhokong** [comment]
So it's an upstream performance issue. Ideally, `f-files` function should use the predicate while collecting files. Unfortunately, that is not the case in implementation. It's using [f--collect-entries](https://github.com/rejeep/f.el/blob/master/f.el#L416-L435) function which collect **ALL** files under a directory, then it filters files using a given predicate.

We can guess that in many cases, the first pass (collecting all files) does not scale.

**Comment by soonhokong** [comment]
I will write a better version of the function, and use it in lean-mode. Then, I'll make a pull-request to the upstream. In the meantime, please avoid using the auto-completion for import where you have too many files.. I feel really bad to say this...

**Comment by soonhokong** [comment]
Some remarks:
1. auto-completion for import first finds all `.lean` files under `lean/library` folder. Then all `.lean` files under the current directory (recursively). I think the second part should be done recursively only if it has `.project` file in the directory (or its parent directories). @leodemoura, does it make sense?
2. Bad news is that elisp only provide a single function - [directory-files](http://www.gnu.org/software/emacs/manual/html_node/elisp/Contents-of-Directories.html). It allows us to pass a regex but to search recursively we have no choice to grep all entries to collect directories. Now, I understand why `f.el` is implemented in the current way..
3. We need a timer to kill this file traversal in emacs...

**Comment by leodemoura** [comment]
> @leodemoura, does it make sense?

Yes, it makes total sense.

**Comment by soonhokong** [comment]
@leodemoura, I've added a timeout to auto-completion for import. It should generates a message when it reaches a timeout. Here is an example:

```
finding files under /Users/soonhok/work/lean/library/...
finding files under /Users/soonhok/work/... timeout (1 sec)   <--
```

In this case, only the files under `/Users/soonhok/work/lean/library` directory are used for auto-completion.

Custom variable `lean-company-import-timeout` is added, it's the time that we assign for `lean-find-files`. Its default value is 1 second but can be customized.
