### ISSUE TITLE
C-c C-g temp-file in HoTT

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#767]
The temp-file solution for `C-c C-g` is not working correctly for HoTT yet. If I don't save my buffer manually now, my `*Lean Goal*` buffer is empty.

**Steps to reproduce.**

1) Copy paste the following in an empty `.hlean` file

``` lean
example : nat :=
begin

end
```

2) Move cursor to empty line and press `C-c C-g`
3) Now save this buffer and press `C-c C-g` again

**Output**

Step 2 gives empty `*Lean Goal*` buffer, step 3 gives the correct `*Lean Goal*` buffer.

**Comment by fpvandoorn** [comment]
Note: when my file is unsaved (in HoTT mode) and I press `C-c C-p` the buffer is also empty.

**Comment by leodemoura** [comment]
I managed to reproduce the problem. @soonhokong I believe the problem is the Emacs code.
That is, `lean.exe` is producing the right information.

**Comment by soonhokong** [comment]
I see. I will fix it today.
