### ISSUE TITLE
syntax-highlight is failing when the last character in the buffer is a unicode one (e.g., λ)

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#773]
https://github.com/leanprover/lean/issues/766#issuecomment-127576213

This is related with [mmm-mode](https://github.com/purcell/mmm-mode).
## How to reproduce

``` lean
import algebra.field

λ
```
## Symptom
- No syntax highlighting
- Error message

```
Error running timer `mmm-mode-idle-reparse': 
```

**Comment by soonhokong** [comment]
@leodemoura, I think this is an upstream issue handling unicode. As a quick fix, please comment the following lines:

https://github.com/leanprover/lean/blob/master/src/emacs/lean-mode.el#L28
https://github.com/leanprover/lean/blob/master/src/emacs/lean-mode.el#L306

**Comment by soonhokong** [comment]
@leodemoura, this problem is related to font-lock rules in `lean-syntax.el` file. I've made done some refactoring of the file. Could you test https://github.com/soonhokong/lean/commit/6de8c1bc9dd7b6d98237153977cb57fbdce60644 ?
- Please check that this mmm-mode problem is resolved by this change.
- Please check that it doesn't break previously working font-lock features. (I've fixed some problems, i.e. `by+`)

**Comment by leodemoura** [comment]
@soonhokong I tested it. The problem is gone. Thanks!

**Comment by soonhokong** [comment]
@leodemoura, thank you. I'll merge my commit into the blessed repo.

**Comment by leodemoura** [comment]
I have already merged it.

**Comment by soonhokong** [comment]
Oh. I just found that.
