### ISSUE TITLE
function definition with example

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#774]
Minor bug: I think you cannot do recursive applications with the function definition package using examples.

``` lean
open nat
example : ℕ → ℕ → Prop
| 0 0               := true
| (succ n) 0        := false
| 0 (succ m)        := false
| (succ n) (succ m) := example n m 
```

gives `invalid expression, unexpected token`

**Comment by avigad** [comment]
I find that error message natural. On the last line, what is expected is not the keyword "example" but the name of the function you are defining (which doesn't have a name).

**Comment by fpvandoorn** [comment]
I agree that there should be an error message when using `example` as a name of something, but the problem is that the "induction hypothesis" is called `example`. 

You can see this if you write

``` lean
open nat
example : ℕ → ℕ → Prop
| 0 0               := true
| (succ n) 0        := false
| 0 (succ m)        := false
| (succ n) (succ m) := _
```

the context of the placeholder is

``` lean
example : ℕ → ℕ → Prop,
n m : ℕ
⊢ Prop
```

So if the "induction hypothesis" `example` is renamed to something else, we can define examples by recursion, which might be useful.

**Comment by avigad** [comment]
Ah, interesting. Do you have a suggestion? Maybe `example_function`? Or `example_def`?

**Comment by robertylewis** [comment]
If anything, I would expect to be able to refer to the function with `this`. Isn't that what's used for anonymous definitions elsewhere?

**Comment by avigad** [comment]
Great suggestion. Yes, we now have anonymous "have" and "suppose", etc. See Section 4.6 in the tutorial. (I just noticed a typo, "--END", which I will fix now.)

**Comment by fpvandoorn** [comment]
I also like Rob's suggestion to call it `this`.

**Comment by leodemoura** [comment]
Come on... this kind of nitpicking is getting out of control.

First, there is a simple workaround:

``` lean
open nat
example : ℕ → ℕ → Prop :=
have foo : ℕ → ℕ → Prop
| 0 0               := true
| (succ n) 0        := false
| 0 (succ m)        := false
| (succ n) (succ m) := foo n m,
foo 
```

Second, I try to be flexible and address issues raised here, but I also want to work on interesting things.
This kind of feature doesn't improve the usability of the system in any significant way, but consumes time and increases the complexity of a module that is already very complex.
Of course, I will not oppose if someone decides to implement it.

**Comment by fpvandoorn** [comment]
I might have gone to far with opening issues for small things. But please give me feedback about that. I have a hard time judging what is worth opening an issue for and what is not (to the extend that I sometimes write the issue text and then decide that the thing is too small to open an issue for). Are there previous issues where you thought that they were too small and nitpicky? One I know is #634, where I thought it would be a quick fix. Also, feel free to postpone/close small issues if you think they fall under the "too nitpicky" category.

And secondly, please keep in mind that I don't know the code. For all I knew this issue only involved changing the string "example" to "this" in a couple of places, and would take you 5 minutes to change.

**Comment by avigad** [comment]
I apologize too. Like Floris, I thought that it was just a matter of changing the name of an internally generated variable from `example` to `this`. You just suggested a similar change in #770. I agree that it is not an essential feature.

**Comment by leodemoura** [comment]
> Like Floris, I thought that it was just a matter of changing the name of an internally generated variable from example to this. You just suggested a similar change in #770.

I don't like having tons of open issues. For me, the goal is to have 0 issues.
I try to reduce the number of issues as much as possible.
Little issues like this one are annoying. It is more annoying than #770 because it also break tests.
If we simply replace "example" with "this", the error messages will use "this" instead of "example".
Here is what I had to do to close this issue:

1- Renamed "example" with "this"
2- Run tests, 18 are broken. 
3- Add hack to use the name "example" instead of "this" when type checking examples. 
4- Run tests again, 1 test is still broken.
5- Add another hack for using "example" instead of "this".
6- Run tests again, everything worked.

This is not fun at all. 
I need help for this kind of issue. Please before opening issues like this one, try to solve it by yourself.
