### ISSUE TITLE
universe variables + function definition package

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#777]
In this example a wrong universe variable is assigned to `lift`:

``` lean
-- HoTT
namespace sum
  definition code.{u v} {A : Type.{u}} {B : Type.{v}} : A + B → A + B → Type.{max u v}
  | code (inl a) (inl a') := lift (a = a')
  | code (inr b) (inr b') := lift (b = b')
  | code _       _        := lift empty
end sum
```

Giving some more universe variables explicitly works:

``` lean
-- HoTT
namespace sum
  definition code.{u v} {A : Type.{u}} {B : Type.{v}} : A + B → A + B → Type.{max u v}
  | code (inl a) (inl a') := lift.{u v} (a = a')
  | code (inr b) (inr b') := lift.{v u} (b = b')
  | code _       _        := lift empty
end sum
```

**Comment by leodemoura** [comment]
This issue is not related to the definitional package. The problem is that Lean does not have support for solving universe constraints of the form `max u ?m =?= max u v`.
I add a heuristic that reduces this kind of constraint to `?m =?= v` when the constraint cannot be postponed anymore.
