### ISSUE TITLE
tactic using now

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#780]
I'm probably making a stupid mistake here, but why does the following tactic fail?

``` lean
example (a b c : Prop) (H : b) : a ∨ b ∨ c :=
by repeat (apply or.inl | apply or.inr | assumption); now
```

Shouldn't this work, similar to https://github.com/leanprover/lean/blob/master/tests/lean/run/eassumption.lean?

**Comment by leodemoura** [comment]
The semantics of or-else is "pick the first one that works".
So, it doesn't work for this problem since Lean would not be able to recover from a bad `or.inl` and `or.inr`. You need to use the `append`. 

``` lean
example (a b c : Prop) (H : b) : a ∨ b ∨ c :=
by repeat (append (append (apply or.inl) (apply or.inr)) assumption); now
```

**Comment by fpvandoorn** [comment]
That makes sense. Thanks!
