### ISSUE TITLE
Aliasing of priority namespace

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#789]
The following aliasing seems unnecessary:

https://github.com/leanprover/lean/blob/master/src/frontends/lean/util.cpp#L483

The issue is that the difference between being in a namespace and having available aliases is subtle. I think the following would be confusing:

``` Lean
namespace foo
definition default := (some other number in some other context)
...
notation [priority default] ... := ...
```

since I think users might think they were in the std.priority namespace, but really their own definition would shadow it. Moreover, it would shadow it beyond the possibility of choice, so if their definition did not have the right type there would be an error.

The Lean library code never makes use of this feature anyway, so only tests would need to change.

**Comment by leodemoura** [comment]
Note that we use "overriding" semantics. 
The idea is to make sure the arithmetic operators are not overloaded at `<expr>` in the `[priority <expr>]` annotation. For example, if `<expr>` is `a + 2`, it will be interpreted as `num.add a 2` even if the current context contains many overloads for `+`.
Lean will also refuse `<expr>` if it contains overloaded symbols. 
Lean does not use the elaborator for this kind of expression.

**Comment by dselsam** [comment]
To clarify, I was only concerned with the `open_priority_aliases` part. I think the handling of `num` (overwriting the aliases and failing if anything else is overloaded) is appropriate. I just don't think the priority aliasing is worth the extra complexity.

**Comment by leodemoura** [comment]
Great. I will remove the `open_priority_aliases` hack.
