### ISSUE TITLE
postpone the execution of show-goal (C-c C-g) until a flycheck process is completed

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#790]
See https://github.com/leanprover/lean/issues/788#issuecomment-130026267

**Comment by soonhokong** [comment]
@rlewis1988 opened #788.

**Comment by soonhokong** [comment]
@rlewis1988, could you test https://github.com/soonhokong/lean/commit/4917dcf8961118ccc56192dbef9111d7d6f45990 ?

**Comment by soonhokong** [comment]
If it's working, you see `flycheck-lean is running...` in the mini-buffer. Eventually, you will see `flycheck is over, start lean-process...`.

**Comment by robertylewis** [comment]
It doesn't seem to be any different. I get the same issue as before.

(Note: I'm not in the office anymore, this was a test on my laptop. But it behaves the same as my office computer on the original problem.)

**Comment by soonhokong** [comment]
@rlewis1988, could you confirm that at least the new implementation is triggered? You can check whether `*Messages*` buffer has "flycheck-lean is running..." lines.

**Comment by robertylewis** [comment]
I don't see that in the Messages buffer, no. Is it possible I have something set up wrong in my emacs config that is keeping it from loading your changes?

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)

;; Install required/optional packages for lean-mode
(defvar lean-mode-required-packages
  '(company dash dash-functional flycheck f
            fill-column-indicator s lua-mode mmm-mode))
(let ((need-to-refresh t))
  (dolist (p lean-mode-required-packages)
    (when (not (package-installed-p p))
      (when need-to-refresh
        (package-refresh-contents)
        (setq need-to-refresh nil))
      (package-install p))))

;; Set up lean-root path
(setq lean-rootdir "/Volumes/Storage/Dropbox/lean-bug/lean")  ;; <=== YOU NEED TO MODIFY THIS
(setq-local lean-emacs-path
            (concat (file-name-as-directory lean-rootdir)
                    (file-name-as-directory "src")
                    "emacs"))
(add-to-list 'load-path (expand-file-name lean-emacs-path))
(require 'lean-mode)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(electric-indent-mode nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(setq lean-delete-trailing-whitespace t)

```

**Comment by soonhokong** [comment]
@rlewis1988, please do the followings:
1. Edit a lean-buffer
2. Save the buffer by pressing `C-x C-s`
3. Press `C-c C-g` to invoke `lean-show-goal`

If the time gap between step 2 and step 3 is short enough, you should see the message `flycheck-lean is running...`.

Question: Did you need to save the buffer to reproduce the problem? I'm afraid that the answer is no...?

**Comment by soonhokong** [comment]
The warning message `flycheck-lean is running...` is displayed only if the current buffer is not modified (saved). We don't use a cache with a modified buffer so there shouldn't be any race condition for that case..

**Comment by robertylewis** [comment]
Aha. When the buffer is saved, I see the message `flycheck-lean is running` and the problem goes away. But the problem is still there when the buffer is modified. I guess that means the issue isn't what you thought? :(

**Comment by soonhokong** [comment]
I think this is a different issue...

For a modified buffer, we save this buffer to a temporary file. Note that this temporary file is not saved at the directory of the original file. For example, a modified buffer of `data/int/order.lean` file can be saved at `/var/folders/wz/6j2w2jp510g6b0ty330hqs7r0000gn/T/flymake4181K6Elean`. Maybe this causes this problem.

@rlewis1988, what are the reproducible steps? Can you reproduce the problem with a small example file such as the following?

``` lean
import standard
example (a : ℕ) : a = a := begin
  induction a,
  rewrite [-nat.add_zero],
  apply rfl
end
```

**Comment by robertylewis** [comment]
The reproducible steps are:
- `open data/int/order.lean`
- at the bottom, put in the following example, and don't save:

``` lean
example (n : ℕ) : n = n :=
  begin
    induction n,
    rewrite [-nat.add_zero],
  end
```
- C-c C-G with the cursor anywhere on the line `rewrite [-nat.add_zero]`

I tried earlier to find a small example and struggled. The same example does not cause an issue if you put it at the bottom of `data/int/basic.lean`.

But, I think you're onto something! The first line of order.lean is `import .basic algebra.ordered_ring`. If you change the relative path to an absolute path (`import data.int.basic algebra.ordered_ring`), the issue goes away. I'm not sure why `rewrite [-nat.add_zero]` triggers the problem, but `rewrite rfl` doesn't?

**Comment by soonhokong** [comment]
It turns out that #790 is not really related to #788 . I think #790 itself is handled by 6443de6. I'll merge my commit to blessed.
