### ISSUE TITLE
Error message for level-param mismatch in coercion

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#794]
The following:

``` Lean
constants (A B : Type)
constants (f : A → B) 
attribute f [coercion]
```

yields:

```
 error: invalid coercion, type of 'f' does not match any of the allowed expected types for coercions
  Pi (x_1 : A_1) ... (x_n : A_n) (y: C x_1 ... x_n), D t_1 ... t_m
  Pi (x_1 : A_1) ... (x_n : A_n) (y: C x_1 ... x_n), Type
  Pi (x_1 : A_1) ... (x_n : A_n) (y: C x_1 ... x_n), A -> B
```

The problem is `f`'s extra level corresponding to `B`. The coercion is pruned at

https://github.com/leanprover/lean/blob/master/src/library/coercion.cpp#L327

and it works if we fix the universe of `B`.

The issue is that the error message does not display enough information to diagnose the problem.

**Comment by leodemoura** [comment]
Any help fixing issues will be very welcome :-)

**Comment by fpvandoorn** [comment]
Related issue: #298. 

I agree that a better error message would be nice.

**Comment by dselsam** [comment]
You can assign this one to me.
