### ISSUE TITLE
unfold-full error if fully applied term is still a function

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#801]
``` lean
open nat
definition seq_diagram (A : ℕ → Type) : Type := (Πn, A n → A (succ n))
variables (A : ℕ → Type) (f : seq_diagram A)
include f

definition shift_diag [unfold-full] (k : ℕ) : seq_diagram (λn, A (k + n)) :=
λn a, f (k + n) a

example (n k : ℕ) (b : A (k + n)) : shift_diag A f k n b = sorry :=
begin
  esimp,
end
```

gives

```
invalid 'rewrite' tactic, rewrite step produced type incorrect term
function expected at
  shift_diag A f k n b

proof state:
A : ℕ → Type,
f : seq_diagram A,
n k : ℕ,
b : A (k + n)
⊢ shift_diag A f k n b = sorry
```

Note: I like the fact that `shift_diag` is considered to be "fully applied" if it has 3 arguments, and doesn't also need the two extra arguments after unfolding `seq_diagram`

**Comment by leodemoura** [comment]
I fixed the problem.

> Note: I like the fact that shift_diag is considered to be "fully applied" if it has 3 arguments, and doesn't also need the two extra arguments after unfolding seq_diagram

This is not the semantics of `[unfold-full]`. In the current implementation, `shift_diag` will be unfolded only when it is applied to 5 arguments.

**Comment by fpvandoorn** [comment]
> This is not the semantics of [unfold-full]. In the current implementation, shift_diag will be unfolded only when it is applied to 5 arguments.

Ok, I think it's fine either way.
