### ISSUE TITLE
esimp fails to unfold recursive definition

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#820]
In the last line, `esimp [rep]` fails. Also, the tactic `esimp [add_add]` would fail in the same position.

``` lean
-- HoTT
import types.nat

open nat eq

definition add_add (n l k : ℕ) : n + l + k = n + (k + l) :=
begin
  induction l with l IH,
    reflexivity,
    exact succ_add (n + l) k ⬝ ap succ IH
end

variables {A : ℕ → Type} (f : Π⦃n⦄, A n → A (succ n))
variables {n : ℕ} (a : A n)
include f

definition rep [reducible] (k : ℕ) (a : A n) : A (n + k) :=
by induction k;exact a;exact f v_0

definition rep_rep_succ (k l : ℕ) (a : A n) :
   rep f k (rep f (succ l) a) =[add_add n (succ l) k] rep f (k + (succ l)) a :=
begin
  esimp [rep],
end
```

**Comment by leodemoura** [comment]
@fpvandoorn In the current implementation, `esimp` fails whenever it cannot fold the recursive application.
The motivation for this heuristic is that we are not really creating something simpler. 
If we really want to unfold `rep` we should use the tactic `unfold rep`. Same for `add_add`.

**Comment by fpvandoorn** [comment]
I was hoping that `esimp` could fold the recursive application of `rep`: it unfolds `rep f (succ l) a` and folds `rep f l a` back to get `f (rep f l a)`.

I do understand that the general case of folding recursive definitions back is very complicated, so if you don't want to spend time on refining the code to see whether terms can be folded back, that's also fine, and then you can just close this issue. I can work around it, if necessary.
