### ISSUE TITLE
temp-file in own project

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#821]
This issue is related to #767. The behaviour of #767 happens in files in own projects which import other files from that project. So if such a buffer is not saved, `C-c C-g` will produce an empty buffer and `C-c C-p` will produce a "unknown identifier"-error.

**Steps to reproduce**

(1) Create a new directory `foo` anywhere (outside any Lean library folder)
(2) Create a file `test1.lean` in `foo`, containing `definition foo := @eq` and save this buffer
(3) Create a project file via the menu bar
(4) Create a file `test2.lean` in `foo` containing

``` lean
import .test1

definition bar : foo 0 0 :=
begin

end
```

(5) In this buffer the behaviour in #767 occurs. So if you save the buffer `test2.lean` then `C-c C-g` and `C-c C-p` work, but if you modify it without saving, neither command works.

(note: this happens for both `.lean` and `.hlean` files)

**Comment by soonhokong** [comment]
This happens because lean-mode creates a temporary file, usually at `/tmp/xxxx`, to process an unsaved buffer (here `test2.lean`). `test2.lean` is importing `test1.lean` which is required to be at the same directory of `test2.lean` but it's not the case here because we create a temp file only for `test2.lean`.

I think the option `--dir` mentioned in https://github.com/leanprover/lean/issues/788#issuecomment-130118017 can be used to solve this problem as well.

**Comment by robertylewis** [comment]
@soonhokong @leodemoura : how much effort do you think this fix would take? I've been working on the analysis library a bit, and keep running into this. There was no one-line fix I noticed scanning through the emacs folder, but I don't know quite what I'm looking at. If you think it's reasonably easy/could point me in the right direction, I'll try harder to figure it out.

**Comment by soonhokong** [comment]
@leodemoura, could you implement `--dir` option? It helps close two issues that we have.

**Comment by leodemoura** [comment]
@soonhokong I will try

**Comment by leodemoura** [comment]
Done it.

**Comment by soonhokong** [comment]
@leodemoura, thanks!

**Comment by soonhokong** [comment]
@rlewis1988, could you test https://github.com/soonhokong/lean/commit/b4b365239f8c7c1b2075c68bf6cc3fedc442b57a ?

**Comment by robertylewis** [comment]
That seems to fix both this issue and #788. Thanks to both of you- this makes things way smoother!

**Comment by soonhokong** [comment]
@rlewis1988, thanks for checking it up. I merged my commit to the blessed repo. Thanks @leodemoura!
