### ISSUE TITLE
include markdown files in the builds

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#823]
People who install Lean from the [builds](http://leanprover.github.io/download/) can still navigate their copy of the standard and HoTT library. However, the markdown files are not included in these builds (at least not with homebrew). It would be useful if these were also included, to know - for example - in which order you should navigate the files.

So the request is to include all markdown files in the `library/` and `hott/` folders to the builds.

**Comment by soonhokong** [comment]
@leodemoura, it can be done by adding `PATTERN "*.md"` into https://github.com/leanprover/lean/blob/master/src/CMakeLists.txt#L471-L476 and https://github.com/leanprover/lean/blob/master/src/CMakeLists.txt#L480-L485. Please let me know if you think it's reasonable to add those lines. I'll make a patch and commit to the blessed repo.

**Comment by leodemoura** [comment]
@soonhokong Yes, it makes sense. Thanks for looking into this stuff.

**Comment by soonhokong** [comment]
@fpvandoorn, homebrew package is just updated. Please try `brew update && brew upgrade lean`. Ubuntu package will be updated tonight around 2:30AM.

**Comment by fpvandoorn** [comment]
Great! Thanks!
