### ISSUE TITLE
abstract tactic

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#825]
It would be nice to have a tactic-mode-variant of the `abstract ... end` block. I think a new tactic `abstract` would do the trick. So for example, if we now write

``` lean
definition long_definition :=
begin
...
{ exact abstract begin apply foo, exact bar end end}
...
end
```

we can write

``` lean
definition long_definition :=
begin
...
{ abstract, apply foo, exact bar}
...
end
```

**Comment by fpvandoorn** [comment]
After thinking a bit, this is not _really_ what I want. What I really want is an attribute `[abstract n1 n2 ...]`. If we give this attribute to a definition `foo`, then whenever we use `foo` in a term, the `n1`-th  `n2`-th, ... arguments of `foo` are abstracted (if `foo` is applied to that many arguments).

Reason: Lots of structures are data + properties, both in the standard library and in the HoTT library. Examples: a `semigroup` has a multiplication + proof of associativity. A `functor` consists of two functions + some properties of those functions. Other examples include: almost all of the algebraic hierarchy, categories, natural transformations and equivalences.

Now suppose we add the attribute `[abstract 5 6]` to `functor.mk`, that would abstact the arguments of `functor.mk` specifying that the functor respects `id` and `comp`. Then we can write 

```
functor.mk F0 F1 *long expression* *longer expression*
```

in a definition `bar` and then if we unfold `bar` we don't have a ridiculously large expression. This is both useful for unification (especially if the abstracted definitions are made `[irreducible]`, which would be fine by me) and for pretty printing (i.e. the current goal will be more manageable).

I also think this would be useful in the standard library, for example, in the future we might want to write something like

```
example my_group := 
group.mk my_mul my_inv my_one (by blast) (by blast) (by blast) (by blast) (by blast) (by blast)
```

without first specifying 6+ lemmas first.

Let me know if you have any concerns.

**Comment by leodemoura** [comment]
I just pushed a commit that allows us to write macros such as

``` lean
notation `$`:max := abstract by blast end
```

This kind of macro is a good workaround. There are many possible variations.
With the macro above, we can write:

``` lean
example my_group := 
group.mk my_mul my_inv my_one $ $ $ $ $ $ $
```

**Comment by fpvandoorn** [comment]
That is indeed nice!

**Comment by leodemoura** [comment]
I'm closing this one, there are reasonable workarounds.
