### ISSUE TITLE
"by+" doesn't work after show

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#830]
The first three of these work, but not the fourth.

``` lean
variable P : Prop
premise HP : P

example : P :=
have H : P, from HP,
H

example : P :=
have H : P, from HP,
show P, from H

example : P :=
have H : P, from HP,
by+ exact H

example : P :=
have H : P, from HP,
show P, by+ exact H    -- invalid expression; by, etc. expected
```

**Comment by javra** [comment]
What does "by+" do?

2015-09-18 15:52 GMT+01:00 Leonardo de Moura notifications@github.com:

**Comment by robertylewis** [comment]
The same thing as "by," but local declarations with "have" are automatically visible. 

``` lean
example : P :=
have H : P, from HP,
by exact H
```

would fail unless H were explicitly marked visible. I think you can also do "begin+".

**Comment by avigad** [comment]
Coincidentally, this just came up on the lean-user mailing list:

  https://groups.google.com/forum/#!topic/lean-user/7pHCPPU9dP8

**Comment by javra** [comment]
Ohh, that's useful. Thanks :)
