### ISSUE TITLE
Ninja missing?

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#838]
```
Traceback (most recent call last):
  File "/usr/local/bin/linja", line 758, in <module>
    sys.exit(main())
  File "/usr/local/bin/linja", line 734, in main
    args = parse_arg(argv)
  File "/usr/local/bin/linja", line 438, in parse_arg
    check_requirements()
  File "/usr/local/bin/linja", line 378, in check_requirements
    g_ninja_path = download_ninja_and_save_at(g_ninja_path)
  File "/usr/local/bin/linja", line 298, in download_ninja_and_save_at
    shutil.copy2(temp_download_path, ninja_path)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/bin/ninja'

Checker definition probably flawed.
```

On running flycheck I get the above error. So apparently ninja is missing. There's only a "linja" but no "ninja" in /usr/local/bin. Shouldn't the installation routine copy it there?

On a similar note: Is it normal that lean-mode does not work automagically after installing lean (from the source)? Whenever I install it on a new machine I have to include this little startup script, from the emacs readme, to ~/.emacs . Before that, emacs can locate the library via M-x locate-library, but I cannot load lean-mode. EDIT: I guess it is normal... Would be great if this could be automatized some day, but maybe that's hard if emacs is not bundled with lean...

**Comment by soonhokong** [comment]
@javra, I assume you're using Ubuntu (or other Linux dist.). How did you install lean on this machine (i.e. via compiling source code / via apt-get)?

**Comment by javra** [comment]
I'm using CentOS (not by choice). I installed it from the sources using make.

**Comment by soonhokong** [comment]
I see. Could you check if there is an existing file `/usr/local/bin/ninja`? If so, please check its permission? (by running `ls -l /usr/local/bin/ninja`)

**Comment by javra** [comment]
As I wrote above, there's only a "linja", no "ninja".

EDIT: I also didn't install ninja independently of Lean.

**Comment by soonhokong** [comment]
I see. Just to check, can you create a file in `/usr/local/bin` without using `sudo`?

**Comment by javra** [comment]
Nope, but I used sudo for the "make install".

**Comment by soonhokong** [comment]
I see.

You're right. When `ninja` is not found on a system, we first download and save `ninja` under `<lean_src_dir>/bin`. But we don't copy this downloaded `ninja` into `/usr/local/bin` when Lean is installed.

**Comment by javra** [comment]
Oh, okay. I did that manually and now the error reads this:

```
Traceback (most recent call last):
  File "/usr/local/bin/linja", line 758, in <module>
    sys.exit(main())
  File "/usr/local/bin/linja", line 743, in main
    return call_ninja(args)
  File "/usr/local/bin/linja", line 517, in call_ninja
    proc = subprocess.Popen([g_ninja_path] + ninja_option + targets, stdout=proc_out, stderr=proc_err)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by soonhokong** [comment]
- I guess you have a permission problem? Could you check you can run `/usr/local/bin/ninja` without `sudo`?
- I'm adding a change to `CMakeLists.txt`.

**Comment by javra** [comment]
Ah, thanks, that solved it!

**Comment by soonhokong** [comment]
Could you test https://github.com/soonhokong/lean/commit/809e579f14192d60da4bd29e39e02808baedde45? I want to make sure that this solves the problem. When it works on your machine, I'll push my commit to the blessed. (Note: you need to delete the existing `/usr/local/bin/ninja` to test it)

**Comment by javra** [comment]
Hm, I just tested it and the `/usr/local/bin/ninja` didn't appear.

**Comment by soonhokong** [comment]
Any error during `sudo make install`?

**Comment by javra** [comment]
Nope.

**Comment by soonhokong** [comment]
Ah... CMake first checks whether there `<lean_source>/bin/ninja` exists in **configuration time**, while we download and install `ninja` in **build time**. That explains why it doesn't copy it during `make install`. Let me check what we can do..

**Comment by soonhokong** [comment]
some reference: https://cmake.org/pipermail/cmake/2009-September/031887.html

**Comment by ExpHP** [comment]
This issue is still around in some form or another.

I'll summarize my case.  The details differ only slightly from the OP:
- Linux user, built from master branch
- Installed to default location of `/usr/local`
- Whenever a file with the `.lean` extension (including new files) was opened for editing, then as the buffer initialized, an error message would appear containing the error message in the OP.
  _(Note: the timing of this error differs slightly from the OP, where it is stated that the error appears "on running flycheck")_
- I could **resolve the first error message by installing ninja through other means** (`sudo apt install ninja` on Ubuntu) and copying it from `/usr/sbin` (yikes!) to `/usr/local/bin`.
- ~~_I never ran into the second error message._  (probably irrelevant; from the conversation it sounds as though the OP's `ninja` binary was first created with `o-x` permissions, whereas mine had `o+x`)~~
- ~~Furthermore, **flycheck functionality seems to work fine for me now**.  By this I mean `C-c ! l` creates a list of errors & print/check statements while `C-c ! {n,p}` navigates.  That said, _I'm not quite sure how it is actually capable of running ninja..._~~
  
  ```
  $ ninja
  log: warning: no configuration file specified, using default values
  log: ninja version 0.1.3 initializing
  die: error: must run as root
  ```
  
  **EDIT: [The ninja I got is actually the wrong tool _entirely!_](https://github.com/leanprover/lean/issues/838#issuecomment-254080794)**

**Comment by leodemoura** [comment]
@ExpHP We are currently working on the `lean3` branch. One good news is that @gebner is working on the new compilation server (https://github.com/leanprover/lean/pull/1155), and how lean projects are handled. In the future, we will not need to use `ninja` to build lean projects.

**Comment by ExpHP** [comment]
@leodemoura Thanks for the status update!  Looks like a pretty big update, is that the branch where new bug reports should be tested or is it still too WIP?

Also, whoops! After digging around I now see there are actually _two different projects called ninja:_ the [build tool](https://github.com/ninja-build/ninja) (which lean uses, and which gets downloaded to `<lean_src>/bin` during the build), and [this thing here with a _very_ different purpose](http://manpages.ubuntu.com/manpages/precise/man8/ninja.8.html) (which is what I got from the Canonical repositories).  Looks like I was bound to run into more trouble eventually with the setup above!

**Comment by gebner** [comment]
With the merge of PR #1178, we no longer have a dependency on ninja.

@leodemoura Can you close this issue?
