### ISSUE TITLE
class instance fails to apply instance

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#842]
In the example below the type class inference does try to apply the instance `is_trunc_eq`, but for some reason it fails, it just tries the next instance. However, replacing the `_` by `!is_trunc_eq` does solve the goal. Did it fail to unify the conclusion of `is_trunc_eq` with the goal during the type class inference?

``` lean
-- HoTT
import algebra.category.constructions.hset

open is_trunc category functor

variables
(I : Precategory)
(F : I ⇒ Precategory_hset)
(X : hset)
(η : Π (a : carrier I), trunctype.carrier X → trunctype.carrier (to_fun_ob F a))
(x : trunctype.carrier X)
(i j : carrier I)
(f : i ⟶ j)

set_option class.trace_instances true
example : is_hprop (to_fun_hom F f (η i x) = η j x) :=
_
-- !is_trunc_eq
```

**Comment by fpvandoorn** [comment]
The following is a bug in the type class mechanism (this is probably a different problem than the previous comment).

``` lean
-- HoTT

import function
open is_trunc function prod
-- local attribute trunctype.struct [priority 3000]
local attribute is_contr_is_section is_contr_is_retraction [priority 2000]
set_option class.trace_instances true
variables {A B : Type₀} (f : A → B)
definition is_hprop_is_retraction_prod_is_section [H : is_equiv f]
 : is_contr (is_retraction f × is_section f) :=
_
```

In the this example the type class inference works. 
It applies `is_trunc_prod` to generate two subgoals `is_contr (is_retraction f)` and `is_contr (is_section f)`, which are solved quickly.

But now uncomment the line which gives a high priority to the instance `trunctype.struct`. Type class inference still succeeds, but does some strange things. The new instance is useless for this problem, but when it is applied to the goal `is_contr (is_retraction f)` the search now looks for a possible solution to the second subgoal. However, it doesn't recognize when it solves the second subgoal and looks further.

``` lean
...
  [2] ?M.19.34.49 : @is_equiv A B f := H -- this solves the goal, but the search continues:
  [2] ?M.19.34.49 : @is_equiv A B f := @is_equiv_prod_rec ?M.19.34.53 ?M.19.34.54 ?M.19.34.55
...
```

Near the end of the trace it happens again. The following solves the goal, but the search continues because the other variable is "stuck" when the useless instance `trunctype.struct` is tried.

```
...
[2] ?M.19.34.164 : @is_equiv A B f := H
...
```

**Comment by leodemoura** [comment]
The latest version does not support HoTT
