### ISSUE TITLE
Opening namespace without a certain notation / Documentation missing

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#843]
Maybe I'm just too confused to find it, but it seems as if the documentation for features like [this](https://github.com/leanprover/lean/blob/e5a82ef516d47319e4b743cc50d4ac7ffa59aa01/tests/lean/run/as.lean) is still missing. How do I again exclude one notation from the `open` command?

**Comment by javra** [comment]
Nvm, I just found the section of the tuturial :)
Edit: It doesn't answer my question, though

**Comment by fpvandoorn** [comment]
So far you cannot cherry-pick which notations you want from a namespace, like you can for declarations. However, you can write `open - [notations] foo` to not import any notation at all from a namespace.

**Comment by javra** [comment]
Hum, okay. Then we might really take a closer look on `category.product_object` :wink:

**Comment by fpvandoorn** [comment]
Yeah, maybe that shouldn't be overloading `×`. Did you already have problems because it was overloaded?

**Comment by javra** [comment]
Yes, it gives an error because it fails to find a precategory on Type

**Comment by fpvandoorn** [comment]
Do you have a small example, or is it going wrong only for a big complicated theorem?
I was hoping that we wouldn't get this error message by giving `product_object` an argument `{D : Precategory}` instead of `{ob : Type} [D : precategory ob]`, but this probably doesn't work because the solution for `D` which is tried is `Precategory.mk Type ?M` and then `?M` gives a problem.

**Comment by javra** [comment]
It's also happening right after opening namespaces and with a variable as a Type... but right now I'm failing to reproduce it outside of my repo :confused: 

```
import algebra.category.functor
import ..dbl_cat.decl

open eq iso iso category functor equiv
open prod prod.ops sigma sigma.ops pi is_trunc

set_option pp.universes true
variables (A B : Type)
check (A × A)
```

**Comment by javra** [comment]
Ha! Condensed it down to a MNWE:

```
import algebra.category
open category prod prod.ops

variables (A : Type)
check (A × A)
```

**Comment by fpvandoorn** [comment]
Hmm... That is indeed bad. The notation also fails when we let the variable `A` be of something where we can actually find a corresponding category, for example `(A : hset)`. Then it still cannot find the right category:

``` lean
import algebra.category
open category is_trunc
variables (A : hset)

check product_object A A
```

I think it illustrates that my approach of making `D : Precategory` and argument to `has_binary_products` is bad, it should probably have two arguments `ob : Type` and `D : precategory ob`:

``` lean
definition has_binary_products' [class] {ob : Type} (D : precategory ob)
definition product_object' {ob : Type} [D : precategory ob]
  [K : has_binary_products' D] (x y : ob) : ob
```

I will do this (not today), and hide the notation `×` for `product_object` in a separate namespace.

**Comment by leodemoura** [comment]
@fpvandoorn @javra 
What is the status of this issue? Should we close it?

**Comment by fpvandoorn** [comment]
I think this issue can be closed. `×` is not overloaded anymore.
