### ISSUE TITLE
Auto-completion after "print definition"

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#846]
Shouldn't there be an autocompletion after "print definition" just like there after "check"? Another thing that might be useful would be to allow to unfold definitions for a "print definition" command.

**Comment by leodemoura** [comment]
@soonhokong I submitted the following candidate fix. 

@javra Could you check if it fixes the issue for you? It fixed for me.

**Comment by soonhokong** [comment]
@leodemoura, I think it's good. @javra, could you check?

**Comment by leodemoura** [comment]
I'm pretty sure it has been fixed, I'm closing it. There are too many issues.
@javra If it is still broken for you, add a comment, and we will reopen.
