### ISSUE TITLE
Installation on Windows 7

### ISSUE THREAD

**Issue by bbentzen** [leanprover/lean3#853]
I downloaded the Lean zip file for Windows, unfolded it in `C:\`. But every time I try to run  `lean.exe`, a DOS window appears and suddenly disappears very quickly, nothing happens. I am using Windows 7.

I also attempted to configure Lean emacs mode to see if it would work. I installed Python v.3.5.0 and emacs 24.5.0.0 both in `C:\`. I have set the command lines
`> setx PATH "%PATH%;c:\Python35-32\"`
`> setx PATH "%PATH%;c:\emacs\bin"`
as well. But I keep having the problem when I try to start the emacs mode by executing the `leanemacs.bat`. Sometimes I can see there's some message in the window (although it disappears so quickly I can't even see what it is saying). I wonder what is going on.

**Comment by soonhokong** [comment]
This must be related to #835. Could you try to set the environment variables via GUI?

![screen shot 2015-10-23 at 10 29 15 am](https://cloud.githubusercontent.com/assets/403281/10695277/f3cb533a-7970-11e5-95f5-fa8393b3f885.png)

**Comment by bbentzen** [comment]
Yeah, I was following this Win 10 issue, but couldn't reproduce the solution.

It works now -  when I went to the System Variables I realized that only the directory `;C:\Python35-32` was present at the end of the listed path. Then I manually included `c:\emacs\bin` and successfully started the Lean emacs mode.

Thanks!
