### ISSUE TITLE
unsolved metavariables with tactics

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#859]
Sometimes, moving into and out of tactic mode leads to "unsolved metavariable"-errors unexpectedly. 

Here's an example:

``` lean
-- HoTT
import hit.quotient

open equiv eq quotient

variables {A : Type} {R : A → A → Type} (Pc : A → Type)
    (Pp : Π⦃a a' : A⦄ (H : R a a'), Pc a ≃ Pc a') {a a' : A} (H : R a a')  (p : Pc a)

theorem my_elim_type_eq_of_rel'
  : pathover (quotient.elim_type Pc Pp) p (eq_of_rel R H) (to_fun (Pp H) p) :=
pathover_of_tr_eq (ap10 (elim_type_eq_of_rel Pc Pp H) p) -- accepted

set_option formatter.hide_full_terms false
theorem my_elim_type_eq_of_rel
  : pathover (quotient.elim_type Pc Pp) p (eq_of_rel R H) (to_fun (Pp H) p) :=
begin exact pathover_of_tr_eq (ap10 (elim_type_eq_of_rel Pc Pp H) p) end -- error
```

Or the following (more complicated) example, which fails, but it works if you remove the `refine abstract begin` and the corresponding `end end`. I'm don't know whether it's the same problem.

``` lean
-- HoTT
import algebra.category.constructions.functor algebra.category.limits

open functor category

definition functor_limit_cone_obj_functor {I C D : Precategory}
  [H : has_limits_of_shape D I] (F : I ⇒ D ^c C) : C ⇒ D :=
begin
fapply functor.mk,
 { intro c, exact limit_object (constant2_functor F c)},
 { intro c d f, fapply hom_limit,
   { intro i, refine to_fun_hom (F i) f ∘ !limit_morphism},
   { exact sorry}},
 { exact sorry},
 { refine abstract begin intro a b c g f, symmetry, apply eq_hom_limit, intro i,
   rewrite [respect_comp,assoc,hom_limit_commute,-assoc,hom_limit_commute,assoc] end end}
end
```

I've encountered this more often, where I wanted to abstract a subterm in a definition, but then the resulting term has unsolved metavariables. A simpler example is `functor_sum_left` in [my personal branch](https://github.com/fpvandoorn/lean/blob/personal/hott/algebra/category/functor/exponential_laws.hlean#L182-L191), where the definitions fails if the last line is abstracted, i.e. replaced by 

``` lean
    { exact abstract begin intro U V W ν μ, apply nat_trans_eq, intro a, induction a: reflexivity end end}
```

**Comment by fpvandoorn** [comment]
Perhaps related:
The theorem `elim_type_eq_of_rel'` in the first example also contains two universe variables `l_3` and `l_4` which _only_ occur as `max l_3 l_4` in the resulting definition:

``` lean
set_option pp.universes true
reveal elim_type_eq_of_rel'
print elim_type_eq_of_rel'
```

**Comment by leodemoura** [comment]
The latest version uses a new tactic framework and does not support HoTT.
