### ISSUE TITLE
unknown annotation kind 'notation_info' from lean.js (emscripten build)

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean3#862]
Dear @leodemoura,

I was updating Lean.js and found this problem. An minimal example is the following line:

``` lean
import data.set
```

and it generates the message "unknown annotation kind 'notation_info'". Do you have any clue where it comes from? I tried to reproduce the problem without using emscripten (i.e. `DMULTI_THREAD=OFF`) but couldn't find a way.

BTW, I had another problem building the latest version of it and had to make a patch: https://github.com/soonhokong/lean/commit/a25b43f1e80fecaf8d00f08e75926d6fc13de0d0

**Comment by avigad** [comment]
@leodemoura This broke the version of Lean used for my course (students have an assignment due tomorrow), but for now @soonhokong  reverted to the previous version (avoiding an emergency).

**Comment by soonhokong** [comment]
Just to provide more information, `4 Sep 2015` version of `lean.js` is running now.

**Comment by leodemoura** [comment]
Have you recompiled the standard library?
This is the kind of error we get when we try to load an old version of the library using a new version.

Thanks,
Leo

**Comment by avigad** [comment]
Maybe just a "make clean-olean"?

**Comment by soonhokong** [comment]
No, this is a fresh VM and I made sure that it's using the up-to-date library.

I'm experiencing something very strange. 
1. I have an example file `test.lean` whose contents is a single line `import standard`. When I run `lean.js` over it, I have the following errors:
   
   ```
   import_module:1:0: error: unknown annotation kind 'notation_info'
   ./test.lean:1:0: error: unknown annotation kind 'notation_info'
   ```
2. Then, I added debug-prints at `register_annotation` and `mk_annotation` functions in [library/annotation.cpp](https://github.com/leanprover/lean/blob/master/src/library/annotation.cpp) to see what's going on.
   
   ``` c++
   void register_annotation(name const & n) {
   std::cerr << "register_annotation: " << n << std::endl;   // <- 
   ...
   expr mk_annotation(name const & kind, expr const & e, tag g) {
   std::cerr << "mk_annotation: " << kind << std::endl;     // <-
   ```
   
   Strangely, the problem goes away after adding these two lines. Now, it generates the following trace:
   
   ```
   register_annotation: have
   register_annotation: show
   register_annotation: @
   register_annotation: as_atomic
   register_annotation: as_is
   register_annotation: !
   register_annotation: by
   register_annotation: by+
   register_annotation: innaccessible
   register_annotation: no_info
   register_annotation: extra_info
   register_annotation: notation_info
   mk_annotation: no_info
   register_annotation: calc
   register_annotation: begin-end
   register_annotation: begin-end-element
   mk_annotation: have
   mk_annotation: have
   ...
   ```
   
   without any `unknown annotation kind` error.

**Comment by leodemoura** [comment]
This is super weird. Are you using a new version of emscripten?

**Comment by soonhokong** [comment]
Yes, I'm using `1.35.4` which is pretty new. I also think that this is a compiler issue (emscripten), let me try an older version.

**Comment by leodemoura** [comment]
Did you try to remove the two lines and try again?

**Comment by soonhokong** [comment]
> Did you try to remove the two lines and try again?

Sure :-), and then I have `unknown annotation kind` again.

**Comment by soonhokong** [comment]
BTW, I simply followed the standard installation procedure: `emsdk install latest && emsdk activate latest`. It installed this version `1.35.4`...

**Comment by leodemoura** [comment]
I will try to build it tomorrow using the desktop in my office.
I tried with my home machine, but the VM is freezing :-(

**Comment by soonhokong** [comment]
I'll test another version of Emscripten as well. Unfortunately, building a version of Emscripten takes 1 - 2 hours.. I'll keep you posted.

**Comment by soonhokong** [comment]
Hmm.. it seems that the problem is related to the Emscripten optimization flags. Removing `-Oz` solves the problem (at least for the simple `import standard`). But it increase the size of `lean.js` from 14MB to 70MB, which is very bad.. I'll try different options.

Reference: https://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html#arguments

**Comment by soonhokong** [comment]
It seems that `emscripten-1.30.6` is generating a correct lean.js code. It passes many tests so far. Once I finish the testing, I'll update one at https://leanprover.github.io/lean.js/lean.js and close this issue.

**Comment by soonhokong** [comment]
@avigad, I just updated https://leanprover.github.io/lean.js/lean.js file which are used by the tutorial and logic_and_proof.

There are some test failures with logic_and_proof. But it's reproducible with the native Lean, so I assume that it's not a problem of lean.js.

FYI, here are a couple of them:

## Chapter 6

``` lean
import standard
import data.nat
open nat

-- BEGIN
example : ∀ n m : ℕ, m ∣ n → n ∣ m → n = m
take m n,
assume `n ∣ m` `m ∣ n`,
obtain k `m = n * k`, from `n ∣ m`,
obtain l `n = m * l`, from `m ∣ n`,
or.elim (eq_zero_or_pos n)
(assume `n = 0`,
show m = n, from calc
m = n * k : `m = n * k`
... = 0 * k : {`n = 0`}
... = 0     : zero_mul
... = n     : `n = 0`)
(assume `n > 0`,
have n * 1 = n * (k * l), from calc
n * 1 = n         : mul_one
... = m * l       : `n = m * l`
... = (n * k) * l : {`m = n * k`}
... = n * (k * l) : mul.assoc,
have 1 = k * l,
from eq_of_mul_eq_mul_left `n > 0` `n * 1 = n * (k * l)`,
have k = 1,
from eq_one_of_mul_eq_one_right (eq.symm `1 = k * l`),
show m = n, from calc
m = n * k : `m = n * k`
... = n * 1 : {`k = 1`}
... = n     : mul_one)
-- END
```

Error

```
06_Existential_Quantifier.org.6.lean:6:27: error: function expected at
  ∀ (a : m ∣ n) (a_1 : n ∣ m),
    n = m
```

## Chapter 8

``` lean
import standard
variables {X Y Z : Type}

definition compose (f : Y → Z) (g : X → Y) : X → Z :=
λ x, f (g x)

infixr  ` ∘ ` := compose

definition id (x : X) : X :=
x

-- BEGIN
lemma left_id (f : X → Y) : id ∘ f = f := rfl

lemma right_id (f : X → Y) : f ∘ id = f := rfl

theorem compose.assoc (f : Z → W) (g : Y → Z) (h : X → Y) : (f ∘ g) ∘ h = f ∘ (g ∘ h) := rfl

theorem compose.left_id (f : X → Y) : id ∘ f = f := rfl

theorem compose.right_id (f : X → Y) : f ∘ id = f := rfl
-- END
```

Error

```
ERROR executing 08_Functions.org.3.lean, for in_code_block block starting at 705, produced output:
FLYCHECK_BEGIN ERROR
08_Functions.org.3.lean:17:31: error: unknown identifier 'W'
FLYCHECK_END
```

**Comment by avigad** [comment]
@soonhokong Thanks for catching these errors; they are fixed now. Thanks even more for getting the online version of Lean working again.
