### ISSUE TITLE
Some symbols not being displayed correctly

### ISSUE THREAD

**Issue by bbentzen** [leanprover/lean3#873]
I wonder why some characters are not being displayed correctly in my emacs (v.24.5.1), as the image below shows:
![test](https://cloud.githubusercontent.com/assets/15263295/11169421/0f4e4b92-8bf2-11e5-81d9-ee71852d3d04.png)
It seems emacs displays them as some sort of character code instead.

For reference, the symbols in the picture are the following:

``` javascript
definition whisker_right [unfold 7] {p q : x = y} (h : p = q) (r : y = z) : p ⬝ r = q ⬝ r :=
  h ◾ idp
```

``` javascript
‒ – — ‘ ’ ‚ „ † ‡ • … ‰ ﹠ ＆ ·
  ¤ ¢ £ € ¥ ¦ § ¶ © ® ™
¼ ½ ¾
“” ‹› «» 〔〕 〈〉 《》 「」 『』 【】〖〗
Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω
ℬ ℭ ℰ ℱ ℋ ℳ ℘ ℛ ℨ
ℯ ℊ ℌ ℐ ℑ ℒ ℓ ℴ ℜ
ℂ ℕ ℙ ℚ ℝ ℤ ℍ
ℵ ⅆ ⅇ ⅈ ⅉ ∅
Å ב ג ד
ƒ µ ø Ø Þ ß ϑ ϒ ϖ Ϝ ϝ
° ‾ ⁄
superscript ⁰ ¹ ² ³ ⁴ ⁵ ⁶ ⁷ ⁸ ⁹ ⁺ ⁻ ⁼ ⁽ ⁾ ⁿ ⁱ
subscript ₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉ ₊ ₋ ₌ ₍ ₎ ₐ ₑ ₒ ₓ ₔ ᵢ ⱼ ᵥ
← → ↔ ↑ ↓ ↖ ↘ ↚ ↛ ↮
↤ ↦ ⇤ ⇥
⇐ ⇒ ⇔ ⇑ ⇓
⇍ ⇏ ⇎
⟵ ⟶ ⟷ ⟸ ⟹ ⟺
∀ ∃ ∴
¬ ∧ ∨ ⊻ ⊼ ⊽ ⊥
∈ ∉ ∋
⊕ ⊗ ⋅ ⨯
∝ ∞
⌈ ⌉ ⌊ ⌋
⌘ ⌚ ⌛ ⏏ ␣ ⌤ ⌥ ⌧ ⌫ ⌶ ⎋ ⎗ ⎘ ⎙ ✂ ✄ ✉ ✍ ⌨ ⏎ ↩ ↵ ↶ ↷ ↹ ⇄ ⇧ ⇞ ⇟
⓪ ① ② ③ ④ ⑤ ⑥ ⑦ ⑧ ⑨
■ □ ▲ △ ▶ ▷ ▼ ▽ ◀ ◁ ◆ ◇ ◊ ○ ● ★ ☹ ☺
☉ ☼ ☽ ☾ ☿ ♀ ♁ ♂ ♃ ♄ ♅ ♆ ♇ ☄
♠ ♣ ♥ ♦ ♩ ♪ ♫ ♬ ♭ ♮ ♯
```

I tried a lot but I can't figure out what is causing emacs to behave like this..

**Comment by soonhokong** [comment]
@bbentzen, could you try the instructions at https://github.com/leanprover/lean/blob/master/src/emacs/README.md#unicode ?

Mainly, it's about:
- use a font with a better unicode-support
- use `unicode-fonts` package

**Comment by bbentzen** [comment]
I'm now using `DejaVu Sans Mono` but the problem persists. 

Then I went to install `unicode-fonts` following the instructions above. But when I run `M-x package-refresh-contents` it shows `contacting host: elpa.gnu.org:80` forever. Also, `M-x package-install` answers me `[no match]` when I input `unicode-fonts`...

I tried to install it manually downloading it and placing the `unicode-fonts.el` file in my `~/site-lisp` as it is said [here](https://github.com/rolandwalker/unicode-fonts#compatibility-and-requirements), but, as I am new in emacs, I don't understand what they mean by 

> add the following to your ~/.emacs file:
> 
> (require 'unicode-fonts)
> (unicode-fonts-setup)

should I add those lines in the body of my `.lean` file or something?

**Comment by soonhokong** [comment]
> But when I run M-x package-refresh-contents it shows contacting host: elpa.gnu.org:80 forever.

I think that it just keeps showing the last message, which is fine. But it seems that you don't have [MELPA](https://melpa.org/#/getting-started) set up in your emacs configuration. If so, please click the [link](https://melpa.org/#/getting-started) and follow the instruction.

If you have already installed `unicode-fonts` packages successfully, you can ignore this step though.

> should I add those lines in the body of my `.lean` file or something?

No. It should be added to your emacs configuration file (i.e. `~/.emacs` or `~/.emacs.d/init.el`).

**Comment by bbentzen** [comment]
This is how my `.emacs` file look like now:

``` elisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["#2d3743" "#ff4242" "#74af68" "#dbdb95" "#34cae2" "#008b8b" "#00ede1" "#e1e1e0"])
 '(cua-mode t nil (cua-base))
 '(custom-enabled-themes nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "DejaVu Sans Mono" :foundry "outline" :slant normal :weight normal :height 98 :width normal)))))
(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line
```

The lines starting from `require 'package .... You might already have this line` have just been added following the above link instructions for MELPA. However, I still can't install `unicode-fonts`, i.e. `M-x package-install` still answers me `[no match]`.

I tried to look for it in the "manage Emac Packages" tab, but `unicode-fonts` is not in my package list.

**Comment by soonhokong** [comment]
> However, I still can't install unicode-fonts, i.e. M-x package-install still answers me [no match].

You may need to run <kbd>M-x</kbd>`package-refresh-contents` before doing  <kbd>M-x</kbd> `package-install`. If you still don't find it, please try <kbd>M-x</kbd> `list-packages` and find `unicode-fonts` there. If you don't have it there, please let me know.

**Comment by bbentzen** [comment]
Yeah, I don't have `unicode-fonts` in my list.

Ok, those are the buffer messages when I call `package-refresh-contents`:

``` text
Contacting host: melpa.org:443
Opening TLS connection to `melpa.org'...
Opening TLS connection with `gnutls-cli --insecure -p 443 melpa.org'...failed
Opening TLS connection with `gnutls-cli --insecure -p 443 melpa.org --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect melpa.org:443 -no_ssl2 -ign_eof'...failed
Opening TLS connection to `melpa.org'...failed
Failed to download `melpa' archive.
Contacting host: elpa.gnu.org:80
```

At first I guessed it had something to do with me being in China - thus being subject to the infamous China's Great Firewall - but it shows me the same message even after my vpn is on.

**Comment by soonhokong** [comment]
> At first I guessed it had something to do with me being in China - thus being subject to the infamous China's Great Firewall...

OK. Can you access https://github.com/rolandwalker/unicode-fonts ? If so, please download `unicode-fonts.el` file manually and put it under a load-path. Then, follow the instructions on https://github.com/rolandwalker/unicode-fonts#quickstart .

**Comment by soonhokong** [comment]
@bbentzen, what do you have when you run `list-packages`? For instance, this is what I have: 

![screen shot 2015-11-19 at 11 13 02 am](https://cloud.githubusercontent.com/assets/403281/11276073/8e01c6e4-8eae-11e5-8d6d-e01f72aa8799.png)

Do you have any packages marked with `available` whose archive is `melpa`?

**Comment by bbentzen** [comment]
No available package whose archive is `melpa`. All my 129 available packages archives are `gnu`:
![test2](https://cloud.githubusercontent.com/assets/15263295/11296774/231551e6-8faf-11e5-8f03-44e36d14d342.png)
I followed the melpa set up instructions you gave in this [link](https://melpa.org/#/getting-started) though, i.e. the following lines

> (require 'package) ;; You might already have this line
> (add-to-list 'package-archives
>              '("melpa" . "https://melpa.org/packages/"))
> (when (< emacs-major-version 24)
>   ;; For important compatibility libraries like cl-lib
>   (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
> (package-initialize) ;; You might already have this line

were added to my `.emacs` file..

**Comment by soonhokong** [comment]
@bbentzen, let's check some basic things first. Can you access https://melpa.org (via a web-browser)? Please try both of `https` and `http`.

**Comment by soonhokong** [comment]
Also, please check the following steps:

> Can you access https://github.com/rolandwalker/unicode-fonts ? If so, please download unicode-fonts.el file manually and put it under a load-path. Then, follow the instructions on https://github.com/rolandwalker/unicode-fonts#quickstart .

**Comment by bbentzen** [comment]
Yes, I can access it normally (I am always browsing with my vpn on).

I download `unicode-fonts.el` and put it in `~\\emacs\share\emacs\24.5\lisp` (not sure if it is the right location), then added

> (require 'unicode-fonts)
> (unicode-fonts-setup)

to my `.emac` file right after the lines from the melpa set up. But still nothing. And it doesn't appear in my package list neither.

Maybe it is something wrong with my `.emacs` file?
![test_emacs](https://cloud.githubusercontent.com/assets/15263295/11299167/64958914-8fbf-11e5-9fc2-4467bf866632.png)

So one just adds the melpa entry to it and melpa is supposed to be properly configured? How can I know melpa is working fine in my emacs?

**Comment by soonhokong** [comment]
> So one just adds the melpa entry to it and melpa is supposed to be properly configured?

Yes. The key part is to add `("melpa" . "https://melpa.org/packages/")` into `package-archives` list, which you have already done in your setup.

> How can I know melpa is working fine in my emacs?

If everything is working correctly, you're supposed to see a list of _avaiable_ packages marked with `melpa` source. It seems something is not working.

> Yes, I can access it normally (I am always browsing with my vpn on).

Question: Which VPN service are you using? Do you need to do some special set up in your web-browser to make it work (i.e. proxy setting)? I suspect that the VPN is (somehow) enabled only on your browsers but not on emacs (or terminal?), because you had the following error log:

```
Contacting host: melpa.org:443
Opening TLS connection to `melpa.org'...
Opening TLS connection with `gnutls-cli --insecure -p 443 melpa.org'...failed
Opening TLS connection with `gnutls-cli --insecure -p 443 melpa.org --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect melpa.org:443 -no_ssl2 -ign_eof'...failed
Opening TLS connection to `melpa.org'...failed
Failed to download `melpa' archive.
Contacting host: elpa.gnu.org:80
```

To check this, please try the following and let me know what you get in emacs:
- <kbd>M-x</kbd>`eshell`
- Type: `wget https://raw.githubusercontent.com/rolandwalker/unicode-fonts/master/unicode-fonts.el`

**Comment by soonhokong** [comment]
Another question: What do you get when you run `gnutls-cli --insecure -p 443 melpa.org` in a terminal?

**Comment by bbentzen** [comment]
(Sorry for the delay, I've been away from my PC these days)

I use Astrill VPN, it supports either plain browsering or OpenVPN - which is supposed to tunnell all applications on the computer, including P2P etc. Yet, `package-refresh-contents` fails even when I try it. 

For the first question, this is what I get:

> Welcome to the Emacs shell
> 
>  c:/Lean/bin $ wget https://raw.githubusercontent.com/rolandwalker/unicode-fonts/master/unicode-fonts.el
> wget: command not found

For the second, I'm not sure if I understand the question - how do I run it in a terminal?

**Comment by soonhokong** [comment]
I just realized that you're using Windows. Let me get some more information:
- Windows version?
- What do you get when you run `M-x version` on emacs?
- Do you remember where you downloaded the emacs that you're using? Was it from https://ftp.gnu.org/gnu/emacs/windows/ ?

**Comment by bbentzen** [comment]
I'm using Windows 7. My emacs version is 24.5.1, as in:

> GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570

Yes, from this link - all as indicated in the Lean Windows installation guide.

**Comment by soonhokong** [comment]
@bbentzen 

Please try `http` instead of `https`, that is, please have the following in your `.emacs` file:

``` elisp
(add-to-list 'package-archives
'("melpa" . "http://melpa.org/packages/"))
```

This should help. Reference: https://github.com/milkypostman/melpa/issues/2109

**Comment by bbentzen** [comment]
Neat! It does: melpa works now. And I've installed `unicode-fonts` too:
![test](https://cloud.githubusercontent.com/assets/15263295/11355906/a94fe384-9293-11e5-9b59-b715a651f419.png)
Some symbols that didn't show before do now, as we can see here: 
![test2](https://cloud.githubusercontent.com/assets/15263295/11356051/ef3a2c96-9294-11e5-8142-68fabe3689b2.png)
It is already a great thing, but not all characters are properly displayed yet - and some are common ones e.g. the symbol `⬝` for `concat` in the HoTT library.

**Comment by soonhokong** [comment]
@bbentzen, I'll check them on my office Windows machine. @fpvandoorn, do you have the same problem?

**Comment by fpvandoorn** [comment]
I had also some problems with it, but after including both of these lines to my `.emacs` file, at least the infix `concat` symbol shows up correctly. 

```
(require 'unicode-fonts)
(unicode-fonts-setup)
```

I think all characters for the HoTT library now work for me, but I haven't checked carefully.

**Comment by soonhokong** [comment]
@bbentzen, please download the following fonts and install them on your machine (right-click and select 'install'):
- http://www.quivira-font.com/files/Quivira.ttf
- https://github.com/googlei18n/noto-fonts/blob/master/hinted/NotoSans-Regular.ttc?raw=true
- https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansSymbols-Regular.ttf?raw=true

Then have the following lines on your emacs setup:

``` elisp
(require 'unicode-fonts)
(unicode-fonts-setup)
(when (member "DejaVu Sans Mono" (font-family-list))
  (set-face-attribute 'default nil :font "DejaVu Sans Mono-11"))
```

**Comment by bbentzen** [comment]
Great! Not only the concat symbol, but every character in the list is now shown perfectly in my emacs:

![test](https://cloud.githubusercontent.com/assets/15263295/11421417/9ee62f42-946f-11e5-9caf-5eae68915a18.png)

For the record, I already had the three fonts installed in my machine, but the problem wasn't solved until I added the abovementioned lines in my `.emacs` file.

Thanks, @soonhokong !

**Comment by soonhokong** [comment]
Great!
