### ISSUE TITLE
install emacs mode after homebrew installation

### ISSUE THREAD

**Issue by txa** [leanprover/lean3#874]
I tried to copy the contents of 
https://github.com/leanprover/lean/blob/master/src/emacs/README.md
into preferences.el but gt a number of error messages (e.g. alist not found). Tried to fix this but then got more errors.
Maybe I need to tell emacs to load the mode from 
/usr/local/share/emacs/site-lisp/lean
but how do I do this?
Thanx a lot,
Thorsten (with the help of Jakob)

**Comment by javra** [comment]
I think there was also some error that the gnu site could not be found? Could it be that the `README.md` ist out of date?

**Comment by soonhokong** [comment]
Yes, this is a known problem of a specific version of emacs. I'll look up a workaround.

**Comment by javra** [comment]
It's emacs 24 IIRC.

**Comment by soonhokong** [comment]
See the comment https://github.com/leanprover/lean/issues/418#issuecomment-107820478.

Could you have `(setq package-check-signature nil)` in your emacs configuration file (at the top), and restart emacs and let me know how it changes things?

**Comment by soonhokong** [comment]
We're mainly rely on [MELPA](https://melpa.org) but flycheck has a dependency on alist which is on [GNU ELPA](https://elpa.gnu.org). By default, emacs is checking signatures of repositories before downloading packages, but [GNU ELPA is partially broken](http://stackoverflow.com/questions/26108655/error-updating-emacs-packages-failed-to-download-gnu-archive#comment45103304_26449253) and it causes this problem.

**Comment by txa** [comment]
So, do I actually need to copy the files from the webpage into my emacs setup or is it sufficient to load some file from the lean emacs directory?

I am mainly confused in the moment.

The setup file form the webpage certainly had the bug that the a list module isn’t loaded even though a fix to this is mentioned in the git history but not present on the webpage. Hence I was wondering wether the instructions on the web are maybe out of date.

Cheers,
Thorsten

**Comment by javra** [comment]
I'm pretty sure you should to copy the lisp code from the README or from your local lean copy into your emacs config.

(btw that email footer does horrible things to the github interface)

**Comment by soonhokong** [comment]
> So, do I actually need to copy the files from the webpage into my emacs setup or is it sufficient to load some file from the lean emacs directory?

Copying the snippet from the website should work. But in your case, you need to first have `(setq package-check-signature nil)` and then paste the one from the website.

Sorry for the confusion. This is a known issue but only found in certain versions of emacs (depends on the default value of `package-check-signature` - `t`:always check signature, `nil`: do not check, `allow-unsigned`: allow unsigned...). For instance, I'm using `24.4.50.1` and it has `allow-unsigned` as a default value which helps me avoid this problem.

I'll add this one into the [known issues and possible solutions](https://github.com/leanprover/lean/blob/master/src/emacs/README.md#known-issues-and-possible-solutions) section.

**Comment by txa** [comment]
I have done this and get the following error messages whet starting emacs:

Compiling no file at Mon Nov 16 17:56:52 2015
Leaving directory `/Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716'
Compiling file /Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716/mmm-auto.el at Mon Nov 16 17:56:52 2015
Entering directory`/Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716/'
mmm-auto.el:61:1:Warning: cl package required at runtime
Compiling file /Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716/mmm-class.el at Mon Nov 16 17:56:52 2015
mmm-class.el:34:1:Warning: cl package required at runtime
Compiling file /Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716/mmm-cmds.el at Mon Nov 16 17:56:52 2015
mmm-cmds.el:32:1:Warning: cl package required at runtime
Compiling file /Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716/mmm-compat.el at Mon Nov 16 17:56:52 2015
mmm-compat.el:35:1:Warning: cl package required at runtime
Compiling file /Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716/mmm-cweb.el at Mon Nov 16 17:56:52 2015
Compiling file /Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716/mmm-defaults.el at Mon Nov 16 17:56:52 2015
Compiling file /Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716/mmm-erb.el at Mon Nov 16 17:56:52 2015
Compiling file /Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716/mmm-mason.el at Mon Nov 16 17:56:52 2015
Compiling file /Users/txa/Library/Application Support/Aquamacs Emacs/elpa/mmm-mode-20150828.1716/mmm-mode-pkg.el at Mon Nov 16 17:56:52 2015
mmm-mode-pkg.el:1:1:Warning: `"convenience"' is a malformed function

Can you make some sense out of this?

Btw, the lean setup code is much more complicated then the one needed for any other system (e.g. Agra). I am also concerned that this may affect some other emacs functionality I need.

Shouldn’t required modules be loaded from the mode itself?

Cheers,
Thorsten

**Comment by soonhokong** [comment]
@txa, the above texts are warnings, not errors, and you won't see them again (next time you start emacs). Could you check?

**Comment by javra** [comment]
Hi @soonhokong, your solution worked, so ths can be closed :smiley:

**Comment by soonhokong** [comment]
:-)
