### ISSUE TITLE
Build fails with strangeninja error

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#897]
All of a sudden, the build on my notebook fails with

```
ninja: error: opening build log: Permission denied
```

Any ideas? Permissions on `/usr/local/bin/ninja` seem fine.

**Comment by soonhokong** [comment]
What do you have when you run `ls -l .ninja_log` on your build directory?

**Comment by soonhokong** [comment]
It's possible that you don't have enough space on your laptop. Could you check that by running `df -h`?

**Comment by javra** [comment]
Hm, I got a fresh copy and deleted the old repo before I read your comments, checking `.ninja_log` would have been obvious. Well, I'll reopen this, should I encounter it again.
