### ISSUE TITLE
Emacs syntax highlighting breaks when opening the second file

### ISSUE THREAD

**Issue by cocreature** [leanprover/lean3#906]
If I open a single `.lean` file everything works fine, however when I try to open a second file (or close and reopen the same one) jit-lock breaks with `Variable binding depth exceeds max-specpdl-size` and syntax highlighting doesn’t work. The rest seems to work fine.

I also tried starting `emacs -q` but I run into the same problem there so it doesn’t seem to be related to my config.

I searched around but I couldn’t find a solution. `max-specpdl-size` is set to 1000 so that shouldn’t be a problem. Also I can’t recall encountering that bug with some other package.

My emacs version is

```
GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.6) of 2015-09-10 on foutrelis
```

and I used the master branch of lean for both the emacs mode and the binary. Also I get my dependencies from elpa.

When I enable `jit-lock-debug-mode` I get the following backtrace

``````
Debugger entered--Lisp error: (error "Variable binding depth exceeds max-specpdl-size")
  cl-remove(nil nil :if-not #[(ovl) "\303\304\"\205\f\305   \n#\207" [ovl pos type overlay-get mmm mmm-included-p] 4])
  apply(cl-remove nil nil :if-not #[(ovl) "\303\304\"\205\f\305 \n#\207" [ovl pos type overlay-get mmm mmm-included-p] 4] nil)
  remove-if-not(#[(ovl) "\303\304\"\205\f\305   \n#\207" [ovl pos type overlay-get mmm mmm-included-p] 4] nil)
  mmm-overlays-at(1 nil)
  mmm-beginning-of-syntax()
 … a lot more of this
  mmm-beginning-of-syntax()
  #[0 "\302\242\203=\300\242\302\242Z\306HA\306H@T\245\307_W\203=\310H\211@T\240\266\310H\211A\300\242\302\242Z\\\241\266\311\302\242\300\242\312\211\301%\207\302\242\204\214\301\203\214\304\313\301!\206P\307\3018\240\203\214\304\242\300\242X\203\214\300\242\304\242ZW\203\214\314H\211@T\240\266\314H\211A\300\242\304\242Z\\\241\266\303\311\304\242\300\242\"\240\210\202E\312ee\312\203\254\300\242\211@@\262W\203\254\262A\262\202\222\203\301\211@@\262\262\303\211@A\262\240\210\204\322\204\322\315\316\317\320\211$\210\302\242\203\336\302\242W\203\350\262\303\242\262\202\321H\211@T\240\266\321H\211A\300\242\302\242Z\\\241\266\302\242\262\301\262\204 \322\323!\203 \203 \324\325!\210\203a\300\242b\210 \210`V\203a`\300\242W\203a\326`\327\"\330>\204a\306H\211@T\240\266\306H\211A\300\242`Z\\\241\266`\262\312\262\300\242ZW\203\222\307H\211@T\240\266\307H\211A\300\242Z\\\241\266\303\311\300\242\312\211%\240\210\202C\331H\211@T\240\266\331H\211A\300\242Z\\\241\266\300\242Z\307_V\203\350\303\311\211\300\242\\\307\245\211\262\312\211\303\242%\240\210\303\242B\203\336\211AB\241\266\202\344\211B\210\202\253\303\311\300\242\312\211\303\242%\240\210\300\242\303\242B\203\211@@\262\300\242ZV\203\211AB\241\266\202B\240\210\202B\2034\211@@\262\300\242ZV\203=\211B\202B\240\210\210\266\300\242\303\242B\303\242\207" [(1) nil (nil) (nil) (1) syntax-ppss-stats 5 2 0 parse-partial-sexp nil syntax-ppss-toplevel-pos 1 add-hook before-change-functions syntax-ppss-flush-cache t 4 boundp font-lock-beginning-of-syntax-function make-local-variable syntax-begin-function get-text-property face (font-lock-string-face font-lock-doc-face font-lock-comment-face) 3 syntax-ppss-max-span syntax-ppss-cache syntax-ppss-last] 12 "\n\n(fn)"]()
  funcall(#[0 "\302\242\203=\300\242\302\242Z\306HA\306H@T\245\307_W\203=\310H\211@T\240\266\310H\211A\300\242\302\242Z\\\241\266\311\302\242\300\242\312\211\301%\207\302\242\204\214\301\203\214\304\313\301!\206P\307\3018\240\203\214\304\242\300\242X\203\214\300\242\304\242ZW\203\214\314H\211@T\240\266\314H\211A\300\242\304\242Z\\\241\266\303\311\304\242\300\242\"\240\210\202E\312ee\312\203\254\300\242\211@@\262W\203\254\262A\262\202\222\203\301\211@@\262\262\303\211@A\262\240\210\204\322\204\322\315\316\317\320\211$\210\302\242\203\336\302\242W\203\350\262\303\242\262\202\321H\211@T\240\266\321H\211A\300\242\302\242Z\\\241\266\302\242\262\301\262\204 \322\323!\203 \203 \324\325!\210\203a\300\242b\210 \210`V\203a`\300\242W\203a\326`\327\"\330>\204a\306H\211@T\240\266\306H\211A\300\242`Z\\\241\266`\262\312\262\300\242ZW\203\222\307H\211@T\240\266\307H\211A\300\242Z\\\241\266\303\311\300\242\312\211%\240\210\202C\331H\211@T\240\266\331H\211A\300\242Z\\\241\266\300\242Z\307_V\203\350\303\311\211\300\242\\\307\245\211\262\312\211\303\242%\240\210\303\242B\203\336\211AB\241\266\202\344\211B\210\202\253\303\311\300\242\312\211\303\242%\240\210\300\242\303\242B\203\211@@\262\300\242ZV\203\211AB\241\266\202B\240\210\202B\2034\211@@\262\300\242ZV\203=\211B\202B\240\210\210\266\300\242\303\242B\303\242\207" [(1) nil (nil) (nil) (1) syntax-ppss-stats 5 2 0 parse-partial-sexp nil syntax-ppss-toplevel-pos 1 add-hook before-change-functions syntax-ppss-flush-cache t 4 boundp font-lock-beginning-of-syntax-function make-local-variable syntax-begin-function get-text-property face (font-lock-string-face font-lock-doc-face font-lock-comment-face) 3 syntax-ppss-max-span syntax-ppss-cache syntax-ppss-last] 12 "\n\n(fn)"])
  syntax-ppss(1)
  font-lock-fontify-syntactically-region(1 626 nil)
  font-lock-default-fontify-region(1 626 nil)
  #[(reg) "@b\210\305   !\210\306   !\210\n@\211A@\262\307#\210\310\f\"\207" [reg mode func mmm-current-overlay mmm-current-submode mmm-set-current-submode mmm-set-local-variables nil mmm-save-changed-local-variables] 4]((1 626))
  mapc(#[(reg) "@b\210\305  !\210\306   !\210\n@\211A@\262\307#\210\310\f\"\207" [reg mode func mmm-current-overlay mmm-current-submode mmm-set-current-submode mmm-set-local-variables nil mmm-save-changed-local-variables] 4] ((1 626)))
  mmm-fontify-region-list(lean-mode ((1 626)))
  #[(elt) "@\301N\205\302@A\"\207" [elt mmm-font-lock-mode mmm-fontify-region-list] 3]((lean-mode (1 626)))
  mapc(#[(elt) "@\301N\205\302@A\"\207" [elt mmm-font-lock-mode mmm-fontify-region-list] 3] ((lean-mode (1 626))))
  mmm-fontify-region(1 626 nil)
  font-lock-fontify-region(1 626)
  run-hook-with-args(font-lock-fontify-region 1 626)
  #[0 "\302\303\300\242\301\242#\207" [(1) (626) run-hook-with-args jit-lock-functions] 4 "\n\n(fn)"]()
  funcall(#[0 "\302\303\300\242\301\242#\207" [(1) (626) run-hook-with-args jit-lock-functions] 4 "\n\n(fn)"])
  jit-lock-fontify-now(1 626)
  jit-lock--debug-fontify()
  apply(jit-lock--debug-fontify nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 0 0 t jit-lock--debug-fontify nil idle 0])
```.
``````

**Comment by soonhokong** [comment]
@cocreature, does it happen with any `.lean` file? If not, could you send me (or copy/paste here) the one that shows this behavior?

**Comment by cocreature** [comment]
@soonhokong Sadly it happens with any .lean file.

**Comment by soonhokong** [comment]
@cocreature, could you check whether you have version `0.2` or `0.5` of `cl-lib` package installed on your emacs system?

**Comment by cocreature** [comment]
@soonhokong According to `describe-package` I have version 1.0 which is `built-in` aka bundled with my emacs version (which I got from the archlinux repos).

**Comment by soonhokong** [comment]
Yes, cl-lib 1.0 comes with emacs24.5 but somehow it's still possible to install other versions, and it's [known to cause this problem](https://github.com/clojure-emacs/cider/issues/443#issuecomment-35075883). Could you run `package-list-packages` and check the other versions are not installed.

**Comment by cocreature** [comment]
I checked and as far as I can see it’s not installed. I also checked `~/.emacs.d/elpa`. Also when running `emacs -q` I set HOME to an empty directory to make sure that packages I had installed didn’t affect it.

**Comment by soonhokong** [comment]
@cocreature, thanks for checking things up. I'll install archlinux VM and try to reproduce this.

**Comment by cocreature** [comment]
Sorry for the confusion, for some reason I now can’t reproduce it with a clean config, so it looks like it is related to my config after all. Not sure why I managed to reproduce it earlier with a clean config. In that case I’ll tinker around with it and try to figure out which part of my config is screwing things up. Thanks a lot for the excellent support.

**Comment by soonhokong** [comment]
I see. Good luck!

**Comment by cocreature** [comment]
For anybody finding this issue the problem was the `mmm-mode` bundled by `proofgeneral` which I had installed globally so even nuking `~/.emacs.d` didn’t help. After I removed `proofgeneral` everything seems to work now. Maybe this should be added to the docs somewhere since I could imagine that the audience is reasonably likely to have installed `proofgeneral`.

Thanks for a great emacs mode @soonhokong (and whoever else was involved) and the support.

**Comment by soonhokong** [comment]
Thanks for the information. Could you check the version of `mmm-mode` and `proofgeneral` that you have on ArchLinux? I'm using `proofgeneral` as well but doesn't have this problem. I'll add a note in the README.md file later.

**Comment by cocreature** [comment]
I had `proofgeneral` version `4.2` which bundled `mmm-mode` in the contrib directory in version `0.4.8` which seems to be pretty ancient. Ofc you can use `proofgeneral` alongside lean, but you probably need to make sure you’re not using that version of mmm-mode.

**Comment by soonhokong** [comment]
@cocreature, thanks again for the report and investigation. I mentioned the problem and possible solutions at [src/emacs/README.md](https://github.com/leanprover/lean/blob/master/src/emacs/README.md#variable-binding-depth-exceeds-max-specpdl-size-error).
