### ISSUE TITLE
Lean very slow after importing large theories

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#918]
On my notebook, lean becomes very slow after importing certain theories from the library, for example flycheck already takes around 5 seconds after each keystroke in this file:

```
import homotopy.sphere

open unit

example : unit := ⋆
```

On my office computer this is not the case. Both are on the current master branch. Does anyone have an idea why that is or pointers to possible troubleshooting?

It's not a flycheck problem, directly compiling it in a terminal also produces the big difference. It also slows down the compilation time of the library to ~30 min.

**Comment by leodemoura** [comment]
Have you compiled in debug mode?

**Comment by javra** [comment]
No, release mode.

**Comment by leodemoura** [comment]
I can't reproduce this problem. On my machine it takes 0.1 sec to process the file, and it consumes 20Mb. I would rebuild everything from scratch (delete build directory and .olean files and rebuild).
I would also check if there are other processes running in the background and consuming all resources (e.g., memory).

**Comment by javra** [comment]
I deleted the entire repository clone actually. There's no memory consuming background processes but I noticed that at least the library build starts three lean threads even if I've only two processor cores. But I don't think that's the cause...

**Comment by javra** [comment]
I don't really know how I managed to do this but there was a ninja process owned by root? Which might be the cause? It didn't consume much CPU time, but when I killed it, Lean became faster again...

I'll reopen if I'm able to reproduce this somehow.
