### ISSUE TITLE
pp.all should print all

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean3#922]
This one gets me at least twice a day -- I think that if we set `set_option pp.all true`, then we should we see everything printed, and not need to additionally set `set_option pp.numerals false`. To be uniform, I think `pp.numerals true` should mean _expand_ numerals, so setting things to true monotonically increases the amount printed.

@leodemoura if you agree, I'll implement this

**Comment by leodemoura** [comment]
I agree.

**Comment by fpvandoorn** [comment]
> I think that if we set set_option pp.all true, then we should we see everything printed

I agree.

> so setting things to true monotonically increases the amount printed.

Other options also do not follow this rule:

``` lean
set_option pp.notation false
set_option pp.abbreviations false
set_option pp.beta false
```

I would be confused when we would change the behaviour for all these options, but maybe that's just because I'm used to the current versions.

Related: maybe it's useful to have a `toggle_option` command, which just toggles the option for boolean-valued options (so that you don't have to remember whether to make something true or false).

**Comment by dselsam** [comment]
Yes, I realized that after I made this post. My plan for right now is to only change one line, so that `pp.all` disables the printing of `numerals`, and then not touch anything else. It is not perfect, since there is no way to "override" `all` if we want `all but with numerals`.

**Comment by leodemoura** [comment]
I'm closing this issue, since @dselsam has already added made the change.
Feel free to reopen.

**Comment by leodemoura** [comment]
BTW, I think it is nice to have the property: setting things to true monotonically increases the amount printed.

We should rename options such as `pp.notation` to `pp.no_notation`. So, it makes sense to set them to `true` to get more information.

> It is not perfect, since there is no way to "override" all if we want all but with numerals.

I will address this issue.

**Comment by dselsam** [comment]
What do you think about Floris's idea to use "toggle" options, so everything increases printing monotonically when "all" is not set, and everything decreases printing monotonically when "all" is set?

**Comment by dselsam** [comment]
To clarify, the idea I am floating is the following:

``` Lean
toggle_option pp.implicits
```

which would just set the `implicits` flag to be true, and then we print implicits if `all && !implicits || !all && implicits`. 

I am not sure, it might be confusing.

**Comment by leodemoura** [comment]
> What do you think about Floris's idea to use "toggle" options, so everything increases printing monotonically when "all" is not set, and everything decreases printing monotonically when "all" is set?

It is yet another command. 

> I am not sure, it might be confusing.

Yeah. 

BTW, the commit above implements the override. It is quite simple. It looks bigger because I changed some procedure names to make them uniform.

**Comment by dselsam** [comment]
I think the override (and also the other "toggle" options floated) defeat the original purpose of this issue -- to make sure that if we set `pp.all true`, we see everything.

``` Lean
set_option pp.universes false
...(thousands of lines)...
set_option pp.all true
check ... -- won't show universes
```

**Comment by leodemoura** [comment]
@dselsam I disagree. 
It think it is really important to override. I felt the need for that many times.
Your counterexample is not realistic. `pp` options are used locally. If you have thousands of lines, you should probably use sections to limit the scope of the settings.

``` lean
local attribute foo [simp]
... thousands of lines ...
... by simp -- why this `foo` rewrite is being used...
```

**Comment by leodemoura** [comment]
BTW, I just added override for `trace` options.
It is another case, I want to override.

``` lean
set_option trace.blast        true
set_option trace.blast.action false
-- trace all blast subclasses but blast.action
```

**Comment by leodemoura** [comment]
BTW, `print options` is quite useful if one is confused about configuration settings.

**Comment by fpvandoorn** [comment]
> BTW, I think it is nice to have the property: setting things to true monotonically increases the amount printed.
> 
> We should rename options such as `pp.notation` to `pp.no_notation`. So, it makes sense to set them to true to get more information.

I'm also OK with this, instead of a `toggle_option` command.
