### ISSUE TITLE
induction on truncated types (2)

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#924]
The fix of #892 allows us to use the `induction` tactic in many proofs in [`types.trunc`](https://github.com/leanprover/lean/blob/master/hott/types/trunc.hlean), which is great.

But unfortunately not all problems with the `induction` tactic on truncated types are solved.

Here is a minimal example. The given proof gives unsolved metavariables. The commented-out proof works.

``` lean
import hit.trunc

open is_trunc trunc

definition set_trunc (A : Type) : Type := trunc 0 A
definition my_rec {A : Type} {P : set_trunc A → Type} [Pt : Πaa, is_hset (P aa)]
  (x : set_trunc A) : P x :=
begin
  induction x, exact sorry
--  refine trunc.rec _ x, exact sorry
end
```

**Comment by fpvandoorn** [comment]
Now that I think about it, maybe this issue is not that important. It works if I manually unfold `set_trunc`. Let me check how often this is a problem in the library.

**Comment by leodemoura** [comment]
BTW, the induction tactic only unfold reducible constants.
If you mark `set_trunc` as reducible, it will also work.
You don't need to manually unfold it.

**Comment by leodemoura** [comment]
I'm closing this issue, the "failed type class resolution -> goal" issue is covered by #926
