### ISSUE TITLE
truncated induction with failing type class resolution

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#926]
If the type class resolution fails when using the `induction` tactic, it should create a new goal for the term it failed to synthesize. Otherwise, you won't be sure whether your `induction` tactic really worked until you've finished the proof.

Minimal example

``` lean
import hit.trunc
open is_trunc trunc
definition wrong_rec {A : Type} {P : trunc 0 A → Type} (x : trunc 0 A) : P x :=
begin
  induction x, -- should generate 2 goals
  exact sorry
end
```

**Comment by leodemoura** [comment]
Latest version does not support HoTT anymore
