### ISSUE TITLE
this and backquotes for let

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#927]
@mikeshulman makes a good suggestion here:
https://groups.google.com/d/msg/lean-user/87wfaVMtgQ8/FAuAI0ZjCwAJ

Can we extend the referencing features we have for `have`: (`this` and backquotes) to the `let` expression? So that something like this would be accepted:

``` lean
example : ℕ :=
let x : ℕ := 3 in
have this = 3, by reflexivity,
have `ℕ` = 3, by reflexivity,
4
```

Maybe what would also be nice is to have a new command (e.g. `pose`) which uses the same syntax as `have` but which is secretly just a `let` expression (i.e. it's transparent).

**Comment by leodemoura** [comment]
The `this` seems unnecessary since have to provide an explicit name for the `let`.
For the new `pose`, it is fine.
The `backquote` is implemented using the tactic framework. 
So, there is no way to support it for `let`/`pose` expressions until the issue #621 is solved.

**Comment by fpvandoorn** [comment]
> The this seems unnecessary since have to provide an explicit name for the let.

True. I would be okay if both features will only be added for `pose`, not for `let`.

**Comment by leodemoura** [comment]
I'm planning to mark this one as "postponed" and close it.
I think we should minimize `let` related extensions until we implement a permanent solution for #621.

**Comment by fpvandoorn** [comment]
Ok.
