### ISSUE TITLE
Omit reflexivities in terms generated by calc

### ISSUE THREAD

**Issue by mikeshulman** [leanprover/lean3#935]
This suggestion was discussed [here](http://homotopytypetheory.org/2015/12/02/the-proof-assistant-lean/#comment-97939): to include a notation like ≡ for "judgmental equality" or "equality proved by reflexivity" that can appear in `calc` and has no effect on the generated term.  Thus, for instance, [here](https://github.com/leanprover/lean/blob/master/library/data/nat/basic.lean#L111) one could write

```
calc 0 + succ m ≡ succ (0 + m) : add_succ
            ... = succ m       : IH
```

(since `add_succ` is just a name for reflexivity) with the result that the generated term would be just (a `subst` of) `IH` rather than a concatenation of it with reflexivity.

I hope this would make `calc` more useful for the HoTT library, where one cares more about the generated term, and also enable more code reuse between the standard library and the HoTT library.

**Comment by javra** [comment]
This sounds quite useful!

**Comment by leodemoura** [comment]
The latest version does not support HoTT anymore.
