### ISSUE TITLE
Emacs installation problem on Ubuntu

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean3#947]
From Michael Ackerman:

> Hello. I know Coq, and I'm studying HoTT, so I'm interested in Lean.
> I installed it under Ubuntu. But to the command `leanemacs'' I get the response`cannot open load file: seq'''. And when I click on the link to install the emacs mode manually, I'm taken to a blank page.
> Any help will be appreciated. Alas, I don't know how to use git.

**Comment by soonhokong** [comment]
@leodemoura, `seq` was added as a required package in `flycheck` recently. I thought that I took care of it by adding it to the `emacs-dependencies` repository, but it seems there is a remaining problem. I'll handle it.

Could you forward  Michael Ackerman's email to me? I'd like to contact him to get information regarding his environment (OS version, emacs version).

**Comment by soonhokong** [comment]
Problem is fixed. [Launchpad](https://launchpad.net/~leanprover/+archive/ubuntu/lean/+packages) is building new PPAs now, which should be downloadable in an hour. Please ask him to upgrade lean via `sudo apt-get update && sudo apt-get upgrade lean` and try `leanemacs` again.
