### ISSUE TITLE
Doc buglets

### ISSUE THREAD

**Issue by awf** [leanprover/lean3#948]
[Can't find the doc file to send a pull request]
1. 
   "In other words, for every A, cons A is the function that takes an element a : A and a list l : list A, and returns a new list, so we have cons a l : list A. " 

should end thus:?

"In other words, for every A, cons A is the function that takes an element a : A and a list l : list A, and returns a new list, so we have cons A a l : list A. " 
1. "avoident pointing" -> "avoid printing"

**Comment by avigad** [comment]
Thanks! The tutorial is in a separate repo; I just issued a pull request that fixes these.

  https://github.com/leanprover/tutorial/pull/153
