### ISSUE TITLE
unicode symbols parsed after "exit"

### ISSUE THREAD

**Issue by avigad** [leanprover/lean3#949]
Some unicode symbols are parsed after exit. For example, each of these symbols gives an "unexpected token" error:

``` lean
exit

∑ ∏ ⋃ ₁ ² 𝒫 
```

Here \sum, \prod, \U, _1, ^2, \powerset are parsed. Upper and lower case greek letters, and for example, the tokens \u, \un, {{ are not.

**Comment by leodemoura** [comment]
They are not parsed, but scanned. 
The scanner looks one token ahead. 
It reports an error if the token after `exit` has not been registered.
I will not fix this.

**Comment by avigad** [comment]
That makes sense. It does not cause problems, so it is reasonable to close it. Thanks.
