### ISSUE TITLE
Broken references to classical.lean and choice.lean in docs

### ISSUE THREAD

**Issue by spl** [leanprover/lean3#973]
Several (if not all) links to `classical.lean` and `choice.lean` in `.md` files are broken. I haven't done a thorough check, but I noticed the issue in `library/library.md` and `logic/logic.md`. The latter document, in particular, should probably be changed to reflect the move of `logic/choice.lean` to `init/classical.lean` (d2eb99bf11d6d1a0650217f86a2d0ed6808909e2).

**Comment by avigad** [comment]
I will go through the whole .md hierarchy soon to try to make sure it is consistent with the directory contents.

@spl We added the .md files as a nicer alternative to browsing the directories, but they are generated by hand, not automatically. Do you think it is worth the extra effort to keep them around and maintain them?

**Comment by spl** [comment]
> We added the .md files as a nicer alternative to browsing the directories, but they are generated by hand, not automatically. Do you think it is worth the extra effort to keep them around and maintain them?

It seems like a nice way to get a handle on the structure of the library, which is more difficult to derive from the `.lean` files themselves. So, yes, I think it is worth having.

I do have a suggestion for potentially simplifying the maintenance job, however. I don't think it is technically necessary to spread the `.md` files throughout the directories. You could put all the same information in one document – with links including to other sections in the same document. And, to fit GitHub's browsing experience, if you put it in `library/README.md`, it'll show up below the directory listing.

**Comment by avigad** [comment]
I don't think combining everything into one file makes the index easier to format, maintain, or use, so I'll leave it that way it is for now. 

I just updated the information in the library.md file (it is in the pull request above). I still need to review the whole .md hierarchy, though, and the library developers together need to talk about what should be the right default configuration for `standard`.
