### ISSUE TITLE
Non dependent versions of pi_transport

### ISSUE THREAD

**Issue by 11Kilobytes** [leanprover/lean3#976]
Lean's HoTT library does not have a non dependent version of the theorem `pi_transport`. I want to implement these in a pull request, but I don't know where to put them.

**Comment by fpvandoorn** [comment]
Do you mean `arrow_transport` in `types.arrow`?

**Comment by 11Kilobytes** [comment]
Yes, I was misled by the documentation here: https://github.com/leanprover/lean/blob/master/hott/book.md, which says that the code corresponding to Section 2.9, which includes the theorem `arrow_transport` is to be found in `types.pi` and `init.funext`, `types.arrow` is not mentioned.

**Comment by fpvandoorn** [comment]
Good point. I will add it there. Thanks for the feedback.
