### ISSUE TITLE
Limit the line no. of hover information

### ISSUE THREAD

**Issue by javra** [leanprover/lean3#983]
Maybe the number of lines displayed while hovering over some error/output should be limited? I regularly get artefacts like the one attached. (Although I actually think, the window manager should catch these...) I think more than, say, 20 lines on the hovering info is too much.
![screenshot from 2016-01-28 12 56 19](https://cloud.githubusercontent.com/assets/148927/12674843/ff9a350a-c67d-11e5-8170-02386e38fe39.png)

**Comment by soonhokong** [comment]
@javra, I'll check what we can do with this. BTW, do you think this broken image is what you get from Lean mode (or some uploading problem)?

**Comment by javra** [comment]
@soonhokong No that's how it actually looks! (CentOS 7 with Gnome 3.14). I'm sure it's actually a bug in Gnome. The glitch has exactly the width of the tool tip window and appears whenever a tool tip is very high.

**Comment by leodemoura** [comment]
`--server` option has been deleted from the `lean3` branch. All `lean-server-*` emacs commands were also deleted. The feature described in this post will be eventually reimplemented in the `lean3` branch using a much simpler architecture suggested by Clément Pit.
