### ISSUE TITLE
Speed up or skip TAGS generation from Emacs mode

### ISSUE THREAD

**Issue by UlrikBuchholtz** [leanprover/lean3#985]
It seems the Emacs mode is a little overzealous about regenerating the TAGS file. Almost every time I use TAGS (e.g., M-.), the TAGS file is regenerated, which can take quite a while, especially when working on the libraries.

I'm hoping that somewhere this could be optimized, for instance by regenerating TAGS at most once every x minutes (preferably in the background), or by speeding up each particular generation by caching the intermediate results (if only one file is slightly changed, regenerating TAGS should be quick).

Or could it be that that's already the intended behavior, and I'm just seeing a bug?

Cc @soonhokong

**Comment by javra** [comment]
Could it be that one of the problems is that there's only one table of TAGS for both .hlean and .lean files? I keep ending up in .lean files when I use M-. in .hlean files! (That's a thing where agda really is a lot more usable)

**Comment by soonhokong** [comment]
I also observed a similar behavior sometimes. It seems that the dependencies for generating TAGS file is not compact enough.

> Could it be that one of the problems is that there's only one table of TAGS for both .hlean and .lean files?

This is a good point as well. I'll fix/update the code later this week.

**Comment by leodemoura** [comment]
The `leantags` command has been deleted from the `lean3` branch. We also removed `.ilean` files. 
`M-.` will be implemented in `lean3` without using a `TAGS` file.
